### ISSUE TITLE
PUT /api/ciphers/share not implemented

### ISSUE THREAD

**Issue by mprasil** [dani-garcia/bitwarden_rs#100]
New vault (#93) calls `PUT` on `/api/ciphers/share` to "Share selected" ciphers. This functionality wasn't present in the previous vault so implementation will be a bit more involved, but should be pretty similar to "move selected".
 
(also woohoo! 100th issue :smile:)

**Comment by tgturner** [comment]
I would love to take a look at this one!

**Comment by mprasil** [comment]
Go for it and don't hesitate to ask for help.

**Comment by krankur** [comment]
I guess we need to add an organization in order to test the "Share" functionality, but I am not able to figure out how to add an organization? I tried uploading a random JSON file as the license file but I am getting a 401 error. Can someone please guide me on this?

**Comment by mprasil** [comment]
Hi, there's no licence required - just create free organization (the first option) and it should have all features after that.

**Comment by dani-garcia** [comment]
I think that happens in the self hosted version (when you build with npm run dist:selfhost)

It should work if you build the normal version (with npm run dist)

**Comment by mprasil** [comment]
@dani-garcia I submitted #109 to merge recent changes from master. We should do this before @krankur touches the sharing API as there were some major changes and will be pain to merge later.

**Comment by mprasil** [comment]
Thanks for merging it. @krankur make sure you're working with latest beta code.

**Comment by krankur** [comment]
@mprasil Will do. Thanks for the heads up.

**Comment by mprasil** [comment]
I think this was resolved in #116
