### ISSUE TITLE
Compatibilidad 

### ISSUE THREAD

**Issue by mgil-tesis** [dani-garcia/bitwarden_rs#1001]
# Please submit all your third party help requests to the forum
Link: https://bitwardenrs.discourse.group/c/help

Buenas tardes,

tengo una duda, para la sincronización con LDAP, se puede hacer con el Bitwarden Directory Connector? 

Lo intenté realizar con la opción que das y el contenedor no logro levantarlo para realizar la configuración.

Muchas gracias por tu atención.

Un saludo.

**Comment by dani-garcia** [comment]
No, por el momento no tenemos soporte para el conector oficial, pero existe un servicio alternativo para sincronización LDAP en la wiki que permite invitar usuarios de un servidor LDAP.

https://github.com/dani-garcia/bitwarden_rs/wiki/Syncing-users-from-LDAP

Saludos.

**Comment by Leboubou111** [comment]
Hi @dani-garcia 

And with official [Directory Connector](https://github.com/bitwarden/directory-connector) ?

I try this to my test environment. DC could connect to Bitwarden_rs and LDAP server (users and groups appears when use Test Now button), but cannot sync users or groups, error `An unexpected error has occurred`.
Sure, I tried with INVITATIONS_ALLOWED and/or SIGNUPS_ALLOWED enable.

**Comment by Leboubou111** [comment]
Oh, ok, I find an issue with an explication : https://github.com/dani-garcia/bitwarden_rs/issues/999

**Comment by dani-garcia** [comment]
As mentioned in #999 this, feature request is included in the meta issue, so closing this to keep the issues list clean.
