### ISSUE TITLE
bitwardenrs/server:latest showing as 1.14.2-1aa5e0d4

### ISSUE THREAD

**Issue by giteke** [dani-garcia/bitwarden_rs#1015]
### Subject of the issue

After server:latest install, 1.14.2-1aa5e0d4 is shown as installed version on admin diagnostic page instead of 1.15.0-1aa5e0d4

### Your environment

* Bitwarden_rs version: 1.14.2-1aa5e0d4

* Install method: Docker
* Clients used: 
* Reverse proxy and version: 
* Version of mysql/postgresql: 
* Other relevant information: 

### Expected behaviour

"Server installed" and "server latest" should be the same
### Actual behaviour

Server Installed: 1.14.2-1aa5e0d4
Server Latest: 

1.15.0-1aa5e0d4
### Relevant logs

![bwrs](https://user-images.githubusercontent.com/59669357/83528634-59c0cf00-a4b7-11ea-9534-9a844c3c6c96.png)

**Comment by Skaronator** [comment]
Thats because `latest` doesn't point to 1.15 yet as you can see here: https://hub.docker.com/r/bitwardenrs/server/tags

Not sure which CI Step exactly push these images but I'd wait a few more minutes. The release was only 7 minutes ago as you created this issue.

**Comment by dani-garcia** [comment]
The tagged release server:1.15.0 is build already, other architectures are missing still.

The latest tag is special in that it doesn't update with the github tags but with the commits, so it won't see the new version number until there is another commit after the tag was created, but if you have an updated latest, you are on the same commit as the 1.15.0 release, which was built yesterday.

**Comment by giteke** [comment]
> The tagged release server:1.15.0 is build already, other architectures are missing still.
> 
> The latest tag is special in that it doesn't update with the github tags but with the commits, so it won't see the new version number until there is another commit after the tag was created, but if you have an updated latest, you are on the same commit as the 1.15.0 release, which was built yesterday.

Gotcha
