### ISSUE TITLE
Release 1.15.0 shows wrong version number

### ISSUE THREAD

**Issue by restonica** [dani-garcia/bitwarden_rs#1016]
### Environment
Logs from last 1.15.0 version

### Expected behaviour
Version 1.15.0-?aa5e0d4 
### Actual behaviour
Version 1.14.2-1aa5e0d4

**Comment by tomamplius** [comment]
seem Ok from last release  Version 1.15.0.

~~~
Jun  3 04:41:14 bitwarden systemd[1]: Started Bitwarden Server (Rust Edition).
Jun  3 04:41:14 bitwarden bitwarden_rs[26359]: /--------------------------------------------------------------------\
Jun  3 04:41:14 bitwarden bitwarden_rs[26359]: |                       Starting Bitwarden_RS                        |
Jun  3 04:41:14 bitwarden bitwarden_rs[26359]: |                           Version 1.15.0                           |
Jun  3 04:41:14 bitwarden bitwarden_rs[26359]: |--------------------------------------------------------------------|
Jun  3 04:41:14 bitwarden bitwarden_rs[26359]: | This is an *unofficial* Bitwarden implementation, DO NOT use the   |
Jun  3 04:41:14 bitwarden bitwarden_rs[26359]: | official channels to report bugs/features, regardless of client.   |
Jun  3 04:41:14 bitwarden bitwarden_rs[26359]: | Send usage/configuration questions or feature requests to:         |
Jun  3 04:41:14 bitwarden bitwarden_rs[26359]: |   https://bitwardenrs.discourse.group/                             |
Jun  3 04:41:14 bitwarden bitwarden_rs[26359]: | Report suspected bugs/issues in the software itself at:            |
Jun  3 04:41:14 bitwarden bitwarden_rs[26359]: |   https://github.com/dani-garcia/bitwarden_rs/issues/new           |
Jun  3 04:41:14 bitwarden bitwarden_rs[26359]: \--------------------------------------------------------------------/
Jun  3 04:41:14 bitwarden bitwarden_rs[26359]: Running migration 20200409235005
Jun  3 04:41:19 bitwarden bitwarden_rs[26359]: [2020-06-03 04:41:19][ws][INFO] Listening for new connections on 0.0.0.0:3012.
Jun  3 04:41:19 bitwarden bitwarden_rs[26359]: [2020-06-03 04:41:19][start][INFO] Rocket has launched from http://0.0.0.0:8000
Jun  3 08:14:11 bitwarden bitwarden_rs[26359]: [2020-06-03 08:14:11][ws::io][INFO] Accepted a new tcp connection from 10.0.0.104:41474.
~~~

**Comment by timendum** [comment]
The issue is in the admin/diagnostics page:

![screenshot](https://user-images.githubusercontent.com/670620/83617768-d7eda600-a589-11ea-91ac-15c862b2b3d0.png)

**Comment by tomamplius** [comment]
No issue for me too

[![2020-06-03_11-11](https://user-images.githubusercontent.com/6951820/83618623-00c26b00-a58b-11ea-95eb-4be1a3c0950c.png)
](url)

**Comment by waschinski** [comment]
When I recreated my docker container and pulled **latest** I ended up with the same result, Web being up-to-date but Server being still on 1.14.2.

Explicitly pulling the **1.15.0** image did update properly though.

**Comment by restonica** [comment]
Thanks waschinski.
Indeed just the lastest tag of raspberry image that currently is on 1.14.2

**Comment by giteke** [comment]
Explanation is here from a closed issue: https://github.com/dani-garcia/bitwarden_rs/issues/1015#issuecomment-637568561

**Comment by restonica** [comment]
Duplicated with #1015 (comment)

**Comment by jjlin** [comment]
@restonica You're probably using the `latest` tag. This is built from the tip of the `master` branch, but because the 1.15.0 release had not been tagged at the time the `latest` image was built, it still shows 1.14.2 because of the way the version string is derived:

https://github.com/dani-garcia/bitwarden_rs/blob/7a6a3e4/build.rs#L41-L43

People using the `1.15.0` tag will get an image built from the same commit, but the version number will show up properly. This issue will fix itself in the next build of `latest` since 1.15.0 is tagged now.
