### ISSUE TITLE
v2 web: Unable to mass delete/delete items.

### ISSUE THREAD

**Issue by mannp** [dani-garcia/bitwarden_rs#102]
Doing a select all and trying to delete items from my test vault.

The following error occurs and no items are deleted.

> => Outcome: Success
> => Response succeeded.
> DELETE /api/ciphers application/json; charset=utf-8:
> => Error: No matching routes for DELETE /api/ciphers application/json; charset=utf-8.
> => Warning: Responding with 404 Not Found catcher.
> => Warning: Data left unread. Force closing network stream.
> => Error: Failed to write response: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }.
> DELETE /api/ciphers application/json; charset=utf-8:
> => Error: No matching routes for DELETE /api/ciphers application/json; charset=utf-8.
> => Warning: Responding with 404 Not Found catcher.
> => Warning: Data left unread. Force closing network stream.
> => Error: Failed to write response: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }.

**Comment by mprasil** [comment]
Thanks for testing the image. This is already tracked under #98, so let's track progress there.

**Comment by mannp** [comment]
Yeah, that was my previous point about the basics. Will do some more testing once you have time to update these initial incompatibilities.
