### ISSUE TITLE
Cloning entry with attachment fails, "Attachment is not owned by the cipher"

### ISSUE THREAD

**Issue by jcklie** [dani-garcia/bitwarden_rs#1022]
### Cloning entry with attachment fails
When I clone an entry with attachment, then I get the error message "Attachment is not owned by the cipher".

### Your environment

* Bitwarden_rs version: Master self compiled db53511855146330fe251334dd769678074b31ff

* Install method: built from source
* Clients used: vault
* Reverse proxy and version: Nginx (by shauder) 
* Version of mysql/postgresql: sqlite
* Other relevant information: Self signed certs, everything else works

### Steps to reproduce

Websockets enabled ,smtp works

1. In an organization, create a new item
2. Attach an image
3. Try to clone it

### Expected behaviour
No error, thing gets cloned

### Actual behaviour
Error toast "Attachment is not owned by the cipher", bitwarden_rs returns 400, empty entry is created

### Relevant logs

Bitwarden log:

```
Jun 05 17:24:48 timetracking bitwarden_rs[22080]: [2020-06-05 17:24:48][request][INFO] POST /api/ciphers/admin
Jun 05 17:24:49 timetracking bitwarden_rs[22080]: [2020-06-05 17:24:49][error][ERROR] Attachment is not owned by the cipher
Jun 05 17:24:49 timetracking bitwarden_rs[22080]: [2020-06-05 17:24:49][response][INFO] POST /api/ciphers/admin (post_ciphers_admin) => 400 Bad Request
```
JS console:
`Failed to load resource: the server responded with a status of 400 ()
`
![image](https://user-images.githubusercontent.com/934600/83894467-a1fb1e00-a751-11ea-9c13-b8e556577b26.png)

**Comment by BlackDex** [comment]
i can confirm the error.
And, if i check the upstream project it doesn't clone attachments at all.
So i think we should match that for now, but this bug causes  those items to not being cloned at all.
