### ISSUE TITLE
Further problems with branding

### ISSUE THREAD

**Issue by fuanegua** [dani-garcia/bitwarden_rs#1030]
Thanks a lot for this great opportunity to run on Raspberry Pi! It works all fine!
… except the custom email-templates. What did I wrong?

I’ve tried it this way:

```
docker pull bitwardenrs/server:raspberry
docker run -d --name bitwarden -v /bw-data/:/data/ -p 8005:80 -e ADMIN_TOKEN=<token> --restart always  -e TEMPLATES_FOLDER=/bw-data/templates/ -e RELOAD_TEMPLATES=true -e ROCKET_TLS='{certs="/ssl/live/<example.com>/fullchain.pem",key="/ssl/live/<example.com>/privkey.pem"}'  -v /etc/letsencrypt/:/ssl/ bitwardenrs/server:raspberry
```

Also I can’t change the logos and images, so they are outside this folder in `/src/static/images`. Is there a way to set this folder to `/bw-data/ ` as well?

Docker is just a new field to me. So sorry if this question is a little stupid.

**Comment by BlackDex** [comment]
Hello @fuanegua,

The issue is with the `TEMPLATES_FOLDER` variable.
You configured it to be in /bw-data/templates/ but you have to look at these variable from within the docker container, and there the data folder is located in `/data`.

So if you change the from:
`-e TEMPLATES_FOLDER=/bw-data/templates/`
To:
`-e TEMPLATES_FOLDER=/data/templates/`

And copy all the template data in there you should be able to change the templates.
Regarding the images, that is possible using the templates folder.
You can of course host those pictures on an other virtualhost or somewhere else on the web.
Or if they are small embed them in the html code even by using a data uri as the src="" element instead of the location of the image. You can convert an image to a data uri via a site like https://www.site24x7.com/tools/image-to-datauri.html

**Comment by fuanegua** [comment]
Thanks a lot for your help, @BlackDex!
Maybe I don’t understand it exactly. So in my mind I want to put all the template files outside the docker container to be able to edit and change the files via FTP. 
So all these files are in `/bw-data/templates`.

Do I understand you right that I shall save the template files inside the docker container? 
Or do I have to create a directory `/data` (or `/bw-data/data/templates` ?!) outside the docker container?

**Comment by BlackDex** [comment]
With the option `-v /bw-data/:/data/` you actually tell docker to mount /bw-data/ in the container as /data/. So outside the container you access the files in `/bw-data/` inside the container they are accessed via `/data/`.
So if you create a folder `/bw-data/templates/` on the host, it will be called `/data/templates/` within the container.

**Comment by fuanegua** [comment]
Okay, thanks! Sounds clear. But unfortunately the hole bitwarden container is not reachable/working, when I create it with:

`docker run -d --name bitwarden -v /bw-data/:/data/ -p 8005:80 -e ADMIN_TOKEN=<TOKEN> --restart always  -e TEMPLATES_FOLDER=/data/templates/ -e ROCKET_TLS='{certs="/ssl/live/<DOMAIN>/fullchain.pem",key="/ssl/live/<DOMAIN>/privkey.pem"}'  -v /etc/letsencrypt/:/ssl/ bitwardenrs/server:raspberry`

`TEMPLATES_FOLDER=data/templates/` or `TEMPLATES_FOLDER=templates/` make the cotainer work again but without the new templates.

Anything else I missed?

**Comment by BlackDex** [comment]
Which folders do you have under your own templates? Does it include both admin and email directories? Or only email?
Because that should work.

**Comment by fuanegua** [comment]
Yes it‘s strange. 
I‘ve got both `/bw-data/templates/admin` and `/bw-data/templates/email` in my Pi root directory. 
Does a slash at the end matter?

**Comment by fuanegua** [comment]
Got it! 
It was simply a broken variable due to copy & paste errors (`{{{` instead of `{{`) inside an edited hbs that brought bitwarden into a restart loop.
I finally understood how to read the logs and I think I'm a few steps further with docker. Thanks for your patience @BlackDex! 🙏🏼

**Comment by AbdullahZubair** [comment]
Hi there, @fuanegua!
I apologize for opening this issue after a long period, but I could really use some help. Currently, I'm using the latest version of Vaultwarden with Docker Compose, and I'm looking to customize the web and email aspects to incorporate our organizational branding, including text, logos, and more. I want to ensure that Vaultwarden reflects our organization's identity.
If you could provide any guidance or suggestions on how to achieve this customization, I would greatly appreciate it. I've been exploring the available options, but I'm looking for some expert advice on the best approach.
Thank you so much in advance for your assistance!
