### ISSUE TITLE
No org_name in invite_confirmed email for already registered users

### ISSUE THREAD

**Issue by fuanegua** [dani-garcia/bitwarden_rs#1034]
Bitwarden_rs version: 1.15.1-a87646b8 with defined template_folder

There must be a problem with the invite_confirmed email and `{{org_name}}` for already registered users.

So if you set an invitation organization name (e.g. Example Org) and invite an email address via admin panel and the receiver is already registered with another email address so he doesn't need to click `Create Account` but `Log In` he will then get a confirmation mail with 
"Your invitation to join bitwarden_rs was confirmed." 

Creating a new account the confirmation is:
"Your invitation to join Example Org was confirmed."

It is the same when adding a new user to an organization and this user is also already registered and just logs in.

So it seems to ignore the set org_name in this situation. 

You could try it by inviting yourself with another mail address (both from admin panel and from organization manage people) and log in with your own account after joining the invitation to reproduce.

**Comment by BlackDex** [comment]
I have tested this, and this works for me just fine.
I can also not see any issue that quickly in the code it self.

See:
![image](https://user-images.githubusercontent.com/610450/101990351-da525a80-3ca6-11eb-80f3-e38d997d0f20.png)

If you still have this issue please provide some more information, screenshots and log file.
For now i'm going to close this issue, but feel free to re-open if this still happens.
