### ISSUE TITLE
Self-hosted Bitwarden RS - iOS Sync not working any more

### ISSUE THREAD

**Issue by nozomij** [dani-garcia/bitwarden_rs#1038]
### Subject of the issue

Since a few weeks my iOS devices don't seem to be able to sync with my self hosted Bitwarden RS docker container any more. It has been working flawlessly for almost a year now while the sync (manual and automatic) it is still working with Mac OS Bitwarden App / Safari extension / Win 10 Firefox extension as well as Win 10 Bitwarden App.
On both iOS devices (iOS 13.5.1) with newest Bitwarden app from Apple App Store sync fails without further information. It just says "synchronization failed" (in German)
### Your environment

* Bitwarden_rs version: 0.6.0

* Install method: 
* Clients used:  iOS Bitwarden Client through App Store, recent
* Reverse proxy and version: 
* Version of mysql/postgresql: 
* Other relevant information: 
Installed via through Home Assistant supervisor (docker)
### Steps to reproduce

I open the recent Bitwarden App on either iPad mini 5 or iPhone 6s both equipped with recent iOS 13.5.1 and configure my Bitwarden url+port. I use duckdns. Then I input mail address and passphrase for the vault and it log ins correctly. However the vault itself is empty and if I click on options > synchronize it fails without further info.

### Expected behaviour

It should synchronize
### Actual behaviour

It fails without further notification
### Relevant logs

log of bitwarden_rs docker container
[2020-06-27 12:47:22][request][INFO] GET /api/sync
[2020-06-27 12:47:22][response][INFO] GET /api/sync?<data..> (sync) => 200 OK
[27/Jun/2020:12:47:22 +0200] 200 -(84.46.37.6) GET /api/sync HTTP/1.1 (Bitwarden_Mobile/2.4.3 (iOS 13.5.1; Model iPad))

**Comment by mqus** [comment]
Thank you for the report!
Your bitwarden_rs version is from the home assistant plugin and is not something we can work with. Could you provide the bitwarden_rs logs right from the start of the container? They should display the right version. 
I also looked up which version the 0.6.0 referred to and its the version of the [hass.io addon](https://github.com/hassio-addons/addon-bitwarden). There are already [newer versions](https://github.com/hassio-addons/addon-bitwarden/releases), did you try them?

**Comment by nozomij** [comment]
You're right. The correct Bitwarden version is 1.3.1.

/--------------------------------------------------------------------\
|                       Starting Bitwarden_RS                        |
|                           Version 1.13.1                           |
|--------------------------------------------------------------------|
| This is an *unofficial* Bitwarden implementation, DO NOT use the   |
| official channels to report bugs/features, regardless of client.   |
| Report URL: https://github.com/dani-garcia/bitwarden_rs/issues/new |
\--------------------------------------------------------------------/

Its bizarre that my home assistant does not offer me any upgrade of the add-on to 0.6.2 at that moment. I would rather not reinstall the add-on itself until absolutely necessary. I am not sure where the bug is since it is working on my desktop computers (W10) as well as Mac OS X Catalina.

**Comment by jjlin** [comment]
The mobile sync issue sounds like it might be the same as #921, but in any case, you should really be running at least [1.15.0](https://github.com/dani-garcia/bitwarden_rs/releases/tag/1.15.0) at this point. If the add-on maintainer hasn't released that yet, maybe you should ask them about it.

**Comment by nozomij** [comment]
I deleted and re-installed the plugin on my Hassio. I somehow got troubled with the admin token which I presumably didn't save so I just created myself a new account in the container into which I imported the vault JSON.
