### ISSUE TITLE
iOS App not syncing - self hosted BITWARDEN_RS Version 1.15.1-b34d5482

### ISSUE THREAD

**Issue by geekblog-dev** [dani-garcia/bitwarden_rs#1039]
### Subject of the issue

I have a self hosted Bitwarden server from:
https://hub.docker.com/r/bitwardenrs/server
Every thing works fine until i used the IOS app to fill another account with the app. After a short logout and login all passwords are censored with stars.

### Your environment

* Bitwarden_rs version: 1.15.1-b34d5482

* Install method: Docker image from : //forums.unraid.net/topic/88086-support-bitwardenrs-bitwarden_rs/
* Clients used: latest IOS App 
* Reverse proxy and version: nginx/1.18.0 
* Version of mysql/postgresql: use standard sqlite
* Other relevant information: 

### Steps to reproduce

New Account login in from IOS App.
Types in Passwords in the IOS App.
Logout from IOS App by settings logout.
Login from the offical IOS App again.
Everything is gone.

### Expected behaviour

New Account login in from IOS App.
Types in Passwords in the IOS App.
Logout from IOS App by settings logout.
Login from the IOS App again.
Everything is great, all Passwords are stored safely.

### Actual behaviour

After logout and login again the passwords were shown like the were censored with (***), even if i login from the webpage.

### Relevant logs

If you can lead me were to find these logfiles, i will have a look and provide some.

**Comment by jjlin** [comment]
Can you elaborate on what you mean by "all passwords are censored with stars"? A screenshot would be helpful.

**Comment by r3garciaz** [comment]
Hi, I have a similar problem, the iOS app don’t sync automatically, I can do manually. I never received a push notifications o something like that’s. 

 Every time I need syncing, I need do manually.

**Comment by tlesmann** [comment]
Same for me. The sync between iOS app and MacOs/WebApp doesn't work (since a long time). I've to resync data on iOS manually and than it's all fine.

**Comment by BlackDex** [comment]
Push notifications do not work when using bitwarden_rs. This functionality only works with the official bitwarden self-hosted or hosted servers because of how these features work and communicate.
It may be possible to implement this, but this requires using an server/license key provided by bitwarden.com and quite some development.

We would gladly accept a well coded PR if someone is willing to do this. But we also do not want to hinder bitwarden.com by using there resource and not providing anything back.

Also, the latest Mobile clients have a sync on refresh (pull-down) feature now, so i think this is less relevant now.
Closing this ticket as this also mentioned on the META Features Request Issue #246 .

**Comment by dawid-woitaschek** [comment]
> Push notifications do not work when using bitwarden_rs. This functionality only works with the official bitwarden self-hosted or hosted servers because of how these features work and communicate.
> It may be possible to implement this, but this requires using an server/license key provided by bitwarden.com and quite some development.
> 
> We would gladly accept a well coded PR if someone is willing to do this. But we also do not want to hinder bitwarden.com by using there resource and not providing anything back.
> 
> Also, the latest Mobile clients have a sync on refresh (pull-down) feature now, so i think this is less relevant now.
> Closing this ticket as this also mentioned on the META Features Request Issue #246 .

Ugh... Did I miss something or is this **MAJOR** note nowhere written down? To me that is a crucial feature, that's missing, although you are able to pull-down to update. imho not less relevant.

**Comment by BlackDex** [comment]
@dawid-woitaschek, well it's not written in the wording as, push is not working, or moblie sync. But it is mentioned on several places like the main wiki page, the meta features request #246 . As is on several issues like these.
