### ISSUE TITLE
Organisation join failure

### ISSUE THREAD

**Issue by ced455** [dani-garcia/bitwarden_rs#1047]
### Subject of the issue
Organisation join failure

### Your environment
* Bitwarden_rs version: 1.15.1-596c9b86
* Install method: docker on unraid
* Clients used: firefox /chrome
* Reverse proxy and version: nginx

* Other relevant information: 

### Steps to reproduce
create a organisation and send invite to a existing user1, user2 accept get "can't accept invitation" (sorry translation from french)
I receive a invitation accepted
user2 organisation tag is not displayed from the admin panel 

### Expected behaviour
user2 should accept the invitation and be able to access logins

### Actual behaviour
user2 cannot access passwords

### Relevant logs
nothing outstanding

**Comment by r32rf** [comment]
I have a twist on this.  I got invited to an organisation and saw a success message.  However, there is no org tag behind my name in the admin panel but the organisation user count reflects that I should be invited.  The owner of the org also got a confirmation mail that I have accepted the invitation.

**Comment by BlackDex** [comment]
@r32rf & @ced455

If you invite a user into an organization either the owner or an admin of that organization should verify this! Untill this is done the user who accepted the invite will not see the collections or passwords from that organization at all

**Comment by BlackDex** [comment]
Closing this ticket because of inactivity.
Feel free to re-open if the issue isn't resolved using the `testing`/`master` version.
