### ISSUE TITLE
Update docker image?

### ISSUE THREAD

**Issue by hexicans** [dani-garcia/bitwarden_rs#1053]
Hello,

Can you update docker image with last version of Bitwarden please?  There a lot of important changes.

The Bitwarden docker version is actually :
Version 2.13.2

Thanks

**Comment by BlackDex** [comment]
@hexicans What do you mean with updating the docker image?
The latest build is from 2 days ago, the same as the latest commit so it has the latest version available.
It even has the updated vault web-gui 2.15.1 running.

**Comment by hexicans** [comment]
@BlackDex Oh, true. seem I have web cache this morning, resolved.

Thanks.
