### ISSUE TITLE
Emails sent from Bitwarden_rs show up as blank attachments in Airmail

### ISSUE THREAD

**Issue by nermolov** [dani-garcia/bitwarden_rs#1057]
### Subject of the issue

Emails sent from Bitwarden_rs show up as blank attachments in [Airmail](https://apps.apple.com/us/app/airmail-4/id918858936?mt=12).

<img width="663" alt="Screen Shot 2020-07-14 at 9 40 09 AM" src="https://user-images.githubusercontent.com/6175137/87432510-18433980-c5b6-11ea-9e38-3e6049cbea9a.png">

### Your environment

* Bitwarden_rs version: 1.14.2-8bbbff75
* Install method: Docker
* Clients used: Safari, Airmail
* Reverse proxy and version: Traefik 1.7
* Version of mysql/postgresql: N/A

### Steps to reproduce

1. Set up SMTP
2. Send email with SMTP

### Expected behaviour

Email notification should be readable.

### Actual behaviour

Email notification shows up blank and as an attachment

**Comment by BlackDex** [comment]
I'm working on some improvements for the e-mail sending and i just tested it with Airmail (4.x).
They seem to work for me.
Also, i checked some older e-mails and i don't have any issues with them either, so why this happened for you i have no idea.
What kind of e-mail is this?

Did you checked this also with the SMTP Test function in the /admin interface?

**Comment by simokhalil** [comment]
Same result here.
Just instaled my BT RS v2.15.1 server on the exact same setup (docker, traefik 1.7), with Mailjet as email gateway.

FYI, with the Test function from the admin, the result is different: email is shown in plain HTML

**Comment by BlackDex** [comment]
I have made some changes in the meantime which should fix your issues.
But for this you need to install the latest (testing) version which is available.
Also `v2.15.1` is not the server version but the web-vault version.

To see which version of bitwarden_rs you are running you need to go to the admin interface to `/admin/diagnostics`.
There you will see which version you are running.

I suggest to at least try to install the testing version from the docker hub and see if that resolves your issue.

**Comment by simokhalil** [comment]
@BlackDex Oh sorry, it's the v1.16.3

Will try with the testing version today and give my feedback

**Comment by simokhalil** [comment]
@BlackDex just installed the testing version and emails are working good
Do we have a release date for this version yet ?
Thank you

**Comment by BlackDex** [comment]
@simokhalil Not yet. We are working-out some small items with some newer mysql/mariadb databases amongst other small items.

**Comment by simokhalil** [comment]
@BlackDex Ok, no problem. Will watch this...

Thanks for your good job anyway guys ;)

**Comment by BlackDex** [comment]
Going to close this one as it has been fixed and verified 😀
