### ISSUE TITLE
Email invite system not working?

### ISSUE THREAD

**Issue by SMAW** [dani-garcia/bitwarden_rs#1058]
I have some issues with setting up my bitwarden_rs server.

I've setup the invitation system and SMTP settings. SMTP settings look fine and the email arrives at my mailbox.
All the links i'm getting (invite or confirm email) arent working.
![image](https://user-images.githubusercontent.com/1489746/87710812-97975f80-c7a6-11ea-84e0-06e6fced421a.png)
The link seems correct with the correct base URL. 

example URL : https://DOMAIN/#/accept-organization/?organizationId=_&amp;organizationUserId=_&amp;email=USER%40DOMAIN%2Enl&amp;organizationName=Bitwarden_RS&amp;token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJuYmYiOjE1OTQ5MjQ5ODcsImV4cCI6MTU5NTM1Njk4NywiaXNzIjoiaHR0cHM6Ly9idy5zbWF3Lm5sfGludml0ZSIsInN1YiI6ImI3OWFmYzlmLWMxYTQtNDRkOC05ZDA1LTRlY2Q4MGMxNDVlYyIsImVtYWlsIjoib3JyaW5Ac21hdy5ubCIsIm9yZ19pZCI6bnVsbCwidXNlcl9vcmdfaWQiOm51bGwsImludml0ZWRfYnlfZW1haWwiOm51bGx9.NcTwC70ONLBqxZaguqX0Qelg2xTioCablLlxha-1KoeNrfVx6GvQCW9DzaZ7RQ9As5hbzeUW9f73lIZUAF9zygkySpNJi9FiqztTyOdjr-9cvIfXkJ-jZHQaX89IklOvUYt2k2AGQPP0HKqhaPzhgte28Sxc0QJNUj1ozlerJDo6hUO9f5UulA_9_pszOY91wWdo6z3_olff4MZgQS9JXS-PpPV_Gqws7lkVwEc-VkosaIyliERHXzVQpLLbWt9Jfd59njuMLXNg3s7yUUR-f-nlNMmxdwpXTlAp-KwxN16qzA43L107q07vwr4N0TdutY5pfEukFO0X

(I also removed the last 10 characters to be sure :)

I've set the following env variables:
      - ADMIN_TOKEN=TOKEN
      - DOMAIN=https://DOMAIN
      - SIGNUPS_ALLOWED=true 
      - INVITATIONS_ALLOWED=true 
      - WEBSOCKET_ENABLED=true 
      - LOG_FILE=/data/bitwarden.log
      - LOG_LEVEL=trace
      - EXTENDED_LOGGING=true

I'm running the installation behind a traefik 2.2.0 config:

      - "traefik.enable=true"
      - "traefik.http.routers.bitwarden.entrypoints=http"
      - "traefik.http.routers.bitwarden.rule=Host(`DOMAIN`)"
      - "traefik.http.middlewares.bitwarden-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.bitwarden.middlewares=bitwarden-https-redirect"
      - "traefik.http.routers.bitwarden.service=bitwarden"
      - "traefik.http.services.bitwarden.loadbalancer.server.port=80"

      - "traefik.http.routers.bitwarden-secure.entrypoints=https"
      - "traefik.http.routers.bitwarden-secure.rule=Host(`DOMAIN`)"
      - "traefik.http.routers.bitwarden-secure.tls=true"
      - "traefik.http.routers.bitwarden-secure.tls.certresolver=cloudflare-dns"
      - "traefik.http.routers.bitwarden-secure.service=bitwarden-secure"
      - "traefik.http.services.bitwarden-secure.loadbalancer.server.port=80"
      - "traefik.http.routers.bitwarden-secure.middlewares=default-headers@file"      

      - "traefik.http.routers.bitwarden-ws.entrypoints=https"
      - "traefik.http.routers.bitwarden-ws.rule=Host(`DOMAIN`) && Path(`/notifications/hub`)"
      - "traefik.http.middlewares.bitwarden-ws-strip.stripprefix.prefixes=/notifications/hub"
      - "traefik.http.routers.bitwarden-ws.middlewares=bitwarden-ws-strip"
      - "traefik.http.routers.bitwarden-ws.tls=true"
      - "traefik.http.routers.bitwarden-ws.tls.certresolver=cloudflare-dns"
      - "traefik.http.routers.bitwarden-ws.service=bitwarden-ws"
      - "traefik.http.services.bitwarden-ws.loadbalancer.server.port=3012"

Also when I open a port directly to the docker container (so without using the Traefik) the links still aren't working.

Is there someone who can help me with the setup of the invite system?

I've tried the latest version of bitwarden_rs and the 1.14.2 version

**Comment by SMAW** [comment]
Found the issue... When I open the mail with Outlook desktop client it works. When I open the link trough webmail (gmail or other webmail) the link is a bit different. Its around the token part.

Webmail : 3&amp;token=e3&amp;token=e
Client : 3&token=e

If I copy the link from webmail, remove the &amp the link works.

I think this is a bug.

**Comment by BlackDex** [comment]
This issue should also be solved with the latest fixes regarding email sending.

Thx for reporting.
