### ISSUE TITLE
Redirect after enabling /admin the first time is wrong

### ISSUE THREAD

**Issue by hasturo** [dani-garcia/bitwarden_rs#1063]
Hi,

ive installed the Server behind 2 reverse Proxy's. Im able to see Login in Page and after enabling Admin Token in docker-compose.yml i can access the Admin Loginpage. After entering my Admintoken the Server sends me a Redirect to localhost/admin. Either is the hint of a Domain Name in the "Enabling Admin Page" Documentation missing or the Redirect is wrong.

-hasturo

**Comment by hasturo** [comment]
Found a Hint to https://github.com/dani-garcia/bitwarden_rs/wiki/Configuration-overview in Forum. Now it is working.

**Comment by dani-garcia** [comment]
Issue is fixed so closing it.
