### ISSUE TITLE
bitwardenrs/server-mysql is not a multiarch image

### ISSUE THREAD

**Issue by 0xERR0R** [dani-garcia/bitwarden_rs#1066]
As announced in the description for [Release 1.16](https://github.com/dani-garcia/bitwarden_rs/releases/tag/1.16.0), the image server-mysql and server-postgresql should be a multiarch image. This is not the case:

![image](https://user-images.githubusercontent.com/25868513/88222189-dffec380-cc65-11ea-9920-8d4eeaae00fa.png)

Am I misunderstanding this?

bitwardenrs/server is multiarch and runs fine on arm7

**Comment by GitSchorsch** [comment]
I would also be interested in an mysql-image for my Raspberry Pi 4 as a replacement for bitwarden/server.

**Comment by SuNNjek** [comment]
Same for bitwardenrs/server-postgresql. I'm currently building every version on my Pi but it takes ages to compile so having a downloadable image would be nice.

**Comment by jjlin** [comment]
Multi-arch for the MySQL and PostgreSQL images are blocked by cross-compilation issues, e.g. #530. If someone steps up to fix that, those images can be easily made multi-arch.

**Comment by rkojedzinszky** [comment]
Until this is resolved, a multiarch multidb image is being built here: https://hub.docker.com/r/rkojedzinszky/bitwardenrs-server.

A multiarch postgresql server is already built here: https://hub.docker.com/r/rkojedzinszky/bitwardenrs-server-postgresql
