### ISSUE TITLE
Auto fill request please read

### ISSUE THREAD

**Issue by EQUALIT-CG** [dani-garcia/bitwarden_rs#1070]
I would like to request a Bitwarden feature
When one goes to sing up to a new Wibsite
you can have it auto fill in your ID that you have setup with Bitwarden
Kind of like Google auto fill but not as damaging.
This way you can only auto fill then things you liek such as you Name and maybe address
But you can Turn this on / Off or something 

# Please submit all your feature requests to the forum
Link: https://bitwardenrs.discourse.group/c/feature-requests

**Comment by dani-garcia** [comment]
I'm not sure what you're trying to say to be honest, but autofill is done by the clients and not the server, so we can't help you there.

Also the browser extensions do have autofill support, you just need to enable it in the options menu:
![image](https://user-images.githubusercontent.com/725423/89301226-b54f3a80-d669-11ea-93fd-a96abdb9473f.png)

**Comment by EQUALIT-CG** [comment]
@dani-garcia
Hi Dani
I'm requesting some type of new adon 
forget the auto fill i'm trying to ask for a new auto fill that can fill in you name DOB address etc only when singing up to new accounts say i wish to make an amazon account and i don't have an account it can then ping / pop up an autofill will my name etc
I hope this is better to understand

**Comment by EQUALIT-CG** [comment]
![image](https://user-images.githubusercontent.com/56815873/89301922-8b1f6c00-d6ad-11ea-8344-4cc5383e5dc3.png)

**Comment by dani-garcia** [comment]
If you select type Identity when creating a cipher, you can add all those fields there, name, address, DOB, phone...
![image](https://user-images.githubusercontent.com/725423/89302173-cd738980-d66a-11ea-8f27-1f04046e3ed8.png)

That can be used with the autofill, or you can press Control+Shift+L to fill the fields for you (at least on Firefox)

That said, if that doesn't work I can't add support for it myself, I just develop the server side, not the addons.

**Comment by GajulanIrcem** [comment]
> ateur prennent en charge le remplissage automatique, il vou



> If you select type Identity when creating a cipher, you can add all those fields there, name, address, DOB, phone... ![image](https://user-images.githubusercontent.com/725423/89302173-cd738980-d66a-11ea-8f27-1f04046e3ed8.png)
> 
> That can be used with the autofill, or you can press Control+Shift+L to fill the fields for you (at least on Firefox)
> 
> That said, if that doesn't work I can't add support for it myself, I just develop the server side, not the addons.



Hello Dany,
is it possible to automatically enable autofill on a vaultwarden?
