### ISSUE TITLE
how to install without docker?

### ISSUE THREAD

**Issue by okami-chen** [dani-garcia/bitwarden_rs#1080]
# Please submit all your third party help requests to the forum
Link: https://bitwardenrs.discourse.group/c/help

**Comment by dani-garcia** [comment]
You can either compile it yourself:
https://github.com/dani-garcia/bitwarden_rs/wiki/Building-binary

Or use a third party package:
https://github.com/dani-garcia/bitwarden_rs/wiki/Third-party-packages
