### ISSUE TITLE
Unlock Bitwarden APP fails: Invalid master password

### ISSUE THREAD

**Issue by Indynaut** [dani-garcia/bitwarden_rs#1084]
I think since the last update of the Bitwarden APP there is a problem with unlocking the app.
When I want to unlock the App, I get an error "Invalid master password".  When I log out completely I can login wihtout problems.
This seems to be only an issue with the local hosted bitwarden_rs. With the "official" bitwarden.com it is working well.
Is it me or a bug? Any solution?
Many thx for any help.

**Comment by sushantvirdi** [comment]
Yes, same here too. Found this on [reddit](https://www.reddit.com/r/Bitwarden/comments/i1te9k/unlock_not_working_windows_10_exe_windows_store/)

**Comment by dani-garcia** [comment]
Fixed in the latest commit, might take a couple of hours for the builds if you are using the docker images.

https://github.com/dani-garcia/bitwarden_rs/commit/ad48e9ed0f91a1a7b38a032b2a538d4c9725f31c
