### ISSUE TITLE
Can't connect to DB: BadConnection

### ISSUE THREAD

**Issue by okami-chen** [dani-garcia/bitwarden_rs#1085]
### Your environment

* Bitwarden_rs version: 

* Install method: 
* Clients used: 
* Reverse proxy and version: 
* Version of mysql/postgresql: 
* Other relevant information: 

### Relevant logs

```
[2020-08-05 14:20:17.397][panic][ERROR] thread 'main' panicked at 'Can't connect to DB: BadConnection("Can\'t connect to local MySQL server through socket \'/var/lib/mysql/mysql.sock\' (2)")': src/main.rs:235
   0: bitwarden_rs::init_logging::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/daecab3a784f28082df90cebb204998051f3557d/src/libstd/panicking.rs:530
   2: rust_begin_unwind
             at /rustc/daecab3a784f28082df90cebb204998051f3557d/src/libstd/panicking.rs:437
   3: core::panicking::panic_fmt
             at /rustc/daecab3a784f28082df90cebb204998051f3557d/src/libcore/panicking.rs:85
   4: core::option::expect_none_failed
             at /rustc/daecab3a784f28082df90cebb204998051f3557d/src/libcore/option.rs:1269
   5: bitwarden_rs::main
   6: std::rt::lang_start::{{closure}}
   7: std::rt::lang_start_internal::{{closure}}
             at /rustc/daecab3a784f28082df90cebb204998051f3557d/src/libstd/rt.rs:52
      std::panicking::try::do_call
             at /rustc/daecab3a784f28082df90cebb204998051f3557d/src/libstd/panicking.rs:348
      std::panicking::try
             at /rustc/daecab3a784f28082df90cebb204998051f3557d/src/libstd/panicking.rs:325
      std::panic::catch_unwind
             at /rustc/daecab3a784f28082df90cebb204998051f3557d/src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at /rustc/daecab3a784f28082df90cebb204998051f3557d/src/libstd/rt.rs:51
   8: main
   9: __libc_start_main
  10: <unknown>
```

**Comment by BobWs** [comment]
Had the same problem so out of the blue. Update the image to the latest version but that didn’t help. After the update BW wouldn’t start it was repeatedly restarting. Then I decided to restart my docker and that solved the problem. 
But I guess this is not a normal behavior as I never had this problem before.

**Comment by BlackDex** [comment]
@BobWs , is MySQL also running as a container?
If that is the case it could be bitwarden is started before the MySQL container which causes this error and would en explain why a restart would work.

**Comment by BobWs** [comment]
> @BobWs , is MySQL also running as a container?
> 
> If that is the case it could be bitwarden is started before the MySQL container which causes this error and would en explain why a restart would work.

Yes Mariadb is also running as a container. I could set BW to `depend-on` the Mariadb container but I don’t know how to set it via CLi (command line)

**Comment by BlackDex** [comment]
@BobWs Do you use docker compose?

**Comment by BlackDex** [comment]
Because if so, please checkout this link: https://docs.docker.com/compose/startup-order/

**Comment by BobWs** [comment]
> @BobWs Do you use docker compose?

No I don’t I use CLi in combination with the GUI of Docker on a Synology. They have built a GUI for Docker. So most of the settings I can do via the GUI but sometimes I need more and use CLi. I have never tried docker compose.

**Comment by BlackDex** [comment]
@BobWs Then it would be an option to add the following as a pre-start script for the docker.
A while back @jjlin created a way to have stuff done before bitwarden_rs gets started.
See: https://github.com/dani-garcia/bitwarden_rs/wiki/Starting-a-Container#customizing-container-startup

You could add a script which waits for mysql to be started like this (tested this on the testing image, not the alpine one).
```bash
while ! curl <mysql-db-ip>:3306 --output /dev/null -0 --connect-timeout 2 --max-time 2 ; do sleep 1 ; done
```

**Comment by BobWs** [comment]
> @BobWs Then it would be an option to add the following as a pre-start script for the docker.
> A while back @jjlin created a way to have stuff done before bitwarden_rs gets started.
> See: https://github.com/dani-garcia/bitwarden_rs/wiki/Starting-a-Container#customizing-container-startup
> 
> You could add a script which waits for mysql to be started like this (tested this on the testing image, not the alpine one).
> 
> ```shell
> while ! curl <mysql-db-ip>:3306 --output /dev/null -0 --connect-timeout 2 --max-time 2 ; do sleep 1 ; done
> ```

Thanks for the suggestion I will give it a try and report back if it works.

**Comment by dani-garcia** [comment]
Commit 729c9cf might help if you need bitwarden_rs to retry the connection, by default it retries 15 times, one second between each try, then gives up, configurable by DB_CONNECTION_RETRIES (set to 0 for infinite retries).

**Comment by BlackDex** [comment]
Closing this ticket because of inactivity.
Feel free to re-open if the issue isn't resolved using the `testing`/`master` version.
