### ISSUE TITLE
Unable to unlock when locked

### ISSUE THREAD

**Issue by yubinhong** [dani-garcia/bitwarden_rs#1088]
### Subject of the issue

When i lock , and unlock again, it throw a error : invalid password.
But I loggout , and re-login, it success. 
### Your environment

* Bitwarden_rs version:  1.16.1

* Install method:  docker
* Clients used:  desktop client for macos
* Reverse proxy and version:  nginx
* Version of mysql/postgresql: 
* Other relevant information:

**Comment by dani-garcia** [comment]
This has been solved in the latest commit and is already available in the bitwardenrs/server:testing image, I'll make a new release later today.

**Comment by dani-garcia** [comment]
The release 1.16.3 is made and available in docker hub, closing now
