### ISSUE TITLE
How check installed version?

### ISSUE THREAD

**Issue by mikkelnl** [dani-garcia/bitwarden_rs#1090]
Sorry for being a noob here ;-) but I was wondering how I can check which version I am running?

Bit info on my setup: I run the container on a synology nas via the docker package, and I usually update by exporting the settings, re-downloading the latest image from bitwardenrs/servers:latest, importing the settings and start the container.

I usually check updates via https://github.com/dani-garcia/bitwarden_rs/releases/

Is there any way to see which version is currently running? Maybe via a terminal command?

**Comment by TheGreatestJannet** [comment]
It is shown in the admin page if it is enabled.

**Comment by dani-garcia** [comment]
Also printed on the logs just as the server starts.

**Comment by acwrobel1** [comment]
You can also see the installed version on the portal login/unlock screen.

**Comment by BlackDex** [comment]
> You can also see the installed version on the portal login/unlock screen.

That is only the web-vault version, not the Vaultwarden version, which is not the same.

**Comment by BlackDex** [comment]
Or, `/admin/diagnostics`

**Comment by l4rm4nd** [comment]
Or via API endpoint:

````
https://vaultwarden.example.com/api/version
````

**Comment by EricDuminil** [comment]
@l4rm4nd : Thanks. No `admin/` needed, which I explicitly do not want to enable.
