### ISSUE TITLE
[REQUEST][DOCS] Bitwarden with DB backends

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [dani-garcia/bitwarden_rs#1098]
Hey,
I am new to the **bitwarden_rs** and wanted to deploy with the **MySQL** backend, but I can`t find any documentation about the environment variables that I should use on my **docker-compose**. Shouldn't the **documentation** refer anything about them?
Thanks,
MiguelNdeCarvalho

**Comment by mqus** [comment]
Do you mean [this documentation](https://github.com/dani-garcia/bitwarden_rs/wiki/Using-the-MySQL-Backend) ?

**Comment by MiguelNdeCarvalho** [comment]
Hey, 
I saw that now, but I think it isn't not so visible for the newbies like me. In my opinion this should be on [Starting a Container](https://github.com/dani-garcia/bitwarden_rs/wiki/Starting-a-Container) page or at least referenced. What do you think?
Thanks,
MiguelNdeCarvalho

**Comment by mqus** [comment]
Your specific suggestion (to put some links to configuration articles into the Starting a Container Page) is very good . On the other hand, nothing about any bitwarden_rs configuration is included there, so you could be expected to look further to [Configuration overview](https://github.com/dani-garcia/bitwarden_rs/wiki/Configuration-overview) or other configuration articles. Feel free to alter the article as you like, anyone can edit in the wiki and afaik there is no process involved.

But I also think that we should restructure the documentation sometime in the future (the sections are not that fitting, "Configuration" is way too big to exist without subsections or/and many articles could use some other section like e.g. "Setup". But both names and also "Other Information" are just as inexpressive or even meaningless currently. Some articles only refer to containers, some only to binary releases, others are applicable for all install methods and the title isn't always indicative of that.

**Comment by MiguelNdeCarvalho** [comment]
Hey,
Really thanks for the fast response and I just opened this issue to express what I felt. When I get comfortable with it, I can try to do a pr and try to explain it a little better the **MYSQL** and **PostgreSQL** containers.
Thanks,
MiguelNdeCarvalho

**Comment by BlackDex** [comment]
Closing this ticket as it seems to be solved.
