### ISSUE TITLE
Can store attachments to mysql?

### ISSUE THREAD

**Issue by You66666666** [dani-garcia/bitwarden_rs#1100]
# Please submit all your feature requests to the forum
Link: https://bitwardenrs.discourse.group/c/feature-requests
Can store attachments to mysql?

**Comment by BlackDex** [comment]
In theory this could be possible, but in real life this is going to create issues.
For one, storing files in a database is not consider best practices, and we have to base64 encode the files or store them as blobs.
Which will increase the files and database very much and slow things down.

Is there a specific reason you want those files stored in the database?
The only thing i can think of is easy backup.
