### ISSUE TITLE
bitwarden_rs wont start up on Home Assistant with SSL cert

### ISSUE THREAD

**Issue by RonnieLima** [dani-garcia/bitwarden_rs#1102]
Installing the bitwarden_rs Add On on Home Assitant works fine.  Although upon starting the addon and viewing LOGS it sits at Starting NGINX, and never fully start making bitwarden unreachable.

Has anyone encounterd this before?

**Comment by mqus** [comment]
You should ask this in the https://github.com/hassio-addons/addon-bitwarden repository or in the forum. This issue seems highly specific to the configuration made by home assistant.

**Comment by Ornias1993** [comment]
Yeah this has nothing to do with Bitwarden_RS itself....

**Comment by BlackDex** [comment]
Seems to not be a bitwarden_rs issue it self. And maybe better for the forum https://bitwardenrs.discourse.group/c/third-party-help/6 .
