### ISSUE TITLE
[probably an upstream bug] Nested folder renaming

### ISSUE THREAD

**Issue by nicolaspernoud** [dani-garcia/bitwarden_rs#1103]
### Subject of the issue
When renaming a nested folder from the web interface, the subfolders go "out" of the renamed folder.

### Your environment
Web Vault Version 2.15.1 

### Steps to reproduce
If I have a folder Racine/Professionnel with subfolders, and I rename it to Racine/Professionnel_Test, all the sub folders keep the name Racine/Professionnel/Subfolder and go "out" of the Racine/Professionnel_Test directory.

### Expected behaviour
All the sub folders should be renamed accordingly.

**Comment by jjlin** [comment]
As you said, this is an issue on the client side, as the server doesn't have visibility into the (encrypted) folder names. Bitwarden doesn't have a true concept of nested folders; it's just a naming convention that is special-cased on the display side (https://bitwarden.com/help/article/folders/). The clients could conceivably generate multiple requests to rename all subfolders when you change the name on a parent folder, but you'd have to make a feature request for that (https://community.bitwarden.com/c/feature-requests/5/).

**Comment by nicolaspernoud** [comment]
Ok, thanks for the details. I will do the feature request.
