### ISSUE TITLE
Left and right sidebars show status are not saved. Are always expanded.

### ISSUE THREAD

**Issue by Haxy89** [dani-garcia/bitwarden_rs#112]
I want to save status of left or right sidebar. It should be possible to save if it expanded or not.
Currently status is not saved and sidebars are always expanded.

**Comment by dani-garcia** [comment]
Do you mean in the web vault? We use the upstream version directly, without modifications.

If you want to propose features to the upstream project, I suggest you use the official forums: https://community.bitwarden.com

**Comment by mprasil** [comment]
To add to that, as far as I know, this is purely client side functionality and there's nothing the server can do here.
