### ISSUE TITLE
Static file not found: bootstrap.css.map on admin panel

### ISSUE THREAD

**Issue by Eoras** [dani-garcia/bitwarden_rs#1121]
On the 1.16.3 version, when i go on admin panel à can see on logs:

> [2020-08-30 15:46:47.388][error][ERROR] Static file not found: bootstrap.css.map

Thank you

**Comment by dani-garcia** [comment]
This is because the source map file is not present, but that's only useful if you want to debug bootstrap, so it can be safely ignored.
