### ISSUE TITLE
Console errors header Unrecognized feature: 'ambient-light-sensor' &&  'vr'

### ISSUE THREAD

**Issue by Eoras** [dani-garcia/bitwarden_rs#1122]
I'm using the 1.16.3 version, and when i go on my web pannel, i got this error on the console:

> Error with Feature-Policy header: Unrecognized feature: 'ambient-light-sensor'.
> Error with Feature-Policy header: Unrecognized feature: 'vr'.

Thanks

**Comment by dani-garcia** [comment]
This should be fine, it's a relatively new browser header so not all browsers support all features, Firefox doesn't seem to complain to me but I get the same errors with Chrome. Regardless, it shouldn't cause any issues, not sure why they decided to mark them as errors.

**Comment by dc4444** [comment]
Chrome produces clicking on a Facebook pare. No content is then displayed.

**Comment by Mohammad-Ravand** [comment]
i have this problem too, how to fix this.

**Comment by Mohammad-Ravand** [comment]
my problem is i removed
`		@vite(['resources/js/app.js', "resources/js/Pages/{$page['component']}.vue"])
`

this section from app.blade.php file.
i replaced it back and it working.
