### ISSUE TITLE
Cannot send email

### ISSUE THREAD

**Issue by ForInfinity** [dani-garcia/bitwarden_rs#1128]
### Subject of the issue

When I try to send tow-factor email, smtp error occurs. See log for details.

### Your environment

Ubuntu 20.04 with docker.
* Bitwarden_rs version:  bitwardenrs/server:latest

* Install method:  Docker image with docker-compose
* Clients used: 
* Reverse proxy and version:  Nginx 
* Version of mysql/postgresql: 
* Other relevant information:  
Environment:
      _ENABLE_SMTP: "true"
      SMTP_HOST: "smtp.qiye.aliyun.com"
      SMTP_PORT: 465
      SMTP_SSL: "true"
      SMTP_FROM: "bitwarden@\*\*\*"
      SMTP_USERNAME: "bitwarden@\*\*\*"
      SMTP_PASSWORD: "***"
      SMTP_AUTH_MECHANISM: "Plain"
Mail Server is provided by Aliyun.

### Expected behaviour

Email should be sent.

### Relevant logs

bitwarden    | [2020-09-07 09:31:27.202][request][INFO] GET /api/two-factor
bitwarden    | [2020-09-07 09:31:27.202][response][INFO] GET /api/two-factor (get_twofactor) => 200 OK
bitwarden    | [2020-09-07 09:31:34.220][request][INFO] POST /api/two-factor/get-email
bitwarden    | [2020-09-07 09:31:34.279][response][INFO] POST /api/two-factor/get-email (get_email) => 200 OK
bitwarden    | [2020-09-07 09:31:36.076][request][INFO] POST /api/two-factor/send-email
bitwarden    | [2020-09-07 09:31:51.279][error][ERROR] SmtpError.
bitwarden    | [CAUSE] Io(
bitwarden    |     Os {
bitwarden    |         code: 11,
bitwarden    |         kind: WouldBlock,
bitwarden    |         message: "Resource temporarily unavailable",
bitwarden    |     },
bitwarden    | )
bitwarden    | [2020-09-07 09:31:51.279][response][INFO] POST /api/two-factor/send-email (send_email) => 400 Bad Request

**Comment by BlackDex** [comment]
That looks like the server wasn't able to be reached.
Is DNS working?

Could you check the status within in the `/admin/diagnostics` page to see if that works or not?

**Comment by ForInfinity** [comment]
> That looks like the server wasn't able to be reached.
> Is DNS working?
> 
> Could you check the status within in the `/admin/diagnostics` page to see if that works or not?

Thanks. Proved that SMTP Port is closed by ECS Server.
