### ISSUE TITLE
Email Two factor auth

### ISSUE THREAD

**Issue by andyjhall** [dani-garcia/bitwarden_rs#113]
Hi,

Trying to setup two factor authentication via email gives an onscreen error after entering the master password:

"Errors have occurred
An unexpected error has occurred."

The browser console then shows:
POST https://bitwardenserver/api/two-factor/get-email 404 ()

**Comment by dani-garcia** [comment]
Email is not implemented at the moment. If you need two factor auth, the most reliable option at the moment is TOTP auth.

**Comment by dani-garcia** [comment]
To keep the issue tracker more focused, I'm closing this issue in favor of the meta issue at #246.
