### ISSUE TITLE
Login Fail after Vault Lock (Windows 10 app)

### ISSUE THREAD

**Issue by robobio** [dani-garcia/bitwarden_rs#1130]
## Bug Description

I am hosting BW on the Docker on a Synology NAS and I have never experienced the issue I am about to describe. I have installed the BW app in a fresh Windows 10 installation and the first login to my vault was successful. After locking the vault, though, I was unable to reenter it. A message kept appearing stating that my Master Password is wrong, although it was clearly not. However, I am only able to login to my vault after clicking the log-out button and then re-entiring the Master Password for the new login. For now, I have managed to bypass the problem by using the setting which logs me out after timeout instead of locking the vault. The BW app on my phone works pretty fine as usual. I lock the vault and then unlock it with my Master Password and everything is as it is supposed to be. Same holds true for the BW app in a Windows 10 laptop that I have; all works fine. It seems to be a problem with the fresh windows 10 installation. I have posted this issue at the official BW github but I was forwarded here.  

## Steps To Reproduce

1. Open the BW app on Windows 10
2. Login to your BW account
3. Close BW, or lock the vault
4. Try to reenter your vault by entering the Master Password

## Expected Result

The expected outcome of the above steps would be to simply reenter the vault.

## Actual Result

What actually happens is that an error appears stating that the Master Password is incorrect.

## Screenshot

![BW_error](https://user-images.githubusercontent.com/70844077/92324918-70426d80-f046-11ea-9b8d-c0d1edf663f0.jpg)

## Environment

- Operating system: Windows 10
- Build Version: 1.20.1

**Comment by lakenen** [comment]
I am seeing the same issue on the OS X client.

**Comment by dani-garcia** [comment]
I think this is fixed in server version 1.16.2, unless this is a separate issue.

What server versions are you running?

**Comment by lakenen** [comment]
Ah, yep, just updated my image to 1.16.3 and that fixed it for me.

**Comment by robobio** [comment]
I thought I had updated it, but was wrong. I've updated the image and now all works pretty fine! Thank you very much for the help!
