### ISSUE TITLE
SMTP Gmail valid configuration?

### ISSUE THREAD

**Issue by ppadial** [dani-garcia/bitwarden_rs#1131]
HI all,

i've been trying to setup SMTP with a GMAIL account with no success. I've been going through all the issues but i couldn't find a recommended gmail settings.

I'm facing different errors with different configurations, so, anybody can post me a valid (working for him) Gmail classical smtp settings ?

Thanks in advance,

**Comment by GasperSB** [comment]
Hi!

Have you checked Google account settings for the GMAIL account you plan to use? 

Google Account -> Security -> scroll down until you hit Less secure app access -> make sure it is enabled (On)
by default less secure app access is disabled and this causes an SMTP error. 

My SMTP Email Settings on the BW admin page are the following:

Enabled:  checked (default: true)
Host:  smtp.gmail.com
Enable SSL:  checked (default: true)
Use explicit TLS:  unchecked(default: false)
Port:  587
From Address:  example@gmail.com (gmail account that is going to be used for sending emails)
From Name:  Bitwarden_RS
Username:  username for the above account
Password:  password for the above account

**Comment by ppadial** [comment]
I had the less secure apps marked, using your combo of settings it's working, so thankyou very much for your help @GasperSB .

**Comment by khongi** [comment]
@GasperSB thank you, it's working with your config. For anyone else wandering here, I left blank the following fields:

- SMTP Ath mechanism
- Server name sent during HELO

**Comment by ebanDev** [comment]
Hi ! I'd like to reopen this issue as Google recently changed its policy on "less secure" apps, they now require us to use OAuth (see https://support.google.com/accounts/answer/6010255), do you plan implementing this kind of feature ? :) Thanks

**Comment by stefan0xC** [comment]
@ebanDev As explained on the wiki page you create an app password for Vaultwarden. C.f. https://support.google.com/accounts/answer/185833

**Comment by BlackDex** [comment]
I'm not sure app passwords are still allowed.
There is support for XOAuth in lettere, but there is nothing within Vaultwarden to fetch the oauth token.
