### ISSUE TITLE
Push new docker image to support SSO

### ISSUE THREAD

**Issue by TynThordin** [dani-garcia/bitwarden_rs#1134]
Was released 2 days ago: https://github.com/bitwarden/web/releases/tag/v2.16.0

**Comment by BlackDex** [comment]
SSO Will not work without server-side changes.
We probably have to implement a lot of code to support this.
Only updating the web-vault will not do the trick.

**Comment by Ornias1993** [comment]
> SSO Will not work without server-side changes.
> We probably have to implement a lot of code to support this.
> Only updating the web-vault will not do the trick.

I've looked into it, the server-side changes are actually quite minimal. Their implementation is basically comparable to a reverse proxy in front of bitwarden (but integrated), it does not replace the normal login and master-password requirements. 

Some more info:
https://github.com/bitwarden/server/commits/fd6b10df564778ea73c00e8dcecc00aa74c5eb7d/src/Core/Enums/SsoType.cs
https://bitwarden.com/help/article/getting-started-with-sso/

**Comment by xdubx** [comment]
It would play into my hands if that were to be implemented. But I can only support the statement of Ornias1993.

**Comment by BlackDex** [comment]
Everyone can create a PR to implement this  😉.
Would be nice to have this, including all lot of other stuff.
When someone has time to implement this it will probably be pushed and merged.

**Comment by littlebigmedia** [comment]
This would be huge if added correctly!

**Comment by BlackDex** [comment]
To keep the issue tracker more focused, I'm closing this issue in favor of the meta issue at #246

**Comment by Ornias1993** [comment]
@BlackDex Besides the fact that it has nothing to do with a docker image needing to be pushed.

**Comment by pinpox** [comment]
I'd like to implement this, but would need a bit of guidance since I've not worked on valtwarden yet. @Ornias1993 What/where would be a good starting point for the changes you mentioned? Would be great to get any pointers!

**Comment by jiwanovski87** [comment]
@pinpox Have you already started with the implementation?

**Comment by pinpox** [comment]
@jiwanovski87 There has been some work here: https://github.com/dani-garcia/vaultwarden/pull/1955

**Comment by BloodyIron** [comment]
Can we get SAML?
