### ISSUE TITLE
How to use https connection in local network?

### ISSUE THREAD

**Issue by Haxy89** [dani-garcia/bitwarden_rs#114]
My local vault is on 192.168.0.5:8123 (docker on my NAS), port 8123 is forwarded to 80, so no http. 
How to use https connection to it? I know I need to set port binding 8123 to 443 but what about cert files?
Do I need to generate certs for 192.168.0.5? 
Docs (https://hub.docker.com/r/mprasil/bitwarden/#enabling-https) say I need a domain but I don't have a domain, I want to use it only in my local network and over vpn but with https connection to it.

Thanks ;)

**Comment by dani-garcia** [comment]
I don’t think you need a domain for HTTPS, only for U2F authentication.

You can generate a self signed certificate for your IP, but you’ll probably need to import it in all your devices to avoid certificate warnings.

**Comment by Haxy89** [comment]
Ok Thanks
