### ISSUE TITLE
Unable to disable icon downloads

### ISSUE THREAD

**Issue by klausmcm** [dani-garcia/bitwarden_rs#1145]
### Subject of the issue
I'm trying to disable icons for each entry in my vault. I checked **Disable Website Icons** under **Settings** and when I hit **Save**, a green confirmation pops up that says **Options updated**.

![image](https://user-images.githubusercontent.com/14914359/93560244-91ed0000-f936-11ea-8141-4cdd998b769b.png)

I then log out and close the browser. After I open a new browser and log back in, icons are being downloaded again and **Disable Website icons** is unchecked.

New password entries stick so I don't think this is a permissions issue on the filesystem.

### Your environment

* Bitwarden_rs version: 2.15.1

* Install method: Docker
* Clients used: Browser (Firefox)
* Reverse proxy and version: nginx 1.14.2
* Version of mysql/postgresql: MariaDB 10.4
* Other relevant information: 

### Steps to reproduce
See summary at the top.

I also disabled icon downloads as admin but this doesn't seem to have any effect on the issue described at the top.

![image](https://user-images.githubusercontent.com/14914359/93560387-e6907b00-f936-11ea-9380-067194b29c9d.png)

### Expected behaviour
Setting should stick.

### Actual behaviour
Setting is always unchecked.

### Relevant logs
Not sure which logs to provide.

**Comment by BlackDex** [comment]
Hello @klausmcm ,

Those options there to disable the icon downloads have nothing to do with the server side.
Those options are client side only and thus should be saved in your browsers storage somewhere and are per user.

If you want to disable icon downloading on the whole server you can either use the `/admin` interface to disable them under `General Settings > Disable icon downloads` and check that box, save the settings and you should not see any icons anymore.
