### ISSUE TITLE
New vulnerability: Basic Auth sent out automatically

### ISSUE THREAD

**Issue by astor99** [dani-garcia/bitwarden_rs#1149]
Hi Daniel,

Did you see that https://threadreaderapp.com/thread/1307614248835731456.html ?
Can you update your code when ready ?
https://github.com/bitwarden/browser/pull/1397
Thanks!

**Comment by jjlin** [comment]
This issue is specific to the upstream Bitwarden browser extension code, and doesn't impact any bitwarden_rs deliverables.

**Comment by astor99** [comment]
Great! thanks for your fast reply
