### ISSUE TITLE
Transfer sqlite to mariadb

### ISSUE THREAD

**Issue by gkl1368** [dani-garcia/bitwarden_rs#1157]
When I restore database dump to mariadb, it shows Duplicate entry '{email}' for key 'email'

**Comment by BlackDex** [comment]
Have you check the steps in: https://github.com/dani-garcia/bitwarden_rs/wiki/Using-the-MySQL-Backend

**Comment by gkl1368** [comment]
> Have you check the steps in: https://github.com/dani-garcia/bitwarden_rs/wiki/Using-the-MySQL-Backend ?
> It explains what you need to do to get this working.
Now I use this way
mysql --password --user=bitwarden_rs
use bitwarden_rs
source /bw-data/mysqldump.sql
exit

But after that I can't login. It shows Username or password is incorrect. Try again

And I use Navicat to transfer database Users, It show Duplicate entry '{email}' for key 'email'

**Comment by BlackDex** [comment]
All you need to do is create the dump like in the wiki article. Follow every other step there except the import. Now use that mysqldump.sql in your database manager as the import file, but make sure all tables, except __diesel_migraties before you do thr import

**Comment by gkl1368** [comment]
Resolve. LDAP sync auto add email to user table.
