### ISSUE TITLE
Error of edit Organization information

### ISSUE THREAD

**Issue by gkl1368** [dani-garcia/bitwarden_rs#1159]
When I edit organization information like Business name/Identifier, it shows "An error has occurred.
Error saving organization". 
The bitwarden log:
is [error][ERROR] Error saving organization.
[CAUSE] DatabaseError(
    ForeignKeyViolation,
    "Cannot delete or update a parent row: a foreign key constraint fails (`bitwarden`.`ciphers`, CONSTRAINT `ciphers_ibfk_2` FOREIGN KEY (`organization_uuid`) REFERENCES `organizations` (`uuid`))",
)

**Comment by BlackDex** [comment]
This should be fixed when https://github.com/dani-garcia/bitwarden_rs/pull/1150 is merged.

**Comment by gkl1368** [comment]
After upgrade new test version, can't edit zip code in organization.

**Comment by gkl1368** [comment]
> This should be fixed when #1150 is merged.

After upgrade new test version, It can edit organization information, but can't edit zip code in organization.
