### ISSUE TITLE
Unable to unlock vault with Firefox extension, have to log out and then back in. 

### ISSUE THREAD

**Issue by w4rc0n** [dani-garcia/bitwarden_rs#1162]
### Subject of the issue

Anytime my Firefox session is restarted, I am required to unlock my vault again like normal. However, master password will not unlock the vault. I get: "An Error Has Ocurred: Invalid master password"

However, if I log out, then log back in, it requests my YubiKey again, and allows me to log back in with that very same password.
### Your environment

* Bitwarden_rs version: 2.15.1

* Install method: Docker image
* Clients used:  Firefox extension
* Reverse proxy and version:  nginx version: nginx/1.18.0 (Ubuntu)
* Version of mysql/postgresql: 
* Other relevant information: 

### Steps to reproduce

Restart Firefox session after being signed in, attempt to unlock the vault with the masterpassword.

I start the docker instance like such:
docker run -d --name bitwarden -e SIGNUPS_ALLOWED=false -e DOMAIN=REDACTED -e YUBICO_CLIENT_ID=REDACTED -e YUBICO_SECRET_KEY=REDACTED -v /bw-data/:/data/ -p 800:80 bitwardenrs/server:latest
### Expected behaviour

Should be able to unlock my vault using my master password without relogging
### Actual behaviour

I am unable to unlock my vault without relogging.

**Comment by ruben-kinship** [comment]
I experience the same issue!

**Comment by santiagon610** [comment]
:+1: I've seen this with the MacOS desktop client as well.

Environment:
- Install method: Docker image
- Reverse proxy: Nginx 1.14.1-9 on RHEL 8.2
- Client used: MacOS desktop client 1.20.1

**Comment by BlackDex** [comment]
This has already been fixed in the latest `texting` image on docker.
Please use that one too fix these issues.

**Comment by w4rc0n** [comment]
Not sure I want to use a testing image for my production bitwarden. I suppose I'll wait until it's in `latest`

**Comment by santiagon610** [comment]
> This has already been fixed in the latest `testing` image on docker.
> Please use that one too fix these issues.

Thanks @BlackDex - do you happen to know which PR resolved this?

**Comment by BlackDex** [comment]
I do, https://github.com/dani-garcia/bitwarden_rs/pull/1158 .

**Comment by briceparmentier** [comment]
Hi, I'm facing the same issue on Firefox.
Thanks @BlackDex for fixing this.
I think I will also wait for the fix to be ported in the "latest" docker image. but I'm running the raspberry pi version of it. Will this also be updated with the fix?
My question is how would we get the fix ? Do we need to download/reinstall something, or will it pull the changes automatically? Sorry for the noob question, I'm quite new to docker and this is the first time I'm using this kind of self-hosted tool and deployment.
Will we need to update something on the client side also (firefox plugin, android app...) ?
Thanks a lot !

**Comment by DarkMio** [comment]
Is there an ETA when this is released on `latest`? Doesn't seem to be in `1.17.0`.

**Comment by BlackDex** [comment]
@DarkMio This has been fixed an is available in the latest 1.17.0 version.
I also read reports that some users needed to double check there extension updates for this to be fixed.

**Comment by BlackDex** [comment]
@briceparmentier Which image are you using?
We do not update the old raspberrypi image anymore since we have all images now in bitwardenrs/server where `testing` is linked to the master branch, and `latest` is linked to the latest tagged version, which in this case is `1.17.0`

**Comment by DarkMio** [comment]
@BlackDex It currently seems to work, looks like fixed for now. If any issues come up, I'll keep you posted.

The changelog didn't mention the inclusion of that fix (or I've missed it).

**Comment by santiagon610** [comment]
👍  on the fix, thanks folks!

**Comment by briceparmentier** [comment]
> 
> 
> @briceparmentier Which image are you using?
> We do not update the old raspberrypi image anymore since we have all images now in bitwardenrs/server where `testing` is linked to the master branch, and `latest` is linked to the latest tagged version, which in this case is `1.17.0`

@BlackDex I'm using raspberrypi image since I'm running it on .... a Raspberry Pi :p
By this do you mean that I can switch to the "server" version of the docker image without any trouble on RPi, or that I can't use it on RPi anymore?
I'm a bit concerned about upgrading / changing the docker image I'm using... I'm not very comfortable with tbh, because I don't understand very well how docker behaves. If I stop my machine, change the command line to use the server one, and run it again, will I keep all the data in the previous image?
Thanks again guys!

**Comment by briceparmentier** [comment]
Oh ok I've read the introduction on the wiki, I wasn't aware of the modification to migrate to multiarch image.
I'll walk into this :)
