### ISSUE TITLE
Unexpected "email domain not eligible for invitations" failure

### ISSUE THREAD

**Issue by bland328** [dani-garcia/bitwarden_rs#1163]
### Subject of the issue
I've run into just one email address that I can't invite to Bitwarden_rs because of an `Email domain not eligible for invitations` error. The email address is question is a valid gmail.com address, and I've had no problem with other gmail.com addresses.

### Your environment
* Bitwarden_rs version: 1.16.3
* Install method: Docker image
* Reverse proxy and version: nginx 1.18.0

### Steps to reproduce
When logged in to the Bitwarden_rs web interface as Owner, I attempt to invite "xxxxxxxxx99@gmail.com"
_(I've redacted the real address, which is nine lowercase alpha characters followed by two digits.)_

### Expected behaviour
It should work, just like all the other invitations I've sent, including one to "xxxxx99@gmail.com"
_(fewer alpha characters in this case, but otherwise the same form as above.)_

### Actual behaviour
This error message slides in from the right:
`An error has occurred.`
`Email domain not eligible for invitations`

### Relevant logs
These four lines _(the third being blank)_ are logged when I click Save.
_(I've redacted the UUID in the first line.)_

`[2020-09-29 11:05:32.140][request][INFO] POST /api/organizations/[REDACTED_UUID]/users/invite`
`[2020-09-29 11:05:32.141][error][ERROR] Email domain not eligible for invitations`
` `
`[2020-09-29 11:05:32.141][response][INFO] POST /api/organizations/<org_id>/users/invite (send_invite) => 400 Bad Request`

### Additional information
Since running into this problem, I've successfully invited other `@gmail.com` accounts, but this particular address continues to fail.

Also, I haven't yet tried restarting the Docker container. I realize that _might_ put things right, but I'm hanging on for now in case I can collect useful troubleshooting data before I do that.

I'm happy to collect any additional information that might help troubleshoot this. Thanks for any assistance.

**Comment by BlackDex** [comment]
Do you have anything configured regarding allowed domains? Or not inviting users? Are you able to invite the user via the admin interface?

**Comment by bland328** [comment]
Ah-ha! Thank you--I do have domains restricted, which I apparently did long ago upon initial set up, and forgot about.

What threw me off was that I do already have an @gmail.com user successfully invited, which I must've forgotten was done from the admin interface.

I was able to successfully invite the new @gmail.com user via the admin interface, despite the domain whitelist setting--is that intentional?

**Comment by jjlin** [comment]
Yes, the admin page generally ignores any configured restrictions, considering anyone with access to the admin page can disable those restrictions anyway.

**Comment by bland328** [comment]
Makes sense. Sorry for the false alarm, and thanks greatly for your help!
