### ISSUE TITLE
"Username or password is incorrect." after upgrade from 1.1.0

### ISSUE THREAD

**Issue by themightychris** [dani-garcia/bitwarden_rs#1165]
I have a ~2 year old instance running I believe 1.1.0 from `mprasil/bitwarden:latest`

I tried dropping `bitwardenrs/server:latest` into my `docker-compose.yml` and doing `docker-compose pull && docker-compose up -d` and that seems to work, but the system ends up in a state where all existing logins result in "Username or password is incorrect."

Migrations appear to run during startup:

```
Attaching to bitwarden_web_1
web_1  | /--------------------------------------------------------------------\
web_1  | |                       Starting Bitwarden_RS                        |
web_1  | |                           Version 1.16.3                           |
web_1  | |--------------------------------------------------------------------|
web_1  | | This is an *unofficial* Bitwarden implementation, DO NOT use the   |
web_1  | | official channels to report bugs/features, regardless of client.   |
web_1  | | Send usage/configuration questions or feature requests to:         |
web_1  | |   https://bitwardenrs.discourse.group/                             |
web_1  | | Report suspected bugs/issues in the software itself at:            |
web_1  | |   https://github.com/dani-garcia/bitwarden_rs/issues/new           |
web_1  | \--------------------------------------------------------------------/
web_1  | 
web_1  | Running migration 20180919144557
web_1  | Running migration 20181127152651
web_1  | Running migration 20190526216651
web_1  | Running migration 20191010083032
web_1  | Running migration 20191117011009
web_1  | Running migration 20200313205045
web_1  | Running migration 20200409235005
web_1  | Running migration 20200701214531
web_1  | [2020-09-30 15:42:42.581][start][INFO] Rocket has launched from http://0.0.0.0:80
```

Reverting to the old image and restoring the `/data` directory gets things working again, but I'd like to figure out how to upgrade this instance and the database along with it. Are there any special steps I might be missing for this big version jump outside the automatic migrations?

**Comment by BlackDex** [comment]
What is the error you get? Either browser or bitwarden log, or both when you try to login?

**Comment by themightychris** [comment]
@BlackDex the quote in the issue title is pasted verbatim from the container log, and I believe is the same wording I saw in the browser. I'd have to break it again with an upgrade to confirm, given some tips on what to run / look for I could try again and collect more info to report back before reverting. thanks!

**Comment by BlackDex** [comment]
i would have to try and do the same my self to figure out what could be the case here.
Rather busy the past few day's so don't know if i have the time.

**Comment by themightychris** [comment]
What are the odds that migrating to mysql or postgres before migrating could help my situation or make debugging easier?

**Comment by BlackDex** [comment]
i actually have no clue.
The problem is that you probably can't get a version that old with mysql any more.
Since mprasil's docker hub repo is empty now. That makes it hard for me to test also.

**Comment by themightychris** [comment]
@BlackDex if I set up a VM with a clone of my current database+image and a test user added, would you be interested in having a look?

**Comment by BlackDex** [comment]
Do you have many users or orgs?

**Comment by BlackDex** [comment]
@themightychris What i would need is probably a before and after sqlite database to spot the differences there with indeed a test user which would have access to the before database, and not to the after one.

Then those credentials and both databases would be enough for me.

**Comment by BlackDex** [comment]
@themightychris Actually, if you have the old database with a working user for me, that would be enough also.
Since i can just start my dev instances here with that, and it will do the migration.

**Comment by BlackDex** [comment]
@themightychris on the Matrix Chat there was someone which had similar issues and also uses docker-compose.
He did the following, and that resolved his issue.
```
docker-compose stop bitwarden
docker-compose pull
docker-compose up -d
docker-compose restart bitwarden
```

Could you try the same steps and see if that resolves your issue as well?

**Comment by potvinp** [comment]
> @themightychris on the Matrix Chat there was someone which had similar issues and also uses docker-compose.
> He did the following, and that resolved his issue.
> 
> ```
> docker-compose stop bitwarden
> docker-compose pull
> docker-compose up -d
> docker-compose restart bitwarden
> ```
> 
> Could you try the same steps and see if that resolves your issue as well?

Good morning,

I was having the same issue as @themightychris, and after running the commands you mentioned I no longer receive the error and everything appears to be running without issues. Thanks!

**Comment by BlackDex** [comment]
@themightychris Were you able to solve the issue?

**Comment by pvlplv** [comment]
Resolved same issue for me

> @themightychris on the Matrix Chat there was someone which had similar issues and also uses docker-compose.
> He did the following, and that resolved his issue.
> 
> ```
> docker-compose stop bitwarden
> docker-compose pull
> docker-compose up -d
> docker-compose restart bitwarden
> ```
> 
> Could you try the same steps and see if that resolves your issue as well?

**Comment by BlackDex** [comment]
Closing this ticket die to inactivity.
Also issue seems to be resolved by other user which has the same issue.
