### ISSUE TITLE
The Web module is not automatically updated with the new image

### ISSUE THREAD

**Issue by blackneil** [dani-garcia/bitwarden_rs#1167]
Synology with Dockers.

I come to remove the image, download the new latest image and reconfigure the image.

Server Installed equal the latest but the Web installed didn't equal the latest.

Server Installed (Ok)     :    1.16.3 
Server Latest     :    1.16.3 
Web Installed (Update)     :    2.15.1 
Web Latest     :    2.16.1 

Normal or not ?

What's the way (if it's normal) to upgrade the Web module to the latest ?

**Comment by dani-garcia** [comment]
Yeah it's normal, there needs to be a new release of bitwarden_rs for the new web vault to be updated, if you use the testing image which is updated more often, you'll get web vault 2.16.0, which will update to 2.16.1 once today's images are built (they are building right now).

In the next couple of days I'll make a new stable release that includes the latest vault as well.
