### ISSUE TITLE
Database migration to 1.17.0 fails on mariadb

### ISSUE THREAD

**Issue by ToeiRei** [dani-garcia/bitwarden_rs#1182]
### Subject of the issue

`#1005 - Can't create table bitwarden.favorites (errno: 150 "Foreign key constraint is incorrectly formed")`

### Your environment

* Bitwarden_rs version: 
1.16.3
* Install method: docker-compose using bitwardenrs/server-mysql
* Clients used: 
* Reverse proxy and version: 
* Version of mysql/postgresql: 10.5.6-MariaDB-1:10.5.6+maria~buster - mariadb.org binary distribution
* Other relevant information: 

### Steps to reproduce

1. Install 1.16.3
2. Update to 1.17.0

### Expected behaviour

I would expect the database migration to work

### Actual behaviour

Docker container looped on starting the migrations. Trying to run it manually it said ``#1005 - Can't create table `bitwarden`.`favorites` (errno: 150 "Foreign key constraint is incorrectly formed")``

which is related to 
```
CREATE TABLE favorites (
  user_uuid   CHAR(36) NOT NULL REFERENCES users(uuid),
  cipher_uuid CHAR(36) NOT NULL REFERENCES ciphers(uuid),

  PRIMARY KEY (user_uuid, cipher_uuid)
);
```
in the up script

**Comment by BlackDex** [comment]
This is weird, i just did the exact same, and have no issues.

Also using the same mariadb version
```
mariadb  Ver 15.1 Distrib 10.5.6-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

It is also strange that you can see these error's at all, because foreign-key checking is disabled during migrations because the migrations could create these issues when the order is not completely ok, or we need to do some specials stuff like migrating some data from table x to y.

If you start the server again, does it still produce the same error?
And what if you restart MariaDB first?

**Comment by ToeiRei** [comment]
![image](https://user-images.githubusercontent.com/5990591/95683348-fffdad80-0bea-11eb-851d-9d81e2d48de7.png)

That's all I get - even with a restart

**Comment by BlackDex** [comment]
Wel that is strange. It looks like it is trying to retry it a few times.

**Comment by ToeiRei** [comment]
I got into the error and I think I got a clue: Collation mismatches. Not a big deal.

**Comment by BlackDex** [comment]
Great that you have find the solution.
Could the collation setting being something we need to check, verify or warn on?

**Comment by ToeiRei** [comment]
I would suggest verifying those wouldn't hurt. In my case I think it happened via migrating via various MySQL/MariaDB hosts...

**Comment by BlackDex** [comment]
Thanks, i have added this to the meta feature request #246
