### ISSUE TITLE
Evitar que se dupliquen las organizaciones.

### ISSUE THREAD

**Issue by peroda** [dani-garcia/bitwarden_rs#1185]
Sería interesante si las organizaciones que pueden crear los usuarios no se solapasen.

# Please submit all your feature requests to the forum
Link: https://bitwardenrs.discourse.group/c/feature-requests

**Comment by BlackDex** [comment]
> Translation: It would be interesting if the organizations that users can create do not overlap.

That could be possible maybe, but it's not how the upstream project works i think. And i think we should mimic that as close as possible.
