### ISSUE TITLE
No permite guardar los datos de Nombre empresa e identificador de las organizaciones

### ISSUE THREAD

**Issue by peroda** [dani-garcia/bitwarden_rs#1186]
### Subject of the issue
No se guardan los datos de organización ( nombre empresa e identificador)

### Your environment
* Bitwarden_rs version:
* Install method: Docker
* Clients used: web
* Reverse proxy and version: haproxy 1.8
* Version of mysql/postgresql: sqlite
* Other relevant information:

### Steps to reproduce
Despues de crear una organización nos desplazamos a la pestaña ajustes y completamos los datos de la organización

### Expected behaviour
Se deberían almacenar los datos en la bd sqlite después de guardar, pero no se están guardando

### Actual behaviour
Una vez que pulsamos en guardar nos muestra mensaje de que se ha guardado correctamente pero al refrescar la página vuelven a aparecer vacios esos campos del formulario.

**Comment by BlackDex** [comment]
Hello @peroda, it would be better to ask this question in english, but luckily there are translation apps.

We do not save that information because we don't use it anywhere.
It's also not necessary for the web-vault or other clients to work at all.

Is there a reason you need this specifically?

**Comment by peroda** [comment]
Sorry for writing in spanish.
No, it is not necessary. I commented on it in case it was a failure. Thx
