### ISSUE TITLE
Admin Page unable to read the changed value in config.json

### ISSUE THREAD

**Issue by wcjxixi** [dani-garcia/bitwarden_rs#1187]
I change the value of setting in Admin Page, it can write to config.json, but when I change value of setting in config.json directly, Admin Page unable to read the changed value in config.json.

I have tried to clear the browser's cooke and cache, but still the same.

I think the permissions of the config.json file are correct.

![permissions](https://user-images.githubusercontent.com/45098360/95868987-75a97b00-0d9d-11eb-8258-1f230178cb74.png)

### My Environment

- Server Installed: 1.17.0
- Web Installed: 2.16.1

**Comment by BlackDex** [comment]
Did  you also restarted bitwarden? Because it only reads that file during start.

**Comment by wcjxixi** [comment]
> Did you also restarted bitwarden? Because it only reads that file during start.

Thank you, it has been resolved, as you said, bitwarden needs to be restarted
