### ISSUE TITLE
Can't move read-only objects

### ISSUE THREAD

**Issue by Dubz** [dani-garcia/bitwarden_rs#1188]
### Subject of the issue
A user that is set to read-only mode for a collection cannot edit the item to move it in their collection through the app.
I'm not sure if this is limited to everywhere, or just editing to change its folder. You *might* still be able to do it from the website. I'm not sure if this is a restriction on this end, or Bitwarden's end. I figured I'd report it here first, though.

### Your environment
* Bitwarden_rs version:
Server Installed Ok
    1.17.0
Server Latest
    1.17.0
Web Installed Ok
    2.16.1
Web Latest
    2.16.1

* Install method: Docker
* Clients used: N/A
* Reverse proxy and version: N/A
* Version of mysql/postgresql: N/A
* Other relevant information: Disabled read-only for the user, then they could update. Re-enabled read-only afterwards.

### Steps to reproduce
Normal instance, add a member to a collection with read-only access.

### Expected behaviour
They should be able to edit it to set the folder for this item different than `No Folder`

### Actual behaviour
Error message states they cannot change it.

### Relevant logs
None, yet. Will try to get them later once I get a chance to.

**Comment by jjlin** [comment]
This is a known issue that affects upstream Bitwarden as well:

https://github.com/dani-garcia/bitwarden_rs/blob/257b143df1b01fbd5dcdf84ef3ab08a9d9a0076f/src/api/core/ciphers.rs#L413-L416

It's a consequence of Bitwarden's current design, where per-user metadata like favorite status and folder membership are mixed with the cipher data itself. It could be worked around, but just hasn't been done yet.

**Comment by Dubz** [comment]
Okay. Thank you for this quick response, I will pass the suggestion on to Bitwarden then, so they can handle it instead. I was initially going to do that, but remembered with using a third-party version, things *might* be a little different.
