### ISSUE TITLE
PostgreSQL backend doesn't use the "uuid" type

### ISSUE THREAD

**Issue by pounard** [dani-garcia/bitwarden_rs#1189]
Hello, I noticed that PostgreSQL schema doesn't use the `uuid` type for UUIDs, is there a reason for this ?

**Comment by BlackDex** [comment]
I actually have no idea.
I do see we use varchar and char for uuid's.
I don't know if there is a specific reason for not using uuid.

**Comment by dani-garcia** [comment]
I think it's done that way to keep consistency with SQLite, which doesn't have a specific uuid type.

**Comment by pounard** [comment]
For scaling, UUID performance on PostgreSQL is much better than using VARCHAR (CPU and as well memory consumption) - just highlighting this. I regularly do web applications that uses them, there is no consequence in using a VARCHAR on sqlite side and the real UUID type on the pgsql type besides the fact that pgsql will validate them on UPDATE/INSERT operations (with a new error case you must handle in business code, of course). But using a good uuid library, such a validation errors actually never happened to me.

**Comment by BlackDex** [comment]
I'm not sure what to do with this ticket. Do we want to leave it as-is so that we keep a more uniform format in code, or do we want to change this to _increase performance and scaling_?

I am kinda in favor of keeping it as-is. Also because the main developers/contributors do not use Postgresql them self's as far as i know.
@dani-garcia, what do you think?

**Comment by pounard** [comment]
@BlackDex I have no strong feeling, I originally created purely for informational purpose.

**Comment by dani-garcia** [comment]
If I had to do it all again I'd go with UUIDs too, but seeing as we use uuids everywhere I'd rather keep it as it is now, just to avoid the big migrations we'd have to do to swap them. If the performance ever gets noticeably bad, we can always revisit this decision.
