### ISSUE TITLE
Build fails 

### ISSUE THREAD

**Issue by DSIW** [dani-garcia/bitwarden_rs#1190]
### Subject of the issue
Build fails

### Your environment
* Bitwarden_rs version: 1.17.0
* Install method: built from source

### Steps to reproduce
```
git fetch
git checkout 1.17.0
cargo build -j 1 --release --features sqlite
```

### Expected behaviour
Build succeeds

### Actual behaviour
Build fails

### Relevant logs
```
[...]
Compiling idna v0.2.0
Compiling phf v0.7.24
error: failed to run custom build command for `pear_codegen v0.1.4`

Caused by:
  process didn't exit successfully: `.../bitwarden_rs/target/release/build/pear_codegen-7be71e5879f015c1/build-script-build` (exit code: 101)
  --- stderr
  Error: Pear requires a 'dev' or 'nightly' version of rustc.
  Installed version: 1.46.0 (2020-08-24)
  Minimum required:  1.31.0-nightly (2018-10-05)
  thread 'main' panicked at 'Aborting compilation due to incompatible compiler.', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.1.4/build.rs:24:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This error message doesn't make sense, because my installed version is higher than the minimum.

**Comment by BlackDex** [comment]
You need a nightly of rust/cargo, you are using stable at the moment.
Which is strange since the rust-toolchain should select the correct version automatically.

**Comment by DSIW** [comment]
Using the [async branch](https://github.com/dani-garcia/bitwarden_rs/tree/async) works for me. But would be great to have that functionality also in `master` so that also the stable version of rust would work.

**Comment by BlackDex** [comment]
There is a reason it isn't into master yet. We are waiting for rocket to release the stable async branch if I'm correct.

When that happens we should be able to use stable.
Until then we need to wait.

**Comment by DSIW** [comment]
Sounds good! Thank you for taking care :+1:
