### ISSUE TITLE
SSO with _RS

### ISSUE THREAD

**Issue by yurividal** [dani-garcia/bitwarden_rs#1193]
Is SSO supported on Bitwarden_rs ? I cant seem to fund any documentation, since SSO seems to be a pretty new feature on upstream BW

**Comment by mqus** [comment]
Short answer: no. 

Long answer: look at #246 and #1194

**Comment by BlackDex** [comment]
This has already been added to the meta features request.
I'll there for will close this ticket to keep all clean
