### ISSUE TITLE
Alpine image does not respect TZ environment variable

### ISSUE THREAD

**Issue by snevas** [dani-garcia/bitwarden_rs#1197]
### Alpine image does not respect TZ environment variable
When starting the latest alpine image, UTC time is used. This breaks fail2ban

### Your environment

* Bitwarden_rs version: 1.17.0 

* Install method: Docker image
* Clients used: Web
* Reverse proxy and version: nginx 1.14.2-2+deb10u3
* Other relevant information: TZ=Europe/Amsterdam

### Steps to reproduce
Only changed image: 'bitwardenrs/server' to image: 'bitwardenrs/server:alpine'
### Expected behaviour
Would respect TZ-variable

### Actual behaviour
Was UTC time (-2 hours)

### Relevant logs

'bitwardenrs/server':
> bitwarden    | [2020-10-22 15:10:34.092][start][INFO] Rocket has launched from http://0.0.0.0:80

'bitwardenrs/server:alpine':
> bitwarden    | [2020-10-22 13:15:00.005][start][INFO] Rocket has launched from http://0.0.0.0:80

**Comment by snevas** [comment]
Also adding the following volume did not work:
> '/etc/localtime:/etc/localtime:ro'

**Comment by davidkna** [comment]
`/etc/localtime` might be a symlink. You could try `/usr/share/zoneinfo/Europe/Amsterdam:/etc/localtime:ro` instead.

**Comment by snevas** [comment]
@davidkna still does not work. The alpine dockerfile is missing the tz package and hard sets UTC. See: https://quaded.com/docker-apline-configure-timezone/
and
https://github.com/dani-garcia/bitwarden_rs/blob/master/docker/amd64/Dockerfile.alpine

**Comment by briffle** [comment]
By default, alpine does not include the tzdata package. ( https://gitlab.alpinelinux.org/alpine/aports/-/issues/5543 ) It adds 3.5MB of space to the image, which is rather significant compared to the bare alpine image

To use the timezones, you would need to use apk to install tzdata.

**Comment by snevas** [comment]
I think the 3.5MB would justify timezone support. But that's up to @dani-garcia .

Adding the package manually would break my auto-updating and I won't use this image without timezone support because it breaks fail2ban.

**Comment by polyzen** [comment]
Making a read-only bind mount to the host's `/etc/localtime` seems to have worked for me. `-v /etc/localtime:/etc/localtime:ro` should be the option -- I had manually edited my `config.v2.json` to add the mount.

**Comment by snevas** [comment]
Retested and confirmed working! No need to add anything to the alpine image :+1:

**Comment by polyzen** [comment]
Seems like using the `logtimezone = UTC` option for your jail might be cleaner.
