### ISSUE TITLE
Building Binary First Start MariaDB Error

### ISSUE THREAD

**Issue by r4tze** [dani-garcia/bitwarden_rs#1200]
# Subject of the issue

Fresh compiled executable of Bitwarden_rs does not start, does not initialize the database

# Your environment

Bitwarden_rs version: Version 1.17.0  
Install method: build from source
Clients used: web
Reverse proxy and version: no
Version of mysql/postgresql: MariaDB 10.4.14
Other relevant information:

# Steps to reproduce

Created a database, compiled the bitwarde_rs mySQL Binary, configured the mysql connection string in the .env file, start the bitwarden_rs executable

# Expected behaviour

A running bitwarden_rs

# Actual behaviour

# Got error
`Executing migration script 20180114171611/up.sql
[2020-10-26 17:54:46.480][bitwarden_rs][ERROR] Error creating database pool: DieselMigError.
[CAUSE] QueryError(
    DatabaseError(
        __Unknown,
        "Specified key was too long; max key length is 767 bytes",`

# Relevant logs

---

# More Information
I created the database as described in the wiki. I also tried to change the sql table rows to dynamic length, but as I can see there is only one table:
`__diesel_schema_migrations `

**Comment by BlackDex** [comment]
This could be a collation issue. Please check which charset is used by default for the database.

**Comment by r4tze** [comment]
I created the Database with these charset:
`DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`

Should I use UTF-8? I did not find any charset information in the wiki.

**Comment by BlackDex** [comment]
Yes you need utf8 which is an alias for utf8mb3.
Using utf8mb4 limits the size to 767. This is an innodb limitation.

**Comment by r4tze** [comment]
Okay, this solved the issue! 
`ALTER DATABASE BitwardenDB CHARACTER SET='utf8'  COLLATE='utf8_bin'`
Thanks for the help!

**Comment by jjlin** [comment]
It would probably be better to just replace `VARCHAR(255)` for storing email addresses with `VARCHAR(191)` or smaller to avoid this issue. The RFCs specify that an email address can be up to 320 bytes, so the choice of 255 isn't even for RFC conformance.
