### ISSUE TITLE
Have a plan to support ECC certificates?

### ISSUE THREAD

**Issue by Zerorigin** [dani-garcia/bitwarden_rs#1205]
The same as the title. https://github.com/dani-garcia/bitwarden_rs/issues/630

**Comment by jjlin** [comment]
This really depends on [Rocket](https://rocket.rs/), and I don't see any indications of a plan for ECC support on that side. As noted in https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-HTTPS, using a mature reverse proxy is recommended anyway.

**Comment by BlackDex** [comment]
As a reference: https://github.com/SergioBenitez/Rocket/issues/1461

**Comment by BlackDex** [comment]
Closing this as this is not a bitwaren_rs issue it self.
And again, we do strongly suggest to use a mature reverse proxy to handle ssl instead of bitwarden_rs it self.
