### ISSUE TITLE
improve the sending of emails

### ISSUE THREAD

**Issue by Gurkengewuerz** [dani-garcia/bitwarden_rs#1207]
### improve the sending of emails

I am using bitwarden_rs with my email server to send notification. Currently my rspamd adds the spam header because the mail had no message id. A value of 6 is marked as spam in the default rspamd configuration.
Is there a way to improve this behavior?

```
MISSING_MID (2.5)                         Message id is missing
HTML_SHORT_LINK_IMG_1 (2)                 Short html part (0..1K) with a link to an image
MIME_BASE64_TEXT_BOGUS (1)                Has text part encoded in base64 that does not contain any 8bit characters
URI_COUNT_ODD (1) [3]                     Odd number of URIs in multipart/alternative message
MIME_GOOD (-0.1) [multipart/alternative]  Known Content Type
MIME_BASE64_TEXT (0.1)                    Has Text Part encoded in base64
```

**Comment by BlackDex** [comment]
I noticed this to e few days back. I didn't had any troubles with this. But i know i can be a trigger.
I'll see if I can add this, shouldn't be too hard.

**Comment by Gurkengewuerz** [comment]
@BlackDex thanks would be great! :)
I'm no into rust but maybe i've found something useful in lettrehttps://github.com/lettre/lettre/commit/50d96ad8dfd8295fca22d358dae1fae0fde7e19b

**Comment by BlackDex** [comment]
@Gurkengewuerz i have made some changes which helps preventing spam-triggers.
See #1229 for the changes.
I noticed it also triggered regarding odd uri counts because the plain/text version didn't contained the github link to this project.
So i added that also. And i noticed it also triggered on the plain/text and html/text not being similar, this was because some plain/text messages had HTML code, i removed that also, which removed that trigger.

I tested this by using https://www.mail-tester.com/ which started off giving a 7/10 score, and afterwards it reported a 10/10 score :).

**Comment by Gurkengewuerz** [comment]
wow this sounds awesome @BlackDex! Lets hope the PR get merged soon. Good work!

**Comment by rafi-fisker** [comment]
So I tried using the `testing` image which is supposed to have this fix, but I am still having issues with emails getting marked as phishing/spam by our Microsoft 365 email system. Any ideas?

**Comment by BlackDex** [comment]
@rafi-fisker: It would be nice to know why it got marked as spam by the third-party email-filtering tool then. Else it will be impossible for us to even try to do something. I have fixed all the spamassassin checks which did actually were some sane RFC defaults which weren't used in the mail headers and some link counting.

It could very well still be something totally out of our control, like where  you are sending the mail from for example, if that is untrusted by the filter for example. Or maybe if you have links to an internal accessible only server, it could mark it. There are a dozen reasons why.

**Comment by rafi-fisker** [comment]
@BlackDex The emails were sent via AWS SES SMTP server, with SPF/DKIM validated.
Unfortunately I don't have much visibility into the 3rd party email filtering tool, other than it's name: https://www.vadesecure.com/
