### ISSUE TITLE
One-time opt-out of Google Analytics

### ISSUE THREAD

**Issue by martinlablans** [dani-garcia/bitwarden_rs#121]
By default, the Bitwarden apps come with Google Analytics activated. To opt-out, you need to visit each app/plugin instance and tick the box. This can really add up: With my three machines, two user accounts on each and two browsers, I need to opt-out twelve times. Surely I've forgotten it on one or two instances. This is problematic from a data protection standpoint, especially in Europe.

Some ideas for solutions:
* Allow to change the Google Analytics setting server-wide, allowing the administrator to set it to opt-in.
* Acknowledge the user's decision and store it as a preference server-side.
* Have the Docker container's entrypoint remove the Google Analytics code from the downloaded Vault's JavaScript code (configurable via environment variable).

**Comment by dani-garcia** [comment]
I don’t think there is a way to control other clients from the server, but we could look into modifying the web vault in the build file.

**Comment by fbartels** [comment]
I have noticed the tracking options in the Android apps, but I don't see anything in the web vault (also ublock does not report anything). @martinlablans are you sure there is google analytics in the web vault? 

ps: using the tagged 0.12.0 release.

**Comment by mprasil** [comment]
Submitted a PR, that should remove analytics in self-hosted scenario.

**Comment by mprasil** [comment]
This was resolved in #136
