### ISSUE TITLE
Reports old "Exposed passwords"

### ISSUE THREAD

**Issue by mcfrojd** [dani-garcia/bitwarden_rs#1213]
### Subject of the issue
The report of exposed passwords still shows me passwords that have been changed.
Is the old passwords stored i db for the "updated password counter"?
And if so, is the report generator including these passwords when generating the report?
Or am i missing some "purge" function that "cleans" the database from old changed passwords?

### Your environment

* Bitwarden_rs version:
Server Latest 1.17.0
Web Latest 2.16.1

* Install method: Docker-compose
* Clients used: Android app, chrome app
* Reverse proxy and version: Nginx Reverse Proxy Manager 2.3.1
* Version of mysql/postgresql: 
* Other relevant information:

### Steps to reproduce

When in my web vault, running the tools/report exposed passwords, the report shows me password entries with old (exposed) passwords.
When i click them in the report it shows the old password, and if i click the entry in the vault i see the new changed password (changed 2 month ago)
### Expected behaviour

The report should not generate warnings on passwords that have been changed in the vault.
### Actual behaviour

Im guessing the old passwords are still stored somewhere and the report generator can still find these old passwords and keeps warning me about them.
I cant see the old password anywhere in the web vault, but if i use search and type in my old exposed password i get a list of entries that have had that password before i changed them, but i cant see that old password when i open the items from the list

**Comment by BlackDex** [comment]
Hello @mcfrojd,

All this is done client-side via the web-vault which we do not maintain.
For items regarding the web-vault behaving not as expected you are better of going to https://github.com/bitwarden/web/

**Comment by sichkarmg** [comment]
Mcfrojd Sorry I could not wait long, I have the same problem.
https://github.com/bitwarden/web/issues/690
