### ISSUE TITLE
Very slow on Raspi

### ISSUE THREAD

**Issue by CollinAlpert** [dani-garcia/bitwarden_rs#1217]
I am having a performance issue after installing Bitwarden_rs on my Raspberry Pi 3. The clients are extremely slow in syncing my passwords and even logging in takes up to five seconds. Syncing takes about a minute (I have about 160 passwords, but still). I used to use Rubywarden and it was much faster. I know that running Docker containers on as Raspi can be quite heavy, but I had kind of hoped for this to run more smoothly due to the fact that it is written in Rust. Are there any measures I can take to boost performance? Maybe disable the web interface or something like that?

**Comment by dani-garcia** [comment]
This sounds more like some kind of strange network misconfiguration than anything else, a raspberry pi should be more than enough to run the server even with docker overhead. Do other docker containers work correctly?

**Comment by markuta** [comment]
I can confirm that I have no performance issues on my Raspberry Pi 3 B+. I'm also using two Docker containers, one for a Nginx reverse proxy web server and one for the Bitwarden server. I have about 100 passwords on it, and its been running for a few months now without any issues. 

I wrote a guide on my current set-up (https://markuta.com/bitwarden-and-nginx-server-on-raspberry-pi/) if that might help.

**Comment by CollinAlpert** [comment]
Awesome, I'll check that out. Thank you for your responses. I will close this issue as it is obviously a problem on my side.
