### ISSUE TITLE
newly compiled installation missing bootstrap-native-v4.js?

### ISSUE THREAD

**Issue by pdarcos** [dani-garcia/bitwarden_rs#1225]
Hi everyone,
Debian 10.5

Just did a fresh git clone and compiled the binary. Everything seems to be ok except that when I try to login to the admin panel with the correct creds I get the invalid admin token message.

Looking into the logs I see it complains about finding bootstrap-native-v4.js

[2020-11-16 12:44:58.235][response][INFO] GET /bwrs_static/<filename> (static_files) => 200 OK
[2020-11-16 12:44:58.401][request][INFO] GET /bwrs_static/bootstrap-native-v4.js
[2020-11-16 12:44:58.401][error][ERROR] Static file not found: bootstrap-native-v4.js

Indeed looking through the source one can see that it is no longer available here https://github.com/dani-garcia/bitwarden_rs/tree/master/src/static/scripts

Is this a bug or am I missing something?

Cheers

**Comment by BlackDex** [comment]
I think this is a caching issue since this has been changed.
See: https://github.com/dani-garcia/bitwarden_rs/commit/0822c0c128d3b71b13109bb8c0f94f73174440fe#diff-cc15721ea040f3343cb189290fe0c97c1a074ca3c23bc5c4ecdccbc04b7b4d1a

**Comment by pdarcos** [comment]
Hmm, ok. Where is it being cached and how do I clear it? I rebooted the server but I still get that error message and when I click in the admin panel in General Settings/Advanced/ etc nothing happens...
I'm wondering if my issues are related to the web vault? I compiled it myself and used your 2.16.1 patch when the latest from bitwarden is 2.16.2

**Comment by BlackDex** [comment]
It's the browser cache, since that is where it's going wrong.
The code will return the correct html, so should not return the -v4 version.

**Comment by pdarcos** [comment]
Weird. I've cleared the browser cache, tried a private window and even switched to a new browser yet the issue remains exactly the same.

Can't open the General settings in admin panel and the logs show the usual 

[2020-11-16 15:34:28.603][response][INFO] GET /bwrs_static/<filename> (static_files) => 200 OK
[2020-11-16 15:34:28.604][request][INFO] GET /bwrs_static/bootstrap-native-v4.js
[2020-11-16 15:34:28.604][error][ERROR] Static file not found: bootstrap-native-v4.js
[2020-11-16 15:34:28.604][response][INFO] GET /bwrs_static/<filename> (static_files) => 400 Bad Request

Besides clearing the browser cache what else can I try?

Thanks

**Comment by BlackDex** [comment]
Are you sure it is the latest version you compiled? And did you use the `master` branch?
You can check this by going to `/admin/diagnostics`, it should say `1.17.0-558410c5` if you compiled the master branch.

Also check if you do not have `TEMPLATES_FOLDER` and `RELOAD_TEMPLATES` configured to be sure to be using the compiled-in files.

**Comment by pdarcos** [comment]
Strange indeed because I'm certain I don't have TEMPLATES_FOLDER or RELOAD_TEMPLATES set.

Also, yes I'm at 1.17.0-558410c5. Hmmm, I may just do a fresh git clone and compile it again to make sure nothing went wrong.

**Comment by pdarcos** [comment]
I recompiled the binary and unfortunately no change.
Next I'm going to try with your web-vault instead of compiling my own to see if that makes any difference.

**Comment by pdarcos** [comment]
OK, so I used your web build (2.16.1) instead of compiling my own and the problem remains the same:

[2020-11-16 19:37:43.146][error][ERROR] Static file not found: bootstrap-native-v4.js
[2020-11-16 19:37:43.298][error][ERROR] Static file not found: bootstrap-native-v4.js

I have nginx setup as a reverse proxy but I didn't change anything there and am using the configuration as described in the wiki by shauder, with the only exception that I also have this in my conf file (probably due to websockets if I recall correctly) which is missing from shauder's example. I don't think this is the reason for it trying to server up bootstrap-native-v4.js but I may be worng of course.

location /hub/ {
    proxy_pass http://localhost:8080;
  }

Don't know what else to do to debug this.

**Comment by pdarcos** [comment]
I even tried to manually add the bootstrap-native-v4.js file to src/static/scripts and recompiled but it still complains about it missing and I cannot change any settings through the admin panel.

Has anyone else compiled the binaries recently? Would love to know if this is some weird issue with my server or a bug.

**Comment by BlackDex** [comment]
I just compiled it few times and it's working fine for me.
Also, the `testing` tag on docker is using the same version and i have that running on my production server.

**Comment by pdarcos** [comment]
Hmmm, ok. Then I'm fresh out of ideas. Maybe my .env file is configured with some setting wrong?

Besides the TEMPLATES_FOLDER or RELOAD_TEMPLATES settings (both commented out in my .env) are there any other ones I should look into?

**Comment by BlackDex** [comment]
I just did some development including on the admin page, and it works for me as it should.
I have no clue why you still get the `bootstrap-native-v4.js` to load. It is nowhere in the code at all anymore.

I really think it is some browser-cache, or some other caching mechanism provided by the reverse-proxy you use maybe?

**Comment by pdarcos** [comment]
Thanks @BlackDex and sorry for the lack of response.
I'm dealing with a last minute work thing that came up and haven't had time to test it.

I agree with you that it's likely nginx caching something, so as soon as I have some free time I'll take another look and will revert back.
Please don't spend any more time on this since it seems the problem is only on my setup.
Really appreciate your help. 

Thanks

**Comment by BlackDex** [comment]
@pdarcos No problem, just here to help and keep us posted :).

**Comment by BlackDex** [comment]
Closing this as new builds and local builds do not produce any issues. Feel free to continue on the forum :).

**Comment by oguh22** [comment]
> Are you sure it is the latest version you compiled? And did you use the `master` branch?
> You can check this by going to `/admin/diagnostics`, it should say `1.17.0-558410c5` if you compiled the master branch.
> 
> Also check if you do not have `TEMPLATES_FOLDER` and `RELOAD_TEMPLATES` configured to be sure to be using the compiled-in files.

Hello @BlackDex  I am facing the same issue and I have some templates configured , I agree that if I remove my template folder issue is solved but what doest it means ? 
I need to recreate all my templates based on the latest templates sample files that I can found here on GitHub ? No other solution ?
