### ISSUE TITLE
Apache ProxyPass Issue

### ISSUE THREAD

**Issue by rbdevr** [dani-garcia/bitwarden_rs#1230]
Hi all,

Im trying to configure BitWarden to run behind an Apache server as a subpath

https://myserver/bitwarden

The service is running as localhost:3743

I followed the proxy example in the wiki but I keep getting proxy error:

502 Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /bitwarden .

Reason: Error reading from remote server

I have tried the following setting:

environment variable:
DOMAIN=https://myserver/bitwarden
ROCKET_PORT=3743
ROCKET_TLS='{certs="<cert path>",key="<key path>"}

apache config:
<Location /bitwarden>
RewriteEngine On
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /notifications/hub(.*) ws://localhost:3012/$1 [P,L]
ProxyPass http://localhost:3743

ProxyPreserveHost On
RequestHeader set X-Real-IP %{REMOTE_ADDR}s
</Location

Any assistance would be appreciated

Cheers

**Comment by BlackDex** [comment]
Hello @rbdevr,

`502 Proxy Error` indicates that you probably are not running bitwarden, or not running it on port 3743 (and 3012 for the websockets) or not on localhost but on an other IP.

When you start bitwarden you should see which port it run's on, and also which IP.
If it states it's running on `127.0.0.1` on the same host as where apache httpd is running it should work, or if it states `0.0.0.0`, that should also work on the localhost at least.

**Comment by rbdevr** [comment]
I did manage to get the error sorted by turning off SSL on bitwarden service.

Now I dont get an error from apache, I get a small box written “bitwarden” and a border around it.

Anyone faced this issue?

Cheers

**Comment by o2droid** [comment]
I have similar setup, but I configured `DOMAIN `variable to `https://mydomain/bitwardendir/`.
In apache I have Location configured similar as yours. What I can tell - in browser I have to add trailing / at the end of address, but addons and application works fine (haven't time to write RewriteRule).
```
        <Location /bitwardendir>
        SecRuleRemoveById 911100 //modsecurity remove blocking of PUT requests
        RewriteEngine On
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule /notifications/hub(.*) ws://127.0.0.1:3012/$1 [P,L]
        ProxyPass http://localhost:880
        ProxyPreserveHost On
        RequestHeader set X-Real-IP %{REMOTE_ADDR}s
        </Location>
```

Only thing which doesn't work is notifications hub - getting 503 error.

**Comment by BlackDex** [comment]
Remember to enable `mod_proxy_wstunnel` and `mod_proxy_http`, for example with: `a2enmod proxy_wstunnel` and `a2enmod proxy_http`. Else some items like the `ws://` will not work.

Regarding the `404 Not Found`, i think those items arn't even sent to bitwarden_rs it self but trapped by the reverse proxy.
But please post the bitwarden.log part if that is not the case, so that we can try to figure this out. But i think it's more of an reverse proxy issue then it is bitwarden_rs. Also, i just have also tested Apache HTTPD with the example from the wiki, and that works great. Same goes for the NGINX and HaProxy ones.
