### ISSUE TITLE
Migration from sqlite to mysql incomplete

### ISSUE THREAD

**Issue by fbartels** [dani-garcia/bitwarden_rs#1237]
### Subject of the issue
When following the instructions outlined in https://github.com/dani-garcia/bitwarden_rs/wiki/Using-the-MySQL-Backend and https://github.com/dani-garcia/bitwarden_rs/issues/984 to switch from the default sqlite database to a mysql one, users are able to login and see entries. but entries are missing all data such as usernames, passwords, 2fa token, urls (attachments however are preserved).

### Your environment

* Bitwarden_rs version: 1.17.0
* Install method: build from source as part of https://git.cloudron.io/cloudron/bitwardenrs-app/-/blob/master/Dockerfile
* Clients used: web vault 2.16.1
* Reverse proxy and version: Apache + Nginx
* Version of mysql/postgresql: unknown
* Other relevant information:

### Steps to reproduce
- `sqlite3 db.sqlite3 .dump | grep "^INSERT INTO" | grep -v "__diesel_schema_migrations" > sqlitedump.sql ; echo -ne "SET FOREIGN_KEY_CHECKS=0;\n$(cat sqlitedump.sql)" > mysqldump.sql`
- `sed -i s#\"#\#g mysqldump.sql`
- move data to new system
- import database with `mysql --force --password --user=bitwarden_rs --database=bitwarden_rs < mysqldump.sql`

### Expected behaviour
- password vault has same data as before the migration

### Actual behaviour
- users can login and see items in vault, but items are missing data such as usernames, passwords, urls

### Relevant logs
- no error to be seen in logs

**Comment by BlackDex** [comment]
Did you used the exact same version for sqlite as for mysql?
Not that you used an older sqlite version, and have the mysql run migrations on the database for a newer version.
Because that would cause conflicts.

Those above procedure i have written my self, and i just tested them again, and they seem to work.

**Comment by fbartels** [comment]
Thanks for your feedback @BlackDex. The source system was an official build and the target is a self compiled with only mysql support.

Since it works for you I probably made a mistake somewhere, but before reporting i already tried it twice.

But given that I only need to migrate two users I think I will just use Portwarden to get my users on the new system.

**Comment by BlackDex** [comment]
It could be some other strange item like, encoding of the database, like unicode utf8.
Do you not get any error message at all during either export or import?
