### ISSUE TITLE
Download latest does not work 

### ISSUE THREAD

**Issue by Roughnecksp** [dani-garcia/bitwarden_rs#1239]
### Subject of the issue

If i run: docker pull bitwardenrs/server:latest
I get the following error:
panic: runtime error: invalid memory address or nil pointer dereference
### Your environment
Raspi 

* Bitwarden_rs version: 

* Reverse proxy and version: synology 
* Version of mysql/postgresql: 
* Other relevant information:

### Steps to reproduce

docker pull bitwardenrs/server:latest

**Comment by BlackDex** [comment]
This has nothing to do with bitwarden_rs, it seem more like an issue with docker or your Raspberry Pi is out of memory.

**Comment by Roughnecksp** [comment]
My Pi has enough space.
Look at this issue: so thought there is a fault 
https://github.com/influxdata/influxdb/issues/16064

**Comment by BlackDex** [comment]
Well, you state it happens during the `docker pull` command. And not when bitwarden_rs is starting. So, if the docker pull returns this, it's nothing we can fix. If it happens when bitwarden_rs starts, it would be useful to have the full output, or maybe a screenshot too see if w can do something. Other then that with the very summier info you provided we can't do much I'm afraid.

**Comment by Roughnecksp** [comment]
Sorry you are right 👍
Here the full output

pi@Pi:~ $ docker pull bitwardenrs/server:latest
fatal error: freedefer with d.fn != nil

goroutine 1 [running]:
runtime.throw(0x1be7eea, 0x1a)
        /usr/local/go/src/runtime/panic.go:774 +0x60 fp=0x58b35b8 sp=0x58b35a4 pc=0x8899e8
runtime.freedeferfn()
        /usr/local/go/src/runtime/panic.go:485 +0x28 fp=0x58b35c4 sp=0x58b35b8 pc=0x888fa4
github.com/docker/cli/vendor/github.com/docker/docker/client.(*Client).Info(0x5537180, 0x24fee30, 0x54c0020, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/cli/vendor/github.com/docker/docker/client/info.go:18 +0x2ac fp=0x58b3750 sp=0x58b35c4 pc=0xc9fc68
github.com/docker/cli/cli/command.ElectAuthServer(0x24fee30, 0x54c0020, 0x2514a30, 0x58e41c0, 0x553763f, 0x66bc677a)
        /go/src/github.com/docker/cli/cli/command/registry.go:31 +0x4c fp=0x58b3b74 sp=0x58b3750 pc=0x106d104
github.com/docker/cli/cli/command.ResolveAuthConfig(0x24fee30, 0x54c0020, 0x2514a30, 0x58e41c0, 0x540c360, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/cli/cli/command/registry.go:83 +0xb0 fp=0x58b3c04 sp=0x58b3b74 pc=0x106d5fc
github.com/docker/cli/cli/command/image.AuthResolver.func1(0x24fee30, 0x54c0020, 0x540c360, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/cli/cli/command/image/trust.go:361 +0x48 fp=0x58b3c54 sp=0x58b3c04 pc=0x11c0868
github.com/docker/cli/cli/trust.GetImageReferencesAndAuth(0x24fee30, 0x54c0020, 0x0, 0x0, 0x58e3a50, 0x5734db0, 0x23, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/cli/cli/trust/trust.go:326 +0xd0 fp=0x58b3d1c sp=0x58b3c54 pc=0xde2420
github.com/docker/cli/cli/command/image.RunPull(0x2514a30, 0x58e41c0, 0x7eaaa468, 0x19, 0x0, 0x0, 0x0, 0x100, 0x0, 0x0)
        /go/src/github.com/docker/cli/cli/command/image/pull.go:66 +0x104 fp=0x58b3de0 sp=0x58b3d1c pc=0x11b93b0
github.com/docker/cli/cli/command/image.NewPullCommand.func1(0x55c3180, 0x5431858, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/cli/cli/command/image/pull.go:35 +0x70 fp=0x58b3e24 sp=0x58b3de0 pc=0x11c0230
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0x55c3180, 0x58e3838, 0x1, 0x1, 0x55c3180, 0x58e3838)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:762 +0x350 fp=0x58b3e8c sp=0x58b3e24 pc=0x1060e3c
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x56b8140, 0x58e3830, 0x2, 0x2)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:852 +0x248 fp=0x58b3ef0 sp=0x58b3e8c pc=0x1061640
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:800
main.runDocker(0x58e41c0, 0x24e2548, 0x54aa0e0)
        /go/src/github.com/docker/cli/cmd/docker/docker.go:281 +0x188 fp=0x58b3f60 sp=0x58b3ef0 pc=0x1bb64ac
main.main()
        /go/src/github.com/docker/cli/cmd/docker/docker.go:292 +0xdc fp=0x58b3fa4 sp=0x58b3f60 pc=0x1bb672c
runtime.main()
        /usr/local/go/src/runtime/proc.go:203 +0x264 fp=0x58b3fe4 sp=0x58b3fa4 pc=0x88bb6c
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:868 +0x4 fp=0x58b3fe4 sp=0x58b3fe4 pc=0x8b97f4

goroutine 5 [syscall]:
os/signal.signal_recv(0x5660480)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x14c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x14
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x34

goroutine 7 [chan receive]:
github.com/docker/cli/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x32216c0)
        /go/src/github.com/docker/cli/vendor/k8s.io/klog/klog.go:1010 +0x70
created by github.com/docker/cli/vendor/k8s.io/klog.init.0
        /go/src/github.com/docker/cli/vendor/k8s.io/klog/klog.go:411 +0x13c
pi@Pi:~ $

**Comment by Roughnecksp** [comment]
But the Problem ist the docker pull command.
I think there ist a bug in docker commands

**Comment by BlackDex** [comment]
Seems docker indeed since they are go errors and not rust.
I would check the docker forums, irc, mailinglists to see if you can find an answer there :)

**Comment by Roughnecksp** [comment]
Ok thanks
