### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by veeral-patel** [dani-garcia/bitwarden_rs#1249]
hi - so I'm looking for a version of Bitwarden with an API I can use to create and read passwords programmatically via API. I know Bitwarden's API endpoints to do this aren't documented....are bitwarden_rs's?

**Comment by BlackDex** [comment]
They arn't documented, so its source code regarding that.
You could try to just use the bw cli client for stuff like this.

**Comment by veeral-patel** [comment]
hi @BlackDex - thanks. are there actually endpoints to create and save passwords, if you know?

**Comment by BlackDex** [comment]
Well not from the top of my head. I suggest to just use developer tools via the browser and copy that if you want to figure it out.

Bitwarden_rs does not have the api endpoints (yet) which are available as from the official bitwarden.

**Comment by BlackDex** [comment]
Closing this ticket as this is not a bug.
Feel free to continue this discussion on the forum: https://bitwardenrs.discourse.group/
