### ISSUE TITLE
Cannot create API Key - An unexpected error has occurred - 404 Not Found

### ISSUE THREAD

**Issue by aramaki87** [dani-garcia/bitwarden_rs#1250]
### Subject of the issue
I cannot create API key from Web GUI (selfhosted) "An unexpected error has occurred"

### Your environment
LXC Container running BitwardenRS build from source
WEB UI is running without HTTPS, only HTTP
HAProxy on another machine doing HTTPS (Mapping 443 -> 80)
Port 3012 is also accessible

Server Installed: 1.17.0 
Web Installed: 2.17.0 

ufw temporarily disabled

### Steps to reproduce
I click on generate API Key in the Web GUI and get "An unexpected error has occurred" message.

### Syslog:
Dec  3 07:42:28 bitwardenRS bitwarden_rs[6248]: [2020-12-03 07:42:28.904][request][INFO] GET /api/accounts/profile
Dec  3 07:42:28 bitwardenRS bitwarden_rs[6248]: [2020-12-03 07:42:28.905][response][INFO] GET /api/accounts/profile (profile) => 200 OK
Dec  3 07:42:36 bitwardenRS bitwarden_rs[6248]: [2020-12-03 07:42:36.370][request][INFO] POST /api/accounts/api-key
Dec  3 07:42:36 bitwardenRS bitwarden_rs[6248]: [2020-12-03 07:42:36.370][response][INFO] 404 Not Found

### Conclusion:
It looks like whatever should provide /api/accounts/api-key is not there...
Everything else is up and working. Having multiple organisations and some users accessing them. All good.

**Comment by BlackDex** [comment]
May i ask which version of the web-vault you are using?
Did you build it your self? And if so did  you use `npm run dist`? If not, you probably have the wrong vault version for bitwarden_rs.

**Comment by aramaki87** [comment]
Hi,

I checked the admin panel:

Server Installed Ok
    1.17.0 
Server Latest
    1.17.0 
Web Installed Update
    2.17.0 
Web Latest
    2.16.1 

I think this is the problem. I try another version and report back.

**Comment by aramaki87** [comment]
I reinstalled everything but this time only up to version 2.16.1
I also applied the web vault patch 2.16.1.

Server Installed Ok
    1.17.0 
Server Latest
    1.17.0 
Web Installed Ok
    2.16.1 
Web Latest
    2.16.1 

Now the funny thing is I do not even see the option to generate an API Key anymore from within the web GUI. The section is just gone. Not there anymore. Do I have to enable this somehow?

**Comment by BlackDex** [comment]
If you are referring to the apikey for usage with the bw cli for example, that is not supported (yet). And thus hidden, and thus generates a 404.

**Comment by aramaki87** [comment]
THIS explains everything! Alright, Thank you!.

Last question: Is there another way to automate/script export (to .csv) at the moment? I know that I can export the database but that is not what I am looking for.

**Comment by jjlin** [comment]
The recent [v2.17.1](https://github.com/dani-garcia/bw_web_builds/releases/tag/v2.17.1) release of the web vault properly hides the API key section.

**Comment by aramaki87** [comment]
Alright no option to export to csv at the moment?

**Comment by BlackDex** [comment]
@aramaki87, you cab export the vault via the tools menu when logged-in. Or use the cli https://github.com/bitwarden/cli

**Comment by BlackDex** [comment]
I Will close this issue and make a note of this in #246 that we could try and add this feature.

**Comment by aramaki87** [comment]
Thank you for your reply. However...

In order to use the cli I have to create an API key. The API key is entered in the cli to get access. This is not possible at the moment. As I tried to explain in this topic. 
No feature request required. Just add the generate key feature again to let people create API keys again to enter them in the cli to get access to the cli features.

**Comment by jjlin** [comment]
Read the docs at https://bitwarden.com/help/article/cli/#logging-in. The traditional login method is using your email address. API key login is a very new method that requires additional code in bitwarden_rs to generate API keys, which as we explained, is not currently implemented.

**Comment by svzi** [comment]
Quoting from the official Bitwarden CLI docs (https://bitwarden.com/help/article/cli/#log-in):

> Logging in with the Personal API Key is **recommended for automated workflows or providing access to an external application**.

One year has gone by now, without any progress in this regard. The API key method isn't that "very new" anymore and, way more importantly, it's the recommended way to access the CLI for most stuff. Some software doesn't even offer to authenticate the Bitwarden CLI without an API key and that makes it useless with Vaultwarden.

I doubt the developers of that kind of software would welcome the idea to add a login method that is officially deprecated... :-(

Any update on this topic would be greatly appreciated as I wonder if there are any plans to implement the API key generation or is this feature more at the bottom of the todo list?

Best,
Sven

**Comment by BlackDex** [comment]
As i mentioned above already, it is part of this ticket #246.
Until now no major contributor has started to work on it. Though i was tempted a few times, other things came in between.

As for all open items on #246, people are free and encouraged to create a well written PR to help us.

**Comment by svzi** [comment]
I've already noticed it in #246. Just wanted to get an update on the state which you already provided. So thanks for your feedback. As I've never developed anything with Rust, I wouldn't be able to create a well written PR. Not even nearly. So I hope someone else can and will do this. Until that point I can live without it for sure. Please keep up the good work! 🙏
