### ISSUE TITLE
FIDO U2F isn't shown while login

### ISSUE THREAD

**Issue by Gaojianli** [dani-garcia/bitwarden_rs#1251]
### Subject of the issue
I can add FIDO device(yubikey) at console, but when I try to login, I can't find FIDO options.

### Your environment

* Bitwarden_rs version: 1.17

* Install method: Docker image
* Clients used: MS Edge 87.0.664.52 x64
* Reverse proxy and version: nginx/1.19.0
* Version of mysql/postgresql: 10.5.8-MariaDB-1:10.5.8+maria~focal
* Other relevant information:

### Steps to reproduce

1. Add a U2F device at settings
1. Logout and try to login again

### Expected behaviour
I can choose any 2FA I configured, including U2F

### Actual behaviour
I can't choose FIDO U2F
What I configured:
![image](https://user-images.githubusercontent.com/19235246/100977272-b93d8b80-357b-11eb-9173-01f6eae72a5e.png)

What I see:
![image](https://user-images.githubusercontent.com/19235246/100977243-adea6000-357b-11eb-9f34-ba538bdbd1a1.png)

### Relevant logs
Request to `/identity/connect/token` returns a 400 Bad Request
![image](https://user-images.githubusercontent.com/19235246/100978122-e8083180-357c-11eb-8c84-744f4a68e7f9.png)
Here is the response body:
![image](https://user-images.githubusercontent.com/19235246/100978066-d3c43480-357c-11eb-8caa-ebd51348b790.png)

**Comment by BlackDex** [comment]
I just tested it with a softu2f token and it all seems to work.
If you use any of the other 2FA ones, does it work?

Also, have you tried to remove and re-add the Fido U2F token?

Else we probably need a bit more information like logs etc...

Also, what happens if you create a new account and try to use it there?

**Comment by Gaojianli** [comment]
> If you use any of the other 2FA ones, does it work?

Yes, all work except u2f

> Also, have you tried to remove and re-add the Fido U2F token?

I tried it and it doesn't work.
> Else we probably need a bit more information like logs etc...

> Also, what happens if you create a new account and try to use it there?
A new user can use u2f normally

**Comment by Gaojianli** [comment]
After stop, remove and restart the docker container, it finally works. Strange problem....
