### ISSUE TITLE
Submit button in Create Account page not working

### ISSUE THREAD

**Issue by elliaster** [dani-garcia/bitwarden_rs#1253]
### Subject of the issue

Submit button in Create Account page not working

### Your environment

* Bitwarden_rs version: 1.17.0

* Install method: Docker Image
* Clients used: 
* Reverse proxy and version: 
* Version of mysql/postgresql: 
* Other relevant information:

### Steps to reproduce

Create Docker Instance of Bitwarden_rs
After starting up click "Create Account"
Fill in all information
Click "Submit"

### Expected behaviour

It should create an account 

### Actual behaviour

Stuck on the "Create Account" page

### Relevant logs

> /--------------------------------------------------------------------\,
|                       Starting Bitwarden_RS                        |,
|                           Version 1.17.0                           |,
|--------------------------------------------------------------------|,
| This is an *unofficial* Bitwarden implementation, DO NOT use the   |,
| official channels to report bugs/features, regardless of client.   |,
| Send usage/configuration questions or feature requests to:         |,
|   https://bitwardenrs.discourse.group/                             |,
| Report suspected bugs/issues in the software itself at:            |,
|   https://github.com/dani-garcia/bitwarden_rs/issues/new           |,
\--------------------------------------------------------------------/,
,
[2020-12-04 18:45:55.116][bitwarden_rs][INFO] JWT keys don't exist, checking if OpenSSL is available...,
OpenSSL 1.1.1d  10 Sep 2019,
[2020-12-04 18:45:55.153][bitwarden_rs][INFO] OpenSSL detected, creating keys...,
Generating RSA private key, 2048 bit long modulus (2 primes),
........+++++,
................+++++,
e is 65537 (0x010001),
writing RSA key,
writing RSA key,
[2020-12-04 18:45:56.369][bitwarden_rs][INFO] Keys created correctly.,
Running migration 20180114171611,
Running migration 20180217205753,
Running migration 20180427155151,
Running migration 20180508161616,
Running migration 20180525232323,
Running migration 20180601112529,
Running migration 20180711181453,
Running migration 20180827172114,
Running migration 20180910111213,
Running migration 20180919144557,
Running migration 20181127152651,
Running migration 20190526216651,
Running migration 20191010083032,
Running migration 20191117011009,
Running migration 20200313205045,
Running migration 20200409235005,
Running migration 20200701214531,
Running migration 20200802025025,
[2020-12-04 18:45:56.855][start][INFO] Rocket has launched from http://0.0.0.0:80,

**Comment by BlackDex** [comment]
You probably do not have ssl enabled, please search the issues and wiki before posting a new one.

See: https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-HTTPS
https://github.com/dani-garcia/bitwarden_rs/wiki/Private-CA-and-self-signed-certs-that-work-with-Chrome
https://github.com/dani-garcia/bitwarden_rs/wiki/Running-a-private-bitwarden_rs-instance-with-Let%27s-Encrypt-certs
