### ISSUE TITLE
New Device Logged Emails

### ISSUE THREAD

**Issue by seantdavidson** [dani-garcia/bitwarden_rs#1254]
So I just installed bitwardenrs on my server using docker. If I login to my bitwarden on the same machine I will still get an email saying that I have logged into a new machine. I am not sure if this has to do with my reverse proxy setup I am using or if there is an environment variable I am missing. I am using the LinuxServer.io Swag container for my Reverse Proxy. I would really like not to get an email each time I login. the IP it show in the email is my Router IP.

`docker run -d --name bitwarden \
  -e DOMAIN=https://bitwarden.example.com
  -e SIGNUPS_ALLOWED=false
  -e SMTP_HOST=<smtp.domain.tld> \
  -e SMTP_FROM=<bitwarden@domain.tld> \
  -e SMTP_PORT=587 \
  -e SMTP_SSL=true \
  -e SMTP_USERNAME=<username> \
  -e SMTP_PASSWORD=<password> \
  -v /bw-data/:/data/ \
  -p 8181:80 \
  bitwardenrs/server:latest`

**Comment by BlackDex** [comment]
Well, it seems that for some reason your device-id keeps changing.
I think that this could be some browser setting to not store cookies, or at least clear them on exit/tab-close or something.
Else the device-id should be the same and it would not trigger a new device logic.

**Comment by seantdavidson** [comment]
Then will look up my settings on my browser

**Comment by BlackDex** [comment]
@seantdavidson, an luck with checking the browser settings if it clears all the local-storage?
Within the local-storage there is a key named `appId`, which is used as device-id, if that value disappears or gets cleared every session, it will be seen as a new device.

**Comment by seantdavidson** [comment]
I turned off a setting in Firefox and have not noticed the email every time I login to Bitwarden. Still monitoring.

**Comment by BlackDex** [comment]
Thanks for the response. And good to see that it probably solved your issue.
I'm going to close this ticket then, since it's probably not something we can change anyway on the bitwarden_rs side.
If this does happen again, and you think this is something we should or could solve on the bitwarden_rs side, please re-open this ticket.
