### ISSUE TITLE
When Vault is locked in a new browser session, you cannot login

### ISSUE THREAD

**Issue by module0x90** [dani-garcia/bitwarden_rs#1256]
### Subject of the issue
I am on Arch Linux, latest and greatest and usually use only Vivaldi Browser. I have installed
the Bitwarden extension in there and it is working great.
Everytime though my machine was just started up, BW says
"Your vault is locked. Verify your master password to continue."
but when I provide the correct password, I only get 

An error has occurred
Invalid Master password.

The only way to fix this is to log out, the re-login again.
I just tried Chromium and it is the same there.

### Your environment
Vivaldi 3.4.2066.106 and extension version 1.47.1
Chromium 87.0.4280.66 and extension version 1.47.1
Bitwarden on Docker image using bitwardenrs/server:raspberry, currently on "bitwardenrs/server@sha256:bf5a81392a3e4390ced2a9e935b53165049ec8b2dcf1a531b8b2426d38f1ca26".
According to the webfront end Version 2.15.1.
Routed through Traefik, traefik:v2.3, v2.3.4

### Steps to reproduce
1. Open browser window
2. Login to BitWarden extension
3. Close browser window
4. Re-open browser window
5. Vault shows as locked and logins fail.

### Expected behaviour
It should accept the valid master password just fine. I don't mind it's locked - obviously.

### Actual behaviour
Doesn't accept the valid master password.

**Comment by BlackDex** [comment]
You have to update your bitwarden_rs version! Please search before posting a new issue and read the pinned issues.
https://github.com/dani-garcia/bitwarden_rs/issues/1180

**Comment by module0x90** [comment]
Hi, thanks.
I have updated now, as well as that I changed the docker image now as well.

I can confirm that my issue above is  fixed with version 1.17.0, what I am on right now.
