### ISSUE TITLE
How to update Bitwarden_rs

### ISSUE THREAD

**Issue by IssueFindings** [dani-garcia/bitwarden_rs#1263]
Hello,

I would like to know how update Bitwarden_rs. Indeed, when I use `docker pull bitwardenrs/server:latest` I still have the version 2.16.1 instead of currently 2.17.1 What is wrong ?

Have a nice day.

**Comment by BlackDex** [comment]
The `latest` tag is used for the latest tagged version, `testing` is used for the master branch.
Also see: https://github.com/dani-garcia/bitwarden_rs/issues/1180
