### ISSUE TITLE
Warning message linux/arm/v7

### ISSUE THREAD

**Issue by IssueFindings** [dani-garcia/bitwarden_rs#1264]
Hello,

I run Bitwarden_rs through docker. Each time I launch it, I can read this warning message `WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested` What that really means ? How I can fix it ?

Have a nice day.

**Comment by BlackDex** [comment]
You have the give a bit more information then this. Docker normally checks for the platform it self. It seems that you force a specific platform.

So what we need to see if there is something obvious is what docker create/run command you use, what platform/hardware and which os.

**Comment by IssueFindings** [comment]
Hello,
Sorry for the lack of informations. So, I use `Docker version 20.10.0, build 7287ab3` on `Linux raspberrypi 5.4.72-v7l+ #1356 SMP (...)  armv7l GNU/Linux`. I use the common way to install Docker.
Have a nice day

**Comment by BlackDex** [comment]
You somehow have the amd64 image selected instead of the armv7 one, i know this can sometimes happen and i don't know why, since that is a docker issue not bitwarden_rs.
You could try to add `--platform linux/arm/v7` but i'm not sure if that will help.

**Comment by TheGreatestJannet** [comment]
I have the same issue. It seems to be related to the latest docker update

**Comment by TheGreatestJannet** [comment]
Running: `docker run -e SIGNUPS_ALLOWED=false -e ADMIN_TOKEN=password -e WEBSOCKET_ENABLED=true -p 8081:80 -p 8082:3012 -v /opt/bw-data:/data/ --rm --name bitwarden bitwardenrs/server:latest --platform linux/arm/v7` I get `Command not found: --platform`

**Comment by jjlin** [comment]
`--platform linux/arm/v7` needs to go before `bitwardenrs/server:latest`.

Do you get the same issue if you run another image? For example:

    docker run -it --rm alpine

**Comment by TheGreatestJannet** [comment]
Running that I get: `docker: Error response from daemon: image with reference bitwardenrs/server:latest was found but does not match the specified platform: wanted linux/arm/v7, actual: linux/amd64`

**Comment by TheGreatestJannet** [comment]
This also prevents the systemd file from working and requires bitwardenrs to be manually started every time you reboot.

**Comment by jjlin** [comment]
This is almost certainly a regression in Docker 20.10 then, as `alpine` is an official Docker image. I'd recommend rolling back to Docker 19.03.x until this is fixed.

**Comment by TheGreatestJannet** [comment]
is there anywhere to report the bug to the developers? Looking on the forums it seems that no one has mentioned anything about it so I'm not even sure if they know about it.

**Comment by jjlin** [comment]
https://github.com/moby/moby is probably the right place. Also, did you actually try running the `alpine` image? Just noticed your error message wasn't for `alpine`.

**Comment by TheGreatestJannet** [comment]
No I don't get an error message for alpine.

**Comment by EchoDev** [comment]
I can confirm I have the same issue

latest mysql build with armv8
