### ISSUE TITLE
Bitwarden not respecting the hosts & container timezone & manually set timezone.

### ISSUE THREAD

**Issue by iqfx** [dani-garcia/bitwarden_rs#1268]
### Subject of the issue
Bitwarden does not respect timezone.

### Your environment

Server Installed Ok
    1.17.0 
Server Latest
    1.17.0 
Web Installed Update
    2.16.1 
Web Latest
    2.17.1 

* Bitwarden_rs version: Latest (just pulled before posting this)

* Install method: Docker
* Clients used: N/A
* Reverse proxy and version: HA-Proxy version 1.6.15-1ppa1~xenial 2019/10/27
* Other relevant information: The docker container has the right time set. (I manually entered the container and ran date to check)
Just bitwarden seems to force UTC besides me setting europe/amsterdam. Also the docker host has the right time set. The time is of by 1 hour behind in the web interface.

### Steps to reproduce
For this situation I only set tz: to europe/amsterdam in my docker-compose.yml

### Expected behaviour
The correct time should be displayed on the admin page

### Actual behaviour
![Screenshot_2020-12-12_13-21-55](https://user-images.githubusercontent.com/39005172/101983739-4324dd00-3c7d-11eb-8845-2ea9d28de8c7.png)

### Relevant logs
idk, if you need any. No errors are showing.

**Comment by BlackDex** [comment]
The diagnostics page is supposed to show the UTC timezone as it states (UTC). Also as a diagnostic to make sure MFA is working correctly. We could add a server timezone there also using the configured format from the settings. But we keep those values there as it is to prevent timezone configuration issues.

**Comment by iqfx** [comment]
MFA is not working. And i tried the same secret on authy and it works fine there.

**Comment by iqfx** [comment]
Excuse me, fixed it. My own PC was about 50 seconds behind the time.
I just ran `$ timedatectl set-ntp true`

**Comment by BlackDex** [comment]
Hmm... Well, if running bitwarden_rs and the browser on the same host with time-drift is occurring, maybe we should try to get an NTP also, and show and compare that too.
It's something ill put on the list :).
