### ISSUE TITLE
Alpine image doesn't contain sqllite3 command to perform backup

### ISSUE THREAD

**Issue by 80dB** [dani-garcia/bitwarden_rs#1269]
### Subject of the issue
It's suggested to run a cron job to backup sqlite3 with the sqlite3 command, however this command isn't installed in the alpine image.

### Your environment
* Bitwarden_rs version: bitwardenrs/server:1.17.0-alpine

### Steps to reproduce
Start image and open shell and execute "sqlite3" or "find | grep sql".

### Expected behaviour
The sqlite3 command should execute normally.

### Actual behaviour
It'll report sqlite3 isn't found.

### Work-around
Use the non-alpine image for sqlite3 actions.

**Comment by jjlin** [comment]
Presumably your cron job is running directly on your host system; you should run `sqlite3` directly from there as well, installing it if needed,

I don't think the `sqlite3` package is needed in the Debian-based image, so it should probably be removed.

**Comment by BlackDex** [comment]
@jjlin, no, i rather think we need to add it to the alpine image. Or we need to remove the feature from the admin to create a backup. I'm in favor of the first with adding sqlite3 command.

**Comment by BlackDex** [comment]
Though, if creating a cronjob, that job should be on the host though, not within the container.
And it's better to have sqlite3 on the host also to just create a backup via the mapped volume folder.

If you would create a cronjob within the container (which i think isn't possible without installing more software), it will be lost after a new version is being installed.

**Comment by jjlin** [comment]
Ah, I forgot there was a backup function in the admin page. I wonder how many people actually use that, though. Personally, I find it to be of questionable utility, given it doesn't do a complete job (no config, attachments, etc.), and most people would be better off automating it.

**Comment by BlackDex** [comment]
Dockerfiles have been updated to include the libraries.
