### ISSUE TITLE
Error in core.js: Uncaught (in promise) DataError

### ISSUE THREAD

**Issue by sombatos** [dani-garcia/bitwarden_rs#1273]
When trying to Confirm a user receiving the following JS error:

```
core.js:4127 ERROR Error: Uncaught (in promise): DataError
```

What  can be the reason?

> 
> ENABLE_SMTP=false
> 
> bitwardenrs/server:1.17.0

Screenshot:

![2020-12-20_21-54-36](https://user-images.githubusercontent.com/40499291/102721819-343dca80-430e-11eb-8932-ccff37ed30dc.png)

**Comment by sombatos** [comment]
Deleted the user via /admin, reinvited and it worked fine.

**Comment by BlackDex** [comment]
Actually that message means you were not using HTTPS.
The security API's needed for the web-vault to work arn't allowed.
