### ISSUE TITLE
Cannot bulk delete collection items

### ISSUE THREAD

**Issue by lucianf** [dani-garcia/bitwarden_rs#1274]
### Subject of the issue
I created an organization, imported a few dozen items (they ended up in the Unassigned collection), and now I'm trying to delete them as I understood the correct process is to rather have the items imported into a user vault and shared from there into the organization collection.

However, when I select multiple items (either by using the checkboxes next to the items, or by using the bulk "select all" from the gear dropdown), after I pick "delete selected" nothing happens.

### Your environment
* Bitwarden_rs version: 1.17.0
* Install method: docker latest
* Clients used: web (2.16.1)
* Reverse proxy and version: nginx
* Version of mysql/postgresql: n/a
* Other relevant information:

### Steps to reproduce
Standard configuration of bitwarden_rs using docker-compose and linuxserver swag (nginx) as reverse proxy (for SSL).

### Expected behaviour
Deleting multiple items should work

### Actual behaviour
Debugging the POST query in the web console I see the response payload has a 422 Unprocessable Entity error with the following contents:" The request was well-formed but was unable to be followed due to semantic errors."

Deleting one item alone works, but I'm really looking to delete all items in bulk rather than one by one.

### Relevant logs
```
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="utf-8">
                <title>422 Unprocessable Entity</title>
            </head>
            <body align="center">
                <div role="main" align="center">
                    <h1>422: Unprocessable Entity</h1>
                    <p>The request was well-formed but was unable to
                be followed due to semantic errors.</p>
                    <hr />
                </div>
                <div role="contentinfo" align="center">
                    <small>Rocket</small>
                </div>
            </body>
            </html>
```

**Comment by BlackDex** [comment]
This has been fixed in the master branch.
To use that version please pull the `testing` tag instead of the `latest`.
