### ISSUE TITLE
Cannot log back into Firefox add-on. 

### ISSUE THREAD

**Issue by KnightTim** [dani-garcia/bitwarden_rs#1275]
### Subject of the issue
Cannot log back into Firefox addon. 

I was previously logged into the Firefox addon, when I try to login in displays an error: "An error has occurred. Error saving device"
Looking at the logs I believe this has something to do with unique IDs for devices. 

### Your environment

* Bitwarden_rs version: 1.17.0

* Install method: built from source 
* Clients used: Firefox Add-on
* Reverse proxy and version: nginx 1.10.3
* Version of mysql/postgresql: N/A (whatever is default) 
* Other relevant information: Using Firefox add-on version 1.47.1
https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/versions/

### Steps to reproduce
I am not sure how to reproduce, I think it was caused when I restored a backup of the sqlite DB from yesterday. 

### Steps to workaround
I am able to bypass the issue by uninstalling the Firefox add-on, restarting Firefox, then re-installing the add-on and logging in. 

### Expected behavior
The add-on should not have logged me out, or at least should have allowed me to login back in without reinstalling it. 

### Actual behavior
I can't login to the add-on. 

### Relevant logs
```
Dec 20 19:53:14 bitwarden_rs[28995]: [2020-12-20 19:53:14.225][error][ERROR] Error saving device.
Dec 20 19:53:14 bitwarden_rs[28995]: [CAUSE] DatabaseError(
Dec 20 19:53:14 bitwarden_rs[28995]:     UniqueViolation,
Dec 20 19:53:14 bitwarden_rs[28995]:     "UNIQUE constraint failed: devices.uuid",
Dec 20 19:53:14 bitwarden_rs[28995]: )
Dec 20 19:53:14 bitwarden_rs[28995]: [2020-12-20 19:53:14.227][response][INFO] POST /identity/connect/token (login) => 400 Bad Request
```

**Comment by BlackDex** [comment]
After a database restore it is better to deauthorize all user sessions. This would probably prevented your problem. The reason is that your backup already had your exertion in there but the extension logged-out because the security token was invalid, or it couldn't find the server for some reason.
