### ISSUE TITLE
Can't send email

### ISSUE THREAD

**Issue by e-belair** [dani-garcia/bitwarden_rs#1277]
### Subject of the issue
Server unable to send any email, I tried every possible settings, every time get the same error:
![image](https://user-images.githubusercontent.com/596562/102871838-35bae000-443f-11eb-9198-aa82dceac51d.png)

Usually I'm connection to ovh mail servers with these setting and use ssl

### Your environment
* Bitwarden_rs version:
1.17.0 with postgres
Installation via docker

Logs:
```
[2020-12-22 09:13:02.694][error][ERROR] SMTP IO error: Resource temporarily unavailable (os error 11)
[2020-12-22 09:13:02.694][response][INFO] POST /admin/test/smtp (test_smtp) => 400 Bad Request
```

**Comment by BlackDex** [comment]
@e-belair: Did you resolved it?

**Comment by e-belair** [comment]
Yeah, I think there were a network problem. Thank you
