### ISSUE TITLE
Cant connect to MySQL databse after upgrade to 1.18.0

### ISSUE THREAD

**Issue by EC58** [dani-garcia/bitwarden_rs#1289]
### Subject of the issue
After updating my docker version from 1.17 to 1.18 I can no longer connect to the MySQL database:

Getting the following error:
[bitwarden_rs][ERROR] Error creating database pool: DieselConError.

[CAUSE] BadConnection(

    "Plugin caching_sha2_password could not be loaded: /usr/lib/x86_64-linux-gnu/mariadb19/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory",

)

My mysql user is using mysql_native_password so I dont see why this error pops up. Should I be using MariaDB instead?

**Comment by musover** [comment]
I am also having this issue, running in a kubernetes cluster using CRI-O as a container runtime.

**Comment by BlackDex** [comment]
I suggest to use a mariadb container for the database. Or create a database user which does not use the the latest mysql password features. That error message will only appear if it needs to use that password feature. But that isn't build into. It is something we need to see if that is possible at all using the current library versions.

**Comment by sbmw** [comment]
Thanks @BlackDex but (as with @EC58) my database user is already set to not use the sha2 password features.  The same db user was working fine with 1.17.0. 

```
mysql> select User, Plugin from user;

+------------------+-----------------------+
| User             | Plugin                |
+------------------+-----------------------+
| bitwarden        | mysql_native_password |

```

Perhaps one of the updated dependencies in 1.18.0?

**Comment by BlackDex** [comment]
Which image are you using? amd64? Alpine or default?

**Comment by sbmw** [comment]
Default I believe:

bitwardenrs/server-mysql:1.18.0

**Comment by BlackDex** [comment]
I would suggest to start using the `bitwardenrs/server:latest` version with the next release instead of the `-mysql`, both are the same and we will probably remove the -mysql and -postgresql versions in the future.

Could you try to install the libmariadb3 package within the docker?
It will only work untill the next restart, but at least you could test if it works.

You could add this via the start.sh feature by creating a script called bitwarden_rs.sh and volume-mount that to /etc/bitwarden_rs.sh which gets started before bitwarden itself.

Check if that works.

**Comment by sbmw** [comment]
Hey, so I switched to bitwardenrs/server:latest and volume mounted the startup file with contents:

```
apt-get update
apt-get install libmariadb3
```

The container log now shows:

```
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://security.debian.org/debian-security buster/updates/main amd64 Packages [260 kB]
Get:3 http://deb.debian.org/debian buster InRelease [121 kB]
Get:4 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [7860 B]
Fetched 8414 kB in 2s (4910 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
libmariadb3 is already the newest version (1:10.3.27-0+deb10u1).
libmariadb3 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
/--------------------------------------------------------------------\
|                       Starting Bitwarden_RS                        |
|                           Version 1.18.0                           |
|--------------------------------------------------------------------|
| This is an *unofficial* Bitwarden implementation, DO NOT use the   |
| official channels to report bugs/features, regardless of client.   |
| Send usage/configuration questions or feature requests to:         |
|   https://bitwardenrs.discourse.group/                             |
| Report suspected bugs/issues in the software itself at:            |
|   https://github.com/dani-garcia/bitwarden_rs/issues/new           |
\--------------------------------------------------------------------/

[INFO] No .env file found.

[2021-01-04 12:41:31.018][bitwarden_rs::util][WARN] Can't connect to database, retrying: DieselConError.
[CAUSE] BadConnection(
    "Plugin caching_sha2_password could not be loaded: /usr/lib/x86_64-linux-gnu/mariadb19/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory",
)

...
```

So, already installed?

**Comment by sbmw** [comment]
Is "[INFO] No .env file found." the issue?

I'm volume mounting a directory containing a config.json to /data, this contains my mysql user details.

Should we be using a .env file?

**Comment by BlackDex** [comment]
No, that is just to notice that your environment isn't using a .env file.
Docker loads all the environment variables into the environment. So nothing to worry about.

The strange thing is.
Debian (Buster) doesn't have that library file at all, it's no where in there repo's.
It only is on Ubuntu, and that is not what we are using to build these container images.
All is using the same Debian version.

**Comment by jjlin** [comment]
This seems unlikely to have anything to do with the bitwarden_rs upgrade per se, as I don't think there have been any related changes between 1.17.0 and 1.18.0. So there's probably been a MySQL server or configuration change on your side, perhaps without your knowledge. If you do a web search for `Plugin caching_sha2_password could not be loaded`, there are various things you can try.

Debian will be including this plugin in the next release (Bullseye), but that probably won't be out until mid-late 2021:

* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962597
* https://packages.debian.org/bullseye/amd64/libmariadb3/filelist

**Comment by EC58** [comment]
Could this be the issue: 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962597

**Comment by musover** [comment]
While attempting to migrate from MySQL to PostgreSQL, I have found out that despite being configured to use mysql_native_password as an authentication backend, the user bitwarden_rs uses to connect was still using caching_sha2_password regardless, and this is due to a missing setting on /etc/my.cnf on the MySQL server itself.

As a stopgap solution, you can try adding/uncommenting `default-authentication-plugin=mysql_native_password` on the [mysqld] section, which will enforce mysql_native_password.

**Comment by everyx** [comment]
> While attempting to migrate from MySQL to PostgreSQL, I have found out that despite being configured to use mysql_native_password as an authentication backend, the user bitwarden_rs uses to connect was still using caching_sha2_password regardless, and this is due to a missing setting on /etc/my.cnf on the MySQL server itself.
> 
> As a stopgap solution, you can try adding/uncommenting `default-authentication-plugin=mysql_native_password` on the [mysqld] section, which will enforce mysql_native_password.

I have already changed the user's auth type to `mysql_native_password`, but not change the global default auth type to `mysql_native_password`, and  this error is still be reported when upgrade to v1.18.

**Comment by rouben** [comment]
Thank you, @musover, this fixes the issue.
I am running MySQL server version: 8.0.22-0ubuntu0.20.04.3 - (Ubuntu). This is not MariaDB.

@everyx, try the suggestion. This option needs to be added to the appropriate section of your MySQL server, not the Bitwarden docker image.

**Comment by everyx** [comment]
> Thank you, @musover, this fixes the issue.
> I am running MySQL server version: 8.0.22-0ubuntu0.20.04.3 - (Ubuntu). This is not MariaDB.
> 
> @everyx, try the suggestion. This option needs to be added to the appropriate section of your MySQL server, not the Bitwarden docker image.

@rouben I use MySQL 8 instance offered by DigitalOcean Management Database servcie, so I couldn't change the global auth type, but I can changed this for a single user, and I did it, but the error still happens, the v1.17 is worked for this user-specified workaround.

**Comment by rouben** [comment]
@everyx I tried the per-user override ass well with no success. The only thing that worked for me is the server-level setting. Unfortunately with a managed MySQL instance you may not have the ability to change that setting. Having said this, I don't know why the previous release of BitWarden-RS MySQL docker build did work with the per-user override. There is speculation that it may have something to do with the build image for the MySQL enabled BitWatden-RS binary within this docker image...
