### ISSUE TITLE
Accent

### ISSUE THREAD

**Issue by dr400** [dani-garcia/bitwarden_rs#1290]
Hi,

Work done is great ! just a quick remark about accentuated words. In the interface, the accentuated letters are displayed with �.
I'm using bitwaren_rs under docker. Is there a specific ENV variable to make it display accentuated words correctly ?
Thx in advance
Cédric
PS : import from csv

**Comment by BlackDex** [comment]
Could you explain where you see this?
Because if this has anything to do with e web-vault it's not something we can fix.

Could you provide a screenshot maybe to show what you mean?

**Comment by dr400** [comment]
I've exported from another wallet. The export was CSV. For some cards, accented characters were not properly exported.
The interface is web based
![image](https://user-images.githubusercontent.com/48514024/103455381-d4bbc380-4cec-11eb-88b7-b93368bc29ba.png)

**Comment by BlackDex** [comment]
That is something we can not fix. This is all done via the web-vault which is build and maintained by bitwarden.com.

You should make an issue there an report this.

**Comment by dr400** [comment]
ok thanks !
