### ISSUE TITLE
F2A FIDO since 1.18.0

### ISSUE THREAD

**Issue by thelittlefireman** [dani-garcia/bitwarden_rs#1301]
reregister does nothing

### Subject of the issue
2FA FIDO not working in 1.18.0

### Your environment

* Bitwarden_rs version: 1.18.0

* Install method: Docker
* Clients used: web browser chrome
* Reverse proxy and version: nginx 1.18
* Version of mysql/postgresql: 
* Other relevant information:
DOMAIN YUBIKEY_API SERVER and secret redacted
Perfectly working in 1.17.0 i just upgrade the docker without change configuration

### Steps to reproduce
Activate 2FA in your account.
Disconect
Try login in web browser with 2FA FIDO
FIDO is loading infinitly

### Expected behaviour
2FA FIDO connection works

### Actual behaviour
FIDO is loading infinitly

### Relevant logs
Nothing special in logs, no message in web console like in #1300

![https://i.ibb.co/8Yh4fs5/screen.jpg](https://i.ibb.co/8Yh4fs5/screen.jpg)

**Comment by BlackDex** [comment]
I think error 5 means that either there's no https or the domain doesn't match. Please check those items first
