### ISSUE TITLE
bitwarden_rs hangs at web1

### ISSUE THREAD

**Issue by Yosemite82** [dani-garcia/bitwarden_rs#1302]
Hello

I'm completely new to Docker and all the stuff arround and I'm trying now for too long to install bitwarden_rs with SSL. After a lot of research I've found bitwarden-rs-nginx-docker from RomanHargrave and after a lot of reading and trying I was able to build a bitwaren_rs Docker. But when I'm now starting up my container, it stays in a loop here: 

```
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- ('fa237e48d9e77859bfc560f2ef202932411e5db68ecf7d83b8a60522250a3ae5')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.30/containers/fa237e48d9e77859bfc560f2ef202932411e5db68ecf7d83b8a60522250a3ae5/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {'AppArmorProfile': 'docker-default',
 'Args': [],
 'Config': {'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': ['/start.sh'],
            'Domainname': '',
            'Entrypoint': None,
            'Env': ['PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
                    'ROCKET_ENV=staging',
...
```

My Dockerfile is from here: https://github.com/RomanHargrave/bitwarden-rs-nginx-docker/blob/master/Dockerfile and my docker-compose.yml looks like that: 

```
version: "3.3"
services:
  web:
    build: .
    ports:
      - "80:80"
      - 443:443"
  redis:
    image: "bitwardenrs/server"
```

After fireing up, it loops here: 

`web_1    | [2021-01-08 23:52:53.718][parity_ws][INFO] Listening for new connections on 0.0.0.0:3012.`

I have no clue, where to start... Hope, anybody can help me.

Thank you in advance and regards
Marcel

**Comment by Biepa** [comment]
If you're new to docker. Why not just start the bitwardenrs container itself, instead of the one you linked?

**Comment by Yosemite82** [comment]
Hi Biepa

Due to my Bitwarden-Installation-Horror-Trip let me go to the package mentioned above. But in the meantime I've postet my question also there... Roman answered there and I'm looking forward to get this pies of ... up and running.
