### ISSUE TITLE
Cannot download attachments via iOS/iPad/OSX and Browser-addon (all browsers)

### ISSUE THREAD

**Issue by tchap2** [dani-garcia/bitwarden_rs#1313]
### Subject of the issue

Upon uploading an attachment (.jpg and .pdf) via iOS/iPad/OSX and any browser add-on (all browsers), I amm unable to download that attachment with following error message:
- iOS/iPad: "Unable to download file"
- OSX, and browser addon: continuous spinning wheel.

When browsing to Bitwarden folder->attachments on my server, I can clearly see attachments in encrypted form.
### Your environment

* Bitwarden_rs version: 1.18.0

* Install method: Docker (bitwardenrs, 1.18.0) on UNRAID server (6.8.3)
* Clients used:  iOS, iPad, OSX, browser addons (Firefox, Safari, Chrome)
* Reverse proxy and version:  Letsencrypt docker (by linuxserver.io)
* Version of mysql/postgresql: 
* Other relevant information:

### Steps to reproduce

See above in description

### Expected behaviour

Able to download and view attachments

### Actual behaviour

See above in description

### Relevant logs

Bitwarden log does't show any error messages, not even a log of an attempt to download the attachment.

**Comment by BlackDex** [comment]
You probably have the DOMAIN variable configured incorrectly.
If that doesn't match the actual domain the attachment download will fail.

**Comment by tchap2** [comment]
> You probably have the DOMAIN variable configured incorrectly.
> If that doesn't match the actual domain the attachment download will fail.

Can you pls elaborate? Where is DOMAIN variable configured?

**Comment by BlackDex** [comment]
I don't know exactly how unraid works. But you probably have configured some settings for the docker container. There you need to configure the DOMAIN variable to match what you type in into the browser or clients to connect to your server.

See: https://github.com/dani-garcia/bitwarden_rs/blob/37cc0c34cf5732cbe7b0d4aea622acdd615e3ef6/.env.template#L194

**Comment by tchap2** [comment]
> I don't know exactly how unraid works. But you probably have configured some settings for the docker container. There you need to configure the DOMAIN variable to match what you type in into the browser or clients to connect to your server.
> 
> See:
> 
> https://github.com/dani-garcia/bitwarden_rs/blob/37cc0c34cf5732cbe7b0d4aea622acdd615e3ef6/.env.template#L194

Thnx but the domain is set up correctly. I'd appreciate context-appreciative answer, from someone who knows and understand both UNRAID, Letsencrypt and Bitwarden.

**Comment by tchap2** [comment]
> I don't know exactly how unraid works. But you probably have configured some settings for the docker container. There you need to configure the DOMAIN variable to match what you type in into the browser or clients to connect to your server.
> 
> See:
> 
> https://github.com/dani-garcia/bitwarden_rs/blob/37cc0c34cf5732cbe7b0d4aea622acdd615e3ef6/.env.template#L194

Yup. the issue was in Docker Bitwarden config file. Instead of https:// it was http://
works now.

**Comment by BlackDex** [comment]
Great :).

**Comment by Magic-Deceiver** [comment]
is it possible to give me a pointer on where I can find this .env file? I am experiencing the exact same issue but I am completely not sure where to go after searching for answers for hours. Any helps would be greatly appreciated!

**Comment by jjlin** [comment]
https://github.com/dani-garcia/bitwarden_rs/wiki/Configuration-overview
