### ISSUE TITLE
bitwardenrs/server:raspberry missing

### ISSUE THREAD

**Issue by biggdaniell** [dani-garcia/bitwarden_rs#1315]
It seems this image is no longer available, I get "manifest for bitwardenrs/server:raspberry not found: manifest unknown: manifest unknown"

**Comment by BlackDex** [comment]
That is was not being updated for a long time already.
You should just use `bitwardenrs/server:latest` or `bitwardenrs/server:testing`.
It should select the correct image automatically.
If you are using an `arm32v6` based Raspberry Pi, you may need to use one of these two, `bitwardenrs/server:latest-arm32v6` or `bitwardenrs/server:testing-arm32v6`.

**Comment by biggdaniell** [comment]
I'm using a Raspberry Pi 4 and already tried with latest, the install is getting stuck while the web interface is actually up and usable. However, I can't create an account, nothing happens when I click submit (or create, whatever).
Also, RPI4 is using arm v7, not sure is latest-arm32v6 is the right image.
