### ISSUE TITLE
Docker install fails

### ISSUE THREAD

**Issue by jackald** [dani-garcia/bitwarden_rs#1320]
### Subject of the issue
Docker install fails

### Your environment
Docker image image: bitwardenrs/server:latest pulled today
 Bitwarden_rs version: 
|                           Version 1.18.0                           |

Install method: Docker
Clients used: 
Client: Docker Engine - Community
 Version:           20.10.2
* Reverse proxy and version: 
* Version of mysql/postgresql: 
* Other relevant information:

### Steps to reproduce
Stack used in portainer:
version: 2
services:
    BitwardenRS:
      image: bitwardenrs/server:latest
      container_name: BitwardenRS
      volumes:
      - /srv/b7ee8e59-561e-41ad-b896-e8dca8accc33/Docker/BitWardenRS:/data
      ports:
      - 8086:80
      restart: unless-stopped

### Expected behaviour
Container to start and the web gui to be reachable

### Actual behaviour
The container erros with 'Failed to turn on WAL: DatabaseError(__Unknown, "disk I/O error")': src/db/mod.rs:275

### Relevant logs
/--------------------------------------------------------------------\

|                       Starting Bitwarden_RS                        |

|                           Version 1.18.0                           |

|--------------------------------------------------------------------|

| This is an *unofficial* Bitwarden implementation, DO NOT use the   |

| official channels to report bugs/features, regardless of client.   |

| Send usage/configuration questions or feature requests to:         |

|   https://bitwardenrs.discourse.group/                             |

| Report suspected bugs/issues in the software itself at:            |

|   https://github.com/dani-garcia/bitwarden_rs/issues/new           |

\--------------------------------------------------------------------/

FO] No .env file found.

[2021-01-20 22:54:23.576][panic][ERROR] thread 'main' panicked at 'Failed to turn on WAL: DatabaseError(__Unknown, "disk I/O error")': src/db/mod.rs:275

   0: bitwarden_rs::init_logging::{{closure}}

   1: std::panicking::rust_panic_with_hook

             at rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/panicking.rs:595:17

   2: std::panicking::begin_panic_handler::{{closure}}

             at rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/panicking.rs:497:13

   3: std::sys_common::backtrace::__rust_end_short_backtrace

             at rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/sys_common/backtrace.rs:141:18

   4: rust_begin_unwind

             at rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/panicking.rs:493:5

   5: core::panicking::panic_fmt

             at rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/core/src/panicking.rs:92:14

   6: core::option::expect_none_failed

             at rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/core/src/option.rs:1268:5

   7: bitwarden_rs::db::sqlite_migrations::run_migrations

   8: bitwarden_rs::db::DbPool::from_config

   9: bitwarden_rs::util::retry_db

  10: bitwarden_rs::main

  11: std::sys_common::backtrace::__rust_begin_short_backtrace

  12: std::rt::lang_start::{{closure}}

  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once

             at rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/core/src/ops/function.rs:259:13

      std::panicking::try::do_call

             at rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/panicking.rs:379:40

      std::panicking::try

             at rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/panicking.rs:343:19

      std::panic::catch_unwind

             at rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/panic.rs:396:14

      std::rt::lang_start_internal

             at rustc/da384694807172f0ca40eca2e49a11688aba6e93/library/std/src/rt.rs:51:25

  14: main

  15: __libc_start_main
      
  16: _start

**Comment by BlackDex** [comment]
You seem to be using some kind of shared storage for your /data folder. Shared/Network storage is know to cause some issues. So either disable wal using the configuration or use a different database.

**Comment by jackald** [comment]
Turning of wal worked thank you.
