### ISSUE TITLE
Single Organization & Personal settings to be hidden

### ISSUE THREAD

**Issue by hvisage** [dani-garcia/bitwarden_rs#1361]
as requested: https://bitwardenrs.discourse.group/t/spinning-dialog-box-edit-policy-single-organization/573

### Your environment

web_build 2.17.1 & 2.18.1

* Bitwarden_rs version: 1.18.0
* web_build 2.17.1 & 2.18.1

* Install method: rust compiled
* Clients used: 
* Reverse proxy and version: 
* Version of mysql/postgresql: 
* Other relevant information:

### Steps to reproduce

go to Policy & click on Single Organization (2.17.1+) and Personal entries (2.18.1)

![image](https://user-images.githubusercontent.com/11662665/107074882-07784080-67f2-11eb-89d6-8a1e4bf1dc44.png)
Get a spinning wheel

### Expected behaviour

Seems the need to hide these.

**Comment by jjlin** [comment]
Personal Ownership was already implemented in #1326, though it hasn't made it in a release yet.

**Comment by BlackDex** [comment]
This is not personal ownership is not the same as single organization.

**Comment by BlackDex** [comment]
Also, i can confirm this on the `testing` and `master` branch.

**Comment by jjlin** [comment]
> This is not personal ownership and it is not the same as single organization.

I know, I'm only referring to the Personal Ownership part of this issue.

**Comment by BlackDex** [comment]
Ah, sorry, looked over the title hehe.

**Comment by hvisage** [comment]
Well, both hit me, so that's the reason I added both in the header/title ;)

**Comment by BlackDex** [comment]
If you compile the master branch you would at least have the personal ownership function.
