### ISSUE TITLE
build error with 1.19.0 (async branch)

### ISSUE THREAD

**Issue by bhopmann** [dani-garcia/bitwarden_rs#1369]
### Subject of the issue

Latest `1.19.0` version on `async` branch fails to build.

### Your environment

* Bitwarden_rs version: `1.19.0` (using the `async` branch):

* Install method: manual build
* Clients used: 
* Reverse proxy and version: 
* Version of mysql/postgresql: 
* Other relevant information: compile for sqlite 

### Steps to reproduce

```
git clone https://github.com/dani-garcia/bitwarden_rs.git
git checkout origin/async
cargo build -j 1 --release --features sqlite
```

### Expected behaviour

successful build

### Actual behaviour

build error when compiling `bitwarden_rs`

### Relevant logs

```
error: could not compile `bitwarden_rs`

Caused by:
  process didn't exit successfully:
[...]
(signal: 9, SIGKILL: kill)
```

**Comment by BlackDex** [comment]
On what kind of hardware are you trying to build this?
Most of the time these errors are low memory related.

Also, the async branch could be build with the latest stable if im correct. You just need to override the rust-toolchain file by using `cargo +stable build ...`
