### ISSUE TITLE
Migrate from official self hosted is possible?

### ISSUE THREAD

**Issue by riccardospeggiorin-centropaghe** [dani-garcia/bitwarden_rs#1372]
Hi, is it possible to migrate from the docker official self hosted installation ?
Thanks

**Comment by tanerpaca** [comment]
I’ve done it very recently without any problem, just export vault and import in bitwarden_rs, took me few seconds.

**Comment by riccardospeggiorin-centropaghe** [comment]
mm ok but I don't ask for my own vault, but for all the users's vaults
