### ISSUE TITLE
Group Sync via the Directory Connector does not work

### ISSUE THREAD

**Issue by bokkabonga** [dani-garcia/bitwarden_rs#1401]
### Subject of the issue
Syncing Groups via the Directory Connector does not work, while Syncinc Users works just fine. When using the "Test Sync" button the Directory Connector will find the Group and the Users inside the Group but after hitting the "Sync Now" Button no Users will be invited.

  ### Your environment (Generated via diagnostics page)
  * Bitwarden_rs version: v1.19.0-c836f88f
  * Web-vault version: v2.18.1
  * Running within Docker: true
  * Internet access: true
  * Uses a proxy: false
  * DNS Check: true
  * Time Check: true
  * Domain Configuration Check: true
  * HTTPS Check: true
  * Database type: MySQL
  * Database version: MariaDB 10.4
  * Clients used: Directory Connector Portable Windows
  * Reverse proxy and version: 
  * Other relevant information: 

### Steps to reproduce
1. Open Directory Connector and configure it to Connect to LDAP Server. 
2. Define Group Filter and test the Sync
3. Try to actually Sync

### Expected behaviour
Users should be invited to the Organisation.

### Actual behaviour
No Invitations are beeing send. Nothing appears in the Log or the Developer Console of the Directory Connector itself.

**Comment by BlackDex** [comment]
Bitwarden_RS doesn't support groups. Therefor i think that that part of the directory connector will not work with our implementation.
