### ISSUE TITLE
Unable to backup the database because "attempt to write a readonly database"

### ISSUE THREAD

**Issue by X4V1** [dani-garcia/bitwarden_rs#1404]
Hello

I'm facing an issue that i'm struggling to debug.
When I'm trying to do a backup with the command: /usr/bin/sqlite3 /data/db.sqlite3 ".backup 'data/db_backup/backup.sqlite3"
I'm getting an error saying "attempt to write a readonly database".
I can't find why it says that the database is readonly, did I missed something ? Am I forced to stop the container before running this command ?

Kind regards,

Xavier

**Comment by jjlin** [comment]
`data/db_backup/backup.sqlite3` probably isn't writable.

**Comment by X4V1** [comment]
Thank for your answer, I think you're right. It seems to make a difference when I change folder permission. Thank :)
