### ISSUE TITLE
Can't import from lastpass

### ISSUE THREAD

**Issue by sstraus** [dani-garcia/bitwarden_rs#1406]
### Subject of the issue
Import from lastpass fail. Seems something related to cards or private notes. 
### Your environment
* Bitwarden_rs version: 2.18.1

**Comment by BlackDex** [comment]
Hello,

First, please update to the latest version as mentioned on several places before you were able to report an issue.

Second, we really need more info then this. Were there errors in the bitwarden_rs logs? Etc.. etc..

**Comment by sstraus** [comment]
As i know is the latest docker version. Where can I get required log files in the docker filesystem?

**Comment by BlackDex** [comment]
Ah, i see now that you used the web-vault version instead of the bitwarden_rs version.
The logs should be in your volume called bitwarden.log, or use `docker logs <container-name>`

**Comment by sstraus** [comment]
Finally  I succeed splitting the csv file in chunks. Probably was a timeout.
Thank you.

**Comment by dumblob** [comment]
@sstraus how many lines did the chunks have (just to get an impression what to watch out for).
