### ISSUE TITLE
Unable to select collection when cloning to another organization in web vault, but desktop app works fine

### ISSUE THREAD

**Issue by yumenoshizuku** [dani-garcia/bitwarden_rs#1427]
### Subject of the issue

In web vault, when cloning from one organization to another, the Collections pane shows `There are no collections to list.` when changing organization selection. But the desktop app can show the collections correctly.
### Your environment

* Bitwarden_rs version: 1.19.0, also tested with 1.18.0, 1.17.0
* Web installed: 2.18.1, also tried substituting with bitwarden/web:2.18.1 docker image but the problem persists

* Install method: Docker-compose
* Clients used:  Chrome, Firefox, Edge, Safari
* Reverse proxy and version:  Apache/2.4.41 (Ubuntu) on another machine
* Version of mysql/postgresql:  SQLite 3
* Other relevant information:
```
# Reverse Proxy Configuration
<VirtualHost *:80>
  ServerName public.domain.com
  ProxyPreserveHost On
  DocumentRoot /var/www/html
  ProxyPass /.well-known !
  ProxyPass / http://private.ip:80/
  ProxyPassReverse / http://private.ip:80/
  RewriteEngine on
  RewriteCond %{SERVER_NAME} =public.domain.com
  RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<VirtualHost *:443>
  ServerName public.domain.com
  ProxyPreserveHost On
  DocumentRoot /var/www/html
  RewriteEngine On
  RewriteCond %{HTTP:Upgrade} =websocket [NC]
  RewriteRule /(.*)           ws://private.ip:3012/$1 [P,L]
  RewriteCond %{HTTP:Upgrade} !=websocket [NC]
  RewriteRule /(.*)           http://private.ip:80/$1 [P,L]
  ProxyPass /.well-known !
  ProxyPass / http://private.ip:80/
  ProxyPassReverse / http://private.ip:80/
  SSLCertificateFile /etc/letsencrypt/live/public.domain.com/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/public.domain.com/privkey.pem
  Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
```
```
# Environment variables in .env file
WEBSOCKET_ENABLED=true
WEBSOCKET_ADDRESS=0.0.0.0
WEBSOCKET_PORT=3012
SIGNUPS_ALLOWED=false
ORG_CREATION_USERS=my_account_email
ADMIN_TOKEN=complex_token
DOMAIN=public.domain.com
```
```
# docker-compose.yml
version: '3'

services:
  bitwarden:
    image: bitwardenrs/server
    restart: always
    volumes:
      - /bw-data:/data
    ports:
      - 80:80
      - 3012:3012
    env_file:
      - /etc/bitwarden/.env
```
### Steps to reproduce

Edit .env, setup Apache reverse proxy on another machine, run bitwarden_rs with `docker-compose up -d`
Create two or more organizations, then create a few collections in each organization. Add one or more items to any of the collection. Click the gear icon and choose Clone.

### Expected behaviour

When selecting a different organization under Ownership, the Collections pane should show a list of collections in that organization that the user has write access to.

### Actual behaviour

The Collections pane shows `There are no collections to list.`

### Relevant logs

Created an item in First Organization, First Collection
<img width="397" alt="ItemInFirstOrg" src="https://user-images.githubusercontent.com/4616011/108775400-0738ae80-752f-11eb-8cbe-692b3712affb.png">
Affter clicking Clone, can choose another collection in the same organization
<img width="298" alt="CloneInitial" src="https://user-images.githubusercontent.com/4616011/108775422-0e5fbc80-752f-11eb-82e0-b871da8ee757.png">
After choosing another organization, no collections are shown
<img width="298" alt="CloneSecondOrg" src="https://user-images.githubusercontent.com/4616011/108775439-13247080-752f-11eb-9149-d7deafbb83db.png">
In desktop app, after clicking Clone, can choose another collection in the same organization
<img width="528" alt="DesktopCloneInitial" src="https://user-images.githubusercontent.com/4616011/108775451-1586ca80-752f-11eb-9cec-b6810cf452c6.png">
In desktop app, after choosing another organization, available collections are shown
<img width="530" alt="DesktopCloneSecondOrg" src="https://user-images.githubusercontent.com/4616011/108775460-1881bb00-752f-11eb-8414-4a4c4616845a.png">

**Comment by jjlin** [comment]
Thanks for the detailed report. I was able to reproduce this issue in the bitwarden_rs web vault. However, I was also able to reproduce it at https://vault.bitwarden.com/, so the issue originates in the upstream web vault code. I'd suggest opening an issue at https://github.com/bitwarden/web/issues and providing them the steps to reproduce.

When you open an issue there, I'd suggest that you only mention https://vault.bitwarden.com/, and leave out any mention of bitwarden_rs or your hosting environment to avoid any potential confusion about whether this is a bitwarden_rs issue. Or at least be very clear that the issue does affect https://vault.bitwarden.com/.

**Comment by yumenoshizuku** [comment]
Thanks for the advice!

**Comment by vandermark1977** [comment]
I have the same problem? Is this resolved?

**Comment by BlackDex** [comment]
See https://github.com/dani-garcia/vaultwarden/discussions/3016

**Comment by vandermark1977** [comment]
Hmm, I am not using the browser plugin, I am just working inside the vault in the webbrowser. Plugin is active though... Why cant I see any collections when I try to clone to different organization?

https://share.bartserver.nl/!MX3qPjL8jk/pasted-2022-12-26T132700.862Z.png

**Comment by BlackDex** [comment]
It doesn't matter which client you use. It just isn't supported.
Only way would be to clone it to your personal vault and then move it to the other org afterwards.

**Comment by vandermark1977** [comment]
Thank you, that makes the issue clear for me. Your suggestion worked fine, tx!
