### ISSUE TITLE
Problems after update

### ISSUE THREAD

**Issue by MeiRos** [dani-garcia/bitwarden_rs#1428]
### Subject of the issue

I just updated my Bitwarden and Nginx. Both are docker images. I'm running it on Raspberry pi 3 B+. I have updated many times and system worked fine until now.
After update it's hard to connect with browser and when I can, I didn't see my passwords. Passwords are still in my app. It shows only Bitwarden logo when I can't connect.
### Your environment

* Bitwarden_rs version: just updated 

* Install method: docker image 
* Clients used: 
* Reverse proxy and version: 
* Version of mysql/postgresql: sqlite
* Other relevant information:

### Expected behaviour

Start working like before
### Relevant logs

I'm sorry, but I don't have time to write more. I wrote something to discussion. There were similar cases.
This is also warning to others.
Can I lose my passwords in the app if it syncronize with the server? (I have backup too)
I'll continue to test my system and write more here. As soon as I have time.

**Comment by BlackDex** [comment]
Posting at two places is not really useful.

Also, we need more information like logs from bitwarden and maybe even nginx. We can't help you right now with what you gave.

Could you also check the /admin/diagnostics page and generate a support strong there?
