### ISSUE TITLE
[Feature Request] Support Send api

### ISSUE THREAD

**Issue by markcs** [dani-garcia/bitwarden_rs#1482]
Bitwarden have introduced Send.  Refer to https://bitwarden.com/products/send/

When trying this functionality from Android, I see the following error in the server logs

```
[2021-03-12 23:37:08.973][request][INFO] POST /api/sends
[2021-03-12 23:37:08.973][response][INFO] 404 Not Found
```

It would be great if it could be implemented in bitwarden_rs

**Comment by videogame-hacker** [comment]
The lead developer has already posted a stance on this:

https://github.com/dani-garcia/bitwarden_rs/issues/246#issuecomment-796966385

> I'll take a stab at implementing it over the weekend.

**Comment by BlackDex** [comment]
This has been mentioned a few times already. https://github.com/dani-garcia/bitwarden_rs/issues/246#issuecomment-796966385
