### ISSUE TITLE
A possibility to use local ip instead domain

### ISSUE THREAD

**Issue by Darkyere** [dani-garcia/bitwarden_rs#1485]
I have a Raspberry PI 4 on which i wont to have my BitWardenrs server.

And i just want to WireGuard into my network and get access to my BitWardenrs server though its IP address.

Following the guide on 
[Using Docker-Compose](https://github.com/dani-garcia/bitwarden_rs/wiki/Using-Docker-Compose)
I go to the bottom of the page and choose
[DNS-alias-mode](https://github.com/acmesh-official/acme.sh/wiki/DNS-alias-mode)

But i cant seem to figure out how to do this with certificates and just a local IP on my LAN.

This is my config

```
# docker-compose.yml
version: '3'

services:
 bitwarden:
  image: bitwardenrs/server:latest
  restart: always
  volumes:
      - ./bw-data:/data
      - ./ssl:/ssl
  ports:
    - 443:80
  environment:
   ROCKET_TLS: '{certs = "/ssl/fullchain.pem", key = "/ssl/key.pem"}'
   LOG_FILE: '/data/bitwarden.log'
   SIGNUPS_ALLOWED: 'true'
```

----

Any help would be appreciated

**Comment by fe-data** [comment]
https://github.com/dani-garcia/bitwarden_rs/wiki/Running-a-private-bitwarden_rs-instance-with-Let%27s-Encrypt-certs
