### ISSUE TITLE
Upgrade to new version 2.19

### ISSUE THREAD

**Issue by gkl1368** [dani-garcia/bitwarden_rs#1488]
Running migration 20210311190243
BitWarden              | Executing migration script 20210311190243/up.sql
BitWarden              | [2021-03-15 10:39:46.977][bitwarden_rs::util][WARN] Can't connect to database, retrying: DieselMigError.
BitWarden              | [CAUSE] QueryError(
BitWarden              |     DatabaseError(
BitWarden              |         __Unknown,
BitWarden              |         "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'NOT NULL,\n  password_hash     BLOB,\n  password_salt     BLOB,\n  password_iter...\' at line 11",

I have this problem when I upgrade to 2.19，I use docker with MySQL. It work ok before update.

**Comment by BlackDex** [comment]
Please check your database Collation.
See: https://github.com/dani-garcia/bitwarden_rs/issues/1305#issuecomment-774558466 for some info.
This could cause some strange issues when it has a different collation, it could very well be this issue.

**Comment by dani-garcia** [comment]
I think MySQL doesn’t allow using key as a column name, might need to rename it to akey like with the user table.

We’ll need to modify the existing MySQL migration and create two new ones for the other two.

**Comment by gkl1368** [comment]
> I think MySQL doesn’t allow using key as a column name, might need to rename it to akey like with the user table.
> 
> 
> 
> We’ll need to modify the existing MySQL migration and create two new ones for the other two.

OK. I will wait for your modify. Thanks

**Comment by gkl1368** [comment]
After upgrade to new docker image, it works. Thanks.
