### ISSUE TITLE
Report Organization type as Enterprise or something less limited

### ISSUE THREAD

**Issue by mprasil** [dani-garcia/bitwarden_rs#15]
I think we should report any Organization as `Enterprise` (5) to remove the artificial limits imposed by client applications for `Free` type. Just changing the `Plan` and `PlanType` fields doesn't seem to work however as we don't really return them outside of Organization creation. I'm actually not sure what API is the client using to figure the current plan for Organization.

**Comment by dani-garcia** [comment]
What are the client-side limits exactly? I figured it was all done on the server side and that field didn't serve any actual purpose.

**Comment by mprasil** [comment]
For example you can't add attachment to shared cipher. The Vault won't even do any request and straight away prompts you to update your plan.

**Comment by dani-garcia** [comment]
I can't test it right now, but try putting MaxStorageGb in the organization to_json function to a numeric value other than zero.

**Comment by mprasil** [comment]
That worked! :smile: Created a PR #16 for that.
