### ISSUE TITLE
File becomes unavailable after Send modification

### ISSUE THREAD

**Issue by Nyxtorm** [dani-garcia/bitwarden_rs#1504]
### Subject of the issue

When I create a Send with a file, it works. But if I change the Send's password (for example), the file becomes impossible to download.

### Deployment environment

* Bitwarden_rs version: v1.19.0-b987ba50
* Web-vault version: v2.19.0
* Running within Docker: false
* Internet access: true
* Uses a proxy: false
* DNS Check: true
* Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Install method: built from sources
* Clients used: web vault (for the test)
* Reverse proxy and version: nginx/1.19.5

### Steps to reproduce

1. Create a Send with a simple .png
2. Check if you can download it
3. Make a change (password in my case)
4. Check if you can download the file again

### Expected behaviour

The file should be able to be downloaded after a modification of the Send (change password for example)

### Actual behaviour

The file becomes unavailable and its title changes on the Send.

### Troubleshooting data

Before modification on the Send :

![image](https://user-images.githubusercontent.com/20800786/111450167-6a71c700-8710-11eb-929a-8b13f9bac454.png)

After a change on the Send : 

![image](https://user-images.githubusercontent.com/20800786/111450219-78274c80-8710-11eb-962c-f5bb7a32c1ea.png)

Sorry for my bad English and thank you for offering us all this work on this version of Bitwarden!

**Comment by dani-garcia** [comment]
Fixed in https://github.com/dani-garcia/bitwarden_rs/commit/551810c4862506ed39780850a35ac12df1aca1a9
