### ISSUE TITLE
MySQL not enabled on Alpine Images

### ISSUE THREAD

**Issue by mplx** [dani-garcia/bitwarden_rs#1513]
### Subject of the issue

MySQL not enabled on alpine images; [wiki docs](https://github.com/dani-garcia/bitwarden_rs/wiki/Using-the-MariaDB-%28MySQL%29-Backend) suggest it works with alpine images ("...based upon MariaDB client libraries since that is what both Debian and Alpine provide...")

### Deployment environment

docker images `bitwardenrs/server:1.19.0-alpine` and `bitwardenrs/server:1.18.0-alpine`

* MySQL/MariaDB version: 10.3.27-MariaDB-0+deb10u1

* Other relevant details: same config works with debian images `bitwardenrs/server:1.19.0` and `bitwardenrs/server:1.18.0`

### Steps to reproduce

start docker container with alpine images `bitwardenrs/server:1.19.0-alpine` or `bitwardenrs/server:1.18.0-alpine` and try to connect to mysql

### Expected behaviour

connects to mysql

### Actual behaviour

```
bitwarden_test_bitwarden@docker    | Error loading config:
bitwarden_test_bitwarden@docker    | 	`DATABASE_URL` is a MySQL URL, but the 'mysql' feature is not enabled
```

**Comment by BlackDex** [comment]
Resolved.
Changed wiki to be accurate.
