### ISSUE TITLE
Unable to apply web build patch 2.19.0

### ISSUE THREAD

**Issue by hirodragon** [dani-garcia/bitwarden_rs#1520]
### Subject of the issue
Unable to apply web build patch 2.19.0 from https://github.com/dani-garcia/bw_web_builds/tree/master/patches
### Deployment environment
Rasbian 10 (Buster)

* bitwarden_rs version:
1.19.0

* Install method:
Building own binary

### Steps to reproduce

`git clone https://github.com/bitwarden/web.git web-vault.git`
`cd web-vault.git`
`git checkout v2.19.0`
`curl -O https://raw.githubusercontent.com/dani-garcia/bw_web_builds/master/patches/v2.19.0.patch`
`git apply v2.19.0.patch`

### Expected behaviour

Patch is applied.

### Actual behaviour

Patch is not applied, error message occurs:
`error: jslib/src/angular/components/register.component.ts: No such file or directory`
`error: patch failed: src/app/services/services.module.ts:135`
`error: src/app/services/services.module.ts: patch does not apply`
Same behaviour for 2.18.1 patch, last patch succesfully applied was 2.18.0.

**Comment by Nyxtorm** [comment]
Hello,

Your jslib folder should be empty. You should make a clone of the repository https://github.com/bitwarden/jslib.git and copy its contents to your empty web-vault's jslib folder.

For example : 

```
git clone https://github.com/bitwarden/web.git web-vault.git
git clone https://github.com/bitwarden/jslib.git
rsync -rtlDvP  jslib.git/ web.git web-vault.git/jslib/
cd web-vault.git
git checkout v2.19.0
curl -O https://raw.githubusercontent.com/dani-garcia/bw_web_builds/master/patches/v2.19.0.patch
git apply v2.19.0.patch
```

Before, the jslib folder was included in the web-vault repository. He now has his own repository.

Sorry for my English and hoping to have helped.

**Comment by Nyxtorm** [comment]
I suggest a better solution : 

`git clone --recurse-submodules https://github.com/bitwarden/web.git web-vault.git`

instead of

`git clone https://github.com/bitwarden/web.git web-vault.git`

This way, just one clone is enough, git will automatically get the submodules (so the jslib repository in this case)

**Comment by BlackDex** [comment]
Or you can run the following command after a simple clone within the cloned folder:
```bash
git submodule update --init --recursive
```
