### ISSUE TITLE
LDAP

### ISSUE THREAD

**Issue by cyberb** [dani-garcia/bitwarden_rs#1534]
I wan to implement a simple LDAP auth as I need it for Syncloud (https://github.com/syncloud/platform) project.
Similar to this (https://github.com/cyberb/api/commit/2d011fff7df062d36a6044806d2b7f893e74e334) once done for a rust pi-hole fork.
I have quickly checked the code and I think the logic will be as follows:

1. Configure ldap (enabled, address, binddn)
2. Change webui to allow non email username (optional)
3. Backend: if enabled and authenticated against LDAP
4. Backend: register user with the info from LDAP record if does not exist yet.

Any advices before I start?
I will do this anyway even if it will stay in my fork.

**Comment by nightmared** [comment]
Hello, I'm interested in such a feature too, but I wonder how this can work given the problems discussed at https://github.com/dani-garcia/bitwarden_rs/pull/677#issuecomment-553606347 (the fact that a password change in the LDAP directory will make the vault inacessible). Do you plan on adding an ldap attribute to store t fixed passwordfor the vault, or do you have another idea to solve this hurdle?

Thanks!

**Comment by BlackDex** [comment]
There already is a working solution which uses the official support directory tools from bitwarden. See:  https://github.com/dani-garcia/bitwarden_rs/commit/85e3c73525d327042c1ad142e48c044a5dbdd89c
LDAP and SSO can only be used for account creation or validation. Not for auto login. You always need a master password to decrypt the vault.
So, what would be an addition to this project would be SSO, but that is a huge endeavor.
