### ISSUE TITLE
can´t create an account

### ISSUE THREAD

**Issue by theazriel** [dani-garcia/bitwarden_rs#154]
Hey,

i create to docker under ds218+ with the command:

docker run -d --name bitwarden -v /bw-data/:/data/ -p 9400:80 mprasil/bitwarden:latest

the files was create in this folder. I have acces to the start page from bitwaren, when i go to create user and type all data in -> move send, it do nothing.

I get no error und an nothing. 
Have i forgotten any step ?

**Comment by mprasil** [comment]
This sounds similar to #153 - is that what you're experiencing?

**Comment by mprasil** [comment]
I'm going to close this ans it sounds like the same issue as #153, feel free to reopen if you think it's different.

**Comment by theazriel** [comment]
Hi,
Ok.
I will try this stets, and hope to a fix it.One question, for this docker i will need a ssl certificate or will this run normally without this?


-------- Ursprüngliche Nachricht --------Von: mprasil <notifications@github.com> Datum: 27.08.18  14:30  (GMT+01:00) An: dani-garcia/bitwarden_rs <bitwarden_rs@noreply.github.com> Cc: theazriel <matthias.staats@e.mail.de>, Author <author@noreply.github.com> Betreff: Re: [dani-garcia/bitwarden_rs] can´t create an account (#154) 
I'm going to close this ans it sounds like the same issue as #153, feel free to reopen if you think it's different.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dani-garcia/bitwarden_rs","title":"dani-garcia/bitwarden_rs","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/dani-garcia/bitwarden_rs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mprasil in #154: I'm going to close this ans it sounds like the same issue as #153, feel free to reopen if you think it's different."}],"action":{"name":"View Issue","url":"https://github.com/dani-garcia/bitwarden_rs/issues/154#issuecomment-416210533"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dani-garcia/bitwarden_rs/issues/154#issuecomment-416210533",
"url": "https://github.com/dani-garcia/bitwarden_rs/issues/154#issuecomment-416210533",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [dani-garcia/bitwarden_rs] can´t create an account (#154)",
"sections": [
{
"text": "",
"activityTitle": "**mprasil**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@mprasil",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"dani-garcia/bitwarden_rs\",\n\"issueId\": 154,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/dani-garcia/bitwarden_rs/issues/154#issuecomment-416210533"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 372488435\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by mprasil** [comment]
It doesn't need ssl certificate if you don't want HTTPS.
