### ISSUE TITLE
Support Password History

### ISSUE THREAD

**Issue by ptman** [dani-garcia/bitwarden_rs#155]
Seems that latest bitwarden apps support password history. What is missing for bitwarden_rs to also support history?

**Comment by dani-garcia** [comment]
This is done now with #156

**Comment by mprasil** [comment]
Docker build is [triggered](https://hub.docker.com/r/mprasil/bitwarden/builds/baf4pqsshijkgeh459kpfdi/), should be done in about an hour.

**Comment by masterwishx** [comment]
do we have setting for pass history ?
