### ISSUE TITLE
send url reverting to bitwarden.com

### ISSUE THREAD

**Issue by lgwapnitsky** [dani-garcia/bitwarden_rs#1566]
Where do I set the URL for send so that it uses my domain from the web version rather than bitwarden.com?

THank you

**Comment by BlackDex** [comment]
See: https://github.com/dani-garcia/bitwarden_rs/wiki/Configuration-overview

**Comment by lgwapnitsky** [comment]
My domain is set, as is proxy redirect, but the web app still shows the
bitwarden domain

**Comment by BlackDex** [comment]
Could you generate a support string and post it.
And maybe a screenshot of where you see this specific link?
