### ISSUE TITLE
DELETE host.com/api/ciphers/<uuid>/admin 404

### ISSUE THREAD

**Issue by krohrsb** [dani-garcia/bitwarden_rs#158]
Hello!

I am getting a 404 when deleting an item from an organization vault.

```
DELETE https://some-host.com/api/ciphers/some-uuid-here/admin 404 ()
```

I see other deletes for ciphers implemented, just not for `/admin` though I do see `/admin` for `get` and `post`.

https://github.com/dani-garcia/bitwarden_rs/blob/master/src/api/core/ciphers.rs#L518

**Comment by mprasil** [comment]
This should be easy to fix. As a quick workaround, you can delete the item from you Vault instead of organization Vault directly.

**Comment by mprasil** [comment]
@Baelyk I'm about to commit the changes, apologies :confused:

**Comment by Baelyk** [comment]
@mprasil Ah, its fine 👍

**Comment by mprasil** [comment]
I didn't want to have this bug around unnecessary long @Baelyk, this is why I didn't mark it as good first issue. (I did this while Vault 2 was still in beta)

If you're interested in small contributions, maybe you could help a bit with #6? Even if you want to improve one save() function, it would be very welcome and I'm available to help you.
