### ISSUE TITLE
Error during restore: "Cannot read property 'importKey' of null"

### ISSUE THREAD

**Issue by pageb018** [dani-garcia/bitwarden_rs#162]
Doing a test backup and restore. I copy the entire bw-data folder onto a new host. Run a docker-compose up on new host, I get the login page but when trying to authenticate I receive a "Cannot read property 'importKey' of null" error. 

Not sure how to proceed, the logs do not seem to show an error.

bitwarden    | POST /api/accounts/prelogin application/json; charset=utf-8:
bitwarden    |     => Matched: POST /api/accounts/prelogin
bitwarden    |     => Outcome: Success
bitwarden    |     => Response succeeded.
bitwarden    | POST /api/accounts/prelogin application/json; charset=utf-8:
bitwarden    |     => Matched: POST /api/accounts/prelogin
bitwarden    |     => Outcome: Success
bitwarden    |     => Response succeeded.

**Comment by mprasil** [comment]
Please see #153, this seems to be issue with the chrome browser when you're not using https.
