### ISSUE TITLE
As an org admin, assigning myself (or other admin) to a collection results in an error

### ISSUE THREAD

**Issue by janost** [dani-garcia/bitwarden_rs#163]
Reproduction steps:
- Using the latest docker container.
- Log in to the web UI as user who is an organization admin.
- Select organization, click on the Manage tab, select People.
- Click on yourself or another organization admin.
- Under "Access Control" assign the user to any collection or select "This user can access and modify all items".
- Click "Save".

Expected result:
The request succeeds and the edited user gains access to the selected collections.

Actual result:
Red error message pops up saying "Only Owners can grant Admin or Owner type".

Background:
Failing request is:
PUT https://<HOSTNAME>/api/organizations/<ORG_ID>/users/<USER_ID>

**Comment by mprasil** [comment]
Thanks for reporting this. Have you tested this in upstream to see how that works there? I'm not sure how to handle this as granting admin ability to edit himself and other admins essentially gives him owner-level privileges.

**Comment by janost** [comment]
I just tested this upstream.
As an organization admin, I was able to edit my own access to collections using the procedure I described in the issue. Unfortunately I can't test if I can edit other admins, because I only have a free account on upstream.

**Comment by mprasil** [comment]
Thanks for that. I guess it's safe to assume, that it would work for other admin accounts.

**Comment by mprasil** [comment]
Submitted PR #170 that should also resolve this issue.
