### ISSUE TITLE
As a user of an organization, I can't modify an item even though I have read/write access

### ISSUE THREAD

**Issue by janost** [dani-garcia/bitwarden_rs#164]
Reproduction steps:
- Using the latest docker container.
- Log in to the web UI as user of an organization. The user must not have access to all items in the organization, just read/write access to specific collection(s).
- Click on an item, edit something and click "Save".

Expected result:
The request succeeds and my changes have been saved, because I have read/write access to the collection where the item is shared.

Actual result:
Red error message pops up saying "You don't have permission to add cipher directly to organization".

Remarks:
The request succeeds if the user has access to all collections in the organization. ("This user can access and modify all items.")

Background:
Failing request is:
PUT https://<HOSTNAME>/api/ciphers/<CIPHER_ID>

**Comment by mprasil** [comment]
Thanks for reporting that, this bug was introduced recently and hopefully should be fixed with d336d89.

**Comment by janost** [comment]
Awesome, thank you!
I'm going to test it and report back.

**Comment by mprasil** [comment]
Just be aware that the PR wasn't merged yet and even after it's merged it takes about an hour to build the docker image, so if you want to test it now, you need to build your own image.

**Comment by janost** [comment]
Seems to work great, thank you.
