### ISSUE TITLE
Very slow performance - app is almost unusable

### ISSUE THREAD

**Issue by Haxy89** [dani-garcia/bitwarden_rs#168]
My setup:

Docker container, inspect command: https://pastebin.com/raw/1RbG7dGj
I use Firefox addon, web vault and mobile app on IOS.

Almost everytime I can't login at first time, can see that any request does not show in container log after click on login button.
It took over 2 minutes for this request after page refresh and get error:
![obraz](https://user-images.githubusercontent.com/37550896/44954686-3c0ba380-aea6-11e8-8391-d293b45e4c52.png)

Synchronization between Firefox addon and server in local network take 1 minute!
The same with mobile IOS app, sometimes synchronization show connection error, i think because timeouts. The same with saving changes in secure note on mobile, can sync because of error.

No additional info in container log when errors appear in apps: https://pastebin.com/raw/FKa4tMpm

Tested using chrome and the same. it is not related to docker host or local network performance. My docker host is my very fast Qnap Nas and other containers on this host work very fast.
 
Feel free to ask for more info

**Comment by Haxy89** [comment]
@mprasil 
I did monitoring live logs and 9 out of 10 requests does not reach server. So you are right something delaying request before it hit the server. 
I use ublock in firefox but bitwarden web app is whitelisted and problem occurs also on IOS so it is not the cause.

**Comment by mprasil** [comment]
Is it possible that Qnap puts some proxy in front of the service?

**Comment by Haxy89** [comment]
Absolutely not, you can see detailed setting in attached docker inspect command in first post. 
It is just clear docker app on NAS. 
I have other containers installed and worked without any problems.

**Comment by mprasil** [comment]
I don't think that should matter really. Any port should work just fine. It's it only the API calls, that are allow or is allow also when loading static Vault files?

**Comment by Haxy89** [comment]
It also affect static files likes images etc.

**Comment by mprasil** [comment]
Can you try and do a `curl -v` request to one of the static files? Preferably both on your PC and also on the Qnap directly. See if there's any difference.

**Comment by Haxy89** [comment]
Give me a path to example static file please.

**Comment by mprasil** [comment]
Actually just `curl -v 'http://10.0.3.3:8123/' should do. This should load index.html

**Comment by Haxy89** [comment]
Curl from PC in local network:
First try: https://pastebin.com/raw/vRjbRWpm (Connection reset by peer)
Second try: https://pastebin.com/raw/AUuRCvxc

Curl from Raspberrypi in local network:
First try: https://pastebin.com/raw/SmXz3EK6 (Connection reset by peer)
Second try: the same error (Connection reset by peer)
Third try: the same error (Connection reset by peer)
Fourth try: https://pastebin.com/raw/uBVpiBrz

Curl from Qnap Nas (docker host) in local network:
First try: https://pastebin.com/raw/xdNFYimj
Second try: https://pastebin.com/raw/Ne0QWdqp (Connection reset by peer)

As you can see something is wrong with the bitwarden server, it refuse a connection sometimes.

**Comment by mprasil** [comment]
Can you try the same directly from Qnap, but try to access directly `http://10.0.3.3:80`?

**Comment by Haxy89** [comment]
```
curl -v http://10.0.3.3:80
* Rebuilt URL to: http://10.0.3.3:80/
*   Trying 10.0.3.3...
* connect to 10.0.3.3 port 80 failed: No route to host
* Failed to connect to 10.0.3.3 port 80: No route to host
* Closing connection 0
curl: (7) Failed to connect to 10.0.3.3 port 80: No route to host
```

**Comment by mprasil** [comment]
Okay, something doesn't add up here. According to docker inspect you shared before, the container should be running on `10.0.3.3` unless you restarted it in the meantime. Any way, just get the current IP: `docker inspect --format='{{.NetworkSettings.Networks.bridge.IPAddress}}' Bitwarden` and use the IP with port `80` to try curl. Also make sure you do it directly from the Qnap.

Oneliner:
```
curl -v "http://$(docker inspect --format='{{.NetworkSettings.Networks.bridge.IPAddress}}' Bitwarden):80/"
```

**Comment by Haxy89** [comment]
There is no reason that 10.0.3.3 should be accessible on docker host.
My docker host is Qnap Nas (192.168.0.5), on this Nas works docker and it create network for containers with gateway 10.0.3.1 and 10.0.3.3 for Bitwarden container

Calling 192.168.0.5:8123 calls 10.0.3.3:80 according to container inspect command

![obraz](https://user-images.githubusercontent.com/37550896/44959120-29b35900-aeea-11e8-8d82-b05c89e7e70f.png)

**Comment by Haxy89** [comment]
Ok, after did 10 times curl, there is connection from Qnap to 10.0.3.3:80:

```
 curl -v http://10.0.3.3:80
* Rebuilt URL to: http://10.0.3.3:80/
*   Trying 10.0.3.3...
* Connected to 10.0.3.3 (10.0.3.3) port 80 (#0)
> GET / HTTP/1.1
> Host: 10.0.3.3
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< Referrer-Policy: same-origin
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Server: Rocket
< Content-Length: 1354
< Date: Sun, 02 Sep 2018 18:41:49 GMT
<
<!DOCTYPE html>
<html>
```
But most of the times I get:

```
 curl -v http://10.0.3.3:80
* Rebuilt URL to: http://10.0.3.3:80/
*   Trying 10.0.3.3...
* connect to 10.0.3.3 port 80 failed: No route to host
* Failed to connect to 10.0.3.3 port 80: No route to host
* Closing connection 0
curl: (7) Failed to connect to 10.0.3.3 port 80: No route to host
```

So server sometimes respond sometimes does not

**Comment by mprasil** [comment]
Just for the record, which port did you change? Can we resolve it?

**Comment by mprasil** [comment]
Is there any chance that there's something else using the 10.0.3.3 IP? Check the routing table. It sure sounds like networking issue.

**Comment by mprasil** [comment]
Also try changing the 8123 port to something else just in case.

**Comment by Haxy89** [comment]
Changing network type from nat to bridge helps. Do know why

**Comment by mprasil** [comment]
I suspect there were some weird routing issues. Spotty "host unreachable" kinda suggests an IP conflict maybe? Macvlan will expose the container directly at the interface under separate IP and MAC address, so makes sense this would resolve said conflict.

Anyway I don't think this was an actual issue in bitwarden_rs. You've essentially ran pretty standard configuration otherwise and it should be well tested and supported. I'm going to resolve this with the assumption that the issues were caused by some unrelated problem.
