### ISSUE TITLE
Deleting password in organization from web interface doesn't work

### ISSUE THREAD

**Issue by valantur** [dani-garcia/bitwarden_rs#172]
I tried deleting a password I shared with an organization from the web interface, and I got a message saying "unexpected error occurred". Deleting through the Chrome plugin works though. A minor annoyance but I just wanted to bring it up to your attention.

I'm running the latest Docker image.

Thanks!

**Comment by mprasil** [comment]
Hi are you sure you're running the latest image? (did you do `docker pull mprasil/bitwarden` before starting container?) I've tried to reproduce this but couldn't. What exactly did you do to trigger this issue and are there any errors in the logs?

**Comment by valantur** [comment]
My bad. My docker image was old-ish (Aug 28th). I pulled the latest image today and the issue went away. Sorry for the false alarm!

**Comment by mprasil** [comment]
Makes sense, this bug was fixed a while ago. 🙂
