### ISSUE TITLE
Organization import from official server broken

### ISSUE THREAD

**Issue by oversearch** [dani-garcia/bitwarden_rs#178]
Hi there!  Let me start by saying that I really love this implementation of the Bitwarden server.  The speed is fantastic, but what really sold me is how much simpler the implementation is to get running and maintain.  I'm excited to fully transition from the official server code.   Unfortunately, I hit a snag when moving my data out of my old vault on the official server.  

I have a family organization with a few users, so I separately exported each user and the organization.  When I attempted to import the organization content into bitwarden_rs, I got the "unexpected error has occurred" message, which Firefox's debugger showed to be a 400 Bad Request.  Looking at the service output, I get the following:
```
Error: Couldn't parse JSON body: Error("missing field `Type`", line: 1, column: 48477)
``` 
The file appears to be correctly formatted as far as I can tell.  I attempted to tweak it in various ways, cut it down to individual entries, etc - but I could not get it to import.  Any idea why this might be happening? I'm running the server on Arch Linux via the AUR package (both the core and the vault), and it appears to be otherwise fully functional.

Thank you!

**Comment by dani-garcia** [comment]
At the moment, the import to an organization is not yet implemented, the error message is a bit strange because it's matching the wrong route:
`/api/ciphers/import-organization?organizationId=<org_id>`
is matching:
`/api/ciphers/<uuid>`

**Comment by dani-garcia** [comment]
It should be fixed now in the latest master.

**Comment by oversearch** [comment]
Thanks so much for getting back quickly!  The fact that it wasn't implemented certainly explains why I couldn't figure out where the import code was... I thought it was just me hazing zero Rust experience.  I took a look at the commit and it all makes much more sense now (and wow your turn-around time is impressive...).  

Thanks again!
