### ISSUE TITLE
Account deletion using web vault not possible

### ISSUE THREAD

**Issue by BearWithTie** [dani-garcia/bitwarden_rs#181]
Just pulled the latest docker image (1.1.0) and it's not possible to delete accounts from the web vault.
The web vault 2.2.0 sends a DELETE request to /accounts which returns a 404 and judging from the code it seems only a POST to /accounts/delete is handled.
Never tried it before so don't know if/when it worked.

**Comment by mprasil** [comment]
Yeah that sounds like one of those that just need alias for DELETE call. Should be a simple fix.
