### ISSUE TITLE
Docker image for aarch64 not available

### ISSUE THREAD

**Issue by Proximyst** [dani-garcia/bitwarden_rs#185]
I set up mprasil/bitwarden:raspberry on Docker with the commands listed. When it starts, it instantly exits with error 139 and no logs.

```bash
# docker volume create bitwarden_data
bitwarden_data
# docker run --name bitwarden -d --net localnet --ip 172.20.0.30 -v bitwarden_data:/data mprasil/bitwarden:raspberry
af8b74b4c7ae5aa3488d4c406bd9eb6af84218832c1c9b4dbc53c8c2c268415a

# docker ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                       PORTS                                                              NAMES
af8b74b4c7ae        mprasil/bitwarden:raspberry   "/usr/bin/entry.sh /…"   3 seconds ago       Exited (139) 2 seconds ago                                                                      bitwarden

# docker logs bitwarden
# docker info
--snip--
Server Version: 17.12.1-ce
Kernel Version: 4.4.127-mainline-rev1
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: aarch64
CPUs: 6
Total Memory: 3.849GiB
--snip--
```

What does this error mean and how may I go around it? Would it be possible to log the errors' actual meaning? Possibly other logs too, if those aren't already there?

**Comment by mprasil** [comment]
Can you post output of `uname -mpi`? The image is compiled for `armhf` I wonder if it's not `arm64` vs `armhf` incompatibility. Can you try starting the container with `-ti` instead of `-d` to start in foreground?

**Comment by Proximyst** [comment]
Sorry for the late answer. Here is the output (which from Bitwarden's side is nothing):
```
# docker run --name bitwarden -ti --net localnet --ip 172.20.0.31 -v bitwarden_data:/data mprasil/bitwarden:raspberry
Unable to find image 'mprasil/bitwarden:raspberry' locally
raspberry: Pulling from mprasil/bitwarden
2e5bbd238113: Pull complete 
bd5466922a3e: Pull complete 
daa1e16babb1: Pull complete 
d74f0fdf7ee1: Pull complete 
b56eab80ec08: Pull complete 
49556fc391a1: Pull complete 
a5faa670d2c1: Pull complete 
7adbedd4cfa5: Pull complete 
6e4fd8ca118c: Pull complete 
16bd19f52442: Pull complete 
a417d35bcf5a: Pull complete 
902f93d33ab4: Pull complete 
420a0b18a3fd: Pull complete 
83eabeb992e4: Pull complete 
978cd9a983e9: Pull complete 
d203a31a0417: Pull complete 
57e31b501fe9: Pull complete 
5d8170298b99: Pull complete 
44cf28adb87b: Pull complete 
3beba8d81308: Pull complete 
be84d0ec5881: Pull complete 
Digest: sha256:659c073aaf005df12d9cb6ae1ee2c643ff42e3141d7b85cc0764ffbcfa127c88
Status: Downloaded newer image for mprasil/bitwarden:raspberry
# ls /var/lib/docker/volumes/bitwarden_data/_data/
# docker logs bitwarden
```

**Comment by mprasil** [comment]
Can you check the architecture differences? I've posted the commands above.

**Comment by Proximyst** [comment]
@mprasil That's what I did in the above snippet (`--name bitwarden -ti --net` for -ti and bottom command for uname)

**Comment by mprasil** [comment]
Ah sorry, totally missed that! Yeah, it looks like you're on `aarch64` platform, but the image is built for `armhf`. You'll have to compile a binary for your platform unfortunately. If I'll have some free time, I might look into making `aarch64` image, shouldn't be too hard hopefully.

**Comment by mprasil** [comment]
Hi @Proximyst, I've built aarch64 image, `mprasil/bitwarden:aarch64-beta`, can you test it if it works for you?

**Comment by Proximyst** [comment]
Update: Upon trying to create an account, it just yells at me with an "Unexpected error", with no output to docker, nor in the browser console.

**Comment by mprasil** [comment]
Hmm, can you check in developer tools on the network tab if you see any failing requests?

**Comment by dani-garcia** [comment]
Are you by any chance using Chrome and HTTP only? You might need to try other browsers, we've had some problems with that case before.

**Comment by Proximyst** [comment]
It was a badly set up NGinx configuration, actually. It works fine now. Thanks a lot for the work! <3

![https://owo.whats-th.is/818809.png]()
