### ISSUE TITLE
Disabling signups and invitations does not remove "Create Account" box on login

### ISSUE THREAD

**Issue by iamtpage** [dani-garcia/bitwarden_rs#186]
Hi,

I've disabled login via `SIGNUPS_ALLOWED=false` and `INVITATIONS_ALLOWED=false`, yet when I go to the web ui it still shows the option to create an account:

![image](https://user-images.githubusercontent.com/8901422/45601652-3483e880-b9d6-11e8-8587-756145036107.png)

I've verified that you cannot actually create an account, but it might be better UX to disable the "Create Account" box when account creation is disabled, instead of letting them find out after they fill out the whole form.

**Comment by mprasil** [comment]
Unfortunately this is upstream thing. We just pack Bitwarden Vault "as is". (Some other differences are described in the Readme) I'm going to close this as there isn't much we can do here as far as I know, but if you think there's something the API can do to let the Vault know to disable or hide the button, feel free to reopen.

BTW even with registrations disabled, the users can be invited to register, so unless you also disabled that, there is a chance that the button might be needed in some cases.
