### ISSUE TITLE
Manually confirming invited users with Vault 2.2.0 UI

### ISSUE THREAD

**Issue by themightychris** [dani-garcia/bitwarden_rs#187]
The Vault 2.2.0 UI seems to be missing the "Confirm" action on invited users that enables bypassing the email workflow. Is there any way now through the UI to get someone added to an organization?

<img width="511" alt="screen shot 2018-09-17 at 11 34 28 am" src="https://user-images.githubusercontent.com/458494/45633398-ae1ae580-ba6d-11e8-910f-343172227674.png">

**Comment by mprasil** [comment]
Hi, the way this works is that if you invite users that haven't registered yet, (unless you [disable this](https://github.com/dani-garcia/bitwarden_rs#disable-invitations)) they will show as `Invited` and as such you can't confirm them yet. But once they register, they will [automatically](https://github.com/dani-garcia/bitwarden_rs#inviting-users-into-organization) be set as `Accepted` which you can then confirm.

Before they register there's no way to "Accept" them automatically as they don't have valid key set for their account. If you invite users that are already registered, they will straight away show as `Accepted`.

As for "Resend invitation" button, we should handle that API call with proper error saying email sending is not supported.

Hope that helps.

**Comment by mprasil** [comment]
I've created an issue for handling the "resend" callback properly. I think the documentation needs to be improved a it to explain the invitation process.

**Comment by mprasil** [comment]
Documentation PR merged, I'm closing this one, but feel free to reopen if more information is needed.
