### ISSUE TITLE
Fails to build with OpenSSL 1.1.1

### ISSUE THREAD

**Issue by luusl** [dani-garcia/bitwarden_rs#193]
On my machine I have OpenSSL 1.1.1 installed and building fails according to this error:
```
error: failed to run custom build command for `openssl v0.9.24`
process didn't exit successfully: `/home/build/bitwarden_rs-1.1.0/target/release/build/openssl-70a8875277726cb3/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/build/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
```

**Comment by dani-garcia** [comment]
This is a problem with the old `openssl` crate, which doesn't support OpenSSL 1.1.1. (See https://github.com/sfackler/rust-openssl/issues/994).

We have two dependencies that require that `openssl` version: `reqwest`, which works fine in its version 0.9 and `lettre`, which needs a change (See open PR: https://github.com/lettre/lettre/pull/303)

The solutions for now are to:
- Revert to openssl 1.0.2
- Fork lettre with that PR and change the Cargo.toml to use that instead, also updating the reqwest dependency

**Comment by dani-garcia** [comment]
I pushed a fix with the second solution I mentioned here: https://github.com/dani-garcia/bitwarden_rs/tree/openssl-fix

Hopefully the PR is merged soon and we can continue using the upstream version directly.

**Comment by luusl** [comment]
Thank you, I tried that branch and it works.

**Comment by dani-garcia** [comment]
Okay, that PR was merged, so the OpenSSL fix is now in master. With that, we can mark this issue as fixed.

**Comment by chris-morgan** [comment]
Any chance of a bitwarden_rs 1.1.1 release to go with the openssl 1.1.1?

**Comment by dani-garcia** [comment]
You are right, we need a release.
As the changes since the last version are significant, I decided to release a 1.2.0 version. I hope that works for you.

https://github.com/dani-garcia/bitwarden_rs/releases/tag/1.2.0

**Comment by mprasil** [comment]
Just triggered it now, it's gonna take about 6h before all the image versions are done.

**Comment by dobunzli** [comment]
Hello,

Thanks for the work. I want to update the READ ME but just to be sure:

- people who wants to use bitwarden_rs on a "ARM7 plateform" (e.g. raspberry pi) have to use  mprasil/bitwarden:raspberry    instead of  mprasil/bitwarden:latest in the different commands
- people who want to use bitwarden_rs on a "musl plateform" (e.g. gentoo musl) have to us  mprasil/bitwarden:musl    instead of  mprasil/bitwarden:latest in the different commands

Is that correct ?

Thanks

Dominique

**Comment by dani-garcia** [comment]
I think it's `mprasil/bitwarden:alpine` instead, but yeah.

**Comment by mprasil** [comment]
Just a small correction. People on `musl` platform don't have to use `mprasil/bitwarden:alpine`, the required platform dependencies are shipped in the image. So as long as you are on `AMD64` platform, you can use both images.

I'm thinking that maybe we should replace the default Debian based image and just use Alpine as default?
