### ISSUE TITLE
KDF iterations can't be changed

### ISSUE THREAD

**Issue by Biepa** [dani-garcia/bitwarden_rs#195]
Hello,
i'm very new to Github, so let me know if i do this wrong :)

On Vault 2.3.0 under settings i can't change the kdf-iterations.
Just getting the red pop up, that an unknown error occured.

**Comment by dani-garcia** [comment]
This should be done now, I already had a half-working version from yesterday after we merged #191, but now it's finished and available in `master`.

**Comment by mprasil** [comment]
Image is [just building](https://hub.docker.com/r/mprasil/bitwarden/builds/bdajalreimulz5zjgebtohk/), will take about an hour.
