### ISSUE TITLE
Shared Items, Collections and Organisation not being displayed correctly for unconfirmed user

### ISSUE THREAD

**Issue by pixelyo** [dani-garcia/bitwarden_rs#196]
So I have two accounts: A and B

A has 4 items in his vault and shares them over an organization. B is part of A's organization and has permission to view and edit A's items. [This is what B sees.](https://i.imgur.com/mfu5hxE.png) B can see that there are 4 items which are not displayed correctly. B can't see that is is part of an organization.

pretty weird, can somebody help me?

**Comment by mprasil** [comment]
Hi, I think I've managed to reproduce the problem. Go into your organization setting and see if the B is actually confirmed user, or it's just `Accepted`. After you confirm user, he should see the shared stuff properly. (if not try to logout and log back in maybe, but it shouldn't be necessary.

I'm pretty sure we've had this fixed and the passwords weren't showing at all until user was confirmed, but apparently it's broken again, so we need to fix it.

**Comment by pixelyo** [comment]
yep, the invitation was just accepted. I still needed to confirm the user.

B had status `accepted`. A went to Organization > Manage > User and confirmed user B, by opening the drop down menu on the far right, next to B's name and clicking `confirm`. Now B sees all entries as normal.

Thank you @mprasil :)

**Comment by mprasil** [comment]
I'm going to reopen this as we shouldn't show the ciphers to the user until he's confirmed.
