### ISSUE TITLE
Can't connect to server from IOS app when https is enabled

### ISSUE THREAD

**Issue by Haxy89** [dani-garcia/bitwarden_rs#198]
Get "There is a problem connecting to the server"

I am using 1.2.0 docker container with ROCKET_TLS and ROCKET_PORT = 443

**Comment by mprasil** [comment]
Hi can you paste the docker logs here? Just the starting part that prints the configuration used would be helpful. Also can you see any requests in the logs when you try to use the iOS app? Does the Vault interface work for you?

**Comment by Haxy89** [comment]
Vault web interface works when opening in Chrome desktop but can;t open from ios and ios mobile bitwarden app

my server ip is https://192.168.0.19

https://pastebin.com/raw/AtH6hHwg

**Comment by mprasil** [comment]
It looks like it starts with proper configuration. Are there any requests appearing in the logs when you try to use the iOS app? Do I understand right that you can't even use the Vault interface using Safari on iOS device?

**Comment by Haxy89** [comment]
There is no requests in logs when trying to access from iOS. 
I bet this is a problem with self signed cert on iOS.
"Do I understand right that you can't even use the Vault interface using Safari on iOS device?" Yes, exactly
My cert is:

```
-----BEGIN CERTIFICATE-----
MIIDtTCCAp2gAwIBAgIJANBGXG6c3YAPMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
BAYTAlBMMRMwEQYDVQQIEwpTb21lLVN0YXRlMSEwHwYDVQQKExhJbnRlcm5ldCBX
aWRnaXRzIFB0eSBMdGQwHhcNMTgwOTAxMTYwMzIxWhcNMTkwOTAxMTYwMzIxWjBF
MQswCQYDVQQGEwJQTDETMBEGA1UECBMKU29tZS1TdGF0ZTEhMB8GA1UEChMYSW50
ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEAssICQ7RrRjJAxy/FKm5ccZlwFV5PgYgzuaMa2SPEMgpkLhmMEjoWrb0N
oqmcJEX8Gm4fAosY6Xu2pFXiCnfYdX2wi8KPICUgUuYqg4j4DiIrgbdp1vKVr4lQ
0Cc13TqsXAs+r3dxV3yuUSd/ZEpHNJe7oGkaQMwKTPYi5ny9kmb0csPBKLt8Bor0
vHMeiT+ipQnc9EadudqiC9S/SeMG4NHAQp7cpTu4pSpprDJa0hDXKsJOPrAzYZq4
4xQ9O02iGU3QA51QyxU7yLjRczlIXHQ6uzGxsP4SAW/CO0IfstuW3fZOALJ3ITCe
/HAEVNMnNy7VNRT1loG/azKYJMb0BQIDAQABo4GnMIGkMB0GA1UdDgQWBBR/WGkT
meKdAEtjSAEEfLLI/UkSxzB1BgNVHSMEbjBsgBR/WGkTmeKdAEtjSAEEfLLI/UkS
x6FJpEcwRTELMAkGA1UEBhMCUEwxEzARBgNVBAgTClNvbWUtU3RhdGUxITAfBgNV
BAoTGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZIIJANBGXG6c3YAPMAwGA1UdEwQF
MAMBAf8wDQYJKoZIhvcNAQELBQADggEBAJzHHHkmcQuvSwp+dYh7H0OI6evSlE6Z
nIRWu1ebyzRL2+N/KtdNZnXZg6wvJPNVAfHIQNNWP0gd8MV+LMT2+X4zk86zooNl
J7RESnH9wq4U3Tq5T2rvtxSLF+4oZUvUn10pbkxjAmQY7OHftB1aCQ3fRMygyccF
6qsavEr5qhrGPUBt8LfRjTAI4V3tg8+C0v/AqNUDRxolGBJLh7kkLj6DZw1bI6Q1
KJodmtnmZIiwpMcLlf53BianmFZK4LXtMPunbNBd/3fwsI7t62ZUTb2XvijpHpss
hQqNf7lu+/6VLtSc8sGUS5LAVy58hc+w7WffelHl3tgS0KWdDZa6oqQ=
-----END CERTIFICATE-----
```

You can decode it here: https://www.sslshopper.com/certificate-decoder.html

Can you provide proper command to create self signed certificate for my docker container?

**Comment by dani-garcia** [comment]
I'm using bitwarden_rs on iOS and it works for me. I'm running the server directly (without docker), behind my own domain and with let's encrypt certs. Maybe iOS blocks self signed certs?

**Comment by Haxy89** [comment]
I think there is a problem with self signed certs on iOS, can't generate the proper one.
``
openssl req -x509 -newkey rsa:2048 -sha256 -nodes -keyout key.key -out cert.crt -subj "/CN=192.168.0.19" -days 3650
``
This command generate cert and key but still cant connect on iOS

**Comment by mprasil** [comment]
Can you add that cert as trusted on your iOS device?

**Comment by Haxy89** [comment]
I can't. No option to install it when opening from mail

**Comment by mprasil** [comment]
I'm on mobile, so can't really test this, but I wonder if iOS will accept certificate for IP address. Quick googling around suggests, that it might not.

**Comment by Haxy89** [comment]
Make it works on Safari (need to add port: https://192.168.0.19:443) but still no success with app.

**Comment by Haxy89** [comment]
I made it works. Need to create CA certificate then server certificate
