### ISSUE TITLE
Make websocket port configurable

### ISSUE THREAD

**Issue by aminehmida** [dani-garcia/bitwarden_rs#199]
I want to expose birwarden on a specific interface only. I can't do that because the WebSocket server it is currently hard [coded to `0.0.0.0`](https://github.com/dani-garcia/bitwarden_rs/blob/948554a20fd46acc7155303985b9517607b246b9/src/api/notifications.rs#L361)

Similar to #179

Thanks in advance!

**Comment by dani-garcia** [comment]
This should be fixed now, you can use `WEBSOCKET_ADDRESS` to change it.
