### ISSUE TITLE
Support for admin panel

### ISSUE THREAD

**Issue by plasmite** [dani-garcia/bitwarden_rs#202]
Use this every day! Thank you for your excellent work!

Are there any plans to support the admin panel for user management [as described here](https://help.bitwarden.com/article/admin-portal/)? Or is there a way to enable it in the current implementation? The instructions on the linked page do not appear to apply and I do not see any env variables that would allow enabling this feature.

Thank you!

**Comment by dani-garcia** [comment]
The admin panel source is not included with the web vault, and as far as I know it's not publicly available, so we'd have to recreate it from scratch.

At the same time, I don't think implementing this is worth it, to be honest. It would probably be easier to view or edit the sqlite database directly. And if someone needs to view or delete users and organizations very often, they could just create a bash script. Something like:

```sh
sqlite3 data/db.sqlite3 "select * from users;"
```

**Comment by plasmite** [comment]
Thanks I figured this was the case--was poking around in the db already but didn't want to go mucking anything up if there was an alternative. Thanks again!
