### ISSUE TITLE
Configuring SQLite3 backup

### ISSUE THREAD

**Issue by jaapvdv** [dani-garcia/bitwarden_rs#205]
(using mprasil/bitwarden:latest)

I am trying to setup a cronjob to automate a daily backup of the bitwarden-rs data-folder. For that purpose I have added two volumes to the docker run command:

-v /mnt/data/:/data/ 
-v /mnt/backup/:/backup/

Both are visible when executing the shell inside the container.

When I try to test the backup command:

sqlite3 /$DATA_FOLDER/db.sqlite3 ".backup '/backup/backup.sq3'"

I get the error:

bash: sqlite3: command not found

How can I backup my database if (apparently) sqlite3 is not installed/available in the container?

BTW: I also tried crontab -e : 
bash: crontab: command not found

**Comment by shauder** [comment]
Are you running the command from inside the container or your host system?

The error message you show says that it cannot find the sqlite3 binary. Make sure you have sqlite3 installed.

**Comment by jaapvdv** [comment]
Yes, I am trying to run it from inside the container. Should I run it on the Docker host?

**Comment by fbartels** [comment]
Yes, you can safely run it from outside the container.

**Comment by jaapvdv** [comment]
Will do. Thanks.
