### ISSUE TITLE
Deleting folder in Vault doesn't update the cached client-side status of affected ciphers

### ISSUE THREAD

**Issue by mprasil** [dani-garcia/bitwarden_rs#21]
The updates on the server side are actually done correctly, when I reload the Valut page, ciphers are in `No_folder` as they should be, it's only the client-side cache that's wrong. I assume, we should be returning some data from `/api/folder/<id>/delete` to let Vault know which ciphers were updated?

BTW this has nothing to do with #20 - the client side behavior didn't change before or after implementing those changes. It's just something I noticed while working on the PR.

**Comment by dani-garcia** [comment]
I just tried this in the official server at vault.bitwarden.com and it seems to do the same, the method doesn't return anything and the ciphers in the deleted folder are visible from "All items" but not from "No folder". Once the page is reloaded, it's fine again.

It seems like a bug in the web vault to me.

**Comment by mprasil** [comment]
Might be worth reporting upstream so @kspearrin is aware. I don't have Bitwarden account to test unfortunately.

**Comment by mprasil** [comment]
I've reported the issue upstream - [#204](https://github.com/bitwarden/web/issues/204). Closing this one.
