### ISSUE TITLE
Questions re: Issue #212 (Admin Panel)

### ISSUE THREAD

**Issue by joe217** [dani-garcia/bitwarden_rs#214]
Thank you for the prompt response...and my apologies for missing the recent similar post.

Two quick follow-up questions:

1. Isn't the database encrypted? How would I list the user names?
2. If the user names are unencrypted, could you list a sample CLI command that I could use to list them? I tried doing some research on sqlite, but may be a bit above my head. A few simple commands may point me in the right direction for making the actual bash scripts...

I am using bitwarden_rs for a small office.  My goal is to be able to delete users (employees) that leave the company.  I understand that I can remove them from the organization, but I really don't want them to continue to use the service past their employment.

Thanks!

**Comment by mprasil** [comment]
See the discussion under #212, I'm going to close this to not branch off the topic into multiple issues.
