### ISSUE TITLE
Incorrect return type for wrong password via cli

### ISSUE THREAD

**Issue by seanfarley** [dani-garcia/bitwarden_rs#215]
It seems the server implemented here doesn't return the correct type so that the cli can distinguish an incorrectly typed password. I reported this in the bitwarden/cli project https://github.com/bitwarden/cli/issues/28 but the gist is:

```
$ bw login
? Master password: [hidden]
The model state is invalid
```

Instead, the output should be `Username or password is incorrect. Try again.`

**Comment by dani-garcia** [comment]
This should be fixed now with the latest commit

**Comment by seanfarley** [comment]
Thanks!
