### ISSUE TITLE
DB restore

### ISSUE THREAD

**Issue by Biepa** [dani-garcia/bitwarden_rs#223]
Hello together,
I am using the command in the documentation to backup the db.
`sqlite3 /$DATA_FOLDER/db.sqlite3 ".backup '/$DATA_FOLDER/db-backup/backup.sq3'"`

Unfortunately my knowledge about databases is very limited.
How do I restore a backup.sq3 file?

Tried it with...
`sqlite3 db.sqlite3 < backup.sq3`
but getting a "syntax error".

Is that because of the different endings?

**Comment by dani-garcia** [comment]
The backup should be a simple copy of the original database, I think. I'm not sure why we are using different extensions, that seems confusing.

Simply replace the `db.sqlite3` file with the backup to restore it (This probably needs to be done when bitwarden_rs is stopped)

**Comment by Biepa** [comment]
A simple copy with stopped container worked without problems. Thank you for the quick answer.

**Comment by Biepa** [comment]
@mprasil You're right. That was, what I expected.
And if there isn't a need for the different endings, maybe that could also be changed in the documentation as it confused me a bit.

**Comment by dani-garcia** [comment]
The documentation is updated now with #224
