### ISSUE TITLE
Organization Vault does not show unassigned ciphers under "Unassigned"

### ISSUE THREAD

**Issue by mprasil** [dani-garcia/bitwarden_rs#23]
In the Organization Vault, all the ciphers that have no `Collection` assigned do not show under `Unassigned` section. The ciphers are only visible under "All items". From what I can see the API correctly returns such ciphers with `CollectionIds` set to `[]` and when editing the collections assignment, Vault correctly displays that cipher is in no collection, it's just that filtering misbehaves for some reason.

Could be that the upstream API actually returns `Null` instead of `[]` or there is some extra field indicating no collection assignment, that we don't send?

**Comment by dani-garcia** [comment]
I just tried this and I can't reproduce it. The official API returns [] like us, and in my testing it seems to work fine (the ciphers appear both in All items and unassigned). Can you find a simple example where the problem occurs?

**Comment by mprasil** [comment]
I'm just testing it now and it seems like that might have been issue with Vault `1.24.0`, I can't reproduce this in `1.26.0` so I'm going to close this one.
