### ISSUE TITLE
Custom Equivalent Domains API results in 404

### ISSUE THREAD

**Issue by lorenzschmid** [dani-garcia/bitwarden_rs#230]
When trying to set a new "Custom Equivalent Domains" (under Settings > Domain Rules) I receive an error popup: "An error has occurred. An unexpected error has occurred.". Looking at the developer tools I see that the API call `PUT https://[domain]/api/settings/domains` gets a 404 response.

Using Version 2.4.0 in a docker container.

**Comment by mprasil** [comment]
Thanks for reporting this. We're currently handling the settings via the `POST` to `/api/settings/domains`. I guess this got changed in latest Vault and it's now `PUT` call - just like many other `POST` calls in the past. This should be easy to fix.

**Comment by lorenzschmid** [comment]
I don'tknow Rust but isn't it just about chaning the argument in [the following line](https://github.com/dani-garcia/bitwarden_rs/blob/master/src/api/core/mod.rs#L218) from `post` to `put`?

```rust
#[post("/settings/domains", data = "<data>")]
fn post_eq_domains(data: JsonUpcase<EquivDomainData>, headers: Headers, conn: DbConn) -> EmptyResult {
...
```

**Comment by mprasil** [comment]
Almost. Ideally we want to create alias so that both old and new API works. (so that we don't break old clients)
