### ISSUE TITLE
Cannot register U2F key

### ISSUE THREAD

**Issue by odensc** [dani-garcia/bitwarden_rs#235]
When I go to register a U2F key in the web vault, it errors on `POST /api/two-factor/get-u2f-challenge`.

**Comment by mprasil** [comment]
Can you post the whole error log message?

**Comment by dani-garcia** [comment]
It seems the web vault has changed the APIs used for u2f, probably in version 2.4.0 when support for multiple keys was implemented.

For now, if you need to use u2f keys, you can use bitwarden_rs 1.2.0, which uses an older web vault version that should hopefully work.

Hopefully next week I'll have some time to investigate further and fix this.

**Comment by pwlgrzs** [comment]
I presume this is related, I wanted to activate Duo on my instance but getting this:
```
POST /api/two-factor/get-duo application/json; charset=utf-8:
    => Error: No matching routes for POST /api/two-factor/get-duo application/json; charset=utf-8.                                          
    => Warning: Responding with 404 Not Found catcher.
    => Response succeeded.
```

**Comment by dani-garcia** [comment]
Duo support is not implemented at the moment

**Comment by RomanHargrave** [comment]
The "/api/two-factor/got-u2f" endpoint appeared in jslib at [4b7962d - "add support for u2f setup apis"](/bitwarden/jslib/commit/4b7962dc8fba73003be1ae651013f5f817496551)

**Comment by RomanHargrave** [comment]
I have tested and confirmed that _at minimum_, adding the new endpoint is enough to make u2f enrollment and authentication function. 

Of course, this all is still single-key.

**Comment by dani-garcia** [comment]
The PR has been merged now, so I'll close this. If anyone finds another problem, please open another issue.
