### ISSUE TITLE
Failed to delete user on the admin panel

### ISSUE THREAD

**Issue by janost** [dani-garcia/bitwarden_rs#237]
Using the latest docker container, trying to delete a user from the admin panel (`bitwarden_rs` organization) results in the following error message:
```
Oct 29 10:49:00 195.56.148.48 docker[24941]: DELETE /api/organizations/00000000-0000-0000-0000-000000000000/users/<USER_UUID>:
Oct 29 10:49:00 195.56.148.48 docker[24941]: => Matched: DELETE /api/organizations/<org_id>/users/<org_user_id>
Oct 29 10:49:00 195.56.148.48 docker[24941]: ERROR: Failed to delete user - likely because it's the only owner of organization
Oct 29 10:49:00 195.56.148.48 docker[24941]: => Outcome: Success
Oct 29 10:49:00 195.56.148.48 docker[24941]: => Response succeeded.
```

The user is not a member of any organizaton.

**Comment by mprasil** [comment]
Hmm.. I can't quite reproduce this. The error most likely means that `bitwarden_rs` failed to delete some object related to user. (The error message just mentions the most likely reason)

Can you figure out if there's some way to reliably reproduce the issue?

**Comment by dani-garcia** [comment]
This hasn't had activity in some time, so I'm closing it now.
If this is still an issue, please reopen it.
