### ISSUE TITLE
Configure server administrator - how to set password

### ISSUE THREAD

**Issue by Haxy89** [dani-garcia/bitwarden_rs#249]
I created container using:

```
docker run -d --name bitwarden \
  -e SERVER_ADMIN_EMAIL=my@admin.email \
  -v /bw-data/:/data/ \
  -p 80:80 \
  mprasil/bitwarden:latest
```

How to set up password for this admin account?
I have already normal user account that I use

**Comment by mprasil** [comment]
You just register account with that email. That account will have those extra privileges. 

**Note:** Never use the account for storing passwords or anything else other than server administration. So please don't use your normal user account for that.
