### ISSUE TITLE
"Normal" user do not belong to bitwarden_rs organization

### ISSUE THREAD

**Issue by Haxy89** [dani-garcia/bitwarden_rs#250]
I set up new bitwarden version with "SERVER_ADMIN_EMAIL".
I can see new organization:

![image](https://user-images.githubusercontent.com/37550896/48425405-0ec05900-e765-11e8-85f5-de078d18bfc4.png)

But my old normal user do not belong to this organization after log in:
![image](https://user-images.githubusercontent.com/37550896/48425436-213a9280-e765-11e8-9424-e13b16da0a18.png)

Admin belong:
![image](https://user-images.githubusercontent.com/37550896/48425458-2e578180-e765-11e8-944b-cbfdfcdda988.png)

Is this how this new organization works? Also both users are marked as "USER" not "USER" and "ADMIN"

**Comment by mprasil** [comment]
Yes this is working as designed. The `bitwarden_rs` organization is kind of a hack, that creates "virtual" organization for the admin account where all server users are. It's not a real organization and if you remove user there, it will be completely removed from server, so be careful. **Do not use this organization for sharing passwords**

Hope that helps.
