### ISSUE TITLE
Please add docker tag for vault v2.5.0, not latest

### ISSUE THREAD

**Issue by Haxy89** [dani-garcia/bitwarden_rs#252]
Current 1.4.0 docker tag has v2.4.0 web vault 
Current latest docker tag has v2.5.0 web vault 

Could you add 1.4.1 or 1.5.0 tag for docker image for web vault v2.5.0, I don't want to use latest tag because it is not recommended and after some time you don't now which version you are using in your env but I want to use features from v2.5.0.

**Comment by mprasil** [comment]
Yes that's correct. We do aim to have master (latest image) in usable state though and any major development is done in separate branch. (with beta images)

So if you're okay with running that version, @Haxy89, then fell free to use latest, it should work fine and any bugs are mostly related to new vault functionality and usually fixed quite fast. I'm personally using latest.

If you'd rather use versioned release, that's also fine. We do those quite often. The vault 2.5.0 version isn't quite there yet, to do a versioned release, we just got it toa stage where it works enough to merge to master, but some functionality isn't implemented yet.

**Comment by mprasil** [comment]
I'm going to close this issue as we don't need issue reminding us to release new version - we do that as part of normal development. :D
