### ISSUE TITLE
get_org_collection_detail() errors with "Collection not found" when User isn't directly assigned to collection

### ISSUE THREAD

**Issue by mprasil** [dani-garcia/bitwarden_rs#26]
The function doesn't work for `UserOrganization` with `access_all`, for `Admin` or `Owner` that doesn't have direct `CollectionUser` mapping.

This is because we only use `Collection::find_by_uuid_and_user()` in the handler, but the above users don't necessarily need to have access allowed for specific `Collection` as they can generally access any `Collection` within `Organization`. We need to check whether that isn't the case before returning error.

**Comment by dani-garcia** [comment]
This should be fixed by your PR #28 so I'm closing it. Thanks!
