### ISSUE TITLE
Changes in #254 introduced dependency on rust-crypto which block build for AARCH64 

### ISSUE THREAD

**Issue by mprasil** [dani-garcia/bitwarden_rs#262]
The transitive dependency introduced in this PR [blocks aarch64 builds](https://github.com/DaGenix/rust-crypto/issues/383).

**Comment by dani-garcia** [comment]
rust-crypto is deprecated, we would need to have the yubico_rs crate migrated to something else. The recommendation in that thread is [RustCrypto](https://github.com/RustCrypto).

The easiest solution for now would be to put everything that uses the yubico_rs crate under a ´#[cfg(not(target_arch = "aarch64"))]`.

The best solution would obviously be to see if yubico_rs maintainer would accept a PR migrating to an alternative that is actively maintained, but I don't have the time available for it. So if someone wants to help with that, it would be greatly appreciated.

**Comment by mcrosson** [comment]
@dani-garcia Would it be possible to have some kind of build option to turn off Yubikey support?

That would allow those of us on aarch64 the ability to build and run if not having Yubikey support is acceptable.

(I know I'd <3 to run bitwarden_rs and would gladly give up Yubikey support to be able to build/run)

**Comment by dani-garcia** [comment]
Yo are right, I planned on making youkey functionality optional a long time ago and forgot completely. Should be fixed now with 1d034749f7

**Comment by mcrosson** [comment]
@dani-garcia it built on my end :+1: . Any chance you'd be willing to tag a release for those of us running builds on our own? I'd prefer to target your releases rather than master...

**Comment by dani-garcia** [comment]
Sure, I already had a release prepared as a draft for the last couple days, as it's been a month since the last release (and over 80 commits). Might as well do it now.

https://github.com/dani-garcia/bitwarden_rs/releases/tag/1.6.0

**Comment by mprasil** [comment]
This is now resolved.

**Comment by vitorbaptista** [comment]
Hi all,

Given that this issue is solved, should the text at https://github.com/dani-garcia/vaultwarden/wiki/Enabling-Yubikey-OTP-authentication be updated?

It still says that "aarch64 builds of the server version 1.6.0 or older do not support Yubikey functionality due to upstream issues - see #262."
