### ISSUE TITLE
Log messages for successful login

### ISSUE THREAD

**Issue by RomanHargrave** [dani-garcia/bitwarden_rs#264]
We have a login message for failed login attempts, but no counterpart for successful login attempts.

It should include username, and IP address/host, as with the failed attempts.

**Comment by mprasil** [comment]
This should be fairly easy to add.

**Comment by Algebro7** [comment]
I'm guessing the rocket-0.4 branch would be the best place for this due to rocket logging features added in 2fde4e6?

**Comment by dani-garcia** [comment]
Yes, that branch is probably going to be merged sometime this week, so it's probably the best place to make changes to.

**Comment by mprasil** [comment]
This is in latest beta, I think we can now close this.
