### ISSUE TITLE
U2F Chrome extension

### ISSUE THREAD

**Issue by dheimerl** [dani-garcia/bitwarden_rs#271]
I have U2F working, when I log into the web vault, it prompts me to insert my U2F key and press the button. When I try to log into the Chrome extension, it never prompts for the U2F key and in the console error logs in Chrome, I get this message

`Refused to display 'https://bw.unitelinc.com:6443/u2f-connector.html?data=eyJhcHBJZCI6Imh0dHBzOi8vYncudW5pdGVsaW5jLmNvbTo2NDQzL2FwcC1pZC5qc29uIiwiY2hhbGxlbmdlIjoiVG1aR2FFVldMemswTURjNGJIVTRjalY1TkhOYWEzWTBjMHh1UWxvMmQxRXJlRkZTV1dsRlptbFViejA9Iiwia2V5cyI6W3sidmVyc2lvbiI6IlUyRl9WMiIsImtleUhhbmRsZSI6IkFUcm1sYjJha1FJTE16VmRZNFozZWxnVzA2amgtcGlxcFJTYWxibGZVRnFuVWN1dGFvUHZROGV6XzVQcDEzNmF3MGozc0pkSDdLVW5DelFiQW4wdmZ0NUtXWksyaWlONVpGZ3dZQlcwdVV5Z1MtTElYNFUzY3F6a194QVI2R2RqIn1dfQ==&parent=chrome-extension%3A%2F%2Fnngceckbapebfimnlniiiahkandclblb%2Fpopup%2Findex.html%23%2F2fa&v=1' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

Any ideas? I'm running the latest bitwarden_rs docker image, just pulled it this afternoon.

**Comment by dani-garcia** [comment]
Something like this already ocurred to someone else, I think the solution was making some changes to the content security policy, but I can't find the comment right now. I'll see if I can find it later.

**Comment by fbartels** [comment]
I was about to write the same. Are you running bitwarden_rs through a reverse proxy? Such errors usually appears when embedding sites in an iframe.

**Comment by fbartels** [comment]
https://github.com/dani-garcia/bitwarden_rs/issues/44 is likely the ticket @dani-garcia had in mind. I initially read it wrong thinking you were trying to use the u2f token in the web vault directly, but you already said you were using the chrome extension.

**Comment by dani-garcia** [comment]
This has been fixed by #293.
