### ISSUE TITLE
Recommended specs?

### ISSUE THREAD

**Issue by njfox** [dani-garcia/bitwarden_rs#277]
I am trying to plan a bitwarden deployment but the official server is much heavier than I would like. Do you have any information about the recommended specs for `bitwarden_rs` as opposed to the official project?

Thanks!

**Comment by mprasil** [comment]
Hi @njfox, `bitwarden_rs` can run on raspberry pi, so you really don't need very powerful server. :smile: If you want to serve less than about 100 users, you should be fine with almost anything. (including said raspberry) 

To give you some practical example, my server is using about 12MB of memory with handful of users and handful of devices for each. It also uses next to no CPU. (it's mostly idle)

Hope that answers your question.

**Comment by njfox** [comment]
Great, thank you very much for the information! Just as a suggestion, it might be worth adding that to the README in case others have the same question.

**Comment by mprasil** [comment]
Yeah, I wasn't too sure what to specify as a minimal configuration to be honest. I've never really measured anything beyond the fact, that it's using memory in the area of 10MB or so. 😄

I'd be actually interested to hear from people serving hundreds of users.
