### ISSUE TITLE
Just a quick question

### ISSUE THREAD

**Issue by mrtargaryen** [dani-garcia/bitwarden_rs#279]
Hi,

I have a QNAP TS-253Be QTS 4.3.6.0776
I am using Container Station
I have have installed the Docker image mprasil/bitwarden

The image is running, I can see that in Container Station. However, I do not know what IP address  to access the UI on. How do I discover this using the CLI?

Also, are there instructions on adding a SSL cert to Bitwarden in Docker?

Any advice from someone familiar with dock and/or QNAP I will be really really appreciative. Thank you.

**Comment by mprasil** [comment]
Did you forward any ports? I'm not familiar with Qnap docker implementation, but I guess if you forwarded the port, you should be able to access it on the Qnap IP address?

**Comment by mrtargaryen** [comment]
@mprasil I'll try that and update this thread, thank you!

**Comment by mprasil** [comment]
@mrtargaryen worked?

**Comment by mprasil** [comment]
Perfect!
