### ISSUE TITLE
in rocket 0.4 proxy remote ip has change

### ISSUE THREAD

**Issue by TMHBOFH** [dani-garcia/bitwarden_rs#280]
Hi,
with rocket 0.4 the function to get the remote ip has change.
Please see the [changelog](https://github.com/SergioBenitez/Rocket/blob/a4dcb0cf4cfd28671bbc8f101a99dfa1a74668b9/CHANGELOG.md).

> Request::remote() returns the actual remote IP, doesn't rewrite.
> 
> Use Request::real_ip() or Request::client_ip() to retrieve the IP address from the "X-Real-IP" header if it is present.

Thanks for your great work on this project.
best regards

**Comment by dani-garcia** [comment]
This should be fixed in the latest beta commit, good eye!
