### ISSUE TITLE
[Docker] Unable to connect to database when using non-root user

### ISSUE THREAD

**Issue by JuniorJPDJ** [dani-garcia/bitwarden_rs#287]
I wanted to use non-root user and container didn't start.
```
bitwarden_1  | thread 'main' panicked at 'Can't conect to DB: BadConnection("Unable to open the database file")', src/libcore/result.rs:1009:5
```

**Comment by dani-garcia** [comment]
I'm not very knowledgeable in docker, but I imagine this is because the non-root user doesn't have permission in the data folder.

**Comment by bassarf** [comment]
As far as I know, and as far as my 2 minute google research goes, this is a docker thing.
The docker deamon runs as root. But on the docker website there is a manual for non-root users to manage docker: https://docs.docker.com/install/linux/linux-postinstall/

IMO this issue should be closed because it is not specific to bitwarden_rs but rather being a docker thing

**Comment by JuniorJPDJ** [comment]
@bassarf that issue is not about starting container as non-root user, it's about dropping privileges of bitwarden_rs running in docker container to other (non-root) user.
Still, thank you for your interest, my description was misleading.

**Comment by Sohalt** [comment]
You will have to set the correct permissions on the `/data` volume. In addition you need to adjust the `ROCKET_PORT` to something above 1024, as everything below is a privileged port and can only be opened by root.

**Comment by p3lim** [comment]
I had an issue similar to this: `[bitwarden_rs][ERROR] Error creating database directory`
I solved it by setting `DATA_FOLDER` to a subdirectory of the `/data` directory/volume, e.g. `/data/data`.

**Comment by mprasil** [comment]
I've documented the procedure in [wiki page](https://github.com/dani-garcia/bitwarden_rs/wiki/Running-docker-container-with-non-root-user), so I believe this is resolved. I ran the container as `nobody` following the wiki, but feel free to re-open or open new issue if you encounter any problems.
