### ISSUE TITLE
Import not working correctly

### ISSUE THREAD

**Issue by quthla** [dani-garcia/bitwarden_rs#288]
I imported the data from my previous vault into bitwarden_rs but today I noticed that the entries with custom regex broke. The regex was split into 2 url values for some reason.

According line from backup looks like this:
`,,login,server.com,,,^https://server.com/(dasdasdaf|asdasdgasda)/,xyz@xyz.com,verysecretpassword,`

Type also changed from regex to standard match. It got split exactly at the `|` which is also missing the second url value which now is only `asdasdgasda)`

**Comment by dani-garcia** [comment]
Does it work correctly when you import the file in the official server? The import files are parsed by the web vault before the data is sent to bitwarden_rs. We just save the data as it is received.

**Comment by quthla** [comment]
Guess it's an upstream bug then if data is received like that.

**Comment by dani-garcia** [comment]
As we said, this is a limit upstream, so I'll close this.
