### ISSUE TITLE
Cannot log in from Android when 2FA is enabled

### ISSUE THREAD

**Issue by aksdb** [dani-garcia/bitwarden_rs#298]
In the current version of bitwarden_rs, I can no longer login with the Bitwarden Android client with accounts that have 2FA enabled. The app immediately closes.
Since my Android development setup is still kinda sucky (or I suck at using it :-)) the only thing I got out of the debugger was "System.InvalidOperationException: Token not found." without a proper stacktrace.
I presume something in the response is missing. Or maybe simply the casing of the key(s) is different? Apparently it works in the jslib implementation, so it has to be something that the C# implementation of the mobile apps does differently.

**Comment by tycho** [comment]
I've run into this as well. The log for bitwarden_rs claims the login attempt succeeded, but the Android app really didn't like whatever response bitwarden_rs gave.

**Comment by dani-garcia** [comment]
You were right, it was because of a casing issue. That was solved some time ago for the JSON API. But the login is a normal form instead. It should be fixed now in the latest master, tested on iOS.

**Comment by mprasil** [comment]
Image from master [is now building](https://cloud.docker.com/repository/registry-1.docker.io/mprasil/bitwarden/builds/3f994979-c6e9-4cac-9195-14a15ec813d2). Give it about an hour.

**Comment by tycho** [comment]
@dani-garcia Confirmed, that fixed it!

**Comment by aksdb** [comment]
Thanks @dani-garcia (and @mprasil) for getting a fix out that fast. Works fine now :-)
