### ISSUE TITLE
Error on activate 2FA

### ISSUE THREAD

**Issue by TMHBOFH** [dani-garcia/bitwarden_rs#30]
Hi,
at first thanks for your great work on this project.
I get an "An unexpected error has occurred" if would like enable 2FA.

I use [this docker image](https://github.com/mprasil/bitwarden_rs) with Web Vault (version 1.26.0)
the log show 
POST /api/two-factor/authenticator application/json; charset=utf-8:
=> Matched: POST /api/two-factor/authenticator
=> Error: Couldn't parse JSON body: Error("invalid type: string "731025", expected u64", line: 1, column: 17)
=> Outcome: Failure
=> Warning: Responding with 400 Bad Request catcher.
=> Response succeeded.

best regards

**Comment by dani-garcia** [comment]
Thanks, the clients sometimes send numbers or strings. This should be fixed now.

**Comment by TMHBOFH** [comment]
**Thanks** for your fast reply.
Should i open an issue on Web Vault?

**Comment by dani-garcia** [comment]
The official server doesn't seem to care about uppercase or lowercase, or about strings or numbers, so it seems like a conscious design choice by the author. I don't think there is a need to open an issue about it.

**Comment by TMHBOFH** [comment]
ok Thanks for your help
