### ISSUE TITLE
Question: Is the log file periodically deleted?

### ISSUE THREAD

**Issue by mikkelnl** [dani-garcia/bitwarden_rs#305]
Hi,

The `LOG_FILE=` feature in release 1.5.0: is the generated log file somehow truncated/purged after x days? Or wil it continue to build/grow in size?

Thanks!

**Comment by dani-garcia** [comment]
At the moment nothing is done to manage it, but it would be interesting to have some basic functionality to keep the log size in check.

At the moment, we have three options for this:
- Implement somehing ourselves
- Wait until the library we use supports it (there are a couple of open issues already):
    - https://github.com/daboross/fern/issues/14
    - https://github.com/daboross/fern/issues/33
- Use a third party utility, like `logrotate`, there are a lof of tutorials in how to configure it.

Personally, I think the third choice is the best for now, but I've added this to the list of feature requests, so this can be closed.
