### ISSUE TITLE
Multiple U2F devices fails

### ISSUE THREAD

**Issue by jtc42** [dani-garcia/bitwarden_rs#307]
Registering a single U2F device seems to work fine, following the instructions given. However, if I try to add a second device, the first one will no longer be accepted, instead giving "U2F ERROR 4".

Is this established behaviour, or should multiple devices be working?

Also perhaps worth noting that on the U2F "Manage" pannel, registering a device with a name doesn't change the list of devices. It always just shows "U2F Key 1, U2F Key 2, ..." etc.

Yubico OTP works great, but would be amazing to have multiple U2F devices working properly too.

Thanks!

**Comment by dani-garcia** [comment]
At the moment, multiple U2F devices are not implemented, no. It's on our list of feature requests (#246).

I won't personally be implementing it, as I don't have an U2F key available to develop it anymore, but contributions are welcome. For now we could print an error when the user is trying to add more than one key.

**Comment by jtc42** [comment]
Ah okay! I think, if it's easy to do (I'll have a look myself after Christmas, though I have very little experience in this area), removing the list of U2F devices in the manage panel would help, as well as adding a message or warning about adding multiple devices.

Thanks for the quick response! Sorry I missed this on the feature requests.
