### ISSUE TITLE
Helm Chart for Kubernetes deployment.

### ISSUE THREAD

**Issue by Skeen** [dani-garcia/bitwarden_rs#316]
Hi,

Just a bit of shameless self-promotion, and a plea for cooperation in case someone-else considered using Helm deploying bitwarden_rs.

Based upon #234 and [kubernetes-bitwarden_rs](https://github.com/icicimov/kubernetes-bitwarden_rs), originally discussed in https://github.com/mprasil/bitwarden_rs/pull/3, I've developed a Helm Chart for deployment with [Helm](https://docs.helm.sh/).

The result can be found [here](https://github.com/Skeen/helm-bitwarden_rs)

**Comment by mprasil** [comment]
Hey this is very cool. You should create a PR and extend the [Kubernetes deployment](https://github.com/dani-garcia/bitwarden_rs#kubernetes-deployment) section with a link to your chart.

**Comment by Skeen** [comment]
I've updated the wiki here: https://github.com/dani-garcia/bitwarden_rs/wiki/Kubernetes-deployment
