### ISSUE TITLE
Support running behind proxy with HTTP Basic Auth

### ISSUE THREAD

**Issue by khimaros** [dani-garcia/bitwarden_rs#317]
It would be great to allow delegating of credentials from HTTP Basic Auth to Bitwarden. If that is not possible, at least it would be helpful to preserve the credentials. Currently, the Basic Auth credentials are wiped when logging in via the web auth.

**Comment by mprasil** [comment]
I'm not sure if that's really possible. The API is using hashed version of your master password to log you in.

**Comment by dani-garcia** [comment]
I'm not sure we can do this without modifying the web vault. And we try not to do that as much as possible.

I don't think I understand the benefit of it either, if you are trying to put bitwarden_rs under some kind of third party authentication layer, that would break all the clients, and at best we could only fix the web vault. At the same time, it wouldn't provide any more security, as there is not much you can do in bitwarden_rs without an account in the first place.
