### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by ASdeWekker** [dani-garcia/bitwarden_rs#319]
Hi, I'm unable to login to the web vault via firefox. I think I need to add my installation id and key? But I'm not sure where to do that.
I'm on arch so I just downloaded the package from the AUR and built the web-vault myself.
I'm running it on a Raspberry Pi 3 Model B so I'm not using docker. 
I'm able to visit it in my browser but that's where the fun ends.
Could you tell me how I can add the installation key and id? I couldn't find that anywhere in the documentation.

**Comment by mprasil** [comment]
There is no installation id or key required. After you installed bitwarden_rs, you should be able to just register new account and start using it.

**Comment by ASdeWekker** [comment]
Thank you, it's working now! Can't I didn't realise that.
