### ISSUE TITLE
Package gcc-aarch64-linux-gnu is not available

### ISSUE THREAD

**Issue by DazAh** [dani-garcia/bitwarden_rs#322]
Please forgive me if this isn't an issue and I am doing something wrong, complete docker noob here. Anyway when trying to build the docker image for arm using this command:

`sudo docker build -t bitwardenarm -f Dockerfile.aarch64 .`

The gcc package is not found. 
`Package gcc-aarch64-linux-gnu is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source`

**Comment by mprasil** [comment]
That's weird, the package [should be available](https://packages.debian.org/search?keywords=gcc-aarch64-linux-gnu&searchon=names&suite=stable&section=all). However I'm afraid that the build will fail anyways - see #262.

**Comment by dani-garcia** [comment]
The AArch64 build should be fixed now, can you test if this is still a problem?

**Comment by DazAh** [comment]
> The AArch64 build should be fixed now, can you test if this is still a problem?

Will do.

**Comment by dani-garcia** [comment]
Weird, I just tried to compile it now and it worked for me. Are you using the latest master? You might need to do `git pull` to get the latest changes.

**Comment by mprasil** [comment]
Latest master definitely builds fine - we now have aarch64 image on the docker hub. The error message @DazAh shared sounds like older source code without the disabled yubikey functionality in 1d034749f7b3a0c01d9e32287393498b64f50fde.

**Comment by mprasil** [comment]
We had couple successful builds for aarch64 since then, I'm going to assume that @DazAh resolved his issue by pulling the latest code and I'm closing the issue, but feel free to reopen if problem still persists.
