### ISSUE TITLE
Admin Panel User Invitations Don't Function.

### ISSUE THREAD

**Issue by Ryonez** [dani-garcia/bitwarden_rs#324]
Inviting users via the admin Panel doesn't seem to function, even though the page responds with "User invited correctly". The email is never received by the end user.

Steps taken to test:

Tried a password hint.
Tried inviting a user via an organisation.
Both of these resulted in emails being sent.

**Comment by mprasil** [comment]
This is currently WIP by @njfox. Most of the functionality should be there from previous admin implementation, it just needs to be implemented in the new admin interface. Right now the workaround would be to create empty Organization and invite users to the Org.

**Comment by Ryonez** [comment]
Understood, just reporting it as it's a function that's not working.

**Comment by dani-garcia** [comment]
This should work now, with #323 merged.

**Comment by Ryonez** [comment]
Tested on docker, worked great thank you.
