### ISSUE TITLE
Locked Vaults will Redirect to the sign in page even with the correct password after a long time.

### ISSUE THREAD

**Issue by Ryonez** [dani-garcia/bitwarden_rs#325]
I use the web page to access the vault a lot, and find that when enough time has passed, entering my password into the locked vault page does nothing but redirect me to the login page. This is annoying as it has been happening often enough. I gave it the password, and it asks for it yet again.

Is there a way to fix this? My workaround at the moment has been to click "Log Out" form the log screen, but even that pops up a confirmation window.

**Comment by dani-garcia** [comment]
I'm not sure why this would be happening, do you get anything in the logs when you try to unlock and it redirects you?

**Comment by Ryonez** [comment]
I just restarted the server. But I can get the logs in a while, I enabled them yesterday when I went over my bitwarden_rs settings.

But there is like a timer to it. If it hasn't been to long, then you can unlock it fine. But once you hit that timer, you have to log in.

**Comment by dani-garcia** [comment]
The authentication tokens we send expire after an hour, but the client has a refresh token that should not expire. It may be related to that.

**Comment by Ryonez** [comment]
Hmm, it seems to be working now. I locked it before bed, and it let me back on without issue this morning.

I'll try again, maybe it was fixed in version 2.8? I can't find any issue for it logged there though.

I'll keep an eye out a little longer and see it does occur again.

**Comment by Ryonez** [comment]
Gotcha, thank you.

**Comment by Ryonez** [comment]
I'm unable to reopen this myself, but I've got it happening again

![image](https://user-images.githubusercontent.com/16157130/50812850-343e9d00-1379-11e9-92c9-859173fc4ce8.png)

Sorry for the picture, but mc wasn't letting me copy the text out.

@mprasil

**Comment by mprasil** [comment]
Hmmm.. "Invalid refresh token" seems to be the cause. I see There are two calls to `/identity/connect/token`, I wonder if that's just coincidence or actual cause of the problem..

**Comment by Ryonez** [comment]
Maybe?

On my end, I attempted to unlock. It failed, so I was taken back to log in normally.

It feels a bit weird that it did this for so long, then worked for two days when I opened the issue, and showed back up after it was closed.

**Comment by mprasil** [comment]
To me it appears that it happens randomly enough to not happen for a few days. I'll give it another try with latest image update and see if I can reproduce it.

**Comment by mprasil** [comment]
@Ryonez do you use websockets sync in your setup?

**Comment by Ryonez** [comment]
Not that I'm aware of specifically.

I use the linuxserver/letsencrypt docker and proxy pass to the ip. I don't know how to do websocket stuff, though I do need to look into it sometime for something else.

**Comment by mprasil** [comment]
I've ran into this some time ago also on Linux/Firefox combo. But haven't encountered the issue lately.

**Comment by mprasil** [comment]
I haven't encountered this in a long time, so hopefully it's resolved. Feel free to reopen if you can still reproduce this problem.
