### ISSUE TITLE
Authorization header not being sent

### ISSUE THREAD

**Issue by RockyTV** [dani-garcia/bitwarden_rs#327]
I've just installed the application with Docker and added it to my `docker-compose.yml` file, correctly mounting the storage volume and configuring some environment variables for it to work with my nginx reverse proxy container.

After I rebooted my server, I realized that all of my passwords are now gone. Doing a quick check in the "persistent" storage path revealed that the previous database is still there, intact, and there are 2 other sqlite databases, named `db.sqlite3-shm` and `db.sqlite3-wal`, respectively.

It's weird because all of my passwords are gone and the database seems to be intact. I have no idea what to do because all I did was reboot the server.

Log: https://pastebin.com/raw/j0UfnbLH

EDIT: I forgot to mention that my user and my preferences are still there, but my passwords are gone.

**Comment by dani-garcia** [comment]
My first thought was running with different environment variables or a different mount point but if your user is there, that means at least that was saved correctly,  so I'm not sure why the passwords don't appear.

Can you try running `sqlite3 path_to_data/db.sqlite3 "select * from ciphers;"`? That needs to be run outside the container, and you'll need sqlite installed.

A reboot shouldn't delete your data, unless you rebooted in the middle of a transaction.

**Comment by RockyTV** [comment]
Well, it seems like everything is still here, but the web vault isn't showing it. I just tried the bitwarden mobile app and everything is there.

**Comment by dani-garcia** [comment]
That's even stranger. Do you get any error message in the web browsers console?

**Comment by RockyTV** [comment]
![](https://i.imgur.com/yWl7Hp7.png)

**Comment by dani-garcia** [comment]
And from the network tab, what is the response to that /api/sync call?

**Comment by RockyTV** [comment]
401 Unauthorized.

This is weird. I think this is due to my current setup trying to make my DDNS domain work in my local network, using dnsmasq.

**Comment by dani-garcia** [comment]
Try deleting all your cookies for the domain and logging in again. Or maybe try a different browser. Domain shouldn't affect it really.

**Comment by RockyTV** [comment]
I already tried it. It's something with my custom DNS server. However, I can't find any difference in the requests made by different IPs (i.e. internal and external). The response is the same, but the status code for internal IP is 401 whilst the status code for the external IP is 200. Headers are equal.

**Comment by RockyTV** [comment]
I don't know, it just tells me that it sent a 401 to the client. I'm trying to enable logs in the reverse proxy container, which uses a slightly modified version of this https://github.com/jwilder/nginx-proxy

**Comment by RockyTV** [comment]
Alright, I've managed to temporarily fix it for now. I have other containerized services running in my server, such as [The Lounge](https://thelounge.chat), and when I rebooted my server, I tried to access the web vault and it redirected me to The Lounge (weird, because I don't have any fallback host setup in the reverse proxy container). I restarted the bitwarden container and it worked, until I tried to login.

I kept deleting local storage and realized that every time I logged in, some assets from The Lounge would appear in cache. So, I simply cleared the cache for the domain and it's working again. There's still one error in the console, though, but the vault works!

![](https://i.imgur.com/B37iVFQ.png)

**Comment by dani-garcia** [comment]
That last error is because there is a problem with websockets, if you have them disabled it's to be expected.

If you enabled them, then make sure that your proxy is redirecting the correct path to the websocket server, by default at port 3012. You have more info here https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-WebSocket-notifications.

**Comment by DazAh** [comment]
Do you have some fancy SSL setting if using a reverse proxy? I had a very similar problem by applying SSL Stapling and something else which I can't remember.

**Comment by RockyTV** [comment]
I don't think so, it's all managed by the `nginx-proxy`. I haven't touched SSL stapling.

**Comment by BlackDex** [comment]
@rockytv do you still have this issue? If so, it sounds to me like something strange in the nginx config which redirects you or selects a default.

**Comment by mprasil** [comment]
This wasn't updated for quite a while. I'm going to close it. Feel free to reopen if you need more help.
