### ISSUE TITLE
Make the Admin Panel a little safer, to prevent accidentally deleting a user.

### ISSUE THREAD

**Issue by Ryonez** [dani-garcia/bitwarden_rs#330]
So this is a feature request.

Could we please have it so if you click the delete link for a user account in the admin panel, a popup appears that asks you to type the account name before you can click confirm?

At the moment, a box appears at the top of the wind that just has a yes/no selection right next to each other, and it's a little nerve racking that there isn't something to make it a bit safer.

**Comment by dani-garcia** [comment]
That makes total sense, it's fixed in 673adde9

**Comment by Ryonez** [comment]
Thank you, that feels much better >.<
