### ISSUE TITLE
Update Fail2Ban wiki page with rules to block /admin bruteforce

### ISSUE THREAD

**Issue by njfox** [dani-garcia/bitwarden_rs#332]
It's probably worthwhile to update the wiki with a Fail2Ban filter that will block IPs after too many unsuccessful requests to /admin. Currently we only document how to block failed login requests in the web vault.

**Comment by BlackDex** [comment]
For this to work the ERROR message:
`[bitwarden_rs::api::admin][ERROR] Unauthorized Error: "Invalid admin token"`
Needs to have an IP address added.

**Comment by dani-garcia** [comment]
Added the IP in a0a08c4c5af06d

**Comment by njfox** [comment]
Thanks for adding the IP, the wiki has been updated with a fail2ban config for /admin.
