### ISSUE TITLE
Attachment doesn't exist error when trying to modify record with attachment

### ISSUE THREAD

**Issue by lukas665** [dani-garcia/bitwarden_rs#335]
Hi!
There is error when I'm trying to edit and save record with attachments:
`[bitwarden_rs::error][ERROR] Attachment doesn't exist.`
All other actions with attachments are ok (uploading/deleting/downloading).
I'm using raspberry image behind nginx proxy.

**Comment by dani-garcia** [comment]
I don't know how to reproduce this. Can you give a list of steps from a clean database that cause this error? For example: Create user -> Add cipher -> Attach file -> Edit cipher -> Error

Also, if you delete the attachments, can the cipher be edited again?

**Comment by dani-garcia** [comment]
I could finally reproduce it, I think 6f5210 should fix it. Can you give it a try?

**Comment by lukas665** [comment]
I can confirm it's working now.
Thanks!
