### ISSUE TITLE
Enabling YubiKey does not generate a recovery code

### ISSUE THREAD

**Issue by TillMueller** [dani-garcia/bitwarden_rs#342]
First of all - thanks a lot for the work you have done here! Overall, this software works very nicely and I am very happy to have found it!

While configuring my account however I came across the issue that when enabling a YubiKey as the only 2FA method, the recovery key is not generated (see first screenshot) and can therefore not be used.
After enabling the authenticator 2FA method however, the recovery key appears (see second screenshot)
This isn't too much of a problem but I guess it is an easy fix and maybe some users might get confused as to why there is no recovery key available.

Thanks a lot for taking a look at this issue!

![image](https://user-images.githubusercontent.com/20823337/51206821-5ac87f00-1909-11e9-9aa8-c99e5b727862.png)

![image](https://user-images.githubusercontent.com/20823337/51206692-fefdf600-1908-11e9-925f-99394f71037f.png)

**Comment by dani-garcia** [comment]
Good catch!

This should be solved now in https://github.com/dani-garcia/bitwarden_rs/commit/c259a0e3e23800347ed90b4a192b44798c3513fb.

**Comment by TillMueller** [comment]
Awesome, thanks for the quick fix!
