### ISSUE TITLE
bitwarden_rs organization

### ISSUE THREAD

**Issue by MBryde** [dani-garcia/bitwarden_rs#349]
The bitwarden_rs organization that you can join using the docker env: "SERVER_ADMIN_EMAIL" - seems to be a bit out of order.
Sometimes I get the organization listed, sometimes I don't. But if I try to click on it I get kicked out of the session instantly. I can sometimes access the organization from the settings -> organization -> bitwarden_rs. I know their is a new admin page. But the organization method seems better if it worked.

**Comment by mprasil** [comment]
Hi, unfortunately (or gladly, depending who you ask) the old the old "admin" organization is no longer present / supported. If you're using the latest docker image, you shouldn't even see it honestly, sounds like some cached shadow of the old functionality. It was really hacky way to provide the admin functionality and it wasn't sustainable long term. (it was regularly breaking Vault interface) I suggest moving to the new admin page, it should already do what the old system did and it's only going to get better.
