### ISSUE TITLE
builds.rs git info makes release archives unusuable

### ISSUE THREAD

**Issue by Duncaen** [dani-garcia/bitwarden_rs#350]
I'm using the release archives (https://github.com/dani-garcia/bitwarden_rs/archive/1.6.1.tar.gz) to create a bitwarden_rs binary package for a linux distribution.
The preferred way is to use release archives because they are simpler to cache, download and verify with checksums.

```
thread 'main' panicked at 'Unable to read Git info: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:1009:5
```

**Comment by dani-garcia** [comment]
Right, I didn't consider people using the github provided archives for building.
In https://github.com/dani-garcia/bitwarden_rs/commit/86a254ad9ef27af3c35481d1e179a9f2affb8e7d I changed it to ignore the errors, that should solve the problems for any future versions. I have some small changes to email templates and the admin panel that I expect to finish this weekend and then I'll get a new release going.
