### ISSUE TITLE
Installation without Docker?

### ISSUE THREAD

**Issue by Geobert** [dani-garcia/bitwarden_rs#355]
Hi there,

I'm quite a noob in server admin field and I've never used Docker before. Everything on my small personal server (Debian stretch) is installed the old apt way. 

That being said, is there a way to install bitwarden_rs without Docker?

If not, I believe I'll learn Docker ^^

**Comment by geek1011** [comment]
You can extract the docker image (or build it yourself).

First, download: https://github.com/moby/moby/blob/master/contrib/download-frozen-image-v2.sh

Then:

````
rm -rf dl
mkdir dl
cd dl
../download-frozen-image-v2.sh img mprasil/bitwarden:alpine || echo "Error downloading image"
for t in img/*/layer.tar; do
    tar xf "$t" web-vault &>/dev/null
    tar xf "$t" bitwarden_rs &>/dev/null
done
rm -rf img
[[ -d web-vault ]] || echo "Error extracting web-vault"
[[ -f bitwarden_rs ]] || echo "Error extracting bitwarden_rs"
````

Note: You can ignore the errors about go not being installed.

**Comment by dani-garcia** [comment]
If you can build the binary yourself, you can read https://github.com/dani-garcia/bitwarden_rs/wiki/Building-binary. I think that would be the best way. Extracting the binary from the image, like the previous comment mentioned, is also an alternative.

**Comment by Geobert** [comment]
I tried the script, I got `error: "jq" not found!`

**Comment by geek1011** [comment]
You need to apt install jq.

**Comment by Geobert** [comment]
Thanks, I didn't know about jq until today :D 

It seems I need `go` as well

**Comment by mprasil** [comment]
I'm kinda confused what makes you think you need `go`? Is it a dependency to build Vault? You can also skip that step and download already built Vault from [here](https://github.com/dani-garcia/bw_web_builds/releases).

As for your other question, you still need nightly, but there's `rust-toolchain` file in the repository that should make `cargo build` download appropriate version automatically. (we require nightly as our upstream dependency - Rocket requires nightly) Hope that helps.

**Comment by Geobert** [comment]
`go`'s presence is checked in the shell script https://github.com/moby/moby/blob/master/contrib/download-frozen-image-v2.sh but @geek1011 told me it can be ignore

thanks for the nightly explanation!

**Comment by mprasil** [comment]
Ah right, that's for the moby project, yeah that makes sense as it's written in Go.
