### ISSUE TITLE
Invitation and User Deletion not Working on Admin Panel

### ISSUE THREAD

**Issue by paulkernstock** [dani-garcia/bitwarden_rs#358]
I'm running bitwarden_rs from a docker-compose file and had issues with invitation emails not being sent. I pulled the latest docker image today to get the fix of #324 but now I get errors on invitations as well as user deletion. Users are not invited or even added or deleted, respectively. Additionally the error messages only flash for a moment and then the site refreshes.

Twirking around with this, I noticed everything seems to work fine if I debug both respective functions with Firefox and jump through the script statement by statement (invitation is sent and user added/user is deleted).

**Comment by paulkernstock** [comment]
Thanks for bitwarden_rs by the way. This is a great thing to have!

**Comment by dani-garcia** [comment]
Do you get any errors, either in the app logs or the browsers console? Yo can usually mark a checkbox in the browsers developer tools so the messages are not deleted (at least in Firefox you can).

**Comment by paulkernstock** [comment]
The app will only log the successful refresh of the admin page. Same in Firefox: there are only 200-responses being logged (log-deletion disabled), when I try to invite a new user. The flashing error message reads

> Error inviting user: Unknown error

**Comment by dani-garcia** [comment]
Interesting, when I tested it last it worked fine, but now I have the same problem as you. Fixed it in https://github.com/dani-garcia/bitwarden_rs/commit/b8cabadd43b56b0bc3cb385fa4ef8e940bc99f91, thanks!

**Comment by paulkernstock** [comment]
No, thank you! 👍
