### ISSUE TITLE
Error trying manage a collection's users

### ISSUE THREAD

**Issue by srwhite** [dani-garcia/bitwarden_rs#364]
If you view the collections for an organisation (https://server/#/organizations/.../manage/collections) you should be able to click on the "Cog" menu next to each one and manage the list of users.

With bitwarden_rs the pop-up dialog showing the user list never loads for me, instead my browser's console reports:
```
ERROR Error: Uncaught (in promise): TypeError: e.sent(...).map is not a function
TypeError: e.sent(...).map is not a function at vendor.0eaaec5bcaa0824c445b.js:121
```

I have something that appears to fix this, although I have spotted two other issues that I don't yet have have fixes for:
 - With my fix the users list appears, but none of the collections are "ticked" even if the user does have access to them
 - This functionality should be available to "Managers" as well as "Admin", but isn't in bitwarden_rs

**Comment by srwhite** [comment]
The issue is that get_collection_users should return an array rather than a map. The contents of the array are not the values from the existing "user_list" variable, but should be simply a list of user Ids and whether they are read-only or not, i.e. if there is one user it would look like this (but with a real UUID):
[{"Id":"$$UUID$$","ReadOnly":false}]

**Comment by dani-garcia** [comment]
About the users list, they appear selected for me correctly, but the save button doesn't work, that isn't implemented, same as the managers.

**Comment by srwhite** [comment]
Yeah, sorry, between the original report on here and making the pull request I worked out the fix for making the selections show up correctly.

I also note I failed to delete the line:
```
let user = User::find_by_uuid(&self.user_uuid, conn).unwrap();
```
from to_json_collection_user_details, which is now redundant as we don't need any of the extra details it obtains.

I'm interested in the manager functionality, so I might have a go at implementing it if I can find time.

**Comment by dani-garcia** [comment]
I pushed a fix for the unimplemented save from that dialog, so that should work now.

If you need any help with the implamentation of the manager functionality, I'm usually available in the matrix chat, link in readme.

With that, I think we can close this.
