### ISSUE TITLE
webvault working but none of the apps i.e. browser ext, desktop, ios

### ISSUE THREAD

**Issue by morrisfamily** [dani-garcia/bitwarden_rs#367]
so I can get to the webvault at my https://bitwarden.mydomain.org it is behind traefik and letsencrypt is working i.e. I have the green lock when going to site and shows as valid cert when selected.

However every app or client I try does not seem to be working.  I receive a wrong password username error when clicking login.

![bw settings browser ext](https://user-images.githubusercontent.com/33771931/51781883-ecdc3e80-20e4-11e9-9d14-ee4c46374d58.PNG)

![bw browser error](https://user-images.githubusercontent.com/33771931/51781887-fa91c400-20e4-11e9-8daa-5d110bc0a9ec.PNG)

![bw vault access](https://user-images.githubusercontent.com/33771931/51782113-d0420580-20e8-11e9-8a6e-eec0defa4df2.PNG)

**Comment by mprasil** [comment]
Hi, do you see any logs showing up on the server side?

**Comment by morrisfamily** [comment]
i do not see any logs in the data folder and likely because I do not have the : 
-e LOG_FILE=/data/bitwarden.log \

So do I need to restart with that setup and attempt login again?

**Comment by mprasil** [comment]
These are the hardest issues to spot, glad you solved the problem.

**Comment by mabushey** [comment]
@morrisfamily  Where did you find a plugin that lets you specify a `Server URL`?

**Comment by morrisfamily** [comment]
It is the standard chrome extension.
