### ISSUE TITLE
Bitwarden docker behind NGINX issues

### ISSUE THREAD

**Issue by hkyq** [dani-garcia/bitwarden_rs#369]
Hey, I'm trying to run Bitwarden_rs behind NGINX (with cloudflare HTTPS enabled). Here is my `nginx.conf`:

```
server {
        listen          80;
        server_name     bw.domain.net;
        location / {
          proxy_pass http://127.0.0.1:8000;
          proxy_set_header Host             $host;
          proxy_set_header X-Real-IP        $remote_addr;
          proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
        }
}
```
And the command I'm launching the docker with:

```
docker run -d --name bitwarden -v /home/h/bw-data/:/data/ -p 8080:80 mprasil/bitwarden:latest
```

But I haven't been able to reach the server on port 80 (with the nginx config). Going to the IP

**Comment by dani-garcia** [comment]
I deleted you other issue, as you asked. About your problem, I don't know much about proxies and Docker, so maybe someone else sees this and helps you with it.

**Comment by hkyq** [comment]
Thanks (last issue had some PII). Turns out I was going to the wrong IP, whoops. Works now.
