### ISSUE TITLE
error on create new entries with Android app

### ISSUE THREAD

**Issue by TMHBOFH** [dani-garcia/bitwarden_rs#37]
Hi,

i get an error if i want to create  an new entry.
I use the later docker image from mprasil and the newest Android app.

following error are shown by server

POST /api/ciphers application/json; charset=utf-8:
    => Matched: POST /api/ciphers
    => Error: Couldn't parse JSON body: Error("missing field `type`", line: 1, column: 498)
    => Outcome: Failure
    => Warning: Responding with 400 Bad Request catcher.
    => Response succeeded.

How i can help to debug the problem?

Thanks a lot for your help and great job on this project.
@mprasil thanks for your nice docker images

best regards

**Comment by mprasil** [comment]
Hi, I've tested it on my side with Android and can confirm the issue.

**Comment by dani-garcia** [comment]
Yeah, I just checked right now, the android client sends the json keys with the first letter in uppercase (`Type` while we expect `type`, for example), I'll see what I can do

**Comment by mprasil** [comment]
This would be great use case for [case insensitive attribute](https://github.com/serde-rs/serde/issues/586). Sadly not an option for now, but there are some workarounds.
