### ISSUE TITLE
Can't configure Yubikey

### ISSUE THREAD

**Issue by zachary-russell** [dani-garcia/bitwarden_rs#371]
I am having an issue where I can't configure my Yubikey to work with bitwarden_rs. I can get FIDO to work, however. This is not ideal because for some reason U2F is not working in the Firefox extension login (though it is in the FF web vault login).

I am getting this error in the browser when entering my master password: `POST https://bitwarden.protechig.com/api/two-factor/get-yubikey 404`

I am using my host's nginx to proxy to the docker container. I have HTTPS enabled with LetsEncrypt and websockets are working. 

Note: This same exact error happens with Duo set up, and the FIDO keys also don't show names. I have no idea if it's related.

**Comment by dani-garcia** [comment]
I don't think you should be getting a 404 there, did you set up the environment variables mentioned in the wiki? Do you get any errors on the logs?

Duo is not implemented, so the 404 error there makes sense. About U2F, at the moment we only support one key, so the multiple keys and names are not supported either.

**Comment by zachary-russell** [comment]
Thanks for the super swift response @dani-garcia! 

Here is my config file:

![242696914f0b3af4af8fd9f037f67f87 _screen 20shot 202019-01-29 20at 2011 07 16 20am](https://user-images.githubusercontent.com/2122549/51921967-416a0d00-23b6-11e9-857f-40914c108acd.png)

Oddly enough, I can't even find the log files. I tried destroying and recreating the containers and removing the entire `bw-data` directory.

**Comment by dani-garcia** [comment]
The config seems OK to me. Are you using a recent version of the image? You can try to update it with `docker compose pull` with the services stopped.

**Comment by zachary-russell** [comment]
I have no idea what is going wrong. I pulled the image today. It's showing all sorts of odd things (like asking for billing information). I ended up just stopping this project and am running it in K8s now.
