### ISSUE TITLE
Web vault is not found. Please follow the steps in the README to install it

### ISSUE THREAD

**Issue by gdamjan** [dani-garcia/bitwarden_rs#373]
Building it from source (no docker), and running it, gives me this:
```sh
$ cargo run 
    Finished dev [unoptimized + debuginfo] target(s) in 0.95s
     Running `target/debug/bitwarden_rs`
[2019-01-29 21:17:57][bitwarden_rs][ERROR] Web vault is not found. Please follow the steps in the README to install it
```

well, the README file doesn't say anything about no vault.

**Comment by dani-garcia** [comment]
Yeah, we moved that to the wiki. I'll update the message.
Check here: https://github.com/dani-garcia/bitwarden_rs/wiki/Building-binary#install-the-web-vault.

**Comment by gdamjan** [comment]
I did find it eventually, but the message or the README should be more correct still

**Comment by dani-garcia** [comment]
Updated in https://github.com/dani-garcia/bitwarden_rs/commit/f42ac5f2c02b519623547b6c27d489f73b12a190
