### ISSUE TITLE
Web works fine, but no plugins work

### ISSUE THREAD

**Issue by mabushey** [dani-garcia/bitwarden_rs#374]
So far I've looked at the Firefox and Opera plugins (Linux) but they don't work because the server URL is not an option. Do you recommend IPTables rules or hacking the plugins to get them to point at my server? 

BTW bitwarden_rs looks really awesome, I got it running in docker-compose in no time, and I'm glad to see there are K8s docs too!

**Comment by dani-garcia** [comment]
All the extensions allow changing the server url, it's the gear icon in the top left

**Comment by mabushey** [comment]
@dani-garcia Thank you!
