### ISSUE TITLE
Fail2Ban for /admin

### ISSUE THREAD

**Issue by Biepa** [dani-garcia/bitwarden_rs#375]
Hey,
i think there's something wrong with the Fail2Ban config in the wiki.
I wondered why the bitwarden-admin filter doesn't work.

In the Wiki it says:
`failregex = ^.*Unauthorized Error: Invalid admin token\. IP: <HOST>.*$`

But the output in the log is:
`[2019-01-30 10:07:46][bitwarden_rs::api::admin][ERROR] Invalid admin token. IP: x.x.x.x`

So I changed the failregex to:
`failregex = ^.*Invalid admin token\. IP: <HOST>.*$`
and then it worked.

I am not very familiar with Fail2Ban configuration, but I think there might be a mistake in the Wiki.

**Comment by dani-garcia** [comment]
You are right, the documentation wasn't updated when that message was changed. I updated the Wiki now, thanks!
