### ISSUE TITLE
Manage env variables

### ISSUE THREAD

**Issue by chielmi** [dani-garcia/bitwarden_rs#379]
Great docker!

There is one thing I can't figure out. I would like to disable user registration. This should be possible by adding _globalSettings__disableUserRegistration=true_ to ./bwdata/env/global.override.env

But I can't figure out how to do this. The container has no /bwdata. I have mapped /data to a local drive, but adding the global.override.env file in that location made no difference.

Is there a way to add this variable?

**Comment by mprasil** [comment]
Hi, please see [here](https://github.com/dani-garcia/bitwarden_rs/wiki/Disable-registration-of-new-users) - you basically just set the appropriate env variable. Hope that helps.

**Comment by hboetes** [comment]
bit clumsy but here's how I do it:
```
grep -v '^#' .env|sed -e 's|^|export |' > env
source env
cargo run --features sqlite --release
```
