### ISSUE TITLE
The SIGNUPS_ALLOWED variable is ignored.

### ISSUE THREAD

**Issue by JacobCZ** [dani-garcia/bitwarden_rs#384]
When I try to run the docker image with the SIGNUPS_ALLOWED set to false like so:
```
docker run -d --name bitwarden \                                                                                                                                      
  2   -e SIGNUPS_ALLOWED=false \                                                                                                                                          
  3   -e INVITATIONS_ALLOWED=false \                                                                                                                                      
  5   -v /bw-data/:/data/ \                                                                                                                                               
  6   -p 8666:80 \                                                                                                                                                        
  7   mprasil/bitwarden:latest
```
the signup button is still there and users can still create an account.

I'm running BW version 2.8.0  on Ubuntu 18.04.1 (4.15.0-34) and docker version 18.09.1

**Comment by mprasil** [comment]
Are you sure users can still register? The button won't disappear, because Vault isn't aware of the registration availability, but when you try to register you should get an error response back saying that registrationisn't allowed.

**Comment by JacobCZ** [comment]
@mprasil oooooh! My bad, sorry. :slightly_smiling_face:

**Comment by Happyfeet01** [comment]
Can i run this command on an existing container?

**Comment by dani-garcia** [comment]
Yes, you can either stop the container and run it again with the same command but adding `-e SIGNUPS_ALLOWED=false` to it. Or, if you have the admin panel activated, you can change it from there without restarting.

**Comment by Happyfeet01** [comment]
> 
> 
> Yes, you can either stop the container and run it again with the same command but adding `-e SIGNUPS_ALLOWED=false` to it. Or, if you have the admin panel activated, you can change it from there without restarting.

i added the option the docker-compose.yml it works now
