### ISSUE TITLE
Invite mails use `localhost` as domain

### ISSUE THREAD

**Issue by ldidry** [dani-garcia/bitwarden_rs#388]
The [line 72 of the .env.template file](https://github.com/dani-garcia/bitwarden_rs/blob/master/.env.template#L72) says that there is no need to set `DOMAIN` "Unless you are using U2F, or having problems with attachments not downloading" but without setting up `DOMAIN`, the invite link in mails uses `http://localhost` as domain.

This could be fixed either by updating the documentation or using the HTTP headers (Host and Scheme) to find the currently used domain (I don't know if it would work with Docker, I don't know Caddy which is the [suggested proxy](https://github.com/dani-garcia/bitwarden_rs/wiki/Using-Docker-Compose)).

**Comment by mprasil** [comment]
See documentation for [other proxies](https://github.com/dani-garcia/bitwarden_rs/wiki/Proxy-examples). As far as I remember you only need to forward the `Host` header and it should work fine.

**Comment by ldidry** [comment]
It didn't work for me with Nginx.

**Comment by dani-garcia** [comment]
At the moment we only guess the domain for the attachments, the emails require the `DOMAIN` variable to be set, the .env file wasn't updated apparently.

We should update the documentation accordingly, and we could also consider using the same domain-guessing for email if possible (For u2f it might not be a good idea, as the authentication can break if the domain changes).

**Comment by dani-garcia** [comment]
I updated the env file to better reflect the current situation, and also added the domain guessing functionality to the feature requests issue, so I think this can be closed now. Thanks!

**Comment by ldidry** [comment]
Thx :+1:
