### ISSUE TITLE
SMTP Error

### ISSUE THREAD

**Issue by niklasdahlheimer** [dani-garcia/bitwarden_rs#392]
Hey Guys,

I installed the docker image on our Synology-Docker. First of all: Thank you for the really easy way of configuring the container!

I have to issues:

1. If I do not regulate the CPU-usage, the bitwarden-container drives up to nearly 50% of CPU-usage over the time. With lowering the priority it still pumps up to 12%. is this correct? All our other containers (mysql, nginx, wekan,...) use around 0.5-2% CPU...the bitwarden container starts with 0% and then grows over the time, looks like kind of a memory leak...

2. SMTP is not working. The credentials are working in the other containers, so I guess it's not a problem with our mail-server (i also tried a googlemail-server to prove that). When I try to send an invitation mail
 via SSL (Port 465), the log says:
[2019-02-10 16:41:24][lettre::smtp::client][DEBUG] connecting to **.**.**.**:465
(** is our public IP)

our synology:
RS3614xs+, INTEL Xeon E3-1230 v2, DSM 6.2.1-23824 Update 4

A json dump of the container config with hidden (**) credentials
```{
   "cap_add" : null,
   "cap_drop" : null,
   "cmd" : "/bin/sh -c ./bitwarden_rs",
   "cpu_priority" : 10,
   "devices" : null,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : false,
   "enabled" : true,
   "env_variables" : [
      {
         "key" : "LOG_FILE",
         "value" : "/data/bitwarden.log"
      },
      {
         "key" : "ADMIN_TOKEN",
         "value" : "***************************************************************"
      },
      {
         "key" : "SIGNUPS_ALLOWED",
         "value" : "false"
      },
      {
         "key" : "DOMAIN",
         "value" : "*.**********.de"
      },
      {
         "key" : "SMTP_PASSWORD",
         "value" : "****************"
      },
      {
         "key" : "SMTP_USERNAME",
         "value" : "admin"
      },
      {
         "key" : "SMTP_SSL",
         "value" : "true"
      },
      {
         "key" : "SMTP_PORT",
         "value" : "465"
      },
      {
         "key" : "SMTP_FROM",
         "value" : "admin@****************.de"
      },
      {
         "key" : "SMTP_HOST",
         "value" : "mail.*************.de"
      },
      {
         "key" : "PATH",
         "value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "ROCKET_ENV",
         "value" : "staging"
      },
      {
         "key" : "ROCKET_PORT",
         "value" : "80"
      },
      {
         "key" : "ROCKET_WORKERS",
         "value" : "10"
      }
   ],
   "exporting" : false,
   "id" : "2fddab0a4c9d0039de78406153bf6b6a5ae01f4094c5041c63e1161b2dcd797f",
   "image" : "mprasil/bitwarden:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 2171600896,
   "name" : "bitwarden",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 3012,
         "host_port" : 0,
         "type" : "tcp"
      },
      {
         "container_port" : 80,
         "host_port" : 8070,
         "type" : "tcp"
      }
   ],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false
   },
   "ulimits" : null,
   "use_host_network" : false,
   "volume_bindings" : [
      {
         "host_volume_file" : "/docker/Bitwarden",
         "mount_point" : "/data/",
         "type" : "rw"
      }
   ],
   "volumes_from" : null
}
```

Looking forward for your responses! Thank you!

**Comment by dani-garcia** [comment]
The server should basically use no resources when it's idle and not processing any requests. We've had some users in the past have some extra CPU usage when the websockets server is enabled, but I couldn't replicate it (and you don't seem to have it enabled anyway). How long does the process need to be running to reach the CPU usage you mention?

The SMTP issue seems weird. It looks like it can't reach the server. Can you make sure that the docker container has access to the mail server network somehow? If the mail server is in a public IP, you could just check that the container has internet access by making sure that the website icons download correctly.

**Comment by niklasdahlheimer** [comment]
Hey!
Thanks for the quick response!

1. After the container-restart yesterday the container stayed at 0% CPU, I will observe that but can not reproduce it anymore (what is also kind of good :) )

2. About the SMTP issue:
When I try to connect to the mailserver without SSL via port 25 the log says:

```
[2019-02-10 16:28:08][lettre::smtp::client][DEBUG] connecting to ***.***.****.***:25
[2019-02-10 16:28:08][lettre::smtp::client][DEBUG] Read: 220 mail.company.de ESMTP ready<CRLF>
[2019-02-10 16:28:08][lettre::smtp][INFO] connection established to ***.***.****.***:25
[2019-02-10 16:28:08][lettre::smtp::client][DEBUG] Wrote: EHLO bitwarden<CRLF>
[2019-02-10 16:28:08][lettre::smtp::client][DEBUG] Read: 250-mail.company.de<CRLF>250-AUTH<CRLF>250-STARTTLS<CRLF>250-ENHANCEDSTATUSCODES<CRLF>250-8BITMIME<CRLF>250-PIPELINING<CRLF>250-ETRN<CRLF>250-DSN<CRLF>250 HELP<CRLF>
[2019-02-10 16:28:08][lettre::smtp][DEBUG] server mail.company.de with {EightBitMime, StartTls}
[2019-02-10 16:28:08][lettre::smtp][INFO] No supported authentication mechanisms available
[2019-02-10 16:28:08][lettre::smtp::client][DEBUG] Wrote: MAIL FROM:<admin@company.de> BODY=8BITMIME<CRLF>
[2019-02-10 16:28:08][lettre::smtp::client][DEBUG] Read: 250 2.1.0 Sender <admin@company.de> ok<CRLF>
[2019-02-10 16:28:08][lettre::smtp][INFO] ce66e524-03ea-4b89-81a4-71b5124faf11: from=<admin@company.de>
[2019-02-10 16:28:08][lettre::smtp::client][DEBUG] Wrote: RCPT TO:<someone@web.de><CRLF>
[2019-02-10 16:28:08][lettre::smtp::client][DEBUG] Read: 550 5.7.1 Relaying to <someone@web.de> denied (authentication required)<CRLF>
[2019-02-10 16:28:08][lettre::smtp::client][DEBUG] Wrote: QUIT<CRLF>
[2019-02-10 16:28:08][lettre::smtp::client][DEBUG] Read: 221 2.0.0 SMTP closing connection<CRLF>
```

So i guess the access to the network access to the mailserver could not be the problem.

when i google about SMTP and bitwarden I found out about a variable
`globalSettings__mail__smtp__useDefaultCredentials`
Could that be some source of problem?

Should I provide more logs?

Greetings

**Comment by dani-garcia** [comment]
I think the problem might be related to the connection type we are using to securely connect to the server.

At the moment we are starting with an insecure connection that is then upgraded with STARTTLS, but there is also an option to just wrap the entire connection in a normal TLS layer. 

I know of some SMTP servers which use different ports for those two options (like fastmail, which uses `25` or `587` with STARTTLS or `465` with a TLS wrapper), which may be your case.

The upstream settings are not used here so that shouldn't affect anything. I would make sure that all the options appear correctly in the SMTP section of the admin panel, and try using either port `25` or `587` with SSL enabled hoping that the server would accept a STARTLS upgrade in those ports.

If that doesn't work, I could create an option to select between those connection modes.

Also, why does your unencrypted example fail with authentication required? Check in the admin panel if the SMTP username and password are set correctly.

**Comment by niklasdahlheimer** [comment]
Hey!
Connecting to Port 25 with SSL did the job! Great idea!

We are using a Kerio Connect Mail server.

I don't know either why the nonSSL Login via Port 25 failed. The credentials where correct. Maybe bitwarden uses some different kind of AUTH LOGIN or something like that?

Anyway, it works now and I am happy, but if you need any more information about this issue, just tell me, I would love to contribute to this great project (without having any web-development skills :) )
