### ISSUE TITLE
SMTP 

### ISSUE THREAD

**Issue by SeyedGH** [dani-garcia/bitwarden_rs#395]
Error building email. invalid email address what could be the meaning of this?

**Comment by BlackDex** [comment]
It means the code thinks the email address is invalid.
Does the domain starts with a digit for insurance? or does it contains any other special characters?

**Comment by SeyedGH** [comment]
yes domain starts with a digit

**Comment by BlackDex** [comment]
@SeyedGH Please update to the latest version, which has just been released 5 hours ago, which has a fix for exactly this issue.

**Comment by SeyedGH** [comment]
omg big facepalm!
