### ISSUE TITLE
When editing the cipher, can't change the folder to "No folder"

### ISSUE THREAD

**Issue by mprasil** [dani-garcia/bitwarden_rs#4]
When editing cipher that's already in some folder, I can select `No folder` and click save.

Expected result is, that cipher will no longer be in any folder.

Actual result is, that the folder setting isn't updated.

I think there's extra check for `None` where it shouldn't be when updating the cipher, so when no `folder id` is provided in the post data (which is the case of selecting `No folder`) we don't update it. Might be a simple fix (I did something similar in the move handler) but first need to check if it won't affect some other functionality.

**Comment by dani-garcia** [comment]
Thanks, I didn't notice that!
It should be fixed now with e6b6d7f
