### ISSUE TITLE
security against memory attacks?

### ISSUE THREAD

**Issue by pdarcos** [dani-garcia/bitwarden_rs#408]
Hi everyone,

Great project.

Has anyone read the latest report regarding password managers all being vulnerable to reading password in memory? https://www.forbes.com/sites/kateoflahertyuk/2019/02/20/password-managers-have-a-security-flaw-heres-how-to-avoid-it/

I wonder how bitwarden/bitwarden_rs would fare in this audit. Anyone have any more info?

Cheers

**Comment by mprasil** [comment]
I think this question needs to be asked upstream. We use upstream code for the client side.

Server itself (which is what `bitwarden_rs` does) only handles already encrypted data, so there isn't much to leak.

**Comment by mprasil** [comment]
I'm going to close this, but feel free to reopen if you think this question is still relevant for some reason.

**Comment by dani-garcia** [comment]
To add some extra info, all the clients have an option to auto-lock the vault that should remove the master pass from RAM. Other than that and using 2FA, there is no other solution, really. If an attackere has control of your devices you've already lost.

**Comment by pdarcos** [comment]
@dani-garcia That's what I was thinking too.

Thanks for confirming. I've opened up a ticket in the BW repo about this since it is an upstream client side vulnerability. https://github.com/bitwarden/browser/issues/876

Cheers
