### ISSUE TITLE
Document different docker image options

### ISSUE THREAD

**Issue by robertogerola** [dani-garcia/bitwarden_rs#409]
Hello.
I have a RasbperryPi nad have installed docker with the command :+1: curl -sSL https://get.docker.com | sh

Docker installed : Docker version 18.09.0, build 4d60db4

I installed bitwarden_rs but I get this error in the logs:
{"log":"standard_init_linux.go:207: exec user process caused \"exec format error\"\n","stream":"stderr","time":"2019-02-22T08:03:43.382185872Z"}

And bitwarden_rs contianer doesn't start.
Any idea ?

docker inspect bitwarden  command output :

"Id": "cf05b498f6aac9866619198fe630b7fcd75aed13162350f6f22a35d85f3981bb",
        "Created": "2019-02-22T08:00:03.33774869Z",
        "Path": "/bin/sh",
        "Args": [
            "-c",
            "./bitwarden_rs"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2019-02-22T08:03:43.497816142Z",
            "FinishedAt": "2019-02-22T08:03:43.496852962Z"
        },

Many thanks in advance!

**Comment by mprasil** [comment]
Hi, on raspberry you need to use `mprasil/bitwarden:raspberry` image. Is that the one you're trying to use?

**Comment by robertogerola** [comment]
Many thanks! It works perfectly now.
I followed the instructions in the README and used mprasil/bitwarden:latest

If you could add a note regarding RaspberryPI in the README I think it could be very helpful also to other RPI users.

Many thanks for your wonderful work!

**Comment by mprasil** [comment]
Yeah I think we need to document different image options and link to the wiki from Readme.

**Comment by mprasil** [comment]
I'm actually going to keep this open until we add the missing documentation.

**Comment by mprasil** [comment]
This has been now done [here] (https://github.com/dani-garcia/bitwarden_rs/wiki/Which-Docker-image-to-use).
