### ISSUE TITLE
Support armv6 devices like Pi Zero or first Raspberry Pi

### ISSUE THREAD

**Issue by kennymc-c** [dani-garcia/bitwarden_rs#412]
I'm trying to get Bitwarden_rs running on a Raspebrry Pi Zero W. After starting via Docker-Compose the process aborts with Exit Code 139 and no bitwarden log is created. The Docker log looks like this: 

`
Feb 23 19:34:38 pizza dockerd[2573]: time="2019-02-23T19:34:38+01:00" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/7e16114071bcc98abf42609816b7d949f35329
Feb 23 19:34:41 pizza dockerd[2573]: time="2019-02-23T19:34:41+01:00" level=warning msg="OOM monitoring failed" error="cgroups: memory cgroup not supported on this system"
Feb 23 19:34:42 pizza dockerd[2573]: time="2019-02-23T19:34:42+01:00" level=info msg="shim reaped" id=7e16114071bcc98abf42609816b7d949f35329b9b937ff1bc4848816bdb79c8d
Feb 23 19:34:42 pizza dockerd[2573]: time="2019-02-23T19:34:42.801427746+01:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete
`

Previously it worked fine on a Pi 3. I found a similar issues (#185) where you should use the aarch64 image. On the pi zero however i get the following error message after startup:

`
standard_init_linux.go:190: exec user process caused "exec format error"
`

**Comment by mprasil** [comment]
Can you post output of `docker version`?

**Comment by kennymc-c** [comment]
`
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:42:54 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:38:25 2019
  OS/Arch:          linux/arm
  Experimental:     false
`

**Comment by mprasil** [comment]
And you're using `mprasil/bitwarden:raspberry` image, right?

**Comment by kennymc-c** [comment]
right

**Comment by mprasil** [comment]
I think this is due to the fact, that the image is compiled for armv7hf which won't run on pi zero (and RPi 1?) We use `balenalib/armv7hf-debian:stretch` for the raspberry image, which probably won't run on armv6 device. Maybe we could find some other base image for pi 1/zero and create special image for those devices?

**Comment by kennymc-c** [comment]
That would be great. I had already thought that the image was designed for armv7 and that's why it came to this problem. It's actually a bit irritating if the image is called raspberry and not running on the still current Pi Zero models.

**Comment by mprasil** [comment]
Hi, would you be able to test `bitwardenrs/dev:armv6` image on your pi zero? I tried to build the image for armv6 devices, but don't have HW to test it.

> It's actually a bit irritating if the image is called raspberry

Agree, it's mostly for historical reasons. Back then we only supported amd64 (x86) and armv7hf (raspberry pi 2+) so I went with that. Now we have alpine images, aarch64 and hopefully armv6, it's getting a bit complicated. I'm going to document all the options.

**Comment by kennymc-c** [comment]
With `bitwardenrs/dev:armv6` i get exit code code 127 with `/bin/sh: 1: ./bitwarden_rs: not found`  in log

**Comment by mprasil** [comment]
Can you try pulling the latest dev image `docker pull bitwardenrs/dev:armv6` and try running it again?

**Comment by kennymc-c** [comment]
Seems to be working now :) No errors in log but i've only tested the login page so far.

**Comment by mprasil** [comment]
Thanks for testing. I'll create a PR now and once merged will build official image.

**Comment by mprasil** [comment]
Okay, image is now building. Once done, (will take about an hour) it will be available as `mprasil/bitwarden:armv6`.

**Comment by mprasil** [comment]
If you have a time, once the official image is available, can you please fill in a table at the end of [this document](https://github.com/dani-garcia/bitwarden_rs/wiki/Which-Docker-image-to-use)? I'm trying to collect all the various boards and what images were tested.
