### ISSUE TITLE
100% CPU usage if wrong port is specified in email settings

### ISSUE THREAD

**Issue by rcdailey** [dani-garcia/bitwarden_rs#413]
In the `/admin` page, I set up SMTP Email Settings to use `smtp.gmail.com` with port `465`. With this port, sending invitation emails resulted in the app being hung at this step:

    [lettre::smtp::client][DEBUG] connecting to 173.194.200.108:465

(IP address above was different, but the log was the same)

Apparently the TLS port must be used in this case: `587`. I also noticed 100% CPU usage by `bitwarden_rs` on Linux (Docker) when an invitation email was sent while using port 465. I had to kill the service and restart to stop the issue.

I expect the CPU usage to not be so high in this scenario, and for there to be some timeout or error to handle the bad port case, if possible.

**Comment by dani-garcia** [comment]
By default, the SMTP library we use has a timeout of 60 seconds, so I would expect that using the wrong port would ultimately quit after being unable to connect in a minute.

I have no idea why trying to connect to the wrong port would lead to a higher CPU usage, however.

**Comment by cpshoemake** [comment]
I have just observed the same behavior as @rcdailey running on Unraid (Slackware). I made the exact same error, using port 465 instead of 587. My utilization only spikes to 3/40 threads (7.5%) though. Even after correcting the port, utilization isn't normalized until the container is restarted.

Please let me know if you need any other details.

**Comment by dani-garcia** [comment]
Looking through the lettre code, it's possible that in case of error, the connection is left open. I pushed a change that will explicitly close it every time. Hopefully that helps some.

**Comment by mprasil** [comment]
I think this was resolved. Closing the issue now but feel free to reopen if it's still a problem.
