### ISSUE TITLE
[ERROR] Web vault is not found

### ISSUE THREAD

**Issue by pdarcos** [dani-garcia/bitwarden_rs#417]
I reinstalled my bitwarden_rs and now I can't seem to get it to recognize the web-vault any longer.
I have read https://github.com/dani-garcia/bitwarden_rs/issues/373 and it's a similar issue except I can't figure out why I keep getting the message [ERROR] Web vault is not found. To install it, please follow the steps in https://github.com/dani-garcia/bitwarden_rs/wiki/Building-binary#install-the-web-vault

I downloaded the compiled version from your releases page (version 2.8.0d) and unzipped into a newly created web-vault directory at the root of the server (/root/web-vault). I then tried the command line to enable that web-vault on docker run -v /root/web-vault:/web-vault (as I had done before without problems) and I still get the error message.
I then tried enabling it via -e WEB_VAULT_FOLDER=/root/web-vault and I'm getting the same error.

Probably a lack of sleep but I can't figure out what I'm doing wrong this second time around. It seems that it won't recognize my web-vault folder no matter where I put it or how I invoke it.

Any clues?

Thanks

**Comment by mprasil** [comment]
Are you building your docker image? The provided image comes with Vault built in.

Anyways looking at your `docker run` command, it seems like you need to point the `WEB_VAULT_FOLDER` to `/web-vault` as that's where you mount it inside the container.

**Comment by pdarcos** [comment]
Thanks @mprasil 

Yes I was building my own docker image which is where the problem was.
