### ISSUE TITLE
Import not working with folders

### ISSUE THREAD

**Issue by thomasave** [dani-garcia/bitwarden_rs#42]
When importing a file that contains folders using the Web Vault, I get the following error message:
```
POST /api/ciphers/import application/json; charset=utf-8:
    => Matched: POST /api/ciphers/import
    => Error: Couldn't parse JSON body: Error("missing field `key`", line: 1, column: 602)
    => Outcome: Failure
    => Warning: Responding with 400 Bad Request catcher.
    => Response succeeded.
```
I've attached a simple KeePass 2 (xml) file that causes a problem. (rename to .xml)
[folders.txt](https://github.com/dani-garcia/bitwarden_rs/files/2098031/folders.txt)

**Comment by dani-garcia** [comment]
Thanks! I had forgotten to change a couple of values to uppercase. This should be fixed with the latest commit (0905355)

**Comment by thomasave** [comment]
Thanks, it works now!
Is it sufficient to backup the `data` folder to be able to restore the server?

**Comment by dani-garcia** [comment]
Yeah everything needed is inside that folder. You can delete the `data/icon_cache` folder to save space, though.
