### ISSUE TITLE
Safe export result in empty file

### ISSUE THREAD

**Issue by pharao1234** [dani-garcia/bitwarden_rs#421]
Dear. 

first of all a really great implementation of bitwarden. 
Today I tried to export my passwords (to reconsile), but the csv as well as the json file contain no records. 
Can you please advise or fix. 

/#/tools/export

Excel has 0 KB
Json contains only the folder names (even all passwords are assigned to them) 

(I use the docker build on a synology NAS)

Thanks
pharao

**Comment by mprasil** [comment]
Hi, are you passwords in your own Vault or they are shared in Organization? The organization passwords will only export via Organization interface.

**Comment by pharao1234** [comment]
HI, 

That was a good hint, in organisation I was able to export.

Maybe you can help me out here to gain a better understanding. 
Actually I've imported the data from keepass2 (guess into colleaction of my family  organisatin?), afterwards I assigned them to a folder in "my" vault ?. 

How can you distiguish where the passwords actually reside? 

Thanks
pharao

**Comment by mprasil** [comment]
If they have the "shared" icons besides the password they belong to organization. (any shared passwords do, you no longer own the passwords after sharing them) All other are owned by user directly.

I think we can resolve this now? Seems like you've been able to export the passwords. Feel free to reopen if you still have any issues.
