### ISSUE TITLE
/data directory is exposed

### ISSUE THREAD

**Issue by carlchan** [dani-garcia/bitwarden_rs#424]
Looks like the default rocket config exposes the /data directory, allowing download of the db.sqlite3 password database.  While everything in it is encrypted, that doesn't seem like a good idea.

reproduce via going directly to
https://bitwarden_rs.domain/data/db.sqlite3

**Comment by mprasil** [comment]
There must be something else at play here. `bitwarden_rs` serves static files from `web-vault` sub-directory by default. I can't reproduce the issue personally, can you maybe provide some steps to reproduce?

**Comment by carlchan** [comment]
Hmm.  I just have a mostly default config, with web-vault enabled (instaleld using pre-compiled version)

here's the relevant log from cargo:
> [2019-03-06 11:36:53][rocket::rocket][INFO] GET /data/db.sqlite3:
> [2019-03-06 11:36:53][_][INFO] Matched: GET /<p..> [10] (web_files)
> [2019-03-06 11:36:53][_][INFO] Outcome: Success
> [2019-03-06 11:36:53][_][INFO] Response succeeded.

**Comment by mprasil** [comment]
This is what I get when trying the same:

```
[2019-03-06 16:40:52][rocket::rocket][INFO] GET /data/db.sqlite3 text/html:
[2019-03-06 16:40:52][_][INFO] Matched: GET /<p..> [10] (web_files)
[2019-03-06 16:40:52][_][ERROR] Response was a non-`Responder` `Err`: Os { code: 2, kind: NotFound, message: "No such file or directory" }.
```

Do you have your data folder somewhere inside your `web-vault` folder by any chance?

**Comment by carlchan** [comment]
huh.  you're right!  how did that get there??

Yes that would be it, sorry, thank you.
