### ISSUE TITLE
question - how do we change the name given to the token in authy?

### ISSUE THREAD

**Issue by pdarcos** [dani-garcia/bitwarden_rs#426]
When I use authy with 2FA it shows the name of the account as Bitwarden.

Where is this located in the code so I can change it?

Thanks

**Comment by dani-garcia** [comment]
It's hardcoded into the web vault, [here](https://github.com/bitwarden/web/blob/2b6ce14a32e2aadd54cc6d1800f2dec37f151d84/src/app/settings/two-factor-authenticator.component.ts#L85). As it is we can't do much about it.

**Comment by pdarcos** [comment]
Hmm, couldn't we just change that line and on the next where it states "&issuer=Bitwarden"?

Or am I forgetting something?

**Comment by mprasil** [comment]
You are forgetting, that this file is statically served, so any change there would also be static. So it would have to be build-time change.

**Comment by pdarcos** [comment]
Got it. But if we compile the web-vault ourselves with those changes it should work, right?

**Comment by mprasil** [comment]
Yes it will work.

**Comment by pdarcos** [comment]
OK, I'm going to venture into this to see if it works.

I git cloned https://github.com/bitwarden/web.git

Then I started following your instructions here https://github.com/dani-garcia/bitwarden_rs/wiki/Building-binary

I cd into web folder and then I downloaded your v2.8.0.patch and tried to apply it as instructed in the wiki

git apply v2.8.0.patch
error: unrecognized input

I must be missing something. Any ideas?

Thanks

**Comment by dani-garcia** [comment]
Hmm, no idea why that could be happening. Can you chech that the downloaded patch file has the correct encoding and lend of line characters? The copy of the patches I have locally are utf8 and use linux-style line feeds.

**Comment by mprasil** [comment]
@pdarcos I think much easier approach would be to grab the [pre-built Vault](https://github.com/dani-garcia/bw_web_builds/releases/tag/v2.9.0-pre1) and just do your changes there.

**Comment by pdarcos** [comment]
Thanks @mprasil 
I'm going to try that approach since it is indeed much easier. But if it is already pre-built will I still be able to change the strings [here](https://github.com/bitwarden/web/blob/2b6ce14a32e2aadd54cc6d1800f2dec37f151d84/src/app/settings/two-factor-authenticator.component.ts#L85) ?

**Comment by mprasil** [comment]
I think it should still be possible. At the end of the day it's just a bunch of javascript files and the string has to be somewhere there.

**Comment by dani-garcia** [comment]
Editing the already built vault is not the cleanest way, because the code is already minified, but for a small change like this it should be ok.

You'll need to edit the `main.js` file, I think. You can use search and replace for the `&issuer=Bitwarden` and `otpauth://totp/Bitwarden:` strings.

**Comment by pdarcos** [comment]
Thanks guys. Found it in main.js indeed. Gonna change it and see how it works out

**Comment by pdarcos** [comment]
To give feedback.

I ended up applying the patch (there was a typo when I copy/pasted the patch file that I fixed) and building the web-vault from scratch as per your wiki.

now it's built and working fine. The token no longer shows up as bitwarden :)  Now if only I could figure out how to add an icon to the entry like cloudflare has (the original bitwarden also has no icon).

**Comment by dani-garcia** [comment]
That depends on the OTP client, in this case Authy. If they don't let you configure it manually, it means they jsust keep an internal list of some popular options, so there isn't much you can do.

**Comment by pdarcos** [comment]
Yeah, that makes total sense.
Thanks for the help guys.

Closing this now
