### ISSUE TITLE
Support POST to /api/accounts/profile

### ISSUE THREAD

**Issue by DrMurx** [dani-garcia/bitwarden_rs#43]
The be compatible with the Bitwarden API, the endpoint `/api/accounts/profile` should also support POST requests to update your own full name.

**Comment by mprasil** [comment]
Valut posts data in following format:
```
{"name":"User Name","masterPasswordHint":null,"culture":"en-US"}
```

The masterPasswordHint should probably be parsed as Option as it might contain the hint string.

**Comment by dani-garcia** [comment]
I've implemented this now.
I also implemented email address change, which on the upstream server requires inputting a token sent to the new address. As we don't do email validation, I ignore any values to that field, so any value works.
