### ISSUE TITLE
WebSockets endpoints?

### ISSUE THREAD

**Issue by rcdailey** [dani-garcia/bitwarden_rs#430]
Using this guide: https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-WebSocket-notifications

It is stated that the following endpoints must be considered:

* `/notifications/hub`
* `/notifications/hub/negotiate`

However, while I do not remember where I got it, I also am mapping `/api/websocket`. Is this a valid endpoint in the latest version? Or is this incorrect / outdated?

**Comment by dani-garcia** [comment]
I don't think we ever had that endpoint, no. Just the two that you list first. They are also the same that the official server uses, so I don't know where that one could have come from. You should be able to delete it without problems.

**Comment by rcdailey** [comment]
Thank you!
