### ISSUE TITLE
Data Breach Report throws error if account not breached/404 is returned

### ISSUE THREAD

**Issue by domainzero** [dani-garcia/bitwarden_rs#433]
Running the Data Breach Report on an account that has no breaches listed returns an error in the UI instead of a "No breaches found" error. According to the logs, a 404 is returned from the API. This looks like it's probably a web vault issue, but I'm not sure if this problem exists upstream.

Here's a snippet from `docker logs`:
```
[2019-03-13 20:52:32][reqwest::async_impl::response][DEBUG] Response: '404 Not Found' for https://haveibeenpwned.com/api/v2/breachedaccount/<REDACTED>
[2019-03-13 20:52:32][tokio_reactor][DEBUG] dropping I/O source: 0
[2019-03-13 20:52:32][bitwarden_rs::error][ERROR] ReqError.
[CAUSE] Error {
    kind: ClientError(
        404
    ),
    url: Some(
        "https://haveibeenpwned.com/api/v2/breachedaccount/<REDACTED>"
    )
}
```

**Comment by dani-garcia** [comment]
Thanks for bringing this up, when HIBP doesn't find a breach it returns a 404, which we treat as an error and return a generic 400. I've changed it to return a 404 correctly in the latest commit and I've tested that it now works correctly. (https://github.com/dani-garcia/bitwarden_rs/commit/61515160a7688fa4ba2b7a7c5ddea3df2a1c1611)
