### ISSUE TITLE
Password Reset Function

### ISSUE THREAD

**Issue by romrayster** [dani-garcia/bitwarden_rs#434]
Hello,
how do I enable resetting passwords? 
https://domain.tld/#/recover-delete
it throws an error. As well I cannot reset passwords of users from the admin panel.
Thank you!

**Comment by mprasil** [comment]
What are you trying to do? You can't really change user's password as all users passwords are encrypted with a key derived from the password, so they'd lose those.

As for "Recover and Delete" functionality, I think this hasn't been implemented yet. However in the admin panel you can essentially do the same - just delete user and let them create new account with the same email.

**Comment by mprasil** [comment]
I've added "Implement Recover and Delete" feature request to our meta issue #246, to enable user self-service account deletion. In the meantime the described workaround via admin interface should help.

**Comment by romrayster** [comment]
Hello,

thank you for your reply. One of my employees forgot his bitwarden 
password, I was just wondering if we could reset it without losing the 
data. If that's not possible the issue can be closed.

Thank you for adding the issue to #246.

Regards

**Comment by mprasil** [comment]
Yeah unfortunately due to the nature of the way the encryption work (it's all client-side) it's not possible. If you have the client logged in web vault, you can try exporting their passwords that way and then import them to newly created account. Otherwise it's pretty much lost.
