### ISSUE TITLE
Admin Panel

### ISSUE THREAD

**Issue by daxda** [dani-garcia/bitwarden_rs#435]
Hi! I have a problem with the activation of the admin panel. when I try to give the command I found on the wiki. I get this error:

docker: Error response from daemon: Conflict. The container name "/bitwarden" is already in use by container "9c51e44c50f2bcaf80ebbb7c018caf923e89d2c5735e17f665d5ee6f6ff87da7". You have to remove (or rename) that container to be able to reuse that name.

**Comment by mprasil** [comment]
What docker command tells you back is your issue. You probably ran the container with the same name already - most likely from your previous `docker run` command? You can see all containers (including stopped ones) with `docker ps -a`. 

You can remove stopped container with `docker rm <container_name>`.

I assume you're following the wiki. It doesn't say that explicitly, but you cannot change running container settings just by re-running `docker run` command with different parameters. You need to stop previous container, `rm` it if you want to keep the same name and start again with new parameters. Hope that helps.

**Comment by mprasil** [comment]
I'm going to close this as I think the question was answered, but feel free to reopen if you have more questions regarding this.
