### ISSUE TITLE
Unable to upload attachments

### ISSUE THREAD

**Issue by LeCodeCo** [dani-garcia/bitwarden_rs#439]
I'm having issues trying to upload attachments to an item.

When trying to get an attachment, I get the following error in my browser console.
`POST https://*vault.example.com*/api/ciphers/*string*/attachment 413`

![](https://file.properties/host/raw/RizHPKXl.png)

**Comment by dani-garcia** [comment]
Do you get any errors in the log? Is the server behind a proxy that could be modifying the requests in some way?

**Comment by BlackDex** [comment]
Also, please check if the proxy has some kind of upload limitation.
Nginx for instances has some lower values by default. I don't know how this is also the case with other proxy tools.

**Comment by LeCodeCo** [comment]
Bitwarden_rs is behind an Nginx reverse proxy and no error appears in the server log. I'll take a look at my Nginx configuration.

**Comment by mprasil** [comment]
`413`is usually a response for too big requests. How big is the attachment you're trying to upload?

**Comment by LeCodeCo** [comment]
Was Nginx side. Just had to set the maximum upload side in my config. Thanks!
