### ISSUE TITLE
WebSocket notifications and attachments

### ISSUE THREAD

**Issue by CyBiS** [dani-garcia/bitwarden_rs#447]
Hi,

I've set up the WebSocket notifications accoring to the [wiki page](https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-WebSocket-notifications) and the instant sync between web vault, dekstop applications and browser extensions basically works. So when creating new entries or modifying existing ones, all the clients (except of mobile clients due to the missing push notification feature) get updated. However, when adding attachments to an entry (a secure note for instance) the entry doesn't get updated. A manual sync on all clients is necessary.

Is this the expected behaviour?

BR CyBiS

**Comment by dani-garcia** [comment]
Uploading attachments should send a notification to the other clients that the entry was updated, same as updating the entry fields itself would do. I'll have to check if I can reproduce this and what might be causing it.

**Comment by CyBiS** [comment]
I repeated the test and it seems that the sync is not working only when the attachment is added in via the web vault.

When adding attachments via the desktop app or the browser extension, it works as expected, i.e. all clients are synced automatically and show the attachment immediately.

**Comment by CyBiS** [comment]
Is this bug specific to the `bitwarden_rs` implementation or is it also an issue in the original implementation?

**Comment by CyBiS** [comment]
Issue not observed anymore with latest release (v1.9.1-fff72889).
