### ISSUE TITLE
Error on binary build

### ISSUE THREAD

**Issue by Cerothen** [dani-garcia/bitwarden_rs#448]
I am receiving an error when trying to build the binary for bitwarden_rs, I can't seem to figure out how to resolve it though since I am not familiar with compiling rust applications. Any assistance would be great.

`cargo build --release`

```
   Compiling bitwarden_rs v1.0.0 (/opt/bitwarden_rs)
1error[E0433]: failed to resolve: use of undeclared type or module `syslog`
   --> src/main.rs:107:22
    |
107 |     let syslog_fmt = syslog::Formatter3164 {
    |                      ^^^^^^ use of undeclared type or module `syslog`

error[E0433]: failed to resolve: use of undeclared type or module `syslog`
   --> src/main.rs:108:19
    |
108 |         facility: syslog::Facility::LOG_USER,
    |                   ^^^^^^ use of undeclared type or module `syslog`

error[E0433]: failed to resolve: use of undeclared type or module `syslog`
   --> src/main.rs:114:11
    |
114 |     match syslog::unix(syslog_fmt) {
    |           ^^^^^^ use of undeclared type or module `syslog`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0433`.
error: Could not compile `bitwarden_rs`.

To learn more, run the command again with --verbose.
```

**Comment by dani-garcia** [comment]
Oops, I forgot to make syslog a required dependency with the [latest commit](https://github.com/dani-garcia/bitwarden_rs/commit/3bb46ce496d42d3a55f61cecc65888cc4b5a12cb).

I pushed a new commit that should fix this, if you can you should update to that. Otherwise, it should work with your current version if you compile with `cargo build --release --all-features`.

**Comment by Cerothen** [comment]
Can confirm that pulling the changes and trying to compile again resolves the issue.

Thanks!
