### ISSUE TITLE
Add unofficial note to readme

### ISSUE THREAD

**Issue by kspearrin** [dani-garcia/bitwarden_rs#45]
Hi,
Nice project. Could you please add a note to the README that this is an _unofficial_ community developed project? I don't want people to get confused that this is some officially sanctioned version of Bitwarden.

A small note at the top similar to this this would be fine:
https://github.com/jcs/bitwarden-ruby/blob/master/README.md

Thanks.

**Comment by dani-garcia** [comment]
Hi, sorry about that! When I initially created this proyect I didn't expect anyone other than myself to use it, so the old README was basically a bunch of notes to myself so I wouldn't forget how to run the proyect.

I added a note as you suggested, if you think there is any other change I should make, please let me know!

PD: Thank you for creating Bitwarden!
