### ISSUE TITLE
HTTP 500 on api/organization

### ISSUE THREAD

**Issue by PeterHasitschka** [dani-garcia/bitwarden_rs#450]
Hey guys!

Just set up the container on my raspberry using `mprasil/bitwarden:raspberry`.
Works fine so far (Congrats on the fantastic work btw), unless managing my subscriptions on my organization.
On the web interface the API responses a 500. The log file returns the following message:
```[2019-04-10 08:54:19][rocket::rocket][INFO] GET /api/organizations/f7f3bc6c-c2ff-4160-b0e8-8268635e5cc5/subscription application/json:
[2019-04-10 08:54:19][_][INFO] Matched: GET /<p..> [10] (web_files)
[2019-04-10 08:54:19][_][ERROR] Response was a non-`Responder` `Err`: Os { code: 2, kind: NotFound, message: "No such file or directory" }.
[2019-04-10 08:54:19][_][INFO] Outcome: Failure
[2019-04-10 08:54:19][_][WARN] Responding with 500 Internal Server Error catcher.
[2019-04-10 08:54:19][_][INFO] Response succeeded.
```

Sytem used:

- Raspberry 3, raspbian / Debian 9.8
- Docker 18.09.0
- Let's Encrypt cert
- Not default Port for HTTPS on public endpoint

My docker-compose

```version: '3'
services:
  bitwarden:
    image: mprasil/bitwarden:raspberry
    restart: always
    volumes:
        - ./bw-data/:/data/
        - ./certs/:/ssl/
    environment:
      LOG_FILE: "/data/bitwarden.log"
      SIGNUPS_ALLOWED: "true"
      ROCKET_TLS: '{certs="/ssl/cert.pem", key="/ssl/cert.key"}'
    ports:
      - 443:80
```

Got any idea what could cause that error?
Best,
Peter

**Comment by mprasil** [comment]
So you're trying to create organization if I understand you right? I presume you're using web Vault to do that? Are there any extra steps to reproduce this?

**Comment by RomanHargrave** [comment]
It could be org management. In my experience creating organizations works correctly, but tasks like inviting users can be troublesome.

**Comment by mprasil** [comment]
Well I'm not sure what would generate a `GET` call on `/api/organization` so that's why I'm asking. I'd expect `POST` there.

@RomanHargrave can you maybe provide some steps to reproduce these issues? It should work just fine.

**Comment by PeterHasitschka** [comment]
Hi @mprasil!

I've already created an organization, selected the free-version - all via web-interface and another person. Worked fine so far.
The error occurs whenever i want to switch to the subscriptions-tab inside the organization settings
![image](https://user-images.githubusercontent.com/7084114/55909241-c4d88380-5bdb-11e9-8beb-3239f68accde.png)

![image](https://user-images.githubusercontent.com/7084114/55909306-ef2a4100-5bdb-11e9-93cc-752668db38ba.png)

Hope that helps!

**Comment by mprasil** [comment]
Ah that makes sense. This wasn't implemented as there is no paywall in bitwarden_rs. So it doesn't work but you don't need it for premium features anyways.

**Comment by mprasil** [comment]
I'm going to close this as I believe the question was answered, but feel free to reopen if more information is needed.

@RomanHargrave this issue is about functionality that isn't implemented, yours sounds unrelated. If you can get some steps to reproduce your problem or you want some help getting that sort of info to troubleshoot your installation, please open new issue.
