### ISSUE TITLE
Android which APK to choose?

### ISSUE THREAD

**Issue by jonathanmmm** [dani-garcia/bitwarden_rs#451]
Hi,

Android Google Play Store vs F-Droid version.
I wanted to ask as there is no push working right now is there anything missing then that it is not updating?
The Google Play Store also has most of analytics disabled right? Maybe this is netter suited in the Main repo of Kyle?

**Comment by fbartels** [comment]
> Maybe this is netter suited in the Main repo of Kyle?

Probably

>  there is no push working right now

This is indeed a limitation of this project

**Comment by mprasil** [comment]
I think the only difference between these two is that f-droid version doesn't have google services enabled and thus no push notification, but that won't work either way right now. The analytics were completely removed some time ago as far as I know.

**Comment by jonathanmmm** [comment]
https://github.com/bitwarden/mobile/issues/478

I have asked here.
Wanted opinion from people using the fork.

**Comment by mprasil** [comment]
I think that also answers the question here. Thanks for linking that @jonathanmmm. Closing this now.
