### ISSUE TITLE
Systemd-docker how to Install?

### ISSUE THREAD

**Issue by jonathanmmm** [dani-garcia/bitwarden_rs#452]
Hi,
I followed the Guide in
https://github.com/dani-garcia/bitwarden_rs/wiki/Running-with-systemd-docker
An it worked in Ubuntu 18.04 LTS (I beliebte) but in Debian 9 (Stretch) the package "systemd-docker" does not exists. Not even when googling it?

I found https://container-solutions.com/running-docker-containers-with-systemd/

It explains another way.
Is there a good and stable way to Install the package to Debian or is there Somebody writing the Wiki for Debian? Most Rapsberry Pis will Run rasbian (Debian Version) and many other systems, too.

I am glad to Help and try Scripts on my Test system.

**Comment by mprasil** [comment]
I'd suggest asking at the [project repo](https://github.com/ibuildthecloud/systemd-docker), we do not manage that software. Hope that makes sense. Feel free to reopen if there's something we can help you with regarding that.
