### ISSUE TITLE
Server Admin should see all organizations

### ISSUE THREAD

**Issue by cdwiegand** [dani-garcia/bitwarden_rs#454]
An admin user just created an organization, but I (as server owner/admin) cannot see the organization unless I'm invited to it. Shouldn't I, as the owner/admin, see all organizations? Even if it's a separate link on a page where I can audit the company settings and/or invite myself?

**Comment by dani-garcia** [comment]
What do you mean by server owner? Each organization would have it's own separate owner, but there isn't a global server owner.

You can see a list of all users and all the organizations they are a part of in the admin page, there are instructions in the wiki on how to enable it.

I'm not sure what do you mean exactly by auditing settings, but it's not possible to invite yourself to an organization and see it's data without help from a member of it, as the data is all encrypted and we'd need to add the decryption keys to the new user.

**Comment by cdwiegand** [comment]
Ok, I will look through the wiki on how to enable that functionality. As the owner of the physical server, I want to be able to ensure that I'm aware if there's a new "organization" created by one of my users. If I can see a list of those, then that's good enough for me.
