### ISSUE TITLE
License Application

### ISSUE THREAD

**Issue by jimphreak** [dani-garcia/bitwarden_rs#462]
Is it possible to apply an organization license to this self hosted instance?  I'd like to be able to create and share a collection or two between two users.

**Comment by mprasil** [comment]
There is no licence required. Create free organization and it will be unlimited. Hope that helps.

**Comment by jimphreak** [comment]
How does one share the organization with another user though?  If I do invite user from the self hosted instance they never receive an email.

**Comment by mprasil** [comment]
Did you [configure SMTP](https://github.com/dani-garcia/bitwarden_rs/wiki/SMTP-configuration)?

**Comment by jimphreak** [comment]
Nope.  Sorry I had followed another guide that did not make any mention of smtp.  Thank you for the link.

**Comment by mprasil** [comment]
If you don't want to use email, you can leave that as it is and users that are invited automatically accept the invitation basically. So you just invite them and then straight away confirm the accepted invitation.

**Comment by jimphreak** [comment]
Perfect.  Thank you.

**Comment by mprasil** [comment]
👍
