### ISSUE TITLE
System limits / when to move ?

### ISSUE THREAD

**Issue by mickaelperrin** [dani-garcia/bitwarden_rs#464]
Hi,

Newcomer to Bitwarden, I started migrating my LastPass vault to Bitwarden.

However, after migrating around 1300 entries, my Bitwarden vault became unavailable on any client: web / mac app / browser and even cli.

If I correctly understand, this project was created to overcome native Bitwarden limits in terms of performance, but:

- what is considered as a large database needing this project ?
- what are the limits of this project ? How many entries could we have without clients become slow ? unusable ?

Thanks,

**Comment by dani-garcia** [comment]
I personally only ever tested with up to 300 items or so, which is how many I have.
Do you get any specific errors, either in the clients themselves or the server console? Or does it get stuck loading?

**Comment by mickaelperrin** [comment]
It stucks at loading/syncing sadly :(

**Comment by mprasil** [comment]
I think you might be hitting some other issue or limit other than number of passwords. I've just tried to generate test csv file and imported 3000 passwords and all works well. The sync call (`/api/sync`) took about 300ms and generated about 3.1MB response on my not so beefy desktop, which is still very usable.

**Comment by RomanHargrave** [comment]
I don't know about the SaaS or .NET self hosted versions, but I have an extremely large password database which i have not had any issues with.

**Comment by mickaelperrin** [comment]
@RomanHargrave According to the SaaS support, I have too much data in my vault. This is not related to the number of entries but to the data size. I included around 100 SSH keys and 1000 Login data. That's too much for the SaaS service which times out before  finishing to decrypt the vault content.

I finally left over and moved to another commercial password manager :(

At all, thanks for your feedbacks.

**Comment by mprasil** [comment]
Ah, that makes sense in a way. I guess the best option would be to have the ssh keys as attachment, this way they are only decrypted when you try to access them. Might not be as convenient though. Thanks for update @mickaelperrin

**Comment by mickaelperrin** [comment]
Yeah, that's definitely the way to do with Bitwarden Saas, and I think this is the official way to do it also. But it requires more api call to manage and I didn't want to complexify my SSH key management scripts. 

Others considerations exposed by coworkers mainly regarding the UI have also been taken in account to finally decide to left over.
