### ISSUE TITLE
Any ETA on upgrading Web Vault to 2.10.0?

### ISSUE THREAD

**Issue by dustindauncey** [dani-garcia/bitwarden_rs#467]
Hello,

Was just curious is there was any ETA on issuing a recent release of Bitwarden_RS using the latest Bitwarden Web Vault version 2.10.0. Right now it seems the latest in Bitwarden_RS is 2.9.0. As somebody with a relatively large vault (about 600 items, not sure if that's really considered "large" or not), I think people like myself will benefit from the update to web vault 2.10.0 which had a release note stating "Page item listing for better performance on large vaults".

**Comment by mprasil** [comment]
Hi @dustindauncey the `mprasil/bitwarden` image does have `2.10.0` version of Vault bundled in. Are you sure you're really using the latest version of the image?

**Comment by dustindauncey** [comment]
I am running 1.8.0-alpine and it contains 2.9.0 web vault. I prefer to generally stick to versioned tags rather than using "latest" tag for production stability reasons.

**Comment by dustindauncey** [comment]
The latest release from this repository is 1.8.0 as well.

**Comment by dani-garcia** [comment]
I'll probably get a new release going this weekend now that the new Duo integration is working fine.

**Comment by dani-garcia** [comment]
The new release is published now, the images will be built in a couple of hours.
