### ISSUE TITLE
Missing Logo on Logon Page

### ISSUE THREAD

**Issue by Runear** [dani-garcia/bitwarden_rs#471]
My watchtower instance had a fit today and left my docker host in a weird state.

A reboot seemed to fix most of it however now my Bitwarden logon screen doesn't have a logo and I don't know if its due to the new image that triggered the watchtower update or something on my end. I had a look at the latest commits and they seem to be messing with exactly whats broken for me so am assuming its an image issue. Happy to help if you need anything.

Opening the logo in a new window gives me the below:

`{"ErrorModel":{"Message":"Image not found","Object":"error"},"Message":"","Object":"error","ValidationErrors":{"":["Image not found"]},"error":"","error_description":""}`

In the logs I get:

```
[2019-05-02 09:28:12][rocket::rocket][INFO] GET /images/logo-dark@2x.png image/webp:
[2019-05-02 09:28:12][_][INFO] Matched: GET /images/<filename> (images)
[2019-05-02 09:28:12][bitwarden_rs::error][ERROR] Image not found. Image not found
```

Is this something on my end? I tried deleting the image and pulling a clean one and I'm still getting the problem.

**Comment by Runear** [comment]
Have just found that the logo file was changes 2 days ago, but can't find where my install is pulling logo-dark from when it looks like its been logo-gray for a long time.

Any help is appreciated. Will keep digging though.

**Comment by dani-garcia** [comment]
This was caused by a conflicting route in the latest PR, we were using the same route for the email images than the web vault and the first was overriding the second.

I changed the routes yesterday to solve the conflicts, so try to update your current image to the latest version (Not sure if the docker images are updated already).

**Comment by Runear** [comment]
Right! They mustn't be, I tried pulling both a new "latest" and "alpine" image and neither worked... Will wait for the new one to appear, thanks!

**Comment by mprasil** [comment]
They are just building. The latest image should be ready in about an hour.
