### ISSUE TITLE
aarch64 docker image cannot register user

### ISSUE THREAD

**Issue by 5high** [dani-garcia/bitwarden_rs#472]
When complet run bitwarden_rs open web portal regist user , fill all of information click ok , but nothing happend , the page no error and no success information give to me.

anyone can help me ?

**Comment by mprasil** [comment]
HI, this is very likely because you're using chrome, but don't have https enabled. See the note in [Readme](https://github.com/dani-garcia/bitwarden_rs#installation). Try using other browser or set up https.

I'm going to resolve this, but feel free to reopen if that didn't solve your issue.
