### ISSUE TITLE
Item deletion not working properly

### ISSUE THREAD

**Issue by xNevo** [dani-garcia/bitwarden_rs#478]
I can no longer delete any of my items, regardless of their type. When I try click "Delete" in the edit menu or in the context menu nothing happens.

I don't see any errors in the server console, but I see one in the dev tools:

```
Error: Failed to start the connection: Error: Unable to initialize any of the available transports.
e.log @ vendor.5d89a1c78e2fbd6f2ec5.js:133
```

**Comment by dani-garcia** [comment]
Not sure what could be happening, the error is expected if you haven't configured websockets.

I imagine you are using the web vault, can you try another client?

When deleting an item you should see a request like this in the console:
```
[2019-05-11 22:03:27][rocket::rocket][INFO] DELETE /api/ciphers/b882af92-c342-4210-aada-fed39ab85ad8:
[2019-05-11 22:03:27][_][INFO] Matched: DELETE /api/ciphers/<uuid> (delete_cipher)
[2019-05-11 22:03:27][_][INFO] Outcome: Success
[2019-05-11 22:03:27][_][INFO] Response succeeded.
```

**Comment by xNevo** [comment]
I dont see any requests when using the web vault, but it works fine when I'm using the browser plugin

**Comment by xNevo** [comment]
Pretty sure the vault was on my side
