### ISSUE TITLE
Bitwarden intall to Centos 7 

### ISSUE THREAD

**Issue by seigne-m** [dani-garcia/bitwarden_rs#479]
Hello I would like to know if the project is possible to install on centos 7 and if yes what would be the modifications to make the project functional

**Comment by mprasil** [comment]
Typically users use docker to deploy it, if that's something that would work for you, all you need to do is install Docker and then follow the usual installation.

If you want to build and install it directly, you can follow the [build instructions](https://github.com/dani-garcia/bitwarden_rs/wiki/Building-binary), there shouldn't be anything special about CentOS 7 - it's recent enough distribution.

**Comment by mprasil** [comment]
Hi @seigne-m it was couple days since the question and I think your question has been answered, so I'm going to close this, but feel free to reopen or create new issue if any related question pops up.

**Comment by seigne-m** [comment]
thank you very much for your responsiveness,I have just one last question,  I would like to know if your papal make to external services and if so rotten and you list them where I gave a method to list them. Tanks you

**Comment by seigne-m** [comment]
thank you very much @mprasil  for your responsiveness,I have just one last question, I would like to know if your papal make to external services and if so rotten and you list them where I gave a method to list them. Tanks you
