### ISSUE TITLE
ability to add a premium license? 

### ISSUE THREAD

**Issue by pageb018** [dani-garcia/bitwarden_rs#48]
Is this possible? When I go to the page to add, it just sits at loading....

**Comment by mprasil** [comment]
I don't think you need to do that. What premium feature are you missing?

**Comment by dani-garcia** [comment]
As @mprasil said, this proyect should implement all premium features, so there is no use for the billing page.
If something asks for premium, that's a bug and I would appreciate that you report it.

Maybe we should implement the ` /api/accounts/billing` endpoint and return and error message, so it doesn't lead to confusion.

**Comment by pageb018** [comment]
Gotcha. I had paid for the premium version and a family organization in the full install, but would like to migrate. Just making sure I wasn’t missing anything. Thanks for a great project! 
		
		

		Brian, from mobile.
	




On Sun, Jul 1, 2018 at 8:52 AM -0400, "Daniel García" <notifications@github.com> wrote:












As @mprasil said, this proyect should implement all premium features, so there is no use for the billing page.

If something asks for premium, that's a bug and I would appreciate that you report it.


Maybe we should implement the /api/accounts/billing endpoint and return and error message, so it doesn't lead to confusion.
