### ISSUE TITLE
I can't get ssl working on my raspberry pi

### ISSUE THREAD

**Issue by lerker100** [dani-garcia/bitwarden_rs#480]
I got bitwarden up and running without ssl but as soon as I try to enable ssl the container won't even start up.
This is the command I'm using.  
`docker run -d --name bitwarden   -e ROCKET_TLS='{certs="/ssl/certs.pem",key="/ssl/key.pem"}'   -v /ssl/keys/:/ssl/   -v /bw-data/:/data/   -p 443:80   mprasil/bitwarden:raspberry`
I generated the ssl key files and they are in /ssl/keys on the host file system. the files are named the same as in the command. If anyone has a fix I would greatly appreciate it.

`Docker version 18.09.0, build 4d60db4`

**Comment by dani-garcia** [comment]
Any errors on the logs?

**Comment by lerker100** [comment]
I don't know I've never used docker. The reason that I was trying this was I had locked my self out of my bitwarden account with 2fa but I was able to get back in. I will try this again when I have a spare pi again. If I have the same error I can post the logs here if you want? I've already wiped the sdcard that had the logs on it.

**Comment by mprasil** [comment]
Your command sounds correct. When you decide to give it another go, you can use `docker logs` to see log output.

**Comment by mprasil** [comment]
I'm going to close this, hopefully @lerker100 managed to solve the problem as there's no response. Feel free to reopen if it's still not working.
