### ISSUE TITLE
Regex Blacklist Icon Cache Improvement

### ISSUE THREAD

**Issue by jonathanmmm** [dani-garcia/bitwarden_rs#481]
Hi,

I would suggest to improve the default icon blacklist regex (if there is a default).

Version 1:
Disable icons for all private IP addresses (either IPv4 and maybe IPv6?!) not just 192.168.1.x also 192.168.x.x, 10.x.x.x and 172.x.x.x (or what the third was for Ipv4) also 127.x.x.x

Version 2:
Try to fetch the icon as the server directly from the IPs, problem: the server maybe in a different Environment than the local IPs or if the client asks for them he would potentially ask private IP addresses for Icons in all networks he is connected to.

**Comment by dani-garcia** [comment]
At the moment the blacklist is disabled by default, and I'm not sure providing a default is necessarily a good idea, we should probably have a Wiki entry with some examples and explanations though.

In any case, if someone is paranoid enough that revealing the pressence of a server in the internal network is a real issue, I would recommend them to isolate or firewall the bitwarden_rs server in the first place.

**Comment by jonathanmmm** [comment]
@dani-garcia

Ok, I understanf
Would it be possible if the Ip address is private to use the Ip plus port so that the icons get cached by the server. E.g. a router has also a smybol or any other webservice.

Because right know they don't have one, e.g. my router because you can't reach this services from outside you can't fetch the icons as the "bitwarden.com icon server" and reply it back to the bitwarden_rs icon cache.

Or is it possible to custom the icons without switching the TTL of? Because not internal icons should still be updated.

**Comment by jonathanmmm** [comment]
@dani-garcia 

Hi Dani-Garcia

I found out that I get icons from my router or my wd cloud storage.
Does the server gets these icons directly from within the network?
Because the bitwarden.com icon server can't know which icon is needed by http://192.168.2.4 for example.

**Comment by mprasil** [comment]
@jonathanmmm currently the icons are fetched directly from the server. (client sends request to server to get the icon, server will fetch it and cache it server-side) It will try to parse html to gather some possible sources of icons and then goes with the most optimal size. So yeah, if you host your server locally (or if it has route to your network) it should be able to load the favicon.

**Comment by BlackDex** [comment]
@jonathanmmm regarding the ip+port part. That doesn't seem to be possible as far as i know. Since only the host is given without any path or port. Not even if it is https or http.

**Comment by mprasil** [comment]
I believe this was implemented and by default `bitwarden_rs` does not fetch icons from IPs in the private IP range.
