### ISSUE TITLE
Bitwarden_rs use External services ?

### ISSUE THREAD

**Issue by seigne-m** [dani-garcia/bitwarden_rs#485]
thank you very much for your responsiveness,I have just one last question, I would like to know if Bitwarden_rs make and use to **external services** and if so rotten and you list them or a method to list them. Thanks you

**Comment by dani-garcia** [comment]
I'm not sure what do you mean exactly, bitwarden_rs by default makes connections to the web servers of the saved URLs to obtain the icons, which can be disabled by setting the environment variable `DISABLE_ICON_DOWNLOAD=true`, or from the admin panel.

The Duo and Yubikey platforms also make calls to external services (to Duo and Yubico servers respectively), but only when enabled and only when a user is trying to log in.

Hope that solves your questions.
