### ISSUE TITLE
Admin does not support running on sub-path

### ISSUE THREAD

**Issue by LaszloHont** [dani-garcia/bitwarden_rs#488]
Could bitwarden_rs use relative URLs?

I don't want the world to know about https://bitwarden.example.com/ so I am using https://secure.example.com/bitwarden/. This is not findable in the SSL observatory logs, and privacy is why I am self-hosting.

I have tried starting bitwarden_rs with DOMAIN=https://secure.example.com/bitwarden/ but when I visit https://secure.example.com/bitwarden/admin/ and submit the token I get a 404 from /admin/

Thanks.

**Comment by dani-garcia** [comment]
Running on a subdomain won't work unless you apply the patches from https://github.com/dani-garcia/bitwarden_rs/issues/241#issuecomment-436376497.

If the reason you are doing it is exclusively privacy, i would recommend using a less obvious subdomain, like just secure.example.com, or issuing a wildcard certificate which might not make the exact subdomain findable in those logs (I'm not sure if that's how it works, so this might not work).

As far as I know there isn't much we can do here, so I'll close this.

**Comment by gerroon** [comment]
@dani-garcia is there any reason why that patch did not make to the trunk? I personally would like to run it under a subfolder as well but I am not a coder and it seems to me that keeping up the patch with the docker updates quite a bit of involvement if you will.

**Comment by dani-garcia** [comment]
Mostly because it requires to hardcode the subfolder directly into the web vault files, which means every person would need to make a specific build for their own subfolder, so we can't distribute a generic version.

**Comment by gerroon** [comment]
I see, that maks sense. I hope this will be somehow possible in the future
