### ISSUE TITLE
安装好后创建用户没有任何反应

### ISSUE THREAD

**Issue by 2060yxz** [dani-garcia/bitwarden_rs#490]

**Comment by 2060yxz** [comment]
在创建账号页面   输入好相关内容后   点提交没有任何反应

**Comment by dani-garcia** [comment]
If you are using Chrome, you might need to configure HTTPS to create the account. Otherwise try another browser (Firefox for example).

**Comment by mprasil** [comment]
To save a click for non-chinese users here's the translation: 

> After creating the account page, enter the relevant content and click Submit. Nothing happens.

As @dani-garcia said, this sounds like typical problem when using Chrome and non-https connection. Using SSL or using Firefox should help.

@2060yxz closing this as I think your question was answered, feel free to reopen if you still experience problems.
