### ISSUE TITLE
Apache reverse proxy documentation incorrect for websockets?

### ISSUE THREAD

**Issue by MarsWarrior** [dani-garcia/bitwarden_rs#491]
According to the wiki, the following Apache rule is used for websockets:

RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /(.*)  ws://my.domain.com:3012/$1 [P,L]

This doesn't work for me: the logon screen is not shown, but a spinner / loading icon.

This one works for me:
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /notifications/hub(.*)  ws://my.domain.com:3012/$1 [P,L]

I have added the notifications/hub path.

**Comment by dani-garcia** [comment]
I don't understand the apache config very well, but I imagine the RewriteCond line would make the rewrite activate only when the Upgrade header is set for websockets, which should only happen for the hub endpoint. This would make both examples equivalent in my mind, but the second one is definitely more specific, can you update the wiki with those changes?

**Comment by MarsWarrior** [comment]
I have updated the wiki with the path change.
