### ISSUE TITLE
After Docker restart the database is Gone.

### ISSUE THREAD

**Issue by SpinB** [dani-garcia/bitwarden_rs#498]
Hello,

I'm running Bitwarden_rs in a windows server with IIS as a reverse proxy, everything works fine but every time i restart docker, puff the database is gone, the first time i run it i used the following commands like described in the wiki:

docker run -d --name bitwarden -e ADMIN_TOKEN=<same token> -v /bw-data/:/data/ -p 911:80 bitwardenrs/server:latest

and every time i start bitwarden i use this command since run doens't work on a container that already have run

docker start bitwarden

Do i need to add any additional commands to avoid this behavior, also how do i force the container to always restart with docker?

**Comment by shauder** [comment]
My guess would be that if you are on Windows then you may need to adjust the path for a proper Windows directory. 

https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c

**Comment by SpinB** [comment]
Thanks, flawless.

How do i make the container also start automatically with docker, sorry but it's the first time using docker.

**Comment by mprasil** [comment]
I suppose this is resolved now.
