### ISSUE TITLE
reverse proxy config with 1.9.1

### ISSUE THREAD

**Issue by pew** [dani-garcia/bitwarden_rs#499]
Hi,

I just upgraded bitwarden from `mprasil/bitwarden:1.9.0-alpine` to `bitwardenrs/server:1.9.1`. Now my reverse proxy can't find the backend anymore. I'm using traefik, it reports `backend not found` in the log files (that's it).

According to the docker-compose logs from bitwarden it's starting just fine:

```
bitwarden_1_a04f97bb9ef5 | [2019-06-03 09:09:55][_][INFO] 1 response: Application Headers
bitwarden_1_a04f97bb9ef5 | [2019-06-03 09:09:55][launch][INFO] Rocket has launched from http://0.0.0.0:80
bitwarden_1_a04f97bb9ef5 | [2019-06-03 09:09:55][ws][INFO] Listening for new connections on 0.0.0.0:3012.
```

Any significant changes between the old and new docker build mechanism? I also tried `bitwardenrs/server:1.9.0-alpine` which **didn't** work either. Reverting back to `mprasil/bitwarden:1.9.0-alpine` worked just fine.

**Comment by MarsWarrior** [comment]
@ home I'm using `bitwardenrs/server:1.9.0` (Version 1.9.0-08a445e2  according to the bitwarden log) behind an Apache reverse proxy. Before that I used  `mprasil/bitwarden:1.9.0`.

Both just work.

Not sure if that is the `-alpine` version you have troubles with.

Did you restart Traefik? I know from our environment @ work, that sometimes Traefik gets confused and we have to restart Traefik in order to have it recognizing all backends.

**Comment by pew** [comment]
Yes I restarted treafik and I did try both, alpine and non alpine.

**Comment by pew** [comment]
@mprasil Yes, I really just replaced the one line with `image: `, pulled it and restarted. I'll try it again later on if time permits or tomorrow.

**Comment by patrick-othmer** [comment]
I run bitwarden behind haproxy and replaced also the image. No problem on our side.

Did you define traefik labels such traefik.frontend.rule / traefik.port? Are both containers still in the same network?

**Comment by pew** [comment]
@patrick-othmer Yes, this is literally the diff of my docker-compose.yml:

```
3c3
<     image: mprasil/bitwarden:1.9.0-alpine
---
>     image: bitwardenrs/server:1.9.1-alpine
```

I'll change it today and report back. Hopefully I was just too impatient with traefik (but I waited a few minutes and even restarted, so I don't think so)

**Comment by pew** [comment]
Well, works now:

```
docker-compose pull
Pulling bitwarden ... done
docker-compose up -d
Recreating bitwarden_bitwarden_1_c8f778e51638 ... done
```

Didn't even take a minute for traefik to recognize it. Just a bad day yesterday? Today is rather a bad day for me.. well, thank you! I'll go ahead and close this one right now since also no one else reports an issue. Thanks again.

**Comment by gerroon** [comment]
> Apache

Do  you mind telling me your apache proxy setup? I cant get it to work. I can open the main page but I get "unexpected error" when I try to login.

**Comment by MarsWarrior** [comment]
You can check that here, https://github.com/dani-garcia/bitwarden_rs/wiki/Proxy-examples.
The main part is:
```
    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /notifications/hub(.*) ws://<SERVER>:3012/$1 [P,L]
    ProxyPass / http://<SERVER>:80/

    ProxyPreserveHost On
    ProxyRequests Off
```

**Comment by gerroon** [comment]
@MarsWarrior thanks that looks good
