### ISSUE TITLE
Web vault doesn't show TOTP codes, just an upgrade button (Organization Issue).

### ISSUE THREAD

**Issue by Ryonez** [dani-garcia/bitwarden_rs#50]
Been testing things out as I get ready to use this, and found that while sharing a password to an organization, it wouldn't show the TOTP code generated by the key.

After further testing:
You can make entries with authenticator key's. Only the code won't show.
The desktop app and the browser extension do show the codes generated.

My assumption is that while the apps do see the organization as a higher tier than free, the web vault doesn't.

**Comment by Ryonez** [comment]
Err... what?
This is a valid issue:
![image](https://user-images.githubusercontent.com/16157130/42135514-13dd6ae2-7da0-11e8-9a94-41c344e5dcec.png)

**Comment by dani-garcia** [comment]
It should be solved in the latest commit, GitHub closed the issue automatically. Sorry for the confusion!

**Comment by Ryonez** [comment]
Ahh, I understand. Thank you.
