### ISSUE TITLE
Invalid Login Error Code

### ISSUE THREAD

**Issue by uchagani** [dani-garcia/bitwarden_rs#502]
Is there a reason bitwarden_rs returns a `400` instead of a `401` or `403` when invalid credentials are entered?

**Comment by mprasil** [comment]
I believe upstream API implementation also returns `400` or is that not the case?

**Comment by uchagani** [comment]
Not sure tbh. I was just trying to use fail2ban at the reverse proxy layer and saw the 400. I just figured a 403 error would be a more accurate error to look for in the logs.

**Comment by mprasil** [comment]
Just checked and upstream does return `400`, so we need to do the same for compatibility reasons.

I'm going to close this now, feel free to reopen if there are any outstanding questions.
