### ISSUE TITLE
search Chinese Character on web interface not work

### ISSUE THREAD

**Issue by kuyagic** [dani-garcia/bitwarden_rs#503]
I'm using the latest docker image and import some password from enpass.
But on web ui I use chinese to search an item but it does not work

**Comment by shauder** [comment]
Do you experience the same when using the official bitwarden web interface? The version here does not use a different version of the web vault.

**Comment by mprasil** [comment]
@kuyagic if you can reproduce the behavior on the official bitwarden web interface, you can report issue [here](https://github.com/bitwarden/web/issues). Just make sure you can actually reproduce it one their service, you can make free account to test.
