### ISSUE TITLE
Fail2ban with docker bridge ip

### ISSUE THREAD

**Issue by snevas** [dani-garcia/bitwarden_rs#505]
I have my docker behind a apache proxy that does 80 > 81 per wiki instructions. When I try to setup fail2ban, I see it tries to ban the docker bridge ip based on this log:
`[2019-06-13 09:26:51][bitwarden_rs::error][ERROR] Username or password is incorrect. Try again. IP: 172.17.0.1. Username:test@test.com.`

**Comment by snevas** [comment]
bitwarder_rs should use the [X-Forwarded-For](http://en.wikipedia.org/wiki/X-Forwarded-For) header to log the original ip.

**Comment by dani-garcia** [comment]
Rocket uses the `X-Real-IP` header when determining the origin IP address, you should configure the proxy to set that one instead of `X-Forwarded-For`.

**Comment by snevas** [comment]
Hi Dani, thanks for all your work on the project. You rock!
I've tested setting the correct header and it works. I've changed the proxy example in the wiki @
https://github.com/dani-garcia/bitwarden_rs/wiki/Proxy-examples
