### ISSUE TITLE
error: cannot find type `Connection` in this scope

### ISSUE THREAD

**Issue by kushwahashiv** [dani-garcia/bitwarden_rs#507]
Environment
VScode: latest
OS: Macbook Pro 64bit

error:
cannot find type `Connection` in this scope
not found in this scope

![image](https://user-images.githubusercontent.com/4386810/59543162-5d320380-8ebe-11e9-8475-0f1e0fdd4c36.png)

is there anything I'm missing above?

**Comment by dani-garcia** [comment]
You need to enable, either the `sqlite` or the `mysql` feature to compile the code.

In vscode, create a `.vscode` folder in the project root and in a `settings.json` file write the following:
```json
{
    "rust.features": ["sqlite"],
}
```

**Comment by kushwahashiv** [comment]
@dani-garcia Thanks for the reply.
I am using `postgres` in `settings.json` as you mentioned above and FYI  I'm using `postgres` instead of `mysql`  and `sqllite` but seems still it can't resolve and gives the same error as above. seems none of features are being picked so it cannot find `connection`.

**Comment by dani-garcia** [comment]
We don't support postgres at the moment, the only options are sqlite or mysql.

**Comment by kushwahashiv** [comment]
Even it does not work for me for both above i.e. sqlite or mysql.

**Comment by dani-garcia** [comment]
Yeah, you need to select either the sqlite or the mysql feature for the code to compile.
When editing from vscode you can use the config option I mentioned before and when using cargo you'll have to append `--features "sqlite"` for the project to build.

You could also edit `cargo.toml` and add `default = ["sqlite"]` directly under the `[features]` key, and that will work for both the editor and cargo.

Note that you can't select both, it has to be either `sqlite` or `mysql`.

**Comment by kushwahashiv** [comment]
Thanks @dani-garcia.  Yes, that works now.
