### ISSUE TITLE
How can I create user?

### ISSUE THREAD

**Issue by lukasmrtvy** [dani-garcia/bitwarden_rs#516]
How can I create user if I am running bitwarden_rs with `SIGNUPS_ALLOWED=false` and
`INVITATIONS_ALLOWED=false` ? 
Should I run it without `SIGNUPS_ALLOWED=false`, create user and then ..with admin panel disable signups?

**Comment by dani-garcia** [comment]
That's probably the way to go yeah. If you leave invitations open, you can also invite yourself from the admin panel, without keeping signups open to everyone.

**Comment by lukasmrtvy** [comment]
@dani-garcia something that:
`BW_EMAIL` and `BW_PASSWORD/BW_GENERATE_PASSWORD` would be superusefull to create initial admin user.
Thanks

**Comment by dani-garcia** [comment]
The problem with that is we would have to implement the password hashing and encryption key creation, which at the moment is entirely done on the client.

Another option to make sure the server is not exposed to the web before being configured is starting it with ROCKET_ADDRESS=localhost, which would only accept connections from the local machine.

**Comment by lukasmrtvy** [comment]
And what about generating some unique URL, which will provide one click registration. ( It can be send to mail, if SMTP vars will be defined, or may be visible in /admin or in log output )

**Comment by dani-garcia** [comment]
It could be a good idea, but it probably requires modifying the clients to allow sending an extra field while registering.
