### ISSUE TITLE
Creating nested subfolders does not work

### ISSUE THREAD

**Issue by gerroon** [dani-garcia/bitwarden_rs#517]
Hi

According to this page subfolders can be creating with slashes but when I do that I do not get subfolders all I get a folder name with slashes, for instance

new folder
`work/teamA` should createa  `work` folder then a `teamA` folder but instead I get a folder named `work/teamA`

Is this implemented or a missing feature?

https://help.bitwarden.com/article/folders/

thanks

**Comment by gerroon** [comment]
Ok it seems like the top folder has to exists this to work.

**Comment by mprasil** [comment]
Yep, that's expected. It's documented in the page you linked:

> If a folder’s name contains the forward slash delimiter, yet no “parent” folder exists, its name will be displayed in its entirety.

I think we can close this? Feel free to reopen if there's more we can help with.
