### ISSUE TITLE
Email invitations not being send

### ISSUE THREAD

**Issue by shd128** [dani-garcia/bitwarden_rs#519]
I'm having some problems when creating new users.
I've send the email invitation but it doesn't seem to work. The emails are never sent and I cant create the users in any other way.
Which logs should I check¿? Does the email server needs to be configured? Now its out of the box per say.

Thanks!

**Comment by XelNika** [comment]
Did you try the SMTP configuration?
https://github.com/dani-garcia/bitwarden_rs/wiki/SMTP-configuration

**Comment by shd128** [comment]
Hi XelNika, thanks for your reply.
By any chance do you know where are the configuration files for the smtp server at?
Im not using docker, I have it installed on a vm.

Thanks again

**Comment by XelNika** [comment]
SMTP settings go in the environment file. Are you running it as a systemd service? There's an example [here](https://github.com/dani-garcia/bitwarden_rs/wiki/Setup-as-a-systemd-service). Use the template file [here](https://raw.githubusercontent.com/dani-garcia/bitwarden_rs/master/.env.template), SMTP is at the bottom.

**Comment by mprasil** [comment]
@shd128, did that resolve your issue?

**Comment by mprasil** [comment]
Resolving this, feel free to reopen if you still experience problems.

**Comment by shd128** [comment]
> @shd128, did that resolve your issue?

mprasil, yes! thank you!
