### ISSUE TITLE
Support for Subpaths

### ISSUE THREAD

**Issue by waphire** [dani-garcia/bitwarden_rs#528]
Is it possible to run Bitwarden in a reverse proxy setup on a subpath instead of a subdomain?

I've searched around and have only found this: https://github.com/bitwarden/server/issues/277
Is it not a supported scenario for bitwarden_rs too?

**Comment by dani-garcia** [comment]
This isn't a supported feature, but it can be made to work with some changes both to the web vault and the server code. That does mean recompiling the server and the web vault, so I would recommend using a subdomain.

There are some old patches available here: https://github.com/dani-garcia/bitwarden_rs/issues/241#issuecomment-436376497.
