### ISSUE TITLE
I can`t open attachments

### ISSUE THREAD

**Issue by gerroon** [dani-garcia/bitwarden_rs#529]
Hi

I am using the Docker image. I have attachments in some entries (image, pdfs etc) When I try to open them in the web app , I am getting the errors below, I get `An Error Occured` in the page

```
[2019-07-12 16:14:45][rocket::rocket][INFO] GET /api/sync?excludeDomains=true/attachments/e2d7725b-d771-4e2e-9e55-97ccb0fe64b3/f5b823f0078a67c2b358:
[2019-07-12 16:14:45][_][INFO] Matched: GET /api/sync?<data..> (sync)
[2019-07-12 16:14:45][bitwarden_rs::auth][ERROR] Unauthorized Error: No access token provided
[2019-07-12 16:14:45][_][INFO] Outcome: Failure
[2019-07-12 16:14:45][_][WARN] Responding with 401 Unauthorized catcher.
[2019-07-12 16:14:45][_][INFO] Response succeeded.

```

**Comment by mprasil** [comment]
Any proxy in front?

**Comment by gerroon** [comment]
Hi

Yes forgot to mention, I am running it behind Apache proxy, using the proxy settings provided in the wiki.

**Comment by mprasil** [comment]
Can you see if anything relevant pops up in Apache logs? The above logs doesn't seem to be relevant which makes me think there is some Apache configuration blocking attachment requests.

**Comment by gerroon** [comment]
Well those lines of the log is created right when I try to open an attachment. 

I will take a look at the apache logs.

**Comment by mprasil** [comment]
Ah I've noticed the attachment URL is appended to the sync API call. This sounds like wrong configuration on apache side. Can you share your config?

**Comment by gerroon** [comment]
```
RewriteEngine On
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule /notifications/hub(.*) ws://<SERVER>:3012/$1 [P,L]
        ProxyPass / http://127.0.0.1:4030/

        ProxyPreserveHost On
        ProxyRequests Off
        RequestHeader set X-Real-IP %{REMOTE_ADDR}s


```

**Comment by mprasil** [comment]
That part seems Okay, there must be some other configuration that's interfering with the requests. My main concern is this part:

```
/api/sync?excludeDomains=true/attachments/e2d7725b-d771-4e2e-9e55-97ccb0fe64b3/f5b823f0078a67c2b358
```

This seems to be concatenation of two request paths:

```
/api/sync?excludeDomains=true
```

This one is for synchronization and obviously requires login token. (which is why it is complaining about it's absence)

```
/attachments/e2d7725b-d771-4e2e-9e55-97ccb0fe64b3/f5b823f0078a67c2b358
```

Actual attachment download request as it should be. AFAIK this one does not require token. So it seems like your client app actually sends this request correctly, but something in between mangles the request and it is then hitting the wrong `sync` endpoint.

Hope that makes sense.

**Comment by gerroon** [comment]
@mprasil sure it makes sense but it does not solve my issue :) 

Are you guys able to download attachments in a similar setup?

**Comment by mprasil** [comment]
I don't use Apache, so unfortunately can't verify that. But the config you posted seems alright.

The reason the attachment download fails seems to be due to malformed request, so the only outstanding question is what causes this.

To rule out client issue, you can test with curl:

`curl -v "http://yourserver/<attachment_path_from_above>"`

And see the curl output and server logs. That might pinpoint the source of issues.

**Comment by gerroon** [comment]
@mprasil, thank you for the reply. I will try your recommendation.

**Comment by mprasil** [comment]
Any update? Is this resolved?

**Comment by gerroon** [comment]
@mprasil

It does not work. I am even connecting to it using the actual IP of local connection and I am getting the exact same problem. 

I have no problem attaching a file to an item.

Does downloading attachments work for you?

**Comment by gerroon** [comment]
Also interesting, I upgraded the docker image from `2.10.1` to `2.11` and I am now getting a totally different and unhelpful log lines when clicked on an attachment

```
[2019-08-01 00:13:35][rocket::rocket][INFO] GET /api/sync?excludeDomains=true/attachments/6772a42a-ad76-4d0a-83fe-246b73c9c49f/5dbdba5a85557aaf6ef9:
[2019-08-01 00:13:35][_][INFO] Matched: GET /api/sync?<data..> (sync)
[2019-08-01 00:13:35][bitwarden_rs::auth][ERROR] Unauthorized Error: No access token provided
[2019-08-01 00:13:35][_][INFO] Outcome: Failure
[2019-08-01 00:13:35][_][WARN] Responding with 401 Unauthorized catcher.
[2019-08-01 00:13:35][_][INFO] Response succeeded.

```

**Comment by mprasil** [comment]
Have you also tried the latest image? I was testing with `latest` and with Vault and Firefox extension as a client and it worked fine in both cases for me - both uploading and downloading.

Did you try with curl?

```bash
curl -v "http://yourserver/attachments/6772a42a-ad76-4d0a-83fe-246b73c9c49f/5dbdba5a85557aaf6ef9"
```

I've used the attachment URL from your logs above, but if that attachment is gone, adapt the URL to some valid ID.

**Comment by gerroon** [comment]
This is what I get

https://bin.privacytools.io/?151dceae1a126917#7i7Wgpk1dzogng6eNHNemfutlD8rpv3lA5UBT5jLyaI=

**Comment by mprasil** [comment]
Did you see corresponding request also in bitwarden_rs logs?

**Comment by mprasil** [comment]
Any update @gerroon ?

**Comment by mprasil** [comment]
I'm going to resolve this hoping that no response means the problem was resolved. Feel free to reopen if issue still persists.
