### ISSUE TITLE
Can't even start container

### ISSUE THREAD

**Issue by bapesta786** [dani-garcia/bitwarden_rs#531]
Hey - running docker on Ubuntu Server and I have multiple containers running perfectly fine so far (Radarr, Sonarr, SABNZBD, Guacamole, Portainer) however whenever I try to start Bitwarden, I'm presented with the following error:

docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:275: applying cgroup configuration for process caused \"mountpoint for cgroup not found\"": unknown.

I'm really not sure what this refers to?  I'm using the basic docker run command as stated in the instructions.  I've tried different paths, different port numbers etc, but issue persists.

**Comment by mprasil** [comment]
Which image are you using?

**Comment by bapesta786** [comment]
> Which image are you using?

The one from here:
https://github.com/dani-garcia/bitwarden_rs

Docker image list shows:
bitwarden/setup         1.30.4              0c33ae73cf92        2 months ago        220MB

**Comment by JasperZ** [comment]
[bitwarden/setup](https://hub.docker.com/r/bitwarden/setup) is the official bitwarden image and not the one suitable for this repository. The image for this repo is [bitwardenrs/server](https://hub.docker.com/r/bitwardenrs/server)

**Comment by bapesta786** [comment]
> [bitwarden/setup](https://hub.docker.com/r/bitwarden/setup) is the official bitwarden image and not the one suitable for this repository. The image for this repo is [bitwardenrs/server](https://hub.docker.com/r/bitwardenrs/server)

my apologies, i posted the wrong one.  My comment has been updated with the correct image.

**Comment by bapesta786** [comment]
Looks like I have a wider issue - I've restarted a running container (Sabnzbd) and I've been hit with the same message.  I will try a restart of the OS and report back.

**Comment by bapesta786** [comment]
This can be closed - an OS reboot has fixed it .
