### ISSUE TITLE
RPM Builds

### ISSUE THREAD

**Issue by MrMEEE** [dani-garcia/bitwarden_rs#532]
Hi

Thanks for the great work..

I was thinking of doing RPM builds of the this project.. Is someone already doing that, or could it be something that you would include in the wiki info??

Regards

Martin

**Comment by mqus** [comment]
You can add it yourself here: https://github.com/dani-garcia/bitwarden_rs/wiki/Available-packages

**Comment by MrMEEE** [comment]
Ah, cool.. will do that when I have some CentOS/RHEL packages ready

**Comment by mprasil** [comment]
Looking forward to that. I think this can be closed now? Feel free to reopen if there are more questions.

**Comment by MrMEEE** [comment]
I have added a link to the repository on the wiki.. I think everything is working :).. Thanks for the info..

Packages will automatically be built when new versions are available..
