### ISSUE TITLE
Create organization??

### ISSUE THREAD

**Issue by MrMEEE** [dani-garcia/bitwarden_rs#534]
Hi

I'm getting this, when I try to add an organization???

![Screenshot_20190715_202517](https://user-images.githubusercontent.com/768031/61239214-b64fba00-a73e-11e9-8ab4-d5fd12635f7c.png)

Shouldn't this be available??

**Comment by MrMEEE** [comment]
Oh.. this is only if I built the web-vault myself... weird

**Comment by MrMEEE** [comment]
No ... I was mistaken... same issue

**Comment by dani-garcia** [comment]
This should work using the official docker images, if you are building the web vault yourself you need to apply the patches: https://github.com/dani-garcia/bw_web_builds/tree/master/patches

Or you can download the prebuilts from here: https://github.com/dani-garcia/bw_web_builds/releases

**Comment by MrMEEE** [comment]
I have applied the patches..

I have just tried it with your prebuilts... still the same...

**Comment by dani-garcia** [comment]
I'm not sure why that could be happening then. Make sure your browser doesn't have an old version cached or that bitwarden_rs is serving the correct version.

Also make sure you are building the web vault correctly after applying the patches (tho i'm pretty sure it's just `npm run dist`).

For reference this is what i'm getting:
![image](https://user-images.githubusercontent.com/725423/61244445-8b6b6300-a74a-11e9-96e1-04dffb81b772.png)

**Comment by MrMEEE** [comment]
Forget it, I must have done something wrong.. works now, sorry

**Comment by alexpearce92** [comment]
Good call on the cached version. Switching over from official Bitwarden to Vaultwarden retained some Bitwarden restrictions in the web UI. Doing a hard reload resolved the problem and the Vaultwarden patches were correctly applied.
