### ISSUE TITLE
delete-recover not possible

### ISSUE THREAD

**Issue by rustysponge** [dani-garcia/bitwarden_rs#539]
Hey there,
I'm running bitwarden_rs on a Synology DS218+ without any problems so far (web access, browser extension & mobile apps work fine for quite a while now). Now I needed to delete-recover an account as I lost my second factor authentication device. I have a local backup of the password-data, so the potential deletion of the account isn't my problem.
My problem: when I submit the mail-address associated with the 'lost' account, I get an unspecific error in the UI. Looking in the log-file, bitwarden tells me this:

```
[2019-07-19 07:10:45][rocket::rocket][INFO] ^[[32mPOST^[[0m ^[[34m/api/accounts/delete-recover^[[0m ^[[33mapplication/json; charset=utf-8^[[0m:
[2019-07-19 07:10:45][_][ERROR] No matching routes for ^[[32mPOST^[[0m ^[[34m/api/accounts/delete-recover^[[0m ^[[33mapplication/json; charset=utf-8^[[0m.
[2019-07-19 07:10:45][_][WARN] Responding with ^[[31m404 Not Found^[[0m catcher.
[2019-07-19 07:10:45][_][INFO] ^[[32mResponse succeeded.^[[0m
```

As far as I understand, there seems to be a problem with the delete-recover route, but I don't have a clue what the root cause of this might be as anything else works perfectly fine. Is it bug or a configuration problem? Do you need more information on the setup?

**Comment by mprasil** [comment]
Yes, you're right, this wasn't implemented yet. It is tracked under feature requests issue #246.

As a workaround you can delete user from the admin interface and then just register again.

Hope that helps. I'm going to close this, but feel free to reopen if you have more questions.

**Comment by mprasil** [comment]
As a side note, I *think* you should be able to disable 2fa if you feel like editing the DB directly. I'm not sure what the exact query would be, maybe open a new issue or hop on our chat, someone familiar with 2fa might know.

**Comment by rustysponge** [comment]
Thanks, I really appreciate your quick response! I'll have a look at the admin page (haven't used it until now) - that should be easier than playing around with the DB to deactivate 2fa. :-)
