### ISSUE TITLE
Problem with starting docker bitwarden

### ISSUE THREAD

**Issue by LeoArnts** [dani-garcia/bitwarden_rs#542]
After a restart of the Ubuntu server and starting the docker bitwarden i get the following error:

docker: Error response from daemon: error while creating mount source path '/bw-data': mkdir /bw-data: read-only file system.

Does someone have a solution ?

Regards,
Leo

**Comment by mprasil** [comment]
It sounds like you have your filesystem mounted read-only. Could be corrupted filesystem or something similar. Can you create the directory yourself? (`sudo mkdir /bw-data`)

**Comment by mprasil** [comment]
Have you figured out the problem?

**Comment by mprasil** [comment]
Hi, I hope you figured the issue and this is now solved. I'm going to close this as there was no response for couple days. Feel free to reopen if you still experience problems.

**Comment by LeoArnts** [comment]
Sorry  the problem was gone after an update of docker in Ubuntu. But its back again.

**Comment by LeoArnts** [comment]
root@docker:~# docker pull bitwardenrs/server:latest                                                
latest: Pulling from bitwardenrs/server
Digest: sha256:52f309e4deccd2191b1985a462651990dbe6ac324b4e29394c93e0cd0686bb47
Status: Image is up to date for bitwardenrs/server:latest
docker.io/bitwardenrs/server:latest
root@docker:~# docker run -d --name bitwarden -v /bw-data/:/data/ -p 80:80 bitwardenrs/server:latest
6837e21a5fba10b799c66f563b5ef1fb86200f58e5a32168b222ef320d9dc611
docker: Error response from daemon: error while creating mount source path '/bw-data': mkdir /bw-data: read-only file system.

**Comment by mprasil** [comment]
This seems to be some local system issue. I'd check the filesystem and drive maybe.

**Comment by DaniloSteps** [comment]
Had the same problem using Ubuntu 20.04.3 with preinstalled docker option on a Proxmox vm.

The solution in my case was to simply run the command with /root/vw-data instead of /vw-data.

Don't know why, but worked.
