### ISSUE TITLE
ROCKET_TLS issue. Not such file or directory.

### ISSUE THREAD

**Issue by joopjuh** [dani-garcia/bitwarden_rs#543]
I'm trying to add certificates generated from a LetsEncrypt docker.
I've added the folder to the Bitwarden docker.

/share/CACHEDEV1_DATA/appdata/letsencrypt/config/etc/letsencrypt/live/domainnamehere  -> /ssl

When i start the container without the ROCKET_TLS it boots and i'm able to see the folder that i attached to the docker.
The certificates are also visible in that folder.

When i enable the ROCKET_TLS and add in {certs="/ssl/fullchain.pem",key="/ssl/privkey.pem"} it generates an "No such file or Directory" error.

I've tried removing the quotes but still the same issue.
Also moved the certificates into the /data folder but still getting the same error that is unable find find the file or directory.

I'm running this on a QNAP with the help of portainer as container station is not the greatest tool.
Tried the same settings in container station but same results.

**Comment by mprasil** [comment]
Very likely the issue here is, that the cert files you're mounting under `/ssl` are just symlinks to some other location which isn't mounted. See [here](https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-HTTPS) for details.

**Comment by joopjuh** [comment]
I also tried using the certificates in the archive folder but still same results.

**Comment by TheDeadGuy** [comment]
I had an issue similar to this with docker compose.

https://github.com/dani-garcia/vaultwarden/wiki/Using-Docker-Compose

the volumes are listed like:
      - ./vw-data:/data # the path before the : can be changed

so i did the same for the SSL mapping too.

However, this made the data unreadable upon request.

To resolve. remove the "." at the start of the volume. That resolved it for me. not sure if it was the same for you as you didn't have your volume config shown here.

**Comment by BlackDex** [comment]
The `.` at the front means relative to the path the `docker-compose.yaml` file is at. Removing the `.` will make that path absolute and means `/vw-data` at the root of your filesystem.
