### ISSUE TITLE
Save Password in Organization as Default 

### ISSUE THREAD

**Issue by ujaeggi** [dani-garcia/bitwarden_rs#557]
Can I set the shared option with organization as default? So that when a users clicks on „save“ in the browser extension it’s saved on the organization? I think most users accidentally put the password into the private vault and will never notice this (for them it‘s available).

**Comment by mprasil** [comment]
I think this needs to be requested upstream as this is purely client-side thing. I can see the [feature request was already created](https://community.bitwarden.com/t/save-password-in-organization-as-default/7159). I'm going to close this now.
