### ISSUE TITLE
Certificate installation help for self-signed reverse proxy

### ISSUE THREAD

**Issue by vargbeaumont** [dani-garcia/bitwarden_rs#561]
Hello! Sorry if this isn't the right place to ask. I have a bitwarden_rs server running on a local server and I have a self-signed reverse proxy setup so that I can use HTTPS in Chromium based browsers without issue. My question is how do I install the certificate on Windows to allow me to use HTTPS in the application also? I have taken the cert.pem file and changed the extension to .cer so Windows will recognise it, I installed it to trusted root certification authorities however I am still unable to connect within the Windows Bitwarden app with HTTPS.

**Comment by AndrewMoscoe** [comment]
https://github.com/dani-garcia/bitwarden_rs/wiki/Private-CA-and-self-signed-certs-that-work-with-Chrome
