### ISSUE TITLE
Hosting web vault on CDN

### ISSUE THREAD

**Issue by AlliotTech** [dani-garcia/bitwarden_rs#563]
takes too long to open，Should some resources be added to CDN? thks
![image](https://user-images.githubusercontent.com/24980252/62672514-97ef7e00-b9cd-11e9-97a9-0deaed0ecb18.png)

**Comment by dani-garcia** [comment]
are you using the docker images or compiling yourself? is the bitwarden_rs server behind a proxy?

**Comment by AlliotTech** [comment]
I used docker images . and the server don't use proxy. i checked the network ,js file take a long time to load .

**Comment by mprasil** [comment]
Can you try loading the js files using `curl`? Can you see the request in server logs?

**Comment by timaschew** [comment]
I'm using version 1.9.1 with docker and nginx with HTTPS and it works super fast for me.

**Comment by AlliotTech** [comment]
> Can you try loading the js files using `curl`? Can you see the request in server logs?

yes，i tried.I think it's because main.xxx.js and vendor.xxx.js is too big and loads too slowly.  maybe it is due to my server only have 1M bandwidth . So I want to know if I can drop these larger JS files into the CDN. thks to reply

**Comment by mprasil** [comment]
I think if you compile the web vault yourself with the settings pointing to your server instance for API, you should be able to host entire Vault from CDN.

**Comment by AlliotTech** [comment]
ok   thank you
