### ISSUE TITLE
Icon extraction fails

### ISSUE THREAD

**Issue by quthla** [dani-garcia/bitwarden_rs#565]
For saturn.de and bwin.com it will just create the miss file

**Comment by mprasil** [comment]
What version are you using?

**Comment by quthla** [comment]
Latest docker image. Were you unable to reproduce the issue?

**Comment by mprasil** [comment]
I think I was able to reproduce that with saturn.de, but bwin.com works fine for me. I'm not sure why saturn.de fails though, I can see this in logs:

```
Download failed for https://www.saturn.de/favicon.ico
```

But when I try to poke the same URL with curl, it works fine.

**Comment by BlackDex** [comment]
I have identified the bug this afternoon. It has to do with cookies, and rather the lack off but still sending the header. This breaks the saturn.de website. Trying to think of a good way to fix this.
