### ISSUE TITLE
Very Slow to Load Web Vault Page from WAN Side

### ISSUE THREAD

**Issue by hg2s** [dani-garcia/bitwarden_rs#572]
I think I noticed an earlier comment about this but it's disappeared so I'm mentioning it again in case it proves useful. 

I am running the current release of the Docker image (build 8be2ed6) with Ubuntu 18.04, Nginx and Let's Encrypt SSL.

When I load the Web Vault home page (v. 2.10.1) from the WAN (public) side it takes about two minutes to load the page, displaying the Bitwarden logo and spinner the whole time. From the LAN (private) side it loads almost instantaneously, taking maybe a second or two. Browser choice does not affect the delay and once the browser obtains the page things move quickly. The server seems to work fine in every other respect. 

The Nginx configuration is based on the example given on the proxy-examples page (https://github.com/dani-garcia/bitwarden_rs/wiki/Proxy-examples) with the exception that in this case a redirect for https and a different port number for the server are applied. The Nginx reverse proxy serves two other servers and neither act slower from the WAN side.  

I am relatively new to bitwardenrs having updated only a couple times so I can't claim to have any prior experience with earlier builds to compare performance. 

Does anyone have any suggestions on how to eliminate the delay from the WAN side? It's somewhat annoying but, as I say, things do seem to work as advertised. 

Thanks for your help.

**Comment by fbartels** [comment]
Are you referring to https://github.com/dani-garcia/bitwarden_rs/issues/563?

What is your upload speed? What is shown in the elements and network tab of your browse wen this happens?

**Comment by hg2s** [comment]
Yes, #563 seems to be the post. 

Upload is 1 Mbps. 

Elements seems to grab & load the page completely, if that's what you're asking. In Network I see initial activity up to when it hits the fonts - fontsawesome-webfont and Open_sans-normal-400 - at which point it halts for a time and then pops again into activity loading messages.json, manifest.json, favicon, Open_Sans-normal-600 and favicon to finish.

**Comment by fbartels** [comment]
> at which point it halts for a time

I don't think that it really halts. there are two relatively large files that need to be fetched on the first load: main.*.js and vendor.*.js (afterwards they will be served from cache).

The same can be observed when throttling the speed in the network tab.

**Comment by dani-garcia** [comment]
Yeah with a 1Mbps upload the page won't load very fast, the fonts are about half a megabyte in total, and the javascript is around 4MB, so a first load on that connection is not going to be fast.

**Comment by mprasil** [comment]
I think this was answered. Closing it now, but feel free to re-open if you have more questions.

**Comment by repomaa** [comment]
I'm experiencing the same issue with an upload of 100Mbit/s. Everything is painstakingly slow. I host other web apps on the same server and have never had any issues.

**Comment by MaxXor** [comment]
Same issue here with 1 Gibt/s. The vendor.js file is transferred very slowly and it's huge (multiple MB).

**Comment by BlackDex** [comment]
@MaxXor Try enabling compression on your reverse-proxy that should lower the size of the vendor js to less then 1MB.
Also, it's not something we can fix on the side of vaultwarden.

**Comment by xpader** [comment]
It is stranger on this issue, i visit my site via socks5 proxy to my home server, download file and upload file was very fast, but visit valutwarden web is very slow.
This is definitely  not network speed problem.

**Comment by hg2s** [comment]
Since the original post I have upgraded internet service which made a huge difference, as expected. 

I have also recently added compression to Nginx and I do see an additional change for the better. 

Together the two changes result in a site that is quite usable but, frankly, I still see a slight delay in loading the web page which is discussed above. Not a problem per se. Just an observation.
