### ISSUE TITLE
Import from JSON not always working with MySQL

### ISSUE THREAD

**Issue by fabicodes** [dani-garcia/bitwarden_rs#575]
I think this is a similar issue https://github.com/diesel-rs/diesel/issues/1181
I am running 
`bitwardenrs/server-mysql@sha256:874906c654b7e150e96a119111720fef81fab90af6ec87898eaef8f948514d2e`
using the `bitwardenrs/server-mysql:latest` tag
`Version: 1.9.1-27c23b60`

```[2019-08-16 04:40:24][_][INFO] Matched: POST /api/ciphers/import (post_ciphers_import),
[2019-08-16 04:40:24][rocket::rocket][INFO] POST /api/ciphers/import application/json; charset=utf-8:,
[2019-08-16 04:40:57][rocket::rocket][INFO] GET /api/sync?excludeDomains=true application/json:,
[2019-08-16 04:40:57][_][INFO] Matched: GET /api/sync?<data..> (sync),
thread '<unnamed>' panicked at 'Error loading ciphers: DeserializationError("Numeric overflow/underflow occurred")', src/libcore/result.rs:1051:5
```

Same JSON File works fine with the current non-MySQL build

**Comment by dani-garcia** [comment]
Hmm not sure what column could be overflowing, most of the integers should have values under 10 or so. The only ones I can think that are bigger are the attachments file sizes and the number of iterations for the users password, but both should be well under the 32 bit max.

**Comment by dani-garcia** [comment]
Closed due to inactivity.
