### ISSUE TITLE
Code garbage in notes field after keepass import

### ISSUE THREAD

**Issue by muibusan** [dani-garcia/bitwarden_rs#577]
Hi!

I imported my keepass database (CSV). It worked fine except that every notes field in Bitwarden now has some useless code in it. Is this a bug?

Example:
`KPRPC JSON: {"version":1,"formFieldList":[{"name":"password","displayName":"KeePass password","value":"{PASSWORD}","type":"FFTpassword","id":"password","page":-1,"placeholderHandling":"Default"},{"name":"login","displayName":"KeePass username","value":"{USERNAME}","type":"FFTusername","id":"login_field","page":-1,"placeholderHandling":"Default"}],"alwaysAutoFill":false,"neverAutoFill":false,"alwaysAutoSubmit":false,"neverAutoSubmit":false,"priority":0,"altURLs":[],"hide":false,"blockHostnameOnlyMatch":false,"blockDomainOnlyMatch":true}`

Is there any way to delete the notes fields not one by one?
And could the import routine be improved or this this something for the original Bitwarden support?

**Comment by dani-garcia** [comment]
I'm not sure why this could happen, the format parsers are handled entirely by upstream, so maybe the problem's there or maybe we aren't handling the response correctly.

Can you generate a minimal example file that reproduces this error? (Without sensitive info).

**Comment by muibusan** [comment]
Trying to reproduce it made me find the problem. It's not related to the import nor to Bitwarden, rather Keepass itself created a so-called string field in its database for whatever reason. There the code shown above is stored - also compare the attached screenshot. I suppose Keepass somehow creates that field upon automatic detection of a new web page. I didn't even realise there is such a field even tho I was using Keepass for quite some time. It's hidden in a sub menu. It's strange. I don't even understand what Keepass uses that code for. Anyway ... false alarm. 

If at all, the idea would be to introduce a simple dialog in Bitwarden asking whether or not that funny Keepass string field shall be imported or ignored during import.

![string field](https://user-images.githubusercontent.com/16862260/63229009-c9e9b700-c1fb-11e9-9eeb-b0092899b369.gif)

**Comment by mprasil** [comment]
I guess any smart handling of the keepass import would have to be requested client side. So maybe you can report the issue there?

Going to resolve this now.
