### ISSUE TITLE
Raspberry Pi Image Works on ODROID HC2

### ISSUE THREAD

**Issue by moon8orange** [dani-garcia/bitwarden_rs#580]
The Raspberry pi image works on ODROID HC2 running Armbian (which is armv7l). I tested "the create a new user" and "login page". Is it really supposed to work on the ODROID HC2? I guess it is because it has the same a similar architecture, but I'd like to make sure.

Operating System: Armbian 4.14.133-odroidxu4
Machine Hardware Name: armv7l
Machine Hardware details:
* Samsung Exynos5422 Cortex-A15 2Ghz and Cortex-A7 Octa core CPUs
* 2Gbyte LPDDR3 RAM PoP stacked

**Comment by dani-garcia** [comment]
According to https://github.com/dani-garcia/bitwarden_rs/wiki/Which-container-image-to-use#reported-compatibility-table it should work using the `raspberry` image yes. If the image boots at all everything else should work fine.

**Comment by moon8orange** [comment]
I see thanks. I will read the wiki more carefully.
