### ISSUE TITLE
Is there a Change Log for the Docker releases? 

### ISSUE THREAD

**Issue by hg2s** [dani-garcia/bitwarden_rs#584]
Is there a listing or log of the changes included in each release of the Docker images for bitwardenrs/server? 

-Thank you

**Comment by dani-garcia** [comment]
If by releases you mean the versioned ones you can check https://github.com/dani-garcia/bitwarden_rs/releases.

The latest image follows the master branch so you can check the commit log.

**Comment by mprasil** [comment]
I think the question is now answered and we can close this. Feel free to reopen if more info is needed.
