### ISSUE TITLE
Question: Mobile app forks, what does it take?

### ISSUE THREAD

**Issue by grahamPegNetwork** [dani-garcia/bitwarden_rs#591]
Hi there, I read several other issues discussing mobile sync and how either BitWarden would need to add functionality to their mobile apps, or they may need to be forked to handle notifications. 

From what I understand, the upstream mobile applications use push notifications and somehow utilize firebase messaging/apple's (??).

1. How much work would be involved in forking (main maintaining ideally...) the apps to:
A. Refer to a bitwarden_rs server (potentially what is happening in #443 ? )
B. Handle websocket connections? (probably horrible for battery drain come to think about it)
C. Simply run periodic polls to see if things need to sync. I don't really care if my phone is up to date to the second, as long as it gets changes within 5-15 minutes, and I don't have to manually trigger it.

I get iOS is challenging, I feel like with the right resources I should be able to build an APK with my server hardcoded in and distribute it to friends/family, right?

**Comment by dani-garcia** [comment]
Well I never looked into it super deep but as far as I know the clients communicate with the `notifications.bitwarden.com` endpoint when making changes and then the server contacts firebase or apple push notification services which are the ones that send the notification to the client.

To replace it with our own would imply switching the hardcoded endpoint URL to bitwarden's service and point to an instance of our own, which we'd have to create, and changing the push notification services API keys on the apps code. Also the push notification connection might be tied to the app store listing, which might mean it won't be configurable like the server URLs are currently, not sure about that one.

Background websockets are probably impossible in iOS and would probably mean having a constantly running service on Android, with a notification open so the system doesn't kill it, as you say that can't be good for the battery.

Forcing a sync every so often could be reasonable, for example every time the app is open and if it hasn't synced in X time, trigger another sync. In theory the app already does this I think, but not sure what's the syncing logic (It might have been removed now that push notifications are here).

If we used upstream's server with a self hosted installation id that could work, but that would be still using the official server (though I don't think any sensitive data is sent). That said, that system is meant for the official self hosted solution, so I'm not sure about doing that unless we get the green light from the bitwarden devs.

**Comment by mprasil** [comment]
This feels like way out of scope of the `bitwarden_rs` project and should be closed. I'd love to see some independent 3rd party client implementations, but perhaps this is not the right project to do this under?

**Comment by grahamPegNetwork** [comment]
I see where you're coming from and I'm not sure I entirely agree.

When it comes to the official BW code and clients they have things handled. Sure, I could see somebody coming up with a 3rd party client, but I'd have to ask why. Even if you're using BitBetter I believe you're using their servers and the push notifications would work. (that was the main issue originally discussed)

The need for a 3rd party client relates to how _rs is an independent project/implementation of BW and does not rely on their servers. While I agree that other people forking the project may benefit from a client, as far as I can imagine, this seems like an issue limited to the _rs project.

I could be wrong, I mean if somebody forked BW entirely and wanted to run their own centralized registration servers they could, and would in turn need what is being discussed. That said, I haven't heard about anyone trying to do this and *feel* like it would at least be steered primarily by _rs people.

**Comment by mprasil** [comment]
I'm going to close this as it feels a bit out of scope of this project. I don't think we have enough capacity to work on this. Obviously if anyone is interested, they are very welcome to submit a PR.
