### ISSUE TITLE
Can't find 1.10.0 ?

### ISSUE THREAD

**Issue by mikkelnl** [dani-garcia/bitwarden_rs#592]
Hi,

I can't seem to find 1.10.0? Running as a docker container on a Synology NAS, when I search the register for bitwardenrs/server, the latest tag is 1.9.0...?

Is this just a matter of time?

Thanks.

**Comment by dani-garcia** [comment]
Yeah, you are right, it seems docker hub hasn't picked up on the latest release. @mprasil Is there something we need to do to tag the images?

For now, the latest image is pretty much the same as the 1.10.0 release, with the addition of email two factor support, so you can use that if you want.

**Comment by mprasil** [comment]
Apologies, I was away for a while, it definitely needs to be set up on the docker hub, I'm going to check that now.

**Comment by mprasil** [comment]
The builds have now been set up and images are building, you should see them appear in couple hours.
