### ISSUE TITLE
Backup option in the admin panel not available in Docker

### ISSUE THREAD

**Issue by Skaronator** [dani-garcia/bitwarden_rs#596]
Hi!

Just saw in the changelog that you can now backup the SQLite Database in the admin web interface but saidly it looks like that option isn't available for me.

![image](https://user-images.githubusercontent.com/2886913/64064124-428a4380-cbfe-11e9-85b6-4cbaad9384af.png)

Looks like this check results in a `false`:
https://github.com/dani-garcia/bitwarden_rs/blob/026f9da035dcbf5ff12387600162841f94b47154/src/api/admin.rs#L39-L41

since sqlite isn't available in the container:
https://github.com/dani-garcia/bitwarden_rs/blob/469318bcbdca68ca58735f7cc58dd1e943e4da1e/docker/amd64/sqlite/Dockerfile#L32-L35

I tried the following docker images:

- bitwardenrs/server:alpine
- bitwardenrs/server:latest

Currently running version 1.10.0-469318bc

**Comment by mprasil** [comment]
Those lines you linked are for the build container, the final image never had sqlite bundled in. The PR #475 was merged with the understanding that there will be better option than running external command once the sqlite `3.27` becomes more common.

So right now, you can build your own version of the image with sqlite bundled in. Or we can discuss bundling in another binary or we can see if newer sqlite library and built-in backup functionality would be an option now. (the latest would be the ideal solution IMO)

**Comment by TheMardy** [comment]
@mprasil 
I'm afraid we will have to wait for a few more months for the ideal solution. 
We will need a libsqlite-sys 0.17 crate (that version uses SQLite 3.27 for `VACUUM INTO` support) 
After that is out, we have to wait for Diesel to support it as libsqlite-sys 0.17 has a few breaking changes.

**Comment by mprasil** [comment]
I've created PR #638 to use the binary in the meantime.

**Comment by mprasil** [comment]
The latest images should have sqlite bundled in and the backup option should be present in the admin interface. I'm going to resolve this.
