### ISSUE TITLE
Reusing data volume on another container instance empties the DB

### ISSUE THREAD

**Issue by JoseAntonioIdener** [dani-garcia/bitwarden_rs#597]
Hey! First, thanks for the good work of this project! 👌

We detected some data corruption on a date and we have a daily docker volume backup system. Our approach was to take a bitwarden_rs data volume in a given date and restore it locally for debugging purposes.

What we found is that when the container is created pointing to the already populated data volume for bitwarden, it gets empty and all the tables get deleted.

This difficults the migration process of the docker volume to other container instances.

Thanks again and hope you can help me some way! 

Cheers,

**Comment by mprasil** [comment]
Can you specify a way how to reproduce this? I don't quite follow how you got that end result of tables being deleted. I think that just grabbing a copy of data folder and running bitwarden_rs instance using that should just work, this is how you do the upgrade after all..

**Comment by mprasil** [comment]
No response for couple weeks, so I'm going to close this one as we have no reliable way to reproduce the issue. Feel free to reopen if you can provide more information.

**Comment by JoseAntonioIdener** [comment]
@mprasil Sorry for the delay, we fixed our problems by updating the image of the container to the latest version, now our user is able to see their vault back.

Thanks for the collaboration and sorry again for the delay.
