### ISSUE TITLE
How to migrate sqlite3 database to Bitwarden_rs/mysql database

### ISSUE THREAD

**Issue by BobWs** [dani-garcia/bitwarden_rs#598]
Hi,

Thanks for the mysql implementation! At the moment I'm testing this image. I've successfully installed it on Synology docker with mariadb. So far so good.

But how to migrate my current database sqlite3 to mysql database while maintaining all users and all attachments and organizations.

I just tried to export the current bitwarden vault (json file). And I imported it in the new vault (mysql version) and this went well, only the attachments didn't come along. And I also miss the organizations.

Can someone tell you how to do this via a step-by-step plan? Is it possible to do this via phpadmin? For example, that you import the sqlite3 into the bitwarden database?

**Comment by mprasil** [comment]
Well between discussion under #497 and in our matrix room, there is no bulletproof way to migrate directly the DB. The only "officially" supported way is export/import via vault, but you have to do this for every user and organization and attachments won't be moved over as you noticed.

Unless someone steps up and writes a tool to migrate the DB and then keeps it up to date with latest schema changes, it's just not easily possible.

**Comment by BobWs** [comment]
Thanks! I've manage to successfully dump my sqlite3 database en imported this in Mariadb. Everything went smooth all users account, organisations and attachment where imported also the TOTP in some of the account.

If I have time I will put my steps together and post it. It will be based on docker synology because that is the machine I'm using.

**Comment by mprasil** [comment]
You can add it to [our wiki](https://github.com/dani-garcia/bitwarden_rs/wiki). Also please add some note that this is not officially supported, because I feel like there are lot of edge cases where this will fail. Thanks for reporting back.
