### ISSUE TITLE
SMTP support?

### ISSUE THREAD

**Issue by pageb018** [dani-garcia/bitwarden_rs#60]
Is this possible? Would love to be able to send out emails when setting up users and/or adding them to collections.

**Comment by mprasil** [comment]
This would be cool to have, just a note that the way some of the current things work would have to be changed. For example registering users or adding them to collections effectively skips the invitation step. Now this can actually be beneficial for people, that do not want to necessary use SMTP for this functionality. So if anyone feels like implementing this, I'd certainly like it to be optional and I'd hope to have the option to keep the current functionality.

**Comment by dani-garcia** [comment]
Currently SMTP support is not something on my radar, but I'm not against it as an idea for the future as long as it's optional.
With a little research I discovered an SMTP client library for Rust (https://github.com/lettre/lettre) that seems reasonably simple to use, so maybe a proper implementation won't be particularly complex.

**Comment by pageb018** [comment]
Makes perfect sense. Appreciate the great work.
