### ISSUE TITLE
Docker start fails with latest image version

### ISSUE THREAD

**Issue by dominikstraessle** [dani-garcia/bitwarden_rs#603]
I'm running bitwarden_rs with docker in swarm mode and with automatic image updates. Tonight the newest image of bitwarden_rs has been pulled and since then the startup of the container fails. When I afterwards manually pulled the next older version for testing purposes, everything runs smoothly like before.

Not working: `bitwardenrs/server:alpine`
Working: `bitwardenrs/server:1.10.0-alpine`

A docker inspect of the container gives the following error message in the `Health` section:
```json
{
"Health": {
                "Status": "unhealthy",
                "FailingStreak": 3,
                "Log": [
                    {
                        "Start": "2019-09-06T08:29:51.743115269+02:00",
                        "End": "2019-09-06T08:29:52.162213371+02:00",
                        "ExitCode": 1,
                        "Output": "/bin/sh: bash: not found\n"
                    },
                    {
                        "Start": "2019-09-06T08:30:02.181111963+02:00",
                        "End": "2019-09-06T08:30:02.562809027+02:00",
                        "ExitCode": 1,
                        "Output": "/bin/sh: bash: not found\n"
                    },
                    {
                        "Start": "2019-09-06T08:30:12.590872269+02:00",
                        "End": "2019-09-06T08:30:12.964838957+02:00",
                        "ExitCode": 1,
                        "Output": "/bin/sh: bash: not found\n"
                    }
                ]
            }
}
```

A `docker stack ps <my-bitwarden-service-name>` gives the following ERROR:
```
task: non-zero exit (137)
```

I think this could have something to do with the following merge request: [ Adds Healthcheck for default docker container #589 ](https://github.com/dani-garcia/bitwarden_rs/pull/589)

**Comment by thehawkes** [comment]
Same problem here with the latest debian build
the problem is that curl is missing in the image that is needed for the healthcheck
```
➜ docker exec -it bitwardenrs bash
root@0637c97d4738:/# curl
bash: curl: command not found
```

i've temp fixed it by installing curl after the container was created

**Comment by mprasil** [comment]
This was caused by #589, as a quick workaround you can add `--no-healthcheck` to your docker run command. For docker compose you can disable healthcheck:
```yaml
healthcheck:
  disable: true
```

**Comment by mprasil** [comment]
PR submitted to fix this.

**Comment by mprasil** [comment]
The PR is now merged, it will take couple hours to rebuild all images.
