### ISSUE TITLE
How to update the bitwardenrs/server-mysql?

### ISSUE THREAD

**Issue by BobWs** [dani-garcia/bitwarden_rs#606]
Hi,

How to update the bitwardenrs/server-myqsl? For the regulair server I used this for updating the server, but for the mysql version it isn't working?

Can you please clarify the procedure for me. There isn't much information about the myslq version. Is it stable to use? 

`# Pull the latest version`
`docker pull bitwardenrs/server:latest`

`# Stop and remove the old container`
`docker stop bitwarden`
`docker rm bitwarden`

`# Start new container with the data mounted`
`docker run -d --name bitwarden -v /bw-data/:/data/ -p 80:80 bitwardenrs/server:latest`

**Comment by mprasil** [comment]
Essentially the procedure in both cases is to pull latest version, stop and remove old container and start new container with the same parameters as you used for the old one.

There isn't anything specific for the mysql version.

**Comment by BobWs** [comment]
> Essentially the procedure in both cases is to pull latest version, stop and remove old container and start new container with the same parameters as you used for the old one.
> 
> There isn't anything specific for the mysql version.

Well thats what I'm doing and after updating the containers starts-up and when try to login I get an error that user and password don't match. So then I remove the container manually again and configure it manually with the same parameters and then I can login normally without any problems. So I don't now why it won't work with the script. 

`docker pull bitwardenrs/server-mysql:latest`
`docker stop bitwarden-mysql`
`docker rm bitwarden-mysql`
`docker run -d --name bitwarden-mysql \`
`-v /volume1/docker/bitwarden/data/:/data/ \`
`-v /volume1/docker/bitwarden/ssl/:/ssl/ \`
`-e ROCKET_TLS='{certs="/ssl/cert.pem",key="/ssl/privkey.pem"}' \`
`-e DATABASE_URL='mysql://bitwarden:<password>@mysql/bitwarden' \`
`-e ENABLE_DB_WAL='false' \`
`-e RUST_BACKTRACE='1' \`
`--link mariadb:mysql \`
`-p 8443:80 bitwardenrs/server-mysql:latest`

For information I used the same method to update the non mysql version and it was working just fine.

**Comment by fbartels** [comment]
Hi @BobWs,

"the script" being what you posted in your last reply?

**Comment by BobWs** [comment]
> Hi @BobWs,
> 
> "the script" being what you posted in your last reply?

Hi @fbartels,

Yes, What I posted in the reply is what I'm using in a script, which runs as a task on my Synology Nas to update Bitwarden Server.

**Comment by BobWs** [comment]
Sorry my mistake I made a typo in writing the script 😏 Everything works fine now!
I going to close this issue.
