### ISSUE TITLE
Latest Docker build appears "unhealthy"

### ISSUE THREAD

**Issue by hg2s** [dani-garcia/bitwarden_rs#607]
When I try to run the latest build of bitwardenrs/server (amd64, linux) I receive an "unhealthy" status from Docker, like so:
  
```
  CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                     PORTS                            NAMES
467d269eebd2        bitwardenrs/server:latest   "./bitwarden_rs"         2 minutes ago       Up 2 minutes (unhealthy)   3012/tcp, 0.0.0.0:8008->80/tcp   bitwarden
```

If I revert and specify the image 1.10.0 I receive no such message. 

The server appears to be working and I have not seen this message before. Is it a problem in my installation, a bug, an artifact? For the moment I am reverting to 1.10.0 specifically. 

Ubuntu 18.04.3 LTS | Nginx 1.14.0 | Docker 18.09.5

Thanks for your help.

**Comment by hg2s** [comment]
I see a new release of bitwardenrs/server, Digest 7e5ba76c8154, that seems to be working. The container spins up with a "healthy" status. -Thanks!

**Comment by dani-garcia** [comment]
Yep there was a bug in the new health check code but it's fixed now. Note that it was reporting false positives, so everything should have worked anyway.

**Comment by mprasil** [comment]
Latest images should be fine now, apologies for the inconveniences caused.
