### ISSUE TITLE
Server SSL erro on deploy stack

### ISSUE THREAD

**Issue by thiago304** [dani-garcia/bitwarden_rs#610]
Dear,
I am trying to deploy a bitwardenrs stack with HTTPS and have the following error in the stack logs:

bitwarden_rs_bitwarden.1.acbhzf27v0z@getsemani.tiagoti.com.br | [2019-09-07 00:35:02] [rocket :: config :: error] [ERROR] environment variable ROCKET_TLS = '{certs = "/ ssl / certificate.pem", key = "/ ssl / bitwarden.pem "} 'could not be parsed

My Stack Settings:

version: "3"
services:
  bitwarden:
    image: bitwardenrs / server: 1.10.0
    environment:
      - DOMAIN = http: //bitwarden.home.ad.local
      - SIGNUPS_ALLOWED = true
      - INVITATIONS_ALLOWED = true
      - WEBSOCKET_ENABLED = true
      - ROCKET_TLS = '{certs = "/ ssl / certificate.pem", key = "/ ssl / bitwarden.pem"}'
      - SMTP_HOST = localhost
      - SMTP_FROM = bitwarden @ localhost
      - SMTP_PORT = 25
      - SMTP_SSL = false
      - SHOW_PASSWORD_HINT = true
    volumes:
      - / etc / localtime: / etc / localtime: ro
      - / DATA / bitwarden_rs: / data /: rw
      - / ssl: / ssl /: rw
    deploy:
      labels:
        - traefik.enable = true
        - traefik.web.frontend.rule = Host: bitwarden.ad.home.local
        - traefik.web.port = 80
        - traefik.hub.frontend.rule = Host: bitwarden.ad.home.local; Path: / notifications / hub
        - traefik.hub.port = 3012
        - traefik.hub.protocol = ws
        - traefik.docker.network = traefik_public
    networks:
        - traefik_public

networks:
  traefik_public:

**Comment by Ayitaka** [comment]
Pretty sure its just a matter of removing the apostrophes:

`- ROCKET_TLS='{certs="/ssl/certificate.pem", key="/ssl/bitwarden.pem"}'` 

changed to:

`- ROCKET_TLS={certs="/ssl/certificate.pem", key="/ssl/bitwarden.pem"}`

Many of the examples give the command line format which is `-e key='val'`

But in docker-compose you can use `- key=val` format or the ` key: 'val'` format for environment settings.

**Comment by thiago304** [comment]
Dear I removed the single quotes as below so the service comes up as the logs below and then falls into an error.

- ROCKET_TLS={certs="/ssl/certificate.pem", key="/ssl/bitwarden.pem"}

LOGS 
bitwarden_rs_bitwarden.1.dylbnxvbrh4y@getsemani.domain.com.br     | [2019-09-07 09:47:18][launch][INFO] Configured for staging.
bitwarden_rs_bitwarden.1.dylbnxvbrh4y@getsemani.domain.com.br     | [2019-09-07 09:47:18][launch_][INFO] address: 0.0.0.0
bitwarden_rs_bitwarden.1.dylbnxvbrh4y@getsemani.domain.com.br    | [2019-09-07 09:47:18][launch_][INFO] port: 80
bitwarden_rs_bitwarden.1.dylbnxvbrh4y@getsemani.domain.com.br    | [2019-09-07 09:47:18][launch_][INFO] log: normal
bitwarden_rs_bitwarden.1.dylbnxvbrh4y@getsemani.domain.com.br    | [2019-09-07 09:47:18][launch_][INFO] workers: 10
bitwarden_rs_bitwarden.1.dylbnxvbrh4y@getsemani.domain.com.br    | [2019-09-07 09:47:18][launch_][INFO] secret key: private-cookies disabled
bitwarden_rs_bitwarden.1.dylbnxvbrh4y@getsemani.domain.com.br    | [2019-09-07 09:47:18][launch_][INFO] limits: forms = 32KiB, json* = 10MiB
bitwarden_rs_bitwarden.1.dylbnxvbrh4y@getsemani.domain.com.br    | [2019-09-07 09:47:18][launch_][INFO] keep-alive: 5s
bitwarden_rs_bitwarden.1.dylbnxvbrh4y@getsemani.domain.com.br     | [2019-09-07 09:47:18][launch_][INFO] tls: enabled
bitwarden_rs_bitwarden.1.dylbnxvbrh4y@getsemani.domain.com.br     | [2019-09-07 09:47:18][rocket::fairing::fairings][INFO] Fairings:
bitwarden_rs_bitwarden.1.dylbnxvbrh4y@getsemani.domain.com.br     | [2019-09-07 09:47:18][_][INFO] 1 response: Application Headers
bitwarden_rs_bitwarden.1.dylbnxvbrh4y@getsemani.domain.com.br     | [2019-09-07 09:47:18][launch][INFO] Rocket has launched from https://0.0.0.0:80
bitwarden_rs_bitwarden.1.dylbnxvbrh4y@getsemani.domain.com.br     | [2019-09-07 09:47:18][ws][INFO] Listening for new connections on 0.0.0.0:3012.

ERRO
| [2019-09-07 09:46:52][rocket::config::error][ERROR] I/O error while setting tls.certs:
bitwarden_rs_bitwarden.1.hyqjtqll7sbr@getsemani.domnain.com.br    | [2019-09-07 09:46:52][_][INFO] No such file or directory (os error 2)


I am deploying the application to the docker stack.

**Comment by Ayitaka** [comment]
Its saying it cannot find the files. Your configuration is saying to check /ssl (not /path/to/docker-compose.yml/ssl).

So either make sure your certificates are in the literal directory /ssl or change your configuration to 
`- ./ssl:/ssl/: rw`
to indicate that the files are in a directory under the directory where you started docker-compose:

i.e. `/path/to/docker-compose.yml/ssl/`
with `/path/to/docker-compose.yml/ssl/certificate.pem`
and `/path/to/docker-compose.yml/ssl/bitwarden.pem`

**Comment by thiago304** [comment]
Giving back,

It went well when deploying was errors in the old replicas of the service, so now I have another problem, I can not establish ssl connection with bitwarden, publish ports 442: 80 on host and get the following SSL error:

This page isn't working 10.0.1.63 didn't send any data.
ERR_EMPTY_RESPONSE

**Comment by Ayitaka** [comment]
Not sure what 442:80 means.... default port for https:// is 443 or:
```
  ports:
   - 443:80
```
...in bitwarden service section). But you're connecting to something if youre getting that msg?

According to google, that error means something is (temporarily) wrong with the browser or (permanently) wrong with the certificate.

Try making sure your date+time are set correctly and match up, on your server and on your system, or check your anti-virus to make sure it isnt blocking the site for some reason, or clearing browser data/SSL State in your browser's settings (but this is a drastic last resort) - might help.

Certificates signed with SHA-1 (shouldn't happen anymore anywhere?) can also cause this error.

And apparently many other things can potentially cause that error...

Anyone else have any ideas?

**Comment by thiago304** [comment]
I'm sorry Ayitaka the port actually and 443: 80 which is posted on the host was just an error at the time of writing. I am connecting via Google Chrome and then I get this message.

As for the certificate, may be the problem, I generated as tutorial in the bitwardenrs wiki:

https://github.com/dani-garcia/bitwarden_rs/wiki/Private-CA-and-self-signed-certs-that-work-with-Chrome

Let's take a look at the internal CA created to see the certificate and key consistency for the internal hostname.

Thanks for the help.

Soon I'll be back with news.

**Comment by thiago304** [comment]
Haitaka,
Everything went perfect after I recreated the CA - Private key and certificate and then generated new certificates based on this new CA. However, it was a container-side certificate issue, thanks for clarifying my ideas.
