### ISSUE TITLE
Logs filling up with these entries

### ISSUE THREAD

**Issue by BobWs** [dani-garcia/bitwarden_rs#613]
Hi,

My Bitwarden-mysql logs are filling up these entries:

`[2019-09-09 10:31:14][rocket::rocket][INFO] GET /alive:`                         
`[2019-09-09 10:31:14][_][INFO] Matched: GET /alive (alive)`                      
`[2019-09-09 10:31:14][_][INFO] Outcome: Success`                                 
`[2019-09-09 10:31:14][_][INFO] Response succeeded.`                              
`[2019-09-09 10:31:24][rocket::rocket][INFO] GET /alive:`                         
`[2019-09-09 10:31:24][_][INFO] Matched: GET /alive (alive)`                      
`[2019-09-09 10:31:24][_][INFO] Outcome: Success`                                 
`[2019-09-09 10:31:24][_][INFO] Response succeeded.`                              
`[2019-09-09 10:31:34][rocket::rocket][INFO] GET /alive:`                         
`[2019-09-09 10:31:34][_][INFO] Matched: GET /alive (alive)`                     
`[2019-09-09 10:31:34][_][INFO] Outcome: Success`                                 
`[2019-09-09 10:31:34][_][INFO] Response succeeded.`

Could you please explain what this is and is this normal? Or do I have configured something wrong?

**Comment by dani-garcia** [comment]
That's from the healthcheck added recently to the docker image, it shouldn't cause any problems. If it bothers you, you can either disable it adding `--no-healthcheck` to the docker run command, or changing the `LOG_LEVEL` to warn

**Comment by BobWs** [comment]
Okay thanks! It doesn't bother me, was just wondering if it was a problem.
Thanks for clarifying!
