### ISSUE TITLE
bitwardenrs/server-mysql for raspberry pi

### ISSUE THREAD

**Issue by mcore** [dani-garcia/bitwarden_rs#614]
Hello, i noticed there is no build for raspberry for docker image bitwardenrs/server-mysql
bitwardenrs/server is working fine. Is there a plan to have a build for raspberry for mysql version as well? thanks!

**Comment by dani-garcia** [comment]
Yeah we've had some problems with the dependendencies while building those images, so at the moment they aren't available.

**Comment by mcore** [comment]
Thank you for the update! will be patiently waiting :)

**Comment by mprasil** [comment]
See here for more in depth info: #530

**Comment by etho201** [comment]
The last time I checked, MariaDB was the only MySQL compatible database that is **pre-built** for ARM. Is it possible to have bitwardenrs/server:raspberry point to a MariaDB database as opposed to the built in SQLite database?

**Comment by 0xERR0R** [comment]
Sorry for bothering: what is the current status of binary for raspberry pi with MySql support? On docker hub, there is only mysql image for arm64, on github are no precompiled binaries.

**Comment by mprasil** [comment]
I'm not aware of anyone actively working on the mysql images. The best thing to do is to follow updates on #530 as that is the actual blocker.
