### ISSUE TITLE
Disable ADMIN Page

### ISSUE THREAD

**Issue by tda90** [dani-garcia/bitwarden_rs#617]
Hello Everyone,
I've enabled the ADMIN PAGE, but I would like to know how to disable it back.
Since I don't need that's enabled all the time - I would like to disable it once I've finished my "administrative tasks".

**Comment by dani-garcia** [comment]
You'll need to remove the ADMIN_TOKEN setting, both the environment variable and from the config panel if any changes where made there.

**Comment by mprasil** [comment]
As the question was answered, I'm going to close this. Feel free to reopen if you need more help.
