### ISSUE TITLE
config.json -- storing plain text?

### ISSUE THREAD

**Issue by moranbw** [dani-garcia/bitwarden_rs#619]
Does it matter that we are storing the admin_token and smtp_password as plain text in the config.json?  Should the permissions of this file be by default more restrictive?

More asking then suggesting.  I guess this still does not necessarily expose a user's vault, which is the main thing.

**Comment by mprasil** [comment]
You can set the permissions of the file yourself - as long as the container user can read and write to it, it should work fine.

You can also provide these as environment variables and you can the work out yourself how to set them in secure manner.

**Comment by mprasil** [comment]
I'm going to close this one as there are multiple ways to provide the credentials without storing them in config.json and the permissions on the file itself can be set in any way as long as the service can read it and write to it. Feel free to reopen, if there's anything more we can do regarding this.
