### ISSUE TITLE
Offical Docker Hub image

### ISSUE THREAD

**Issue by jkaberg** [dani-garcia/bitwarden_rs#62]
Would you please setup an automated build for bitwarden_rs @ [Docker Hub](https://hub.docker.com)? 

Documentation found [here](https://docs.docker.com/docker-hub/builds/)

Thanks for the hard work you put into this 😄

**Comment by mprasil** [comment]
Hi @jkaberg, you can use [my image](https://hub.docker.com/r/mprasil/bitwarden/) if you'd like. It's automated build based on top of this source code, the only difference is docker hub focused README. (Just a commit I rebase on top of latest changes in this repo)

@dani-garcia the linked hub image accumulated quite a lot of users (to my surprise really) not sure what to do with it at this stage. I don't want to just discontinue it (I'm using it as well) and I don't mind maintaining it at all, but if you like I can give you access there or something to make it "official" and to give you some control over it if you're interested.

Whatever you prefer really as long as it's not confusing for current and future users.

**Comment by dani-garcia** [comment]
@mprasil personally I'm indifferent about it. If you want, you can PR the changes to the README to avoid having to rebase it every time and we can call your version the official.

I'm not sure how Docker Hub works, but if we do that maybe you can point your image to this repository directly and avoid having to use a fork to pull the changes? That way it would be completely automated and save you time.

You are right that now that people are using your image we simply can't take it down.

**Comment by mprasil** [comment]
So to sum up, the official image is available [here](https://hub.docker.com/r/mprasil/bitwarden/). This is now following the upstream source code. I think we can close this now.
