### ISSUE TITLE
MYSQL docker image

### ISSUE THREAD

**Issue by simeonlam** [dani-garcia/bitwarden_rs#620]
Hi everyone,

When I try to build bitwardenrs with mysql, but I got some problem
1. bitwardenrs/server-mysql:1.10.0 will not execute mysql migration script
2. bitwardenrs/server-mysql:latest invite email in admin page got 400 Page not found, but I build it myself is work normally
3. I try to use RDS mysql:5.7 to run migration script cannot auto execute on following migration script: `20180427155151`, `20180508161616`, `20180525232323`, `20180601112529`, `20180711181453`, `20180827172114`, `20180919144557`, `20181127152651`, `20190526216651`
But I can execute them by myself
```
Running migration 20190526216651
thread 'main' panicked at 'Can't run migrations: MigrationError(IoError(Custom { kind: Other, error: "formatter error" }))', src/libcore/result.rs:1084:5
```

Many thanks to the team whose maintain this project

**Comment by mprasil** [comment]
Did you run the migrations manually?

**Comment by simeonlam** [comment]
Yes, I use mysql client to execute by myself also added row to `__diesel_schema_migrations` table

**Comment by mprasil** [comment]
Well you shouldn't really. This should all be done automatically by bitwarden_rs.

**Comment by mprasil** [comment]
Hi @simeonlam, did you try running this with blank DB? Did that solve your problem?

**Comment by andrem1987** [comment]
I ran into the same problem when trying to migrate from sqlite to mariadb (10.1.41).
First i prepared the sqlite database as mentioned [here](https://github.com/dani-garcia/bitwarden_rs/issues/497#issuecomment-511827057).
Then i created a new mysql user with a corrosponding database, created and started the container.

The container immediately stops with the following error:

```
Running migration 20180114171611
thread 'main' panicked at 'Can't run migrations: MigrationError(IoError(Custom { kind: Other, error: "formatter error" }))', src/libcore/result.rs:1084:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at src/libcore/result.rs:1084
  11: bitwarden_rs::migrations::run_migrations
  12: bitwarden_rs::main
  13: std::rt::lang_start::{{closure}}
  14: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  15: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  17: std::panicking::try
             at src/libstd/panicking.rs:275
  18: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  19: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  20: main
  21: __libc_start_main
  22: _start
```
An empty table with the name `__diesel_schema_migrations` and the columns `version` and `run_on` was created, but thats it.

**Comment by andrem1987** [comment]
It was my fault... i created the datebase with the collation `utf8mb4` but it needs to be`utf8`.

**Comment by mprasil** [comment]
That sounds like slightly different problem, although it's a good tip to make sure the DB is created with proper collation.

**Comment by mprasil** [comment]
As there is no response, I'm going to close this. Feel free to reopen @simeonlam if you have more questions regarding this.
