### ISSUE TITLE
Docker admin panel for 1.10.0 doesn't show SQLite backup option

### ISSUE THREAD

**Issue by poblabs** [dani-garcia/bitwarden_rs#626]
Hi, 

The release notes for 1.10.0 say:

> Added backup option in the admin panel for the SQLite backend, remember to transfer those copies to separate drives!

But when I run the latest docker image (admin panel version Version: 1.10.0-4c07f05b), I do not see anywhere for the SQLite backup option. 

I also didn't see any mention of it in the wiki's [backing up the vault](https://github.com/dani-garcia/bitwarden_rs/wiki/Backing-up-your-vault) page. 

Not sure what I am missing?

**Comment by Skaronator** [comment]
#596
