### ISSUE TITLE
"Preflight respons is not succesful" when logging in Safari extension 

### ISSUE THREAD

**Issue by mikkelnl** [dani-garcia/bitwarden_rs#628]
MacOS updates Safari to 13.0, which cause the Bitwarden Safari Extension to stop working. Found out I had to update to Bitwarden 1.16.0 which includes a new extension version for Safari 13.0.

But using this version, I get the response 'Preflight respons is not succesful' when I try to login in the extension. Bitwarden itself/the app is working fine; it connects to my bitwarden_rs.

Any ideas what might cause this, or how to fix it? Thanks!

**Comment by vverst** [comment]
That should be fixed by https://github.com/dani-garcia/bitwarden_rs/pull/599.

Which version of bitwarden_rs are you running?

**Comment by mikkelnl** [comment]
I believe the latest; 1.10.0
And the webvault shows 2.11.0

**Comment by vverst** [comment]
The tagged bitwarden_rs 1.10.0 release (2c2276c) will not contain the fix.

Do you know the exact version from the logging? Example:
```
bitwarden_1  | /--------------------------------------------------------------------\
bitwarden_1  | |                       Starting Bitwarden_RS                        |
bitwarden_1  | |                      Version 1.10.0-4c07f05b                       |
bitwarden_1  | |--------------------------------------------------------------------|
bitwarden_1  | | This is an *unofficial* Bitwarden implementation, DO NOT use the   |
bitwarden_1  | | official channels to report bugs/features, regardless of client.   |
bitwarden_1  | | Report URL: https://github.com/dani-garcia/bitwarden_rs/issues/new |
bitwarden_1  | \--------------------------------------------------------------------/
```

**Comment by mikkelnl** [comment]
Could you explain how/where I can find that info? CMD line command maybe?

**Comment by mikkelnl** [comment]
Found it on the /admin page:

Version: 1.10.0-469318bc

**Comment by vverst** [comment]
The version `1.10.0-469318bc` is still before the commit that fixed the issue.
So you probably have to update.

**Comment by mikkelnl** [comment]
Thanks for the info, appreciate it... will try to update asap.

**Comment by lost-carrier** [comment]
If anyone is landing here from Google (like me): ```bitwardenrs/server:1.10.0``` might be the latest release, but ```bitwardenrs/server:latest``` is even a bit later... ;-)

**Comment by mprasil** [comment]
That's correct, there wasn't yet a numbered release containing the fix. @dani-garcia maybe we should release 1.10.1 as this hits a lot of people that don't want to use latest.

**Comment by luckydonald** [comment]
Pulling 1.10.1 did not work.
```bash
$ docker pull bitwardenrs/server:1.10.1
Error response from daemon: manifest for bitwardenrs/server:1.10.1 not found
```

**Comment by mprasil** [comment]
@luckydonald that version wasn't released. You'll have to use latest for now.

**Comment by timreuscher** [comment]
I'm getting this error with the latest bitwardenrs Version 1.11.0-d292269e

**Comment by luckydonald** [comment]
Could you guys cut a bugfix release for this bugfix please?

**Comment by xthursdayx** [comment]
I'm still having this problem with the most recent version of Safari and Bitwarden... I'm using a custom BW server, if that matters.

**Comment by luckydonald** [comment]
@xthursdayx Yes that matters.
Upgrade to the latest `bitwarden_rs` (in which issue tracker you are writing)

**Comment by xthursdayx** [comment]
> @xthursdayx Yes that matters.
> Upgrade to the latest `bitwarden_rs`, or merge the changes made here into your custom version.

Oops, apologies, I should have been more clear about what I meant - that I was running this as a docker container. However I just checked the Docker Hub page for the image I was using (https://hub.docker.com/r/mprasil/bitwarden/) and noticed that it has been depreciated in favor of https://hub.docker.com/r/bitwardenrs/server, so I will update my docker accordingly.

**Comment by luckydonald** [comment]
Lel, I think I used that one previously as well.

**Comment by dani-garcia** [comment]
Closed due to inactivity.
