### ISSUE TITLE
Save logs to a file

### ISSUE THREAD

**Issue by dani-garcia** [dani-garcia/bitwarden_rs#63]
From #58:

> it would be nice to have the logs sent to a file rather than the console, that would make it easier to debug and also allow people to use a logging system like ELK to potentially track metrics.

> The current logging is due to the web framework we use, Rocket. At the moment Rocket doen't support configuring the logging, but I know it's in the roadmap for future versions.

**Comment by ptman** [comment]
Some ways to achieve this are: run under systemd so that output is captured by journal or pipe to logger:

    ./bitwarden_rs | logger -s -t bitwarden

**Comment by campZero** [comment]
I run the container under unRAID, how could I implement this or is this to be done from "outside" of the container ?

**Comment by mprasil** [comment]
Docker container logs to stdout, so docker daemon should be able to capture those. Not sure if unraid has some interface to capture and show those logs?

**Comment by ptman** [comment]
@campZero take a look at the `--log-driver` option to `docker run`

**Comment by campZero** [comment]
Well the docker.log file stays empty, unraid can show the log of bitwarden, but in this log there is no evidence of an unseccessful login attempt, it's just all kinds of GET this and POST that, so fail2ban could not capture possible bruteforce attempts (which in my case is what I'm trying to achieve.)

I would need a file that I could expose to the letsencrypt container which houses the fail2ban for the reverse proxy, so the file would need to be on the unRAID or in the /data folder of bitwarden, but looking at the docker container layout is ancient greek in reverse to me, sadly.

**Comment by dani-garcia** [comment]
To keep the issue tracker more focused, I'm closing this issue in favor of the meta issue at #246.
