### ISSUE TITLE
Issue "preflight response not successful"

### ISSUE THREAD

**Issue by damanti-me** [dani-garcia/bitwarden_rs#636]
regarding that post: 
[https://www.bountysource.com/issues/80665655-preflight-respons-is-not-succesful-when-logging-in-safari-extension](url)
MacOS updates Safari to 13.0, which cause the Bitwarden Safari Extension to stop working for self hosting options. Found out I had to update to Bitwarden 1.16.0 which includes a new extension version for Safari 13.0.

But using this version, I get the response 'Preflight respons is not succesful' when I try to login in the extension. Bitwarden itself/the app is working fine; it connects to my bitwarden_rs.
please update the Bitwarden App for Hass.io

**Comment by mprasil** [comment]
See here #628. You might need to update to "latest"

**Comment by poldim** [comment]
Running into this now only on Safari (Chrome is fine), running the latest versions of everything.  Anyone have any recommendations on what to check?

![image](https://user-images.githubusercontent.com/16869713/74164317-01a94880-4bfa-11ea-8ab1-44472f38ec71.png)


![image](https://user-images.githubusercontent.com/16869713/74164297-f7874a00-4bf9-11ea-94a1-b0057b618bde.png)

**Comment by damanti-me** [comment]
what version is your Bitwarden app on your mac?

**Comment by poldim** [comment]
Latest from the App Store

**Comment by damanti-me** [comment]
I downloaded the app directly from the bitwarden website. The browser addon is included. Works fine for me...

**Comment by poldim** [comment]
And you’re self hosting?

**Comment by damanti-me** [comment]
> And you’re self hosting?
> […](#)
> On Feb 11, 2020, at 2:54 AM, damanti-me ***@***.***> wrote: ﻿ I downloaded the app directly from the bitwarden website. The browser addon is included. Works fine for me... — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

yes, i do
