### ISSUE TITLE
Not able to run container with SMTP support

### ISSUE THREAD

**Issue by jhornet** [dani-garcia/bitwarden_rs#637]
Hi there, first of all many thanks to the work you have put in here!

I am using the docker container to host bitwarden_rs on my own premise.

When I run the docker container by using the command (as described here: [https://github.com/dani-garcia/bitwarden_rs/wiki/SMTP-configuration](url)):

sudo docker run -d --name bitwarden \
-e SMTP_HOST=<smtp.gmail.com> \
-e SMTP_FROM=<info@gmail.com> \
-e SMTP_PORT=587 \
-e SMTP_SSL=true \
-e SMTP_PASSWORD=<xyz>
-e DOMAIN=https://mydomain:8443 \
-p 8443:80 \
bitwardenrs/server:latest

I am getting the error: **-bash: smtp.gmail.com: No such file or directory**

Wondering what I am doing wrong... Any ideas how to solve the issue?
Thank you in advance

**Comment by McKael** [comment]
@jhornet Remove the characters `<` and `>` from the command.

**Comment by jhornet** [comment]
Thank you very much that solve the issue :-)
