### ISSUE TITLE
Accessing credentials in applications (preferably PHP)

### ISSUE THREAD

**Issue by lamka02sk** [dani-garcia/bitwarden_rs#646]
We are migrating our existing infrastructure to cloud and we are trying to secure our application secrets a little bit more. Our plan was to use bitwarden as both: secrets storage for apps and credential manager in our company. The problem is that official image is extremely heavy for our limited use and it looks like bitwarden_rs does not support docker secrets (?).

The question we couldn't find answer for is if we can access valut's credentials from our applications. Preferably from PHP, or if there is something better/more capable/easier to use (Rust, Node,...).

Thank you for your recommendations!

**Comment by mprasil** [comment]
This should be technically possible, however the problem with this approach is that you'll end up implementing huge part of the functionality on your own. Bitwarden is encrypting all credentials client side, so a lot of the logic is also there and obviously all of the encryption.

I think you're looking at two vastly different use cases where on one side bitwarden is good fit, but for the other use case something like Hashicorp Vault would probably work better.

**Comment by BlackDex** [comment]
I agree with @mprasil.
The only other option i can think of, is using the bitwarden cli: https://blog.bitwarden.com/bitwarden-command-line-tool-now-available-e6184407b719

Call the cli tool via the PHP tooling, and let it output as JSON and parse that json with PHP.

**Comment by lamka02sk** [comment]
@BlackDex Thank you! The CLI looks very promising and we will probably implement it this way.

The problem with another solutions is synchronization. We would like to achieve automatic secret updates when they change in the company's valut. It's definitely not the right solution, but most convenient.

**Comment by mprasil** [comment]
I think the question was answered and we can close this, but feel free to reopen if more questions regarding this pop up.
