### ISSUE TITLE
Idea: local HIBP

### ISSUE THREAD

**Issue by My1** [dani-garcia/bitwarden_rs#649]
couldn't one download extract and use the HIBP database locally to avoid the need for any APIs or API keys or whatever?

obviously just extracting wouldnt be enough since a search on a 30GB blob wouldnt be very awesome but by splitting them into several smaller files by prefix (similar to the API) it could be done I even had a PHP script somewhere which I used to split the files (no idea whether it helps but at least it could show the process)

I obviously would not expect bitwarden to do the actual splitting. but rather you split it beforehand and just give it in as a folder to mount and it can have fun

**Comment by dani-garcia** [comment]
Well the Passwords API which is the one you mention works without an API key, the key is only needed for the breached accounts API, which lists all the breaches found for a given email address, and as far as I know there is no way to bulk download that data.

**Comment by BlackDex** [comment]
There isn't.
We could try to generate a link to the correct site with the email prefilled.

There could be an other way i tested before. But that kinda defeates the whole apiv3. And a chance of getting blocked. Also, i think a link would work just as well.

**Comment by My1** [comment]
okay I am deeply sorry, I misunderstood that part

**Comment by My1** [comment]
although a local passwords API might be fun for intranet-only systems

**Comment by dani-garcia** [comment]
Right, I can imagine for systems with a lot of users it could be useful. Checking the official page, the databases aren't that big and they are easy to obtain (https://haveibeenpwned.com/Passwords).

That said, this change would require modifications in the clients themselves, as the Passwords API is used directly in the clients, so at the moment there isn't much we can do ourselves.

**Comment by My1** [comment]
well I have no idea how to rust but at least I have some idea how to do it in PHP (the language I know best) maybe that can help adapting it

**Comment by BlackDex** [comment]
@my1, it did triggered me to do some changes. And i created a pull request so you are able to just click on a link to do a data breach check without buying an API key.
Though buying an API key makes the integration a bit more complete.

**Comment by mprasil** [comment]
I'm closing this one as the PR from @BlackDex does very good job for HIBP. The local password API would need client change and actually local implementation of the API which is way out of scope of this project.
