### ISSUE TITLE
"disable admin token" in admin panel could be improved

### ISSUE THREAD

**Issue by My1** [dani-garcia/bitwarden_rs#650]
the message "Disable Admin Token (Know the risks!)" is kinda ambigous as it can be read as to "disable the access to admin completely" instead of "let everyone in", similar to as how disabling passwords on SSH does not mean "do not require passwords" but rather "require a different auth mechanism, aka public keys"

**Comment by dani-garcia** [comment]
You are definitely right that the naming is confusing, and something like "bypass admin security" might be more adecuate. We can easily change the description in the admin page, but changing the config option would be a breaking change (Though I think just the description would be good enough for now)

**Comment by My1** [comment]
exactly, especially considering you dont just get the env var out of nowhere and the wiki clearly states the purpose and stuff

**Comment by dani-garcia** [comment]
Fixed in https://github.com/dani-garcia/bitwarden_rs/commit/662bc2752345ef37cb394b2dd709b269dab86fd1#diff-6d8a5e2104954a026de2bfe2b936aea4, thanks!
