### ISSUE TITLE
creating new collection/manage org from desktop software

### ISSUE THREAD

**Issue by My1** [dani-garcia/bitwarden_rs#659]
readme says to post here regardless of client, so that's what I'm doing.

is there a way to create a collection/folder/whatever in an organization from the desktop application, or manage organizations in any way?

**Comment by mprasil** [comment]
AFAIK Desktop app and mobile apps share almost the same codebase and none of those allow managing organizations. So most likely you need to use web interface for that.

**Comment by mprasil** [comment]
I think this was answered, so closing it. Feel free to reopen if you need more help.
