### ISSUE TITLE
Possible to export data using API ?

### ISSUE THREAD

**Issue by ss-17** [dani-garcia/bitwarden_rs#662]
Hi.

I wish to programmatically export data of an organization to a file. Is there any API for it? Will really appreciate if you can provide some pointers.

Thanks

**Comment by dani-garcia** [comment]
You should be able to use the console client, but I haven't tested it: https://help.bitwarden.com/article/cli/#export

**Comment by ss-17** [comment]
Thanks for the quick response. Before posting here, I did go through the documentation of that cli client but can't seem to find a way to point it to a custom self-hosted server instead of bitwarden's own service.

**Comment by dani-garcia** [comment]
This should work, I think: https://help.bitwarden.com/article/cli/#config

**Comment by ss-17** [comment]
Ahh sorry. Don't know how I missed that. Should learn to read thoroughly. Thank you so much :)

**Comment by 0xERR0R** [comment]
Export of organization entries is not possible via CLI, see Issue https://github.com/bitwarden/cli/issues/44

**Comment by mprasil** [comment]
I think this was answered, so closing it, but feel free to reopen if you need more help.
