### ISSUE TITLE
 Install Bitwarden on Centos 7

### ISSUE THREAD

**Issue by zJeanMiliodas** [dani-garcia/bitwarden_rs#665]
I am performing the procedure of the installation. But I have a doubt. When I do the installation. I can put anything on this line: Enter the domain name for your Bitwarden instance (eg bitwarden.example.com) :?

Can I also just put the IP VM? Because it just doesn't work.

The problem is that testing on CentOS 7 when I run the "./bitwarden update" command it tells you that the mysql containey is still restarting. VM have 4GB.

I did a test on Ubuntu and the problem is different. When I made the command "./bitwarden update" it gave a message that was successful. However when I access my browser it fails. What do I do?

**Comment by dani-garcia** [comment]
Are you running the official server images? Bitwarden_rs doesn't have any './bitwarden update' commands.

You should check the wiki:
If you want to use the docker image: https://github.com/dani-garcia/bitwarden_rs/wiki/Starting-a-Container

If you want to compile and run the server directly: https://github.com/dani-garcia/bitwarden_rs/wiki/Building-binary

**Comment by mprasil** [comment]
`./bitwarden update`is definitely from [upstream](https://github.com/bitwarden/server/blob/master/scripts/bitwarden.sh#L88), so @zJeanMiliodas needs to ask there instead. This repository is for unofficial 3rd party bitwarden server implementation. Closing this now.
