### ISSUE TITLE
Cannot create Recovery Code

### ISSUE THREAD

**Issue by paradeiser** [dani-garcia/bitwarden_rs#669]
I have this issue, I discussed earlier with kspearrin at bitwarden/web 
Might be an bitwarden_rs issue:
https://github.com/bitwarden/web/issues/421

I cannot create/view recovery codes if the first 2FA option (Auth-App, 6-digit code) is not selected.
If Duo and/or Mail is activated (working just fine) I still get the message:
"No 2FA activated. After you activate 2FA you can view code here…"

thank you,
pardeiser

**Comment by BlackDex** [comment]
I see in the code that there is no recover code generated during the duo setup.
This should be fixed to do that.

This also goes for the e-mail 2FA. Since that also doesn't generate a recover token.

**Comment by dani-garcia** [comment]
This is fixed in the latest commit https://github.com/dani-garcia/bitwarden_rs/commit/e449912f05d63a3499609ae00184796dd7390bf0. You should delete the email or duo 2fa and then reenable it again for the changes to apply
