### ISSUE TITLE
Importing from exported Bitwarden JSON wipes out categories

### ISSUE THREAD

**Issue by hank** [dani-garcia/bitwarden_rs#672]
I had nicely categorized logins from Lastpass and after exporting and re-importing into another instance those were gone. I assume they weren't carried with the exported data. Please allow export and import of these. Thanks!

**Comment by hank** [comment]
... and now I realized that it also doesn't seem to import categories! So all the categorized logins are actually GONE COMPLETELY. Good thing I have the original instance around as a backup.

**Comment by hank** [comment]
Just tried exporting CSV, and it appears to lack all categorized logins.

**Comment by hank** [comment]
A workaround for now is to just copy the old bitwarden data directory from the old container (mprasil/bitwarden) to the new bind mount for the bitwardenrs/server container and start it up. It seems to work just fine with the old database and everything shows up nicely.

**Comment by mprasil** [comment]
When you say categories, do you mean collections? Because collections are in organization and user-side export does not contain organization passwords. For that you need to do the export in the organization interface.

**Comment by mprasil** [comment]
I'm closing this as there is no response, but feel free to reopen if you need more help with this.
