### ISSUE TITLE
failed to falidate DUO credentials

### ISSUE THREAD

**Issue by Trigun** [dani-garcia/bitwarden_rs#675]
Hi, when trying to config the duo 2fa it keeps saying: failed to falidate duo credentials.
I did a complete new install.

**Comment by MartB** [comment]
Did you set up the duo api credentials inside the configuration?

=> DUO_IKEY etc.

**Comment by Trigun** [comment]
yes, I setup: 
The integration key
The Secret key
API -hostname

also, I had it working before but for some reason(maybe due to an update) I keep having the same error.

Thx for your help!

**Comment by Firestorrrm** [comment]
Encountering the same error after doing a fresh install.

`bitwarden_1  | [2019-10-22 19:37:08][bitwarden_rs::error][ERROR] Failed to validate Duo credentials.
bitwarden_1  | [CAUSE] Error(
bitwarden_1  |     Io(
bitwarden_1  |         Custom {
bitwarden_1  |             kind: TimedOut,
bitwarden_1  |             error: "timed out",
bitwarden_1  |         },
bitwarden_1  |     ),
bitwarden_1  |     "https://api-xxxxxx.duosecurity.com/auth/v2/check",
bitwarden_1  | )`

**Comment by Firestorrrm** [comment]
Encountering the same error after a fresh install...

```
bitwarden_1  | [2019-10-22 19:37:08][bitwarden_rs::error][ERROR] Failed to validate Duo credentials.
bitwarden_1  | [CAUSE] Error(
bitwarden_1  |     Io(
bitwarden_1  |         Custom {
bitwarden_1  |             kind: TimedOut,
bitwarden_1  |             error: "timed out",
bitwarden_1  |         },
bitwarden_1  |     ),
bitwarden_1  |     "https://api-xxxxxx.duosecurity.com/auth/v2/check",
bitwarden_1  | )

**Comment by Trigun** [comment]
Apperantly the authenticator app also doesn't work.

hopefully it will be fixed soon as 2FA is crucial for a tool like this.

thnx!

**Comment by shauder** [comment]
Duo is working fine for me. Do you have it setup through the admin page or did you set it up at the user level?

I have mine just configured for my user since I am using my own personal duo and others can use theirs.

**Comment by Trigun** [comment]
> Duo is working fine for me. Do you have it setup through the admin page or did you set it up at the user level?
> 
> I have mine just configured for my user since I am using my own personal duo and others can use theirs.
> 
> EDIT: I was on 1.9.1-8be2ed62 and I upgraded to 1.11.0-5ac66b05 and Duo is still working for me.

With an upgrade it should work but with a new install it doesn't work. not sure why as I've tried older versions as well. not sure where it goes wrong.

**Comment by Trigun** [comment]
issue is solved! to solve it check if the time is in sync with(for example) with your logfile output.
If not, just do a hwclock tot sytem sync and it will work once you try to setup the 2fa

**Comment by shauder** [comment]
This is a common problem with any 2FA solutions.

**Comment by Trigun** [comment]
> This is a common problem with any 2FA solutions.

I know, but for some reason I never checked the time assuming once its set correclty is should always work. glad its fixed now :)
