### ISSUE TITLE
fail2ban regex will match but no match found when actually running

### ISSUE THREAD

**Issue by Ezzahhh** [dani-garcia/bitwarden_rs#678]
I have followed the instructions in the wiki to setup fail2ban. My setup is with caddy and bitwarden_rs both running in docker with root and using cloudflare cdn for https. My log is being output in /bw-data/bitwarden.log and it appears to be updating. My OS time and the log time appear to match up. When I run fail2ban's regex on the given one in the wiki and the bitwarden.conf it appears to find matches. However, when I try to spam logins myself the fail2ban log does not show any indication that anything is happening even with the verbosity set to DEBUG. Comparatively, the ssh blocking appears to work. 

bitwarden.conf

```
[INCLUDES]
before = common.conf

[Definition]
failregex = ^.*Username or password is incorrect\. Try again\. IP: <HOST>\. Username:.*$
ignoreregex =
```

bitwarden.local

```
[bitwarden]
enabled = true
port = 80,443
filter = bitwarden
action = iptables-allports[name=bitwarden]
logpath = /bw-data/bitwarden.log
maxretry = 3
bantime = 14400
findtime = 14400
```

fail2ban.log it basically just does usual startup and ends like this:

`2019-10-22 23:05:34,232 fail2ban.jail           [15452]: INFO    Jail 'bitwarden' started`

**Comment by hwwilliams** [comment]
Hey @Ezzahhh , you may have to use the following action in bitwarden.local since you're using docker and docker uses the forward chain in iptables.

`action = iptables-allports[name=bitwarden, chain=FORWARD]`

**Comment by Ezzahhh** [comment]
My understanding from the wiki was to not include the chain forward because I have docker AND caddy as a reverse proxy in front.

**Comment by hwwilliams** [comment]
In that case I'm not too sure, I'm also using docker but with Traefik instead of Caddy. I use the `chain=forward` action as I mentioned and its working fine for me with no changes to Traefik.

Perhaps someone else can chime in.

**Comment by Ezzahhh** [comment]
Yeah it's definitely something to do with my bitwarden config, because fail2ban is banning IPs for sshd and that is working fine.

**Comment by dani-garcia** [comment]
Closed due to inactivity.

**Comment by savowe** [comment]
I had the very same issue. Tried some things posted in other issues such as checking for correct timezone settings and so forth nothing worked. Even though `fail2ban-regex` got all the correct hits with the regex `^.*Username or password is incorrect\. Try again\. IP: <HOST>\. Username:.*$'` it would not work when actually running fail2ban.
It started working when I changed the timestamp to
`-e LOG_TIMESTAMP_FORMAT="%Y-%m-%d %H:%M:%S"`
leaving out the `%3f` at the end.
