### ISSUE TITLE
Email 2FA not sending email when trying to login (requires pressing "send again")

### ISSUE THREAD

**Issue by 80dB** [dani-garcia/bitwarden_rs#682]
We enabled email 2FA and when logging in from a new client we correctly get the message that we need to type in the code from the email. However the email is not send until "send again" is pressed. 

Tested in web vault, desktop client and browser plugin.

The log will contain this upon logging in for the first time:
JsonError. {"TwoFactorProviders":[1],"TwoFactorProviders2":{"1":{"Email"....

Only after pressing "send again" will the log say that an email was sent.

bitwarden_rs v1.11-alpine running in Docker
Latest version of desktop/plugin software

I'm suspecting that the original server software will send you an email upon trying for the first time.

Also, unless I misinterpreted the code, email 2fa should be available as soon as email functionality has been turned on (smtp settings), however we specified smtp from/host/port/sll/username/password but email 2fa wouldn't work until we either set ENABLE_EMAIL_2FA or _ENABLE_EMAIL_2FA to true (not sure which one did the trick, specified them both).

**Comment by BlackDex** [comment]
@80dB As this is an old post and there are a lot of items added and fixed, and i have tested this my self just yet i think this is either fixed or something configured wrong on the server side.

Therefor i suggest to close this ticket.
