### ISSUE TITLE
Bitwarden Admin Portal

### ISSUE THREAD

**Issue by gfish69** [dani-garcia/bitwarden_rs#684]
I am new to Linux and Docker. Jumping in with both feet, I have setup an Unraid server and loaded Bitwarden Docker. I have it running behind reverse proxy and all seems well, but according to Bitwarden help I should be editing global.override.env by adding my email username. 

Example: adminSettings__admins=john@example.com,bill@gmail.com,tom@example.com

I have tried "ip address"/admin and get the following error:
The admin panel is disabled, please configure the 'ADMIN_TOKEN' variable to enable it

What am I missing? Thanks in advance !

**Comment by dani-garcia** [comment]
The bitwarden help is for the official server image, which doesnt apply to bitwarden_rs.

The usage guides for bitwarden_rs are in the wiki, here are some that might help:
https://github.com/dani-garcia/bitwarden_rs/wiki/Starting-a-Container
https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-admin-page

**Comment by gfish69** [comment]
I did try linked enabling admin page. All commands work except last (bitwardenrs/server:latest)
 I get: # docker run -d --name bitwarden \
> -e ADMIN_TOKEN="randomkey" \
> -v /bw-data/:/data/ \
> -p 80:80 \
> bitwardenrs/server:latest
sh: 1: docker: not found
#
I am using the docker in Unraid. Docker name is bitwarden. Any idea? Thanks again!

**Comment by dani-garcia** [comment]
Well if the docker command is not found, you might need to make sure it's available in your PATH, or maybe you need to use the GUI to create the container, I don't know much about unraid.

**Comment by dani-garcia** [comment]
Closed due to inactivity.
