### ISSUE TITLE
Issue with mounting directories as a data volume

### ISSUE THREAD

**Issue by deeztek** [dani-garcia/bitwarden_rs#686]
I realize this is probably an odd issue, I'm wanting to deploy bitwardenrs on Vsphere Integrated Containers. One of the limitations with VIC that I'm running into is the fact that you are not able to mount directories as a data volume. So, including the -v option for persistent storage in the command below fails:

docker run -d --name bitwarden -v /bw-data/:/data/ -p 80:80 bitwardenrs/server:latest

If I don't use the -v option, the container gets created successfully, but I'm assuming that I don't have persistent storage at at that point. One of the workarounds is to create a volume before-hand and then use that in the container. So, I created a bw-data volume, but I'm  not really clear on how to integrate that into bitwardenrs.

I would appreciate some help on this.

Thanks a lot!

**Comment by dani-garcia** [comment]
Can you try to remove the slashes from the left side of the `:` in the `-v` parameter?

Like this:
```
docker run -d --name bitwarden -v bw-data:/data -p 80:80 bitwardenrs/server:latest
```

I think Docker would interpret that as a volume name instead of a directory name.

**Comment by deeztek** [comment]
Thanks for the suggestion. It seems to have worked, docker created the container successfully. The /data is a NFS share. So, I'm assuming the bw-data is now mapped to /data NFS share. What type of data/files should I be able to find there?

**Comment by dani-garcia** [comment]
Well the /data path is where the bw-data gets mounted inside the volume, not where it's mapped externally, I'm not sure how to access the data inside a docker volume directly.

About the structure, the important files are the db.sqlite3* files from the database, one attachments folder if you use them, and the config.json file if you use the admin page.

**Comment by mprasil** [comment]
@deeztek did that answer your question?

**Comment by deeztek** [comment]
@mprasil yes. I was able to get everything working. Thanks a lot for the help!
