### ISSUE TITLE
With SIGNUPS_ALLOWED set Create user form can expose existing users email

### ISSUE THREAD

**Issue by danmed** [dani-garcia/bitwarden_rs#691]
I have the latest bitwarden mysql docker image from dockerhub running. Everything is working great but when i went to test if the create accounts had been disabled, it auto filled my email address in..

When i hit submit it told me the user already existed.. Seems to be that it shouldn't even be checking against the database in order to reveal that the email address i had entered existed.. 

I know no one else would autofill using my email address, but it does leave it open to atleast telling an attacker that an account exists

**Comment by BlackDex** [comment]
The autofill is probably something of you own browser.
This doesn't magically get extracted from the database and guessed for the person who want's to login.

It only gets pre-filled when using the link from the e-mail sent if you have an invite e-mail.

About the "user already exists" message, there is no way to not show that message if someone want's to register. You can't report a random error, and the web-interface needs to know it can continue with the signup process.

So, i'm not sure if this can be fixed or not. from the server side.

**Comment by danmed** [comment]
I'm aware that the box was filled in from my browser, that's not the issue.. the issue i'm trying to point out is that half the problem for an attacker to guess the username.. there's basically a feature there telling them they've hit a good account.

If i've got registrations turned off, then the button to create an account shouldn't even exist.. let alone confirm there is an account with that name being used already.

**Comment by mprasil** [comment]
That's good point. I've created PR to fix that.
