### ISSUE TITLE
Modify design without rebuild

### ISSUE THREAD

**Issue by colundrum** [dani-garcia/bitwarden_rs#692]
Hello,
Is it possible to modify design (web pages) without rebuilding the app ?
Thanks

**Comment by BlackDex** [comment]
If you talk about the web-vault.
You can point the app/docker to a specific path for the web-vault without a rebuild of I'm correct.

**Comment by colundrum** [comment]
Thank you so I need to find this specific path

**Comment by BlackDex** [comment]
@colundrum you can find that here: https://github.com/dani-garcia/bitwarden_rs/blob/77b78f09913e70c5f313980657b5c9ba02c2eb3b/.env.template#L30

**Comment by mprasil** [comment]
I think this has been answered, so closing the issue now, but feel free to reopen if more help is needed.
