### ISSUE TITLE
DOCKER： failed to start containers: bitwarden

### ISSUE THREAD

**Issue by liangxyz** [dani-garcia/bitwarden_rs#694]
hello ,I found that the bitwarden_rs cant run in my vps
when I use command line :docker start bitwarden .it have an error 
`Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"bitwardenrs/server:latest\": stat bitwardenrs/server:latest: no such file or directory": unknown
Error: failed to start containers: bitwarden
`
So can any body help me ? thank you very much

**Comment by BlackDex** [comment]
Looks like an issue with the command line arguments.
Please check if if it you didn't make a mistake with some of the arguments.
Please double check the wiki: https://github.com/dani-garcia/bitwarden_rs/wiki/Starting-a-Container

**Comment by liangxyz** [comment]
hello,when I use this command ,it returned an error again 
`docker: Error response from daemon: Conflict. The container name "/bitwarden" is already in use by container "93255bc2bec8d1222b9472a349bb3f1fe1f537eab7a7a5d413253d6287954fd4". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
`
