### ISSUE TITLE
Errors in log default config

### ISSUE THREAD

**Issue by keatontaylor** [dani-garcia/bitwarden_rs#697]
This message effectively fills my logs and occurs ~5 mins depending on the number of connected clients I have. I do not have web sockets enabled, which I believe this route is for, but it would be nice to suppress messages such as this as they get quite annoying when looking for other things in the docker logs. 

Perhaps my config is wrong since others don't seem to be reporting this issue, but I'd thought I'd bring it up in case other have experienced it and to bring it to the attention of the developer. 

[2019-11-02 03:24:11][_][ERROR] No matching routes for OPTIONS /notifications/hub/negotiate.
[2019-11-02 03:24:11][_][WARN] Responding with 404 Not Found catcher.

**Comment by dani-garcia** [comment]
Yeah I know there are some annoying entries in the logs, at the moment we are depending on the web servers logs, but that's all or nothing, we can't selectively hide some logs and not others. Eventually I'd want to migrate to a custom logging solution with our own logic, but I haven't had much time lately.

**Comment by dani-garcia** [comment]
Okay in the latest commits in master I've created a new custom logging system that should be filtering most of the useless mesages out, can you give it a try?

**Comment by dani-garcia** [comment]
Closed due to inactivity.
