### ISSUE TITLE
.env file is not working on windows

### ISSUE THREAD

**Issue by IrosTheBeggar** [dani-garcia/bitwarden_rs#698]
I compiled binaries for both Windows and OSX. The OSX worked with my .env file as expected but the windows versions is ignoring my .env file

**Comment by dani-garcia** [comment]
It works for me, make sure the file doesn't have a hidden extension like .env.txt, and make sure it's placed in the correct location.

**Comment by IrosTheBeggar** [comment]
Looks like this has something to do with permissions and where I execute the file on Windows.  I got it working.  

Thanks
