### ISSUE TITLE
How to support Multiple Yubikey's?

### ISSUE THREAD

**Issue by mattkerrison** [dani-garcia/bitwarden_rs#700]
I followed: https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-Yubikey-OTP-authentication

However I'm wondering how to support multiple Yubikeys, as the Client_ID & Secret_Key that need to be specified in environment settings will be different per key?

**Comment by dani-garcia** [comment]
As far as I know, you only need one client ID and secret key to authenticate with Yubico's API, but that allows you to add multiple Yubikeys for multiple users ( I think the interface allows 5 keys per user and unlimited users)

**Comment by shauder** [comment]
That is correct @dani-garcia. I have two assigned to my user.

**Comment by dani-garcia** [comment]
Closed due to inactivity.
