### ISSUE TITLE
Customizable TOTP tolerance

### ISSUE THREAD

**Issue by arjones85** [dani-garcia/bitwarden_rs#705]
When logging into Bitwarden, I am able to use an "old" OTP code from Authy long after it has already changed over to another one. Is this expected?

**Comment by fbartels** [comment]
Hi @arjones85, 

how "long" ago are you talking? Could be related to https://github.com/dani-garcia/bitwarden_rs/pull/657

**Comment by arjones85** [comment]
When I tested it was a full 10 seconds old but was still accepted.

I don't have any time drift, all devices involved here are NTP bound and syncing their time fine.

**Comment by timendum** [comment]
It's a standard feature, recommended in the rfc[1].

> The validation system should compare OTPs not only with the receiving timestamp but also the past timestamps that are within the transmission delay. A larger acceptable delay window would expose a larger window for attacks. We RECOMMEND that at most one time step is allowed as the network delay.

The time window is 30s, so the code is valid for 1 minute.

[1] [rfc6238](https://tools.ietf.org/html/rfc6238)

**Comment by arjones85** [comment]
Got it, that makes sense!

I'm not sure it's necessary for my setup, but I can see how technically reducing the security by 66% (by allowing up to 3 codes that could be guessed vs just 1) could raise a stink in larger organizations.

I'm in support of a configuration option for this.

**Comment by BlackDex** [comment]
Umm i think this should not be possible since it should mark that code as already used if it has been used already. If the current code or a future code as been used it should not be able to be used again. That is at least how i changed it a few commits ago.

Making this configurable is a nice addition. But i think it should be either false, no time drift, or true, just the previous, current or future one. Nothing more

**Comment by dani-garcia** [comment]
I think the OP means using an unused code that isn't the current one, not using one that's already used.

About giving options, yeah allowing a higher range doesn't make much sense, but at the same time we expect admins to know what they are doing, for example we allow someone to do ADMIN_TOKEN=a, even if having a one character password is a terrible idea. Personally as long as the setting is explained correctly I'm okay with either option.

**Comment by BlackDex** [comment]
Ah, that makes sense indeed about the unused code. Well, if someone needs more then 1 step they better check the time on the devices ;).

But good option indeed.

(As a workaround for now, set the server 30 seconds ahead :p )

**Comment by dani-garcia** [comment]
Resolved in #713, setting AUTHENTICATOR_DISABLE_TIME_DRIFT=true will disable the extra tolerance, only allowing the current time step.
