### ISSUE TITLE
Cannot get notifications / websockets work on apache

### ISSUE THREAD

**Issue by totti4ever** [dani-garcia/bitwarden_rs#708]
I am getting a 404 when opening https://bw.domain.tld/notifications/hub/negotiate in my browser and an error message when I open https://bw.domain.tld/notifications/hub:
`{"ErrorModel":{"Message":"'/notifications/hub' should be proxied to the websocket server or notifications won't work. Go to the README for more info.","Object":"error"},"Message":"","Object":"error","ValidationErrors":{"":["'/notifications/hub' should be proxied to the websocket server or notifications won't work. Go to the README for more info."]},"error":"","error_description":""}`

Any ideas on what I did wrong? Rest is working smoothly and perfectly! Am I just testing wrongly? Should I do something else than open the URLs in browser?

P.S.: I am using docker-compose and have enabled websockets and declared port 3012

```
<VirtualHost` *:443>

    SSLEngine on
    SSLProxyEngine On

    ServerName bw.domain.tld

    SSLCertificateFile /etc/letsencrypt/live/bw.domain.tld/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/bw.domain.tld/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf

    ErrorLog ${APACHE_LOG_DIR}/bw_error.log
    CustomLog ${APACHE_LOG_DIR}/bw_access.log combined

    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /notifications/hub(.*) ws://127.0.0.1:3012/$1 [P,L]

    ProxyPass / https://127.0.0.1:8443/
 #   ProxyPassReverse / https://127.0.0.1:8443/

    ProxyPreserveHost On
    ProxyRequests Off
    RequestHeader set X-Real-IP %{REMOTE_ADDR}s
# RequestHeader setifempty Connection "Upgrade"
# RequestHeader setifempty Upgrade "websocket"


</VirtualHost>
```

**Comment by BlackDex** [comment]
@totti4ever Do you have SSL Enabled on the container?
If so, you probably need to change ws://127.0.0.1:3012 to **wss**://127.0.0.1:3012.
Note the extra "s" for "Secure".

**Comment by CyBiS** [comment]
Although websockets are working fine for me (docker container behind reverse proxy with SSL up to the proxy) I get a 404 error for https://bw.domain.tld/notifications/hub/negotiate and for https://bw.domain.tld/notifications/hub the error message `WebSocket Protocol Error: Unable to parse WebSocket key.` Am I dealing with a misconfiguration?

**Comment by totti4ever** [comment]
> @totti4ever Do you have SSL Enabled on the container?
> If so, you probably need to change ws://127.0.0.1:3012 to **wss**://127.0.0.1:3012.
> Note the extra "s" for "Secure".

Thanks for the advice, but still nothing changed?

**Comment by mprasil** [comment]
Did you try adding the extra setting as in #527? Maybe that will do the trick.

**Comment by dani-garcia** [comment]
Closed due to inactivity.
