### ISSUE TITLE
report

### ISSUE THREAD

**Issue by kenthinson** [dani-garcia/bitwarden_rs#717]
Not a issue just a report. 
bitwardenrs/server:aarch64
I got it running on pi 4. Ubuntu 64bit just now.
In case you want to update this page: Reported compatibility table
https://github.com/dani-garcia/bitwarden_rs/wiki/Which-container-image-to-use

Great work btw.

**Comment by mprasil** [comment]
Feel free to update the table yourself, there's some extra info needed so instead of asking it here, just go there and add a new table row. :wink: 

Thanks for reporting back.

**Comment by kenthinson** [comment]
@mprasil Cool will do. I know some people don't like just anyone making changes to the docs.

**Comment by mprasil** [comment]
We have very welcoming community here. 😉
