### ISSUE TITLE
[Raspberry] Setting host-port with "docker-run -p" does not work (defaults to 80)

### ISSUE THREAD

**Issue by Timeeee** [dani-garcia/bitwarden_rs#719]
I'm using the raspberry-image.

Using the docker-run command from the wiki doesn't set the containers host port correctly.

running 

> docker run -d --name bitwarden -v /bw-data/:/data/ -p 8080:8080 bitwardenrs/server:raspberry

adds the container with exposed port 8080, but the host port is set to 80. This leads to issues as I have another service running with host-port 80. 

I didn't try using a fixed IP with port, as this is not possible in my environment.

**Comment by mprasil** [comment]
`-p` sets the port forwarding. So if you want to expose port `80` in the container as `8080` on the host you need to do `-p 8080:80`.

**Comment by Timeeee** [comment]
I assumed there is a way to change the host port itself (not the forwarding) with `-p` as well. So there is no way to change the host port, which is in this case fixed to `80`, right?

**Comment by mprasil** [comment]
Well you were asking about the host side port as that's where the conflict is. I assume that `bitwarden_rs` will never conflict with the default port `80` inside the container as it's the only thing running inside the container.

If for some reason you _really_ want to change the port where `bitwarden_rs` listens inside the container, you can do that by setting the `ROCKET_PORT` variable. But you'd have adapt the port forward as well: `-e ROCKET_PORT=2345 -p 8080:2345`

**Comment by Timeeee** [comment]
Thank you very much, I finally got it running!
