### ISSUE TITLE
Add robots.txt

### ISSUE THREAD

**Issue by ntimo** [dani-garcia/bitwarden_rs#721]
Hello,
I would like to suggest to add a robots.txt to disallow all indexing of the bitwarden installation. 

```
User-agent: *
Disallow: /
```

**Comment by Jacobite89** [comment]
Setting the "X-Robots-Tag: none" HTTP-Header may be the better way.

e.g. this is my Caddyfile
`#Caddyfile
vault.example.com {
  tls {$EMAIL}
  gzip

  header / {
    # Enable HTTP Strict Transport Security (HSTS)
    Strict-Transport-Security "max-age=31536000;"
    # Enable cross-site filter (XSS) and tell browser to block detected attacks
    X-XSS-Protection "1; mode=block"
    # Disallow the site to be rendered within a frame (clickjacking protection)
    X-Frame-Options "DENY"
    # Prevent search engines from indexing
    X-Robots-Tag "none"
  }

  # The negotiation endpoint is also proxied to Rocket
  proxy /notifications/hub/negotiate bitwarden:80 {
    transparent
  }

  # Notifications redirected to the websockets server
  proxy /notifications/hub bitwarden:3012 {
    websocket
  }

  # Proxy the Root directory to Rocket
  proxy / bitwarden:80 {
    transparent
  }
}`
