### ISSUE TITLE
Cannot read property 'importKey' of null

### ISSUE THREAD

**Issue by diablozzq** [dani-garcia/bitwarden_rs#726]
I'm trying to install bitwardenrs and am getting a "Cannot read property 'importKey' of null" on the Javascript console in Chrome.  This happens when I try to login or create a user account.  I can log into the admin interface.

  I've tried this on my Raspberry Pi on Raspbian Buster using the docker with bitwardenrs/server:raspberry, Virtual Box with Ubuntu 18.04 with docker and bitwardenrs/server:latest and also bitwardenrs/server:1.11.0.

Is this a bug?  Did I not follow the instructions?  I tried 4+ times now and can't seem to figure this out.

**Comment by diablozzq** [comment]
To add some more info, here is the command I was using to install it.

On the Raspberry Pi 4 using the latest Rasbian release:

docker pull bitwardenrs/server:raspberry
docker run -d --name bitwarden  -e ADMIN_TOKEN=test -e LOG_FILE=/data/bitwarden.log -e SIGNUPS_ALLOWED=true -v /bw-data/:/data/ -p 80:80 bitwardenrs/server:raspberry

On Ubuntu 18.04:
docker pull bitwardenrs/server:latest
docker run -d --name bitwarden  -e ADMIN_TOKEN=test -e LOG_FILE=/data/bitwarden.log -e SIGNUPS_ALLOWED=true -v /bw-data/:/data/ -p 80:80 bitwardenrs/server:latest

**Comment by diablozzq** [comment]
Once installed, I used Chrome to browse to the default page.  From there, that's when I was getting that error.  I was unable to ever create an account.

I have not tried another bitwarden client

**Comment by diablozzq** [comment]
Just tried the desktop client and I was able to login.  Must be a javascript client problem?

**Comment by dani-garcia** [comment]
Chrome disallows the use of some crypto APIs that the web page uses when the content is served over HTTP and not HTTPS, the possible solutions are to either enable HTTPS or to use Firefox.

Last time this was mentioned, it's only the account creation that uses these APIs, so as long as you register in another browser Chrome should work.

**Comment by diablozzq** [comment]
Thanks.  This was correct.  HTTPS fixed it.
