### ISSUE TITLE
Error using docker-compose.yml

### ISSUE THREAD

**Issue by aaro-n** [dani-garcia/bitwarden_rs#731]
Write the docker-compose.yml file according to the guide and there is an error at runtime.

[Reference link](https://github.com/dani-garcia/bitwarden_rs/wiki/Using-Docker-Compose)

docker-compose.yml
`# docker-compose.yml
version: '3'

services:
  bitwarden:
    image: bitwardenrs/server:1.11.0
    restart: always
    volumes:
      - ./bw-data:/data
    environment:
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: 'true'   # set to false to disable signups

  caddy:
    image: abiosoft/caddy:1.0.3
    restart: always
    volumes:
      - ./Caddyfile:/etc/Caddyfile:ro
      - caddycerts:/root/.caddy
    ports:
      - 80:80  # needed for Let's Encrypt
      - 443:443
    environment:
      ACME_AGREE: 'true'              # agree to Let's Encrypt Subscriber Agreement
      DOMAIN: 'XXX.XX.info' # CHANGE THIS! Used for Auto Let's Encrypt SSL
      EMAIL: 'XX@gmail.com'  # CHANGE THIS! Optional, provided to Let's Encrypt
      
volumes:
  caddycerts:`

error code
`ERROR: for e620eeb1549d_bitwarden_caddy_1  Cannot start service caddy: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/www/bitwarden/Caddyfile\\\" to rootfs \\\"/var/lib/docker/overlay2/15048d74523e124378cfa169f5ed1a50f6c71ee1a954227c26936c3a68b35dd5/merged\\\" at \\\"/var/lib/docker/overlay2/15048d74523e124378cfa169f5ed1a50f6c71ee1a954227c26936c3a68b35dd5/merged/etc/Caddyfile\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for caddy  Cannot start service caddy: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/www/bitwarden/Caddyfile\\\" to rootfs \\\"/var/lib/docker/overlay2/15048d74523e124378cfa169f5ed1a50f6c71ee1a954227c26936c3a68b35dd5/merged\\\" at \\\"/var/lib/docker/overlay2/15048d74523e124378cfa169f5ed1a50f6c71ee1a954227c26936c3a68b35dd5/merged/etc/Caddyfile\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.`

**Comment by nicokaiser** [comment]
Did you ensure that `./bw-data` and `./Caddyfile` exist (on the host) and are files?

**Comment by dani-garcia** [comment]
Closed due to inactivity.
