### ISSUE TITLE
Missing libmariadb error on startup with latest commit

### ISSUE THREAD

**Issue by mpetrole** [dani-garcia/bitwarden_rs#732]
I was running an older version of Bitwarden_rs from around 6 months ago but I wanted to fix Safari integration so I decided to update to the latest version. I destroyed my existing containers and then pruned all images. I pulled the latest commit and built it following the wiki with the mysql build option (docker build -t bitwarden_rs --build-arg DB=mysql .). After finishing the build, I started it with docker-compose, using the same docker-compose file that I was running before. After startup, Bitwarden fails to load and I see `/bitwarden_rs: error while loading shared libraries: libmariadb.so.3: cannot open shared object file: No such file or directory` in the logs.

I did copy over my docker-compose file, Caddyfile, and bw-data folder contents from my old installation, but I checked and it didn't seem like there was any reason for any of those to cause this kind of error.

My environment is in AWS, I have an EC2 instance running the docker containers and I'm using bitwarden and caddy, then I have a MySQL RDS instance for the DB.

Thanks in advance for any help!

**Comment by dani-garcia** [comment]
If you want to use a different database, you need to use the separate images, the main dockerfile is only for SQLite, because it's missing the correct dependencies. Try using something like:
```
docker build -t bitwarden_rs -f docker/amd64/mysql/Dockerfile .
```

**Comment by mpetrole** [comment]
Sorry for the late response, but that worked, thanks!

**Comment by ToeiRei** [comment]
Wouldn't that be something for the wiki?
