### ISSUE TITLE
Not working through Nginx Proxy Manager

### ISSUE THREAD

**Issue by ataylor1988** [dani-garcia/bitwarden_rs#735]
I have the bitwarden docker setup in my unraid server.  I have several other web facing dockers setup behind the "Nginx Proxy Manager" container without issue.  But bitwarden seems to not be working.

I want it to use HTTPS, but maybe http is the only option?

I do not have config files as this proxy is all gui based but here are screens of my settings.
Nothing in the advance, or custom tab

![proxy1](https://user-images.githubusercontent.com/31442865/69197095-12b05500-0af6-11ea-993a-0ea3a9b53941.PNG)
![proxy2](https://user-images.githubusercontent.com/31442865/69197099-15ab4580-0af6-11ea-98f5-8b33d66257e2.PNG)

**Comment by dani-garcia** [comment]
I assume `https://192.168.1.22:8343` is the address to access bitwarden_rs? Maybe you need to select http there if you are configuring HTTPS in the proxy and not in bitwarden_rs?

**Comment by ataylor1988** [comment]
I would like to forward it as HTTPS, where do i enable HTTPS in the docker?

**Comment by ntimo** [comment]
Take a look at the docs here on how to enable https for the docker container https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-HTTPS

**Comment by ataylor1988** [comment]
So the issue with that at least i think, is that you are setting that up inside the docker container, and in my experience that usually means if you update said docker those settings can get removed.  Also i would much rather have my reverse proxy docker handle everything to do with the certificates as it does with all my other apps, like nextcloud, and ombi.  Is the bitwarden container simply not responding to HTTPS?  I would think all the needs to happen is to allow for HTTPS connections, no need to set the SSL cert and so on up directly in the container.  Unless there is some intricacy related to bitwardenrs that does not allow this.  Other containers such as nextcloud, ombi, organizer, sonarr, radarr, have all worked this way.

**Comment by ntimo** [comment]
If you send a https request to a http endpoint this is not going to work. Therefore you will need to configure bitwarden_rs to use https as explained in the docs.

**Comment by ataylor1988** [comment]
Yes, but the docs you linked are setting up a cert and everything.  I would prefer to not manage the cert inside the container.  I would rather my docker container that is build and dedicated to handling certs, and outside access to handle it.  I just need the bitwardenrs container to allow connections of 443.  Do not need to setup a cert and all that inside its container.

**Comment by dani-garcia** [comment]
Well if you want to use HTTPS between the proxy and bitwarden_rs you need certificates, either proper ones or self signed. 

There isn't much benefit to running self signed certificates compared to just using HTTP, unless the proxy allows certificate pinning, that's why we are recomending either to set up the certificates in the container, or to just use HTTP behind the proxy.

**Comment by ataylor1988** [comment]
So then how do all my other containers just work with HTTPS, without doing setup inside the conainter?  Ombi, Nextcloud, and a few others are setup just like the screen shots above with their ports.  I did not have to do any certificate setup on those, just pointed the proxy at them.

Maybe a feature request for just having bitwardenrs listen on 443 to facilitate this is needed.  This would make a proper https setup much easier for people uncomfortable with docker commands and linux command line.  Not saying im not, i have done plenty, but this would make hosting your own bitwarden way easier for not so technical people.

**Comment by dani-garcia** [comment]
I assume those other services use self signed certificates, which is barely more secure than HTTP, that's why I don't want to add that functionality.

You can still point the proxy to bitwarden_rs directly, just use HTTP, which should be perfectly safe as long as the network behind the proxy is safe.

If you still want to create a self signed certificate, you can use something like this to generate it, and then use the wiki page above to set it up:
```
openssl req -x509 -newkey rsa:4096 -nodes -keyout key.pem -out certs.pem -days 365
```
