### ISSUE TITLE
missing information in email invite

### ISSUE THREAD

**Issue by josuemotte** [dani-garcia/bitwarden_rs#737]
Hello, 

We upgraded the docker image to the latest version and it seems that all verification emails are sent without the join organization link, while the github link is still working

![image](https://user-images.githubusercontent.com/38882772/69243867-2ca87100-0ba4-11ea-97da-5c0da6cca6b9.png)

According to the source of the email, it seems that the verification is well formatted but somehow, no matter the client, the link doesn't show up correctly : 

[email_issue.txt](https://github.com/dani-garcia/bitwarden_rs/files/3869523/email_issue.txt)

Are there any change we need to make on our side to get the email verification work again ? 

Thanks

**Comment by tomuta** [comment]
What is your `DOMAIN` environment variable set to? Based on the attached file it looks like it may be set to something like `DOMAIN="xxxxxx"`. It should be without double quotes like `DOMAIN=xxxxxx`.

**Comment by josuemotte** [comment]
I've changed it but no luck still the same issue, it was "prout.io" now it's prout.io

**Comment by dani-garcia** [comment]
According to that email source, DOMAIN is set to `"https://bitwarden.prout.rocks"`, quotes included. The rest of the URL seems correct to me, check the value from the admin page to see if there are quotes there too.

**Comment by josuemotte** [comment]
Strange it was still in the admin page, it's fixed thank you
