### ISSUE TITLE
sqlite Dockerfile used for mysql-image

### ISSUE THREAD

**Issue by nevsnode** [dani-garcia/bitwarden_rs#739]
It seems like the server-mysql image on Docker Hub is built with the wrong Dockerfile.
I pulled the latest release (1.12.0) and basically ran into issues, until I noticed this in https://hub.docker.com/r/bitwardenrs/server-mysql/dockerfile:
```
[...]
# set sqlite as default for DB ARG for backward comaptibility
ARG DB=sqlite
[...]
```

Or is there some intention behind this? 😅

**Comment by dani-garcia** [comment]
Oops, it seems I configured it wrong for the release builds, I've switched it now, but it will be a couple of hours before it's built. In the mean time you can use the server-mysql:latest image, which at the moment is identical to the release.

**Comment by nevsnode** [comment]
Nice, thanks :+1:
And a general 'thank you' for building this
