### ISSUE TITLE
Cannot Remove U2F key

### ISSUE THREAD

**Issue by ataylor1988** [dani-garcia/bitwarden_rs#742]
Hello,

I got U2F keys to work, and I have enrolled 2 of them, but i want to remove one of them, and i get an unknown error when i try and remove it
![Untitled](https://user-images.githubusercontent.com/31442865/69469089-a1baa880-0d54-11ea-9186-0b351b1ce481.png)

**Comment by dani-garcia** [comment]
Is there any error in the bitwarden_rs log?

Can you check the network tab of the developer tools (usually opens with F12), there should be a failing request (status code 5xx or 4xx), click on it and show us what it says in the response section.

**Comment by ataylor1988** [comment]
Here is  a snip from the log, that error occurs after trying to delete the key

`[2019-11-28 11:41:24][rocket::rocket][INFO] DELETE /api/two-factor/u2f application/json; charset=utf-8:
[2019-11-28 11:41:24][_][ERROR] No matching routes for DELETE /api/two-factor/u2f application/json; charset=utf-8.
[2019-11-28 11:41:24][_][WARN] Responding with 404 Not Found catcher.
[2019-11-28 11:41:24][_][INFO] Response succeeded.
[2019-11-28 11:41:36][rocket::rocket][INFO] GET /alive:
[2019-11-28 11:41:36][_][INFO] Matched: GET /alive (alive)
[2019-11-28 11:41:36][_][INFO] Outcome: Success
[2019-11-28 11:41:36][_][INFO] Response succeeded.`

Here is a screen of the network tab

![vault](https://user-images.githubusercontent.com/31442865/69829272-f347b500-11e4-11ea-9cb0-ca6b28deae4b.PNG)

**Comment by dani-garcia** [comment]
Okay it seems that the function to delete a specific key wasn't implemented, so I did it now. Note that until the new version builds, you can just use the disable all keys at the bottom and then add the correct one again as a workaround. Thanks for reporting it!

**Comment by ataylor1988** [comment]
Just wanted to report, that i pulled the latest docker and was able to remove the key this morning.
