### ISSUE TITLE
cant remove docker image with wrong architecture

### ISSUE THREAD

**Issue by schattenkrieger** [dani-garcia/bitwarden_rs#743]
I just tried to migrate my docker installation from an raspi3 to an intel nuc.
i forgot to change server:raspberrypi to server:latest, so after starting the docker-compose file, docker pulled the raspi image and tried to start it. the only effect was that i was kicked back to the login dialog of my nuc.
i can log in fine again, and docker ps shows me the container is running.
but i can not access anything, and it shows me bitwardenrs/server:rasperrypi as source
no matter what i do to try to stop the container, docker-compose down, docker stop, systemctl stop docker, as soon as i touch the running container i get kicked back to the login screen. i even deleted the docker-compose file and the folders, but the container keeps running, and is still there after a reboot. i can also not start the correct server version, i allways get kicked back to the login.
when try over ssh i get disconnected from the server and it takes a few seconds before the server accepts ssh connections again.
is there any way to get rid of the wrong image without reinstalling the whole server again?

**Comment by mprasil** [comment]
That honestly sounds more like docker problem. It seems that it has some issues with container that is crashing instantly or in unexpected way.

Do you have any data on docker that you'd like to preserve. Some volumes or images you've built? If not, then you can try stopping the docker service (`systemctl stop docker`) and then wipe contents of `/var/lib/docker/`. Then you can start docker and it should look like you freshly installed it.

This will obviously wipe any other containers you might have there, all the images and volumes.. But it sounds like you're kinda starting from scratch anyways.

Also I'm typing this on my mobile without checking the paths and commands correctness, so double check everything suggested.

**Comment by mprasil** [comment]
Did you try that @schattenkrieger ? Did that work?

**Comment by dani-garcia** [comment]
Closed due to inactivity.
