### ISSUE TITLE
Docker variables disappeared from Bitwarden docker template (mprasil) settings

### ISSUE THREAD

**Issue by gizmer** [dani-garcia/bitwarden_rs#744]
My Bitwarden docker (mprasil) was runnning smoothly on UNRAID with exposuring login page via NGIX to the internet. After some server rebuilt I wasn't able to start the Bitwarden docker (Error message "Execution error/Server error"). Then reinstalled the docker via UNRAID Apps plugin. After installation I can't specify docker variables Websocket and external domain name. They are now missing in the template.
Is it the expected behaviour? How can I specify these settings to access Bitwarden from the internet?

**Comment by mprasil** [comment]
If you're using `mprasil/bitwarden` docker image, you should stop right there and upgrade to `bitwardenrs/server`, because the `mprasil/bitwarden` image is quite old and no longer updated or supported.

**Comment by mprasil** [comment]
I'm not that familiar with Unraid, but I guess you're using [this template](https://github.com/selfhosters/unRAID-CA-templates/blob/master/templates/bitwardenrs.xml)? It seems to have some of the variables you mentioned there. Either way, maybe asking [here](https://github.com/selfhosters/unRAID-CA-templates/issues) would help you more, we do not maintain the Unraid templates.

I'm going to close this now, but feel free to reopen if you think we can help you more with this.
