### ISSUE TITLE
Yubikey and Browser extension

### ISSUE THREAD

**Issue by eflemingtra** [dani-garcia/bitwarden_rs#748]
Hi,

Sorry for the dumb question.  I have setup bitwarden_rs to work with my Yubikey so that when accessing my selfhosted instance of it, my Yubikey is required.

Is it possible to use the Yubikey to access the Bitwarden extension on my web browser or on my Android device? The browser extension just sends me to the Bitwarden's website when attempting to set up U2F functionality.

**Comment by dani-garcia** [comment]
You should set up the yubikey on your web vault, and once that's done you can use it to login in the browser extension, is that what you mean?

**Comment by eflemingtra** [comment]
> You should set up the yubikey on your web vault, and once that's done you can use it to login in the browser extension, is that what you mean?

Yeah - I've done that. So I'm using the Bitwarden Firefox extension on desktop, and the Bitwarden App on Android. Despite setting up my Yubikey on the web vault (and when I log onto the web vault it requires me to use my Yubikey), both the browser extension and the Android app just take me to the Bitwarden official webpage, not my hosted webvault.  It seems that they're not communicating to my self hosted instance for 2FA, but otherwise work fine.

**Comment by dani-garcia** [comment]
Well I've just tried and it works fine for me on Firefox, though it does ask to open as a new window instead of a popup.
![image](https://user-images.githubusercontent.com/725423/70375662-aceb0800-1900-11ea-88e5-2dd0e9bcbb6a.png)

Once I click ok a new window opens and I can log in and use the Yubikey as U2F just fine.

**Comment by eflemingtra** [comment]
Mine does this:
![image](https://user-images.githubusercontent.com/13082155/70382370-0c9fec80-19af-11ea-8c64-d2bf23feb753.png)

And then just takes me to Bitwarden's website. Is it because I'm not serving bitwarden_rs from an HTTPS domain? I don't use a direct proxy to interact with my server but a Zero Tier tunnel.

**Comment by mqus** [comment]
just to rule the simple thing out: you did point the firefox addon/android app to your instance by clicking on the cog and entering your url in the first field, right?

**Comment by eflemingtra** [comment]
> 
> 
> just to rule the simple thing out: you did point the firefox addon/android app to your instance by clicking on the cog and entering your url in the first field, right?

Yes, it interacts fine with my self hosted instance otherwise. So if I click on My Vault, it will take me to my self hosted bitwarden_rs instance at http://192.168.1.49:1024

**Comment by mqus** [comment]
(if I think about it, it wouldnt ask for 2fa if that wasnt the case, so sry for the dumb question >.>)

**Comment by dani-garcia** [comment]
@eflemingtra Yeah from that menu it opens the help page, that's expected.

What you need to do is configure the 2FA methods from the web vault, and they will work in the extensions, though you'll need to log out and log back in to see the changes.

**Comment by dani-garcia** [comment]
Closed due to inactivity.
