### ISSUE TITLE
How do I create an organization?

### ISSUE THREAD

**Issue by ptman** [dani-garcia/bitwarden_rs#75]
The web (vault?) client asks for payment when I'm trying to create an org.

Is there some place to discuss this project? On Matrix? IRC? Email list?

**Comment by mprasil** [comment]
Asking here is fine, I'm okay creating an Matrix room if you're interested. 

You just create the free organization, the Vault shows some limits there, but in practice there are no limits when using bitwarden_rs as backend. (server actually reports the Organization as paid one to the client)

**Comment by ptman** [comment]
Thank you for the quick reply. I guess asking here is fine, but I wouldn't mind a chat room on matrix.

**Comment by mprasil** [comment]
I've created new issue #76 to put that up for discussion, meanwhile you can join the [Matrix room](https://matrix.to/#/!cASGtOHlSftdScFNMs:matrix.org) if you're interested.
