### ISSUE TITLE
Release 1.13.0 won't build

### ISSUE THREAD

**Issue by mqus** [dani-garcia/bitwarden_rs#753]
I just wanted to compile the latest release but got the following error(s):
```
error[E0425]: cannot find function `generate_token` in this scope
   --> src/api/core/two_factor/email.rs:324:22
    |
324 |         let result = generate_token(19).unwrap();
    |                      ^^^^^^^^^^^^^^ not found in this scope
    |
help: possible candidate is found in another module, you can import it into scope
    |
300 |     use crate::crypto::generate_token;
    |

error[E0425]: cannot find function `generate_token` in this scope
   --> src/api/core/two_factor/email.rs:331:22
    |
331 |         let result = generate_token(20);
    |                      ^^^^^^^^^^^^^^ not found in this scope
    |
help: possible candidate is found in another module, you can import it into scope
    |
300 |     use crate::crypto::generate_token;
    |

error: aborting due to 2 previous errors
```

btw, would there be value in creating a small ci task which `cargo test`s the master branch and/or PRs? I could make a script.

**Comment by dani-garcia** [comment]
Right, the tests weren't updated, and they aren't run in CI so I didn't notice. `cargo build` should work fine though.

I just fixed the broken tests, thanks for reporting it!

I think updating the current CI setup to run cargo test instead of cargo build will be enough, so I did that too.

**Comment by mqus** [comment]
I just noticed that only cargo test was failing, not the build itself so it was more of a false alarm on my side... sry ;)
I completely forgot that I added `cargo test` to the archlinux package build process a week ago :D
I'll add a patch for those tests for this release to my package.
