### ISSUE TITLE
Auto confirm invited users

### ISSUE THREAD

**Issue by dcelasun** [dani-garcia/bitwarden_rs#754]
Inviting a user and then manually confirming them after they've registered is annoying and becomes a headache for large organizations. Would it be ok if I sent a PR adding a config option to disable it? It would change [this line](https://github.com/dani-garcia/bitwarden_rs/blob/adc443ea80be98a5aaf260eb8c2c7be6e43f6377/src/api/core/organizations.rs#L618) to `UserOrgStatus::Confirmed`.

**Comment by dani-garcia** [comment]
Confirming a user isn’t just done as a mostly useless extra step, it’s during confirmation when the user gets assigned the encryption keys used to decrypt the organization vault, so changing that wouldn’t work.

**Comment by dcelasun** [comment]
Sorry I missed that the first time, but I can also copy that bit to the invite accept endpoint. Would that be OK?

**Comment by dani-garcia** [comment]
Well there's not much to do in the accept endpoint because that's called by the user, and the user doesn't have the encryption keys yet, this would need to be done by the organization admins.

You could modify the server to make the invites autoaccepted, so you could immediately confirm the user afterwards, which should work because it's what's being done when email is disabled:

https://github.com/dani-garcia/bitwarden_rs/blob/adc443ea80be98a5aaf260eb8c2c7be6e43f6377/src/api/core/organizations.rs#L475-L479

Another option would be to have a running process with bitwarden_cli autoconfirming all members of the org: https://help.bitwarden.com/article/cli/#confirm

**Comment by dcelasun** [comment]
> and the user doesn't have the encryption keys yet, this would need to be done by the organization admins

Why can't we do that in the invite accept handler?

> You could modify the server to make the invites autoaccepted, so you could immediately confirm the user afterwards

That doesn't really help me. My use case is:

- Invite up to 20 users at a time with access to certain collections
- Users register via the invite link
- Users log in and see all passwords in those collections

Basically, I want to be able to invite someone and forgot about them. This is especially important in a large organization where Bitwarden's unusal two step signup causes a lot of friction.

**Comment by dani-garcia** [comment]
Because the invite accept handler is executed by the user, and the user doesn't have the encryption keys for the org until an admin gives them during the confirmation process.

Any changes to this process would imply modifying the web vaults code considerably and that's something we've been trying to avoid so far.

**Comment by dcelasun** [comment]
OK, thanks. I'll try to do this on a private fork and will open a PR if I end up with something decent.

**Comment by etfz** [comment]
> You could modify the server to make the invites autoaccepted, so you could immediately confirm the user afterwards, which should work because it's what's being done when email is disabled:
> 
> https://github.com/dani-garcia/bitwarden_rs/blob/adc443ea80be98a5aaf260eb8c2c7be6e43f6377/src/api/core/organizations.rs#L475-L479

I don't know whether this will get seen here, but is a modification like this still viable? I noticed that particular block has since been removed.

**Comment by stefan0xC** [comment]
The existing code has just been refactored a bit. The logic is still there.
https://github.com/dani-garcia/vaultwarden/blob/1ec049e2b5f2f1aa3b8d035e94915b131c5e9e25/src/api/core/organizations.rs#L899-L902

**Comment by BlackDex** [comment]
> The existing code has just been refactored a bit. The logic is still there.
> 
> https://github.com/dani-garcia/vaultwarden/blob/1ec049e2b5f2f1aa3b8d035e94915b131c5e9e25/src/api/core/organizations.rs#L899-L902

That is only for existing users, not for new users. In the previous version that was also the case for newly invited users.

**Comment by stefan0xC** [comment]
A new user will be automatically accepted on registration if mail is disabled:
https://github.com/dani-garcia/vaultwarden/blob/1ec049e2b5f2f1aa3b8d035e94915b131c5e9e25/src/api/core/accounts.rs#L135-L141

**Comment by BlackDex** [comment]
Ah, it's moved to an other location :). Yea that seems to be a bit more logical.
Good, thanks for the pointers.

**Comment by etfz** [comment]
I don't fully understand how things work there, but is that not just the logic for the regular registration process? If you are invited to an organisation without already having an account, you accept the invitation by registering. That is the normal behavior, as far as I know. I can't see any checks for mail configuration there, but that might just be beyond my understanding.

The original code, as far as I understand, would mark the invitation as accepted as soon as it was sent by the organization administrator. Although perhaps that requires the account already being registered, in which case it does not really help my cause. Perhaps that is what OP meant by that solution not really helping them, come to think of it. So yeah, I'm referring to cases where an existing user account does not exist. Disabling email did not seem to change anything about the invitation process in that case.

It's just sort of a frustrating process.

1. User requests an invite (signups disabled)
2. X hour delay
3. Admin sends invitation
4. X hour delay
5. User accepts invite and registers account
6. X hour delay
7. Admin confirms user
8. X hour delay
9. User notices confirmation and can get to work

Certainly this describes sort of a worst case communication scenario, but it's just so many trips, where logically two of those delays could be eliminated. I don't suppose we're in a better place to improve any of this today, three years later? I understand some of it is tied to upstreams code.

**Comment by etfz** [comment]
I suppose that if a user account was created when the invitation was sent, with some finalizing steps left to the invitee, it could be doable. I understand of course that nothing is really designed around that sort of process. I guess such a suggestion would be better to take upstreams.

**Comment by hvanmegen** [comment]
> A new user will be automatically accepted on registration if mail is disabled:
> 
> https://github.com/dani-garcia/vaultwarden/blob/1ec049e2b5f2f1aa3b8d035e94915b131c5e9e25/src/api/core/accounts.rs#L135-L141

I'm not entirely sure how to read that code snippet; What toggle in the admin interface do I have to disable in order to have auto-accepted invites?

**Comment by hvanmegen** [comment]
> Confirming a user isn’t just done as a mostly useless extra step, it’s during confirmation when the user gets assigned the encryption keys used to decrypt the organization vault, so changing that wouldn’t work.

Why would this step need to be a manual process? Doesn't the system have some kind of cron handler or event handler that could handle this? I'm setting up Vaultwarden as a free service for volunteers within our organization for our local schools, but we have over 250 people that will be joining.. having to assign these all manually will be quite the PITA 😅

**Comment by BlackDex** [comment]
@hvanmegen There is no flag for auto accept invites. The only it does that is if the server does not have a SMTP server configured.
The reason for that is that a user can't really accept an invite, since they never received an invite. And acceptance only works via a token which is embedded into the link they need to click.

Vaultwarden does have a cron/job-handler but that can't confirm users. That needs to be done by some who already has access to the organization and have an unlocked vault/decrypted keys within the client. Because those are used to generate keys for the confirmed user. Since Vaultwarden has no knowledge of any password or keys it can't do any of that, nor would that be safe!

**Comment by hvanmegen** [comment]
> @hvanmegen There is no flag for auto accept invites. The only it does that is if the server does not have a SMTP server configured. The reason for that is that a user can't really accept an invite, since they never received an invite. And acceptance only works via a token which is embedded into the link they need to click.
> 
> Vaultwarden does have a cron/job-handler but that can't confirm users. That needs to be done by some who already has access to the organization and have an unlocked vault/decrypted keys within the client. Because those are used to generate keys for the confirmed user. Since Vaultwarden has no knowledge of any password or keys it can't do any of that, nor would that be safe!

Ah I see.. That makes sense. I'll just have to set up a macro or something to babysit that page on the web interface then.. it's a real shame that there isn't a more elegant (read: automated) solution for this.
