### ISSUE TITLE
Problem login with mobile

### ISSUE THREAD

**Issue by rubenzori86** [dani-garcia/bitwarden_rs#756]
Hi there, I have problems with mobile app on all devices that I tested (3 androids and 1 iOS)
 I get there is a problem connecting to the server.

I use HTTPS with valid certificate and I can log in from desktop plugins/apps and any browser, chrome included

**Comment by mqus** [comment]
Please describe your issue with more details. You can follow the [template](https://github.com/dani-garcia/bitwarden_rs/blob/master/.github/ISSUE_TEMPLATE.md) where we already have a guideline for things we'd like to know. Is your issue maybe similar to #687 ?

**Comment by rubenzori86** [comment]
Yes, is the same. I tried with old apk but no success

**Comment by mqus** [comment]
Sorry, I just saw that your entire issue content is commented out (written within `<!--` `-->` brackets), could you edit it to let us see the whole content?

**Comment by rubenzori86** [comment]
Sorry, you can see Noe?

**Comment by mqus** [comment]
Yeah, thanks!
This seems to be a duplicate of #687 then. For me personally, downgrading to 2.0.4 worked as a workaround...

**Comment by rubenzori86** [comment]
I tried again but doesn't work for me...:(

**Comment by BlackDex** [comment]
@rubenzori86 Do you see anything in the logs of bitwarden_rs when you try to connect via the mobile devices?

**Comment by BlackDex** [comment]
Also please check #760 for some more items you can check.

**Comment by aledexter** [comment]
I suppose it is a certificate issue. If you can set http instead https end set into the app the url in http mode you can do a check.

**Comment by BlackDex** [comment]
HTTP is actually not support for bitwarden unless this is fully localhost.
Please check the #760 issue for some more information and also the following wiki pages:
- https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-HTTPS
- https://github.com/dani-garcia/bitwarden_rs/wiki/Private-CA-and-self-signed-certs-that-work-with-Chrome
