### ISSUE TITLE
[rocket::config::error] I/O error while setting tls.certs: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by mbdotnet** [dani-garcia/bitwarden_rs#758]
Hello, im getting this error while trying to set up an https Bitwarden docker server using my domain certificate. 

### Subject of the issue
Docker Run command:
```
docker run -d --name bitwarden \
  -e ROCKET_TLS='{certs="/ssl/mycert.pem",key="/ssl/mykey.pem"}' \
  -v /etc/letsencrypt/:/ssl/ \
  -v /bw-data/:/data/ \
  -p 443:80 \
  bitwardenrs/server:latest
```

Docker Logs output:
```
[2019-12-04 13:55:43][rocket::config::error][ERROR] I/O error while setting tls.certs:
[2019-12-04 13:55:43][_][INFO] No such file or directory (os error 2)
Logger failed to initialize: attempted to set a logger after the logging system was already initialized
```

I dont know if I missed some steps during the installation, but (if it matters) my /etc/letsencrypt folder is empty expect cli.ini.
In the generated directory /bw-data/ there is following content: db.sqlite3, icon_cache, rsa_key.der, rsa_key.pem, rsa_key.pub.der
And in /ssl I just copied the cert and key file, otherwise it is empty.

### Your environment
Debian 10
Docker version 19.03.5
Bitwarden:latest image

### Steps to reproduce
1.) Creating /ssl directory and copy in the cert and key
2.) Run 
```
docker run -d --name bitwarden \
  -e ROCKET_TLS='{certs="/ssl/mycert.pem",key="/ssl/mykey.pem"}' \
  -v /etc/letsencrypt/:/ssl/ \
  -v /bw-data/:/data/ \
  -p 443:80 \
  bitwardenrs/server:latest
```

### Relevant logs
Full docker log of the bitwarden container:

```
/--------------------------------------------------------------------\
|                       Starting Bitwarden_RS                        |
|                      Version 1.13.0-adc443ea                       |
|--------------------------------------------------------------------|
| This is an *unofficial* Bitwarden implementation, DO NOT use the   |
| official channels to report bugs/features, regardless of client.   |
| Report URL: https://github.com/dani-garcia/bitwarden_rs/issues/new |
\--------------------------------------------------------------------/

[2019-12-04 13:55:43][bitwarden_rs][INFO] JWT keys don't exist, checking if OpenSSL is available...
OpenSSL 1.1.1d  10 Sep 2019
[2019-12-04 13:55:43][bitwarden_rs][INFO] OpenSSL detected, creating keys...
Generating RSA private key, 2048 bit long modulus (2 primes)
.............................+++++
..........+++++
e is 65537 (0x010001)
writing RSA key
writing RSA key
[2019-12-04 13:55:43][bitwarden_rs][INFO] Keys created correctly.
Running migration 20180114171311
Running migration 20180217285753
Running migration 20180427155751
Running migration 20180508161616
Running migration 20180525232323
Running migration 20180601112599
Running migration 20180711181453
Running migration 20180867172114
Running migration 20180960191213
Running migration 20180919144557
Running migration 20181127152621
Running migration 20190526716151
Running migration 20191010083232
Running migration 20191117911009
[2019-12-04 13:55:43][rocket::config::error][ERROR] I/O error while setting tls.certs:
[2019-12-04 13:55:43][_][INFO] No such file or directory (os error 2)
Logger failed to initialize: attempted to set a logger after the logging system was already initialized

```

**Comment by Ayitaka** [comment]
Think of a docker container as a separate instance of an OS running on your system with its own directories.

/ssl is a directory inside the docket container. 

/etc/letsencrypt/ is where you want to put your certificates, and then the directory /ssl inside the docker container will point to your regular /etc/letsencrypt/ directory.

**Comment by mbdotnet** [comment]
I already tried this but still got the same error.

**Comment by hiyan** [comment]
Did you check if mycert.pem and mykey.pem exist in /etc/letsencrypt/ ? Note the actual file name.

**Comment by mbdotnet** [comment]
Yeah, they're both in /etc/letsencrypt.

**Comment by mbdotnet** [comment]
Yeah, they're both in /etc/letsencrypt.
(Sry, I accidentally clicked on the wrong button)

**Comment by BlackDex** [comment]
@mbdotnet Do you have the fullchain.pem selected?
It could be for some reason that this could cause an issue.
Also, make sure that the mycert.pem and mykey.pem are not symlinks to the actual files, i think that will break also.

**Comment by mbdotnet** [comment]
No, I selected the right files and both are not linked files

**Comment by BlackDex** [comment]
The docker container/bitwarden_rs is still running right? But it doesn't have SSL to connect only HTTP.
If so, could you check with the container running what the following will output?
```bash
docker exec -it bitwarden ls -al /ssl
```

**Comment by mbdotnet** [comment]
No, I forgot to mentioned that.
The Docker Containaer stops immediately after the (failed) docker run and does not start anymore. The only thing I have is this log.

**Comment by BlackDex** [comment]
Is there anything within the `/bw-data/` folder on the host?
If so, what are the rights of that folder (or files) and do they match `/etc/letsencrypt/`.
I think that the `/etc/letsencrypt` folder is not accessible for the docker container and therefore crashes/stops.

Bitwarden will quit without any info/message if there are some rights/path issues i have noticed.
So, maybe it has something to do with that.

**Comment by mbdotnet** [comment]
I have checked the permissions on /etc/letsencrypt and docker/bitwarden can access it.

A question about the /bw-data/ folder, should it already exist before the docker run and if so, with what content? Currently, the Docker automatically creates the folder

**Comment by BlackDex** [comment]
No content is needed, and what i wondered is what the rights are of that bitwarden "bw-data" folder, and if they match the /etc/letsencrypt folder.

Also, could you maybe add `-e LOG_LEVEL=trace` as an extra environment option, this should generate some more detailed logs.

**Comment by mbdotnet** [comment]
Yes, they're both the same.

`LOG_LEVEL=trace` doesn't give me more information

**Comment by BlackDex** [comment]
Ok...
1. What OS are you running
2. Do you have something like a MAC active? (selinux, apparmor)
3. Are there some docker logs, or is something visible in the `dmesg` or `journalctl -b`?

**Comment by mbdotnet** [comment]
1.) Debian 10
2.) No, nothing. Only software I installed is an OpenSSH server, certbot, Docker and the standard system utilities I selected during the installation. 
3.) So I checked my syslogs and found an dockerd error that my have something to do with it, but i dont know. 

```
Dec  6 12:17:38 sandbox dockerd[584]: time="2019-12-06T12:17:38.671611283+01:00" level=warning msg="1ccb291d46eb23b8b31620c685903fb1e396601c39552a7a0f80086ef80338b5 cleanup: failed to unmount IPC: umount /var/lib/docker/containers/1ccb291d46eb23b8b31620c685903fb1e396601c39552a7a0f80086ef80338b5/mounts/shm, flags: 0x2: no such file or directory"
```

**Comment by BlackDex** [comment]
Ok, just to rule stuff out. try the following.

`docker run -v /bw-data/:/data/ -v /etc/letsencrypt/:/ssl/ -it ubuntu bash`
See if that works, and if you can ls those folders inside the container (you will be in the container right after it has started).

**Comment by mbdotnet** [comment]
This works just perfectly.

**Comment by BlackDex** [comment]
Then i'm at a loss. Maybe someone with a bit more docker experience can help you and debug. But it should just work.
One final option could be to try the alpine image instead of the latest.
so instead of bitwardenrs/server:latest use bitwardenrs/server:alpine .

**Comment by mbdotnet** [comment]
So I did the most logical thing by trying it on another operating system (Ubtuntu 18.04) and it worked with exactly the same command. I don't understand, because my Debian was completely fresh with 0 configurations made. Well, thanks for your help!
