### ISSUE TITLE
Official chat?

### ISSUE THREAD

**Issue by mprasil** [dani-garcia/bitwarden_rs#76]
@ptman asked in #75 whether there's any official chat room for the project. I've just created [#bitwarden_rs:matrix.org](https://matrix.to/#/!cASGtOHlSftdScFNMs:matrix.org) room on Matrix to get us started, just because I happen to use Matrix.

But is there any preference or interest on your side @dani-garcia? We should be able to link Matrix room with IRC quite easily for example.

**Comment by dani-garcia** [comment]
I don't have a preference either way, so I'm fine using matrix.
Now we need to put it in the README so people can find it.
