### ISSUE TITLE
[question] Docker image with postgres support

### ISSUE THREAD

**Issue by dabde** [dani-garcia/bitwarden_rs#763]
### Missing postgres dockerhub image
We currently evaluate bitwarden_rs and are really happy. Currently with sqlite, but our wish is mostly using the postgres solution to use already existing written infrastructure code and maintain only one database type in our environment. But sadly, only sqlite and mysql has an image in dockerhub.

Is there any reason for not having a postgres image? Can we expect ones in near future?

thanks and kind regards
dabde

**Comment by dani-garcia** [comment]
Well mostly to try to keep compile times down, but adding at least the x86 images seems fair enough.

I created a new image and the latest build is already available, the 1.13.0 tagged version will still take some hours.

https://hub.docker.com/r/bitwardenrs/server-postgresql

**Comment by dabde** [comment]
Ohhh thanks, that was fast :smile:
