### ISSUE TITLE
Unable to lunch Bitwarden: Unable to connect to DB 

### ISSUE THREAD

**Issue by skalenyk** [dani-garcia/bitwarden_rs#764]
Hi, 

Im unable to lunch docker container due to error below. 
Please advise. 

thread 'main' panicked at 'Can't conect to DB: BadConnection("Unable to open the database file")', src/libcore/result.rs:1187:5
stack backtrace:
   0:     0x55cb3f068d24 - backtrace::backtrace::libunwind::trace::h03a3268e8025f5e7
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55cb3f068d24 - backtrace::backtrace::trace_unsynchronized::hfdd426654407b9b1
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55cb3f068d24 - std::sys_common::backtrace::_print_fmt::hf13b3576a7afd1fd
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x55cb3f068d24 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6120b5cb7f3f6fb4
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x55cb3f0911cc - core::fmt::write::h5519681e0b8a2078
                               at src/libcore/fmt/mod.rs:1030
   5:     0x55cb3f061977 - std::io::Write::write_fmt::h244d0a52d18abc18
                               at src/libstd/io/mod.rs:1412
   6:     0x55cb3f06aede - std::sys_common::backtrace::_print::h3f6ea6d8a2e1ae5c
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x55cb3f06aede - std::sys_common::backtrace::print::hfaa195f2a5ad8cee
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x55cb3f06aede - std::panicking::default_hook::{{closure}}::heac2a010ba47da52
                               at src/libstd/panicking.rs:188
   9:     0x55cb3f06abd1 - std::panicking::default_hook::h7739a4bc79ee19ed
                               at src/libstd/panicking.rs:205
  10:     0x55cb3f06b5db - std::panicking::rust_panic_with_hook::h4882a1e7ece8be98
                               at src/libstd/panicking.rs:464
  11:     0x55cb3f06b17e - std::panicking::continue_panic_fmt::h14c4652068d7f110
                               at src/libstd/panicking.rs:373
  12:     0x55cb3f06b066 - rust_begin_unwind
                               at src/libstd/panicking.rs:302
  13:     0x55cb3f08d76e - core::panicking::panic_fmt::h15bba873f536c8cb
                               at src/libcore/panicking.rs:82
  14:     0x55cb3f08d867 - core::result::unwrap_failed::h9ebf399f735db4b0
                               at src/libcore/result.rs:1187
  15:     0x55cb3e90afbe - bitwarden_rs::main::hb0f07627534eed01
  16:     0x55cb3e9fa133 - std::rt::lang_start::{{closure}}::h046a4b19ed814b1d
  17:     0x55cb3f06b003 - std::rt::lang_start_internal::{{closure}}::hc2740ed8935d2053
                               at src/libstd/rt.rs:48
  18:     0x55cb3f06b003 - std::panicking::try::do_call::h3894402739883b06
                               at src/libstd/panicking.rs:287
  19:     0x55cb3f07506a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  20:     0x55cb3f06bb7d - std::panicking::try::h5db65b65b7947775
                               at src/libstd/panicking.rs:265
  21:     0x55cb3f06bb7d - std::panic::catch_unwind::hf99e4cf1cf67ce18
                               at src/libstd/panic.rs:395
  22:     0x55cb3f06bb7d - std::rt::lang_start_internal::h08e212477f161066
                               at src/libstd/rt.rs:47
  23:     0x55cb3e9118e2 - main
  24:     0x7fb4e2ae809b - __libc_start_main
  25:     0x55cb3e6f356a - _start
  26:                0x0 - <unknown>

**Comment by mqus** [comment]
Can you provide instructions on how to reproduce your error? e.g. your exact command to start the container, your environment (OS and version, which bitwarden_rs container you used, etc) This error message alone is not useful for us.

**Comment by BlackDex** [comment]
Seems like an permission issue.
But as @mqus also requested, please provide some more information about which database you use.
Which OS, which type of deployment. etc.. as is given in the original bug template.

**Comment by mprasil** [comment]
Closing this as there was no response for over a month. Feel free to reopen if you need more help.
