### ISSUE TITLE
Non-Docker installation?

### ISSUE THREAD

**Issue by hevisko** [dani-garcia/bitwarden_rs#765]
Good day,

 I only see docker deployment options, but need to deploy in a dockerless environments (Like LXCs containers)and would like to see that documentation.

**Comment by pete1450** [comment]
Having troubles but it's running for me after following this
https://github.com/dani-garcia/bitwarden_rs/wiki/Building-binary

**Comment by mqus** [comment]
You could also install one of the [packages](https://github.com/dani-garcia/bitwarden_rs/wiki/Available-packages) on your favourite linux distribution, but building from source should be straightforward. Please raise any issues you might encounter and add to the wiki if you feel that something is missing.

**Comment by dani-garcia** [comment]
Closed due to inactivity.
