### ISSUE TITLE
Login always fails

### ISSUE THREAD

**Issue by pete1450** [dani-garcia/bitwarden_rs#766]
### Subject of the issue
Fresh install build from source with mysql and I can register accounts and they get into my db. When attempting to log in on the web frontend I always get an error that my username or password is incorrect. I've tried this many times with different emails/passwords. Unsure how to debug going forward.

### Your environment

* Bitwarden_rs version: 1.13.0
build from source
* Install method: 
* Clients used: web
* Reverse proxy and version: nginx 1.10.3
* Version of mysql/postgresql: mysql
* Other relevant information: 

### Steps to reproduce
Started with the recommended systemd setup. Enter an email/name/password then attempt to log in with it

### Expected behaviour
Should be logged in

### Actual behaviour
Incorrect email or password error

### Relevant logs

[2019-12-12 23:55:03][request][INFO] POST /api/accounts/prelogin
[2019-12-12 23:55:03][response][INFO] POST /api/accounts/prelogin (prelogin) => 200 OK
[2019-12-12 23:55:03][request][INFO] POST /identity/connect/token
[2019-12-12 23:55:03][error][ERROR] Username or password is incorrect. Try again. IP: 192.168.1.205. Username: <myemail>.
[2019-12-12 23:55:03][response][INFO] POST /identity/connect/token (login) => 400 Bad Request

**Comment by BlackDex** [comment]
Have you tried to create a new/second account and see if you can login with that?
Also, if you login to the /admin page, do you see the username you want to use listed there?

**Comment by pete1450** [comment]
I have created a couple different ones and I am receiving the welcome email for them. As to your second question that is a little odd; the admin page show that there is some user but no information about it. There is an icon and it says they are invited but that is all. Also when trying to delete the user from that page it always tells me I have the wrong email in the confirmation.

**Comment by BlackDex** [comment]
May i ask which mysql database you use?
Is that MariaDB?

**Comment by BlackDex** [comment]
Well, i just did a test build with only mariadb 10.3 libraries installed and bitwaren_rs is linked to libmariadb.so.3 in my case, instead of libmysqlclient.so.20 when using the vanila-mysql.
But both versions seem to work just fine, not issues using it.

Could you try the mysql docker build just to rule out build issues?

**Comment by pete1450** [comment]
Good idea. I used it pointing to my mysql db and it added a user and let me log in. That seems to point to a build issue. What's odd to me is even the self built version is able to create the tables and add a user to them.

**Comment by coppensc** [comment]
I am having the same issue. I have on my synology Bitwarden_rs in dockercontainer.
When I open it  via https i get login and password screen but when I login i get message that login or password are wrong
![Bitwardenlogin](https://user-images.githubusercontent.com/59052056/71169878-48ae3980-225a-11ea-8b3c-33b060908adc.jpg)

**Comment by dani-garcia** [comment]
Closed due to inactivity.
