### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by utlilb** [dani-garcia/bitwarden_rs#768]
Have everything installed and running great in Docker. Where can I change the branding for everything? IE change Bitwarden_rs in invites, admin panel, etc to something else.

**Comment by dani-garcia** [comment]
About emails and admin page, you can modify the templates available [here](https://github.com/dani-garcia/bitwarden_rs/tree/master/src/static/templates/) and place them inside the data folder, so the folder structure is /path/to/data/templates/. You can also set the variable TEMPLATES_FOLDER to change that path.

Any changes in the web vault you'd need to recompile it yourself to apply them.

**Comment by ChonoN** [comment]
> About emails and admin page, you can modify the templates available [here](https://github.com/dani-garcia/bitwarden_rs/tree/master/src/static/templates/) and place them inside the data folder, so the folder structure is /path/to/data/templates/. You can also set the variable TEMPLATES_FOLDER to change that path.
> 
> Any changes in the web vault you'd need to recompile it yourself to apply them.

Hi, I might be missing something very simple but I created a folder called templates in the bw-data folder so it looks like this **/bw-data/templates** with the template files inside. however when an email is sent it still shows up the same way as before. Am I supposed to do an additional step?

**Comment by dani-garcia** [comment]
Note that the template files for email should be in your_data_folder/templates/email/ and inside that you should have all the hbs files, if you just place them in your_data_folder/templates it won't find them.

**Comment by ChonoN** [comment]
I did that after with both the admin and email within the templates folder and then including this;

 -e TEMPLATES_FOLDER=bw-data/templates/email \
 -e RELOAD_TEMPLATES=true \

**Comment by dani-garcia** [comment]
If your hbs files are in bw-data/templates/email, then you'd need to have -e TEMPLATES_FOLDER=bw-data/templates, and that should work.

Note that the reload_templates is only needed if you want to update the template files without restarting the server.

**Comment by ChonoN** [comment]
I did that but alas still nothing as it still uses the default, it might just be a case of me being glib then.

**Comment by fuanegua** [comment]
What about the images-folder? How can I change the logo?

**Comment by fuanegua** [comment]
I’ve tried it this way:

```
docker pull bitwardenrs/server:raspberry
docker run -d --name bitwarden -v /bw-data/:/data/ -p 8005:80 -e ADMIN_TOKEN=<token> --restart always  -e TEMPLATES_FOLDER=/bw-data/templates/ -e RELOAD_TEMPLATES=true -e ROCKET_TLS='{certs="/ssl/live/<example.com>/fullchain.pem",key="/ssl/live/<example.com>/privkey.pem"}'  -v /etc/letsencrypt/:/ssl/ bitwardenrs/server:raspberry
```

Everything works fine except the custom email-templates. What did I wrong?

**Comment by BlackDex** [comment]
@fuanegua This is not really build in the bitwarden_rs web-server, we only parse the templates.
Best thing to serve your own images using a separate endpoint or subdomain redirected by a reverse proxy for these items.

**Comment by BlackDex** [comment]
You could also download the pre-built web-vault, use that and add or change images in the images folder there.

**Comment by BlackDex** [comment]
Anyway, please continue this further on the forum please, since this is not an issue https://bitwardenrs.discourse.group/

Thanks :smile:
