### ISSUE TITLE
Getting '[error: cannot decrypt]' when using organisations

### ISSUE THREAD

**Issue by dabeeeenster** [dani-garcia/bitwarden_rs#77]
- Created an account, and an organisation. 
- Created a second account. 
- Associated second account with organisation
- Created login item with first account 
- When viewing the item with the second account, I just see ```[error: cannot decrypt]```

**Comment by mprasil** [comment]
Sounds like you didn't confirm the second account from the Organization owner (the first account) 

There are two steps, first you invite, then you confirm the invited user. (in original server there's mid step of user confirming they want to join Organization, but that one is skipped with bitwarden_rs as we don't have email functionality to send the invitation)

**Comment by mprasil** [comment]
I tried to reproduce this, but I can't. The only time I can see the "cannot decrypt" message is when the user is invited, but not yet confirmed. In the image bellow you can see Test2 user being in such state. (the list shows they are "accepted") You just need to confirm the user and they should see the cypher after they sync.

![image](https://user-images.githubusercontent.com/8255364/42657651-d208b81e-861a-11e8-9bf6-c44e9e00a392.png)

**Comment by dabeeeenster** [comment]
Thanks for the replies - this was as described - I still needed to confirm the second user. I guess SMTP config would be helpful here.

**Comment by mprasil** [comment]
As per discussion with Dani, I've created #80 to fix this. We shouldn't really be showing you the ciphers in the first place.
