### ISSUE TITLE
Invalid TOTP code when trying to log in

### ISSUE THREAD

**Issue by timaschew** [dani-garcia/bitwarden_rs#770]
### Subject of the issue
Invalid TOTP code when logging in via web vault. I'm pretty sure it worked when I've set it up.
I'm running bitwardn inside of dokku (docker). I've restarted the app and run `sudo timedatectl set-ntp true` to sync the time but it didn't help. On my phone I'm using andOTP and I've tested to login to GitHub with the same app and it works. So it seems that the server is the problem.

### Your environment
* Bitwarden_rs version: VAULT_VERSION="v2.10.1"
* Install method: Docker, Dockerfile, see at the bottom
* Clients used: web, Android, Chrome browser extension
* Reverse proxy and version: nginx (built-in with dokku)
* Version of mysql/postgresql: - (sqlite)
* Other relevant information: 

### Steps to reproduce
Just deployed everything as it is via the Dockerfile. Deployment is handled by [dokku](https://github.com/dokku/dokku)

### Expected behaviour
Login to web vault and typing in password and afterwards 2FA code without any error.

### Actual behaviour
Logging in to to my web vault and typing in my password. After typing in the 2FA code it shows a red notification with the text: **An error has occurred. Invalid TOTP code**

Here is the server log:

```
[2019-12-18 06:19:04][rocket::rocket][INFO] POST /api/accounts/prelogin application/json; charset=utf-8:
[2019-12-18 06:19:04][_][INFO] Matched: POST /api/accounts/prelogin (prelogin)
[2019-12-18 06:19:04][_][INFO] Outcome: Success
[2019-12-18 06:19:04][_][INFO] Response succeeded.
[2019-12-18 06:19:05][rocket::rocket][INFO] POST /identity/connect/token application/x-www-form-urlencoded; charset=utf-8:
[2019-12-18 06:19:05][_][INFO] Matched: POST /identity/connect/token (login)
[2019-12-18 06:19:05][bitwarden_rs::error][ERROR] JsonError. {"TwoFactorProviders":[0],"TwoFactorProviders2":{"0":null},"error":"invalid_grant","error_description":"Two factor required."}
[2019-12-18 06:19:05][_][INFO] Outcome: Success
[2019-12-18 06:19:05][_][INFO] Response succeeded.
[2019-12-18 06:19:18][rocket::rocket][INFO] POST /identity/connect/token application/x-www-form-urlencoded; charset=utf-8:
[2019-12-18 06:19:18][_][INFO] Matched: POST /identity/connect/token (login)
[2019-12-18 06:19:18][bitwarden_rs::error][ERROR] Invalid TOTP code. Invalid TOTP code
[2019-12-18 06:19:18][_][INFO] Outcome: Success
[2019-12-18 06:19:18][_][INFO] Response succeeded.
```

### Relevant logs
Here is the dockerfile which is used for deployment:

```Dockerfile
# Using multistage build: 
# 	https://docs.docker.com/develop/develop-images/multistage-build/
# 	https://whitfin.io/speeding-up-rust-docker-builds/
####################### VAULT BUILD IMAGE  #######################
FROM alpine as vault

ENV VAULT_VERSION "v2.10.1"

ENV URL "https://github.com/dani-garcia/bw_web_builds/releases/download/$VAULT_VERSION/bw_web_$VAULT_VERSION.tar.gz"

RUN apk add --update-cache --upgrade \
    curl \
    tar

RUN mkdir /web-vault
WORKDIR /web-vault

RUN curl -L $URL | tar xz
RUN ls

########################## BUILD IMAGE  ##########################
# Musl build image for statically compiled binary
FROM clux/muslrust:nightly-2018-12-01 as build

ENV USER "root"

WORKDIR /app

# Copies the complete project
# To avoid copying unneeded files, use .dockerignore
COPY . .

RUN rustup target add x86_64-unknown-linux-musl

# Build
RUN cargo build --release

######################## RUNTIME IMAGE  ########################
# Create a new stage with a minimal image
# because we already have a binary built
FROM alpine:3.9

ENV ROCKET_ENV "staging"
ENV ROCKET_PORT=80
ENV ROCKET_WORKERS=10
ENV SSL_CERT_DIR=/etc/ssl/certs

# Install needed libraries
RUN apk add \
        openssl\
        ca-certificates \
    && rm /var/cache/apk/*

RUN mkdir /data
VOLUME /data
EXPOSE 80
EXPOSE 3012

# Copies the files from the context (Rocket.toml file and web-vault)
# and the binary from the "build" stage to the current stage
COPY Rocket.toml .
COPY --from=vault /web-vault ./web-vault
COPY --from=build /app/target/x86_64-unknown-linux-musl/release/bitwarden_rs .

# Configures the startup!
CMD ./bitwarden_rs
```

**Comment by BlackDex** [comment]
Could you verify the date/time on the docker host?
Most of the time this is an issue with timedrifting of the server.
By default there is a timedrift allowed of 30 seconds before and after. But if the server exceeds that, you will get invalid TOTP code messages.

**Comment by timaschew** [comment]
Yes I've checked the time and it is good. 

`date -u` is equal in host, container and my local machine but `date` shows a **UTC** zone in the container but **CET** in the host.

**Comment by timaschew** [comment]
I've deleted the row from the twofactory database and logged in and added again 2FA and now it works again.
BTW: changing the `enabled` in the twofactory table do `0` didn't work.

**Comment by BlackDex** [comment]
Well, if you deleted the row, and enabled the 2FA again, it looks like the 2FA key was invalid.
It could mean two things, it was wrongly generated/displayed, or wrongly saved.
But that would also be strange since it will only activate after a verification code.

In any case, in the code the current time used is also printed during the TOTP error just for an extra check.

**Comment by dani-garcia** [comment]
Closed due to inactivity.

**Comment by probablypablito** [comment]
im having the same issue with the cloud verison.
my TOTP codes suddenly don't work after working for a while. They work fine when i use google authenticator or something similar, but the ones inside Bitwarden don't.

**Comment by Jackdrl** [comment]
Open it because it's a genuine issue :)

**Comment by BlackDex** [comment]
@Jackdrl are you sure? Have you checked the date and time etc..
Also, i would suggest to open a discussion with an output of the support string you can generate from the diagnostics page.
