### ISSUE TITLE
Cannot run migration with sqlite 3.11.0 on Ubuntu

### ISSUE THREAD

**Issue by timaschew** [dani-garcia/bitwarden_rs#775]
I have sqlite3 version 3.11.0 (Ubuntu doesn't have any newer version) and all the migrations scrips where a column is renamed are not working (syntax error).

On StackOverflow I found this: https://stackoverflow.com/a/56260765/736518
So can I just rename the table and create a new one and copy the rows?

> With these four steps you can manually change any SQLite table. Keep in mind that you will also need to recreate any indexes, viewers or triggers on the new table as well.

Do I need to recreate any indexes, viewers or triggers? If yes, how do I do this?

BTW: I've tried to install [the Precompiled Binaries for Linux](https://sqlite.org/download.html) but could not execute them: `bash: ./sqlite3: No such file or directory`

**Comment by dani-garcia** [comment]
We are using a bundled SQLite version that supports that functionality, are you trying to run the scripts by hand? Bitwarden_rs runs them automatically.

**Comment by timaschew** [comment]
🤣 yes I've tried to run them manually.

Great then I will just upgrade the Dockerfile. Thanks!
