### ISSUE TITLE
Address already in use when starting Bitwarden_rs

### ISSUE THREAD

**Issue by Jungack** [dani-garcia/bitwarden_rs#776]
Hello,
I am trying to run bitwarden_rs without docker on my server. However, I come to this error :
`[bitwarden_rs][ERROR] Launch error Bind(Io(Os { code: 98, kind: AddrInUse, message: "Address already in use" }))
`
I am quite a noob sorry... In fact I think I don't know how to manage the `.env` file. After having compiled bitwarden_rs and installed the web-vault, I have copied the `.env.template` file to `/bitwarden_rs/target/release/` and renamed It to `bitwarden_rs.env`. Then, I have modified `WEBSOCKET_PORT=3012` to `WEBSOCKET_PORT=3013` and `ROCKET_PORT=8000` to `ROCKET_PORT=8001`. However, the same error is still there. What is wrong?
Thank you

**Comment by mprasil** [comment]
Hi @Jungack, `bitwarden_rs` is expecting file named `.env` so your file is very likely ignored and then `bitwarden_rs` defaults to port `80` which seems to be used.

**Comment by Jungack** [comment]
> Hi @Jungack, `bitwarden_rs` is expecting file named `.env` so your file is very likely ignored and then `bitwarden_rs` defaults to port `80` which seems to be used.

Hello,

Thank you ! So you mean that I have to rename my `bitwarden_rs.env` file to just `.env` and put It in `/bitwarden_rs/target/release/`?

I have a LEMP stack on my server actually with Nextcloud (and Onlyoffice which is running port `8000`). How can I change the default port used by Bitwarden_rs to remove all the conflicts?

Thank you !

**Comment by fbartels** [comment]
How are you planning on starting the bitwardenrs process? If you are using systemd, the you could also load the env file into the environment with it: https://serverfault.com/a/413408

**Comment by Jungack** [comment]
> How are you planning on starting the bitwardenrs process? If you are using systemd, the you could also load the env file into the environment with it: https://serverfault.com/a/413408

Thanks for replying ! I first wanted to start bitwarden_rs using `cargo run --features sqlite --release`. However you are right, after being able to use the previous command, I planned to use systemd to start bitwarden_rs on boot !
So how can I load the` .env` file first without systemd ?

**Comment by fbartels** [comment]
Like you would source any other file in your shell ;-)

`source .env`

**Comment by Jungack** [comment]
> Like you would source any other file in your shell ;-)
> 
> `source .env`

Ok tanks all is working ! Thank you for your patience !
