### ISSUE TITLE
`Web` devices have longer device UUID that does not fit to MySQL/PostgreSQL `devices.uuid` field

### ISSUE THREAD

**Issue by tyler-public** [dani-garcia/bitwarden_rs#777]
### Subject of the issue
Using sqlite the column `devices.uuid` is of length 40, but the column created in the mysql migration is only 36 characters long

### Your environment

* Bitwarden_rs version: Version 1.13.0-25454697

* Install method: docker
* Other relevant information: manually modifying the columns `devices.uuid` and `devices.user_uuid` to be `char(40)` solve this issue

### Steps to reproduce
1. create sqlite db
2. migrate to mysql via the wiki instructions
3. import sqlite dump into mysql database
4. error

### Expected behaviour
migration goes smoothly

### Actual behaviour
`ERROR 1406 (22001) at line 14: Data too long for column 'uuid' at row 1`

### Relevant logs
`web-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee` is 40 characters long, but the column in the mysql table is created as `char(36)`

**Comment by mprasil** [comment]
That's interesting, it seems like devices with name `web` have longer UUID for some reason. (the extra `web-` prefix) Makes me wonder why/if these clients actually work with MySQL backend. (SQLite has no length limit, so we probably haven't noticed that issue there) I'd assume it would also affect ProtgreSQL users.

I think this is an actual bug now and it must be problematic even outside of migration issues.

**Comment by mprasil** [comment]
Sample SQL data as fetched from sqlite:

```
sqlite> select uuid, name from devices;
86f23efe-8489-49c5-be6e-9b142ec8a20a|safari
web-c65ae106-b674-4f70-a2ef-a60de293769a|web
web-69caa3c7-729c-4bd8-9d73-73cb6d7e6a71|web
88100c74-493e-46b9-aaf0-2ce35fc78c9d|D5803
```

**Comment by dani-garcia** [comment]
Interesting, I just checked my database and none of my devices do that, though I remember a long time ago I manually added that web- prefix for a reason I can't remember now. Is is possible that those are some very old devices?

**Comment by tyler-public** [comment]
They most definitely are old devices, I've been using Bitwarden for quite some time now

-------- Original Message --------

**Comment by mprasil** [comment]
Would it make sense to add migrations SQL to drop any `web-*` devices?

**Comment by tyler-public** [comment]
If the UUIDs aren't used anymore, then yes. Otherwise expanding the column to 40 characters would also be an option.

**Comment by mprasil** [comment]
@dani-garcia can you point me to a piece of code where the `web-` prefix was added? I can't find it and github search certainly doesn't help.. Just to make sure it's already removed.

**Comment by dani-garcia** [comment]
Closed due to inactivity.
