### ISSUE TITLE
Docker image, unable to login

### ISSUE THREAD

**Issue by Megalex42** [dani-garcia/bitwarden_rs#781]
# Subject of the issue

When starting the docker image, it asks to sign up. Sign up doesn't work.

### Expected behaviour

Bitwarden_rs advertises itself as being self hosted, but upon launching it, it asks to sign up or login. I assume it's an account on the bitwarden website, which I don't have and don't desire to have.

There also doesn't seem to be a way to create local accounts for self-hosting purposes

You might refer me to the "admin" faq, but see it here: https://imgur.com/a/N7krPNe and how there's no way to create an account

**Comment by Megalex42** [comment]
See following screenshot of when I access the site for the first time: https://imgur.com/a/rN4yvOI

**Comment by fbartels** [comment]
Hi, Just because something is self hosted does not mean that there are no user accounts ;-)

You have to click on the "create an account".

**Comment by Megalex42** [comment]
How do you protect is so that Account Creation is not open to anyone who has knowledge of the URL?

Also, it seems like the Submit button doesn't do anything

**Comment by mprasil** [comment]
As @fbartels says, you need to create account. This account is created on *your* server (it's an local account) and it is in no way managed or hosted by official upstream bitwarden service.

Submit not doing anything sounds like you're not using HTTPS and trying to register from Chrome. Use Firefox for registration or set up HTTPS.

If you want to disable signups for new users, you can for example set `SIGNUPS_ALLOWED=false` - see [docs here](https://github.com/dani-garcia/bitwarden_rs/wiki/Disable-registration-of-new-users).

**Comment by Megalex42** [comment]
Wow plz, guys, let's be reasonable.

What service out there allows ANONYMOUS REGISTRATION? Think about it. Like, really think about it. that's SUPER INSECURE.

>SIGNUPS_ALLOWED=false

Sure, how do you create an account if registration is disabled?

>you need to create account. This account is created on your server

No it's not. have you even tried it? I don't think you have.

**Comment by fbartels** [comment]
> How do you create an account while sign up is disabled?

There is a wiki here with lots of helpful articles, for example this one:
https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-admin-page

**Comment by Megalex42** [comment]
> > How do you create an account while sign up is disabled?
> 
> There is a wiki here with lots of helpful articles, for example this one:
> https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-admin-page
> 
> > You might link me to some SMTP server config, but think about it. Can you name even 1 program that requires an SMTP server configured to even work, without the ability to create a local account?
> 
> This project is not among those that require a working SMTP setup. But I can think of a ton. Roundcube as a Webmailer is one.

Thanks for the reply. Plz see a screenshot of the admin page:

https://imgur.com/a/N7krPNe

Again, no way to create an account. "invite" link may send a request thru SMTP, but there's something missing.

**Hey guys, plz make sure to actually test the scenario before replying.

All of the replies so far are completely irrelevant and already been answered**

**Comment by Megalex42** [comment]
The docker image is completely broken

https://imgur.com/a/SkiHNOI

Login doesn't even work lol

**Comment by Megalex42** [comment]
How to recreate the issue?

Go to  https://github.com/dani-garcia/bitwarden_rs

Follow the two step installation:

docker pull bitwardenrs/server:latest

docker run -d --name bitwarden -v /bw-data/:/data/ -p 8080:80 bitwardenrs/server:latest

Browse to http://localhost:8080

Witness that your Bitwarden doesn't work at all

**Comment by fbartels** [comment]
The following works for me:

`docker run -d --name=bitwarden-rs --restart=unless-stopped -v /var/lib/bitwarden_rs:/data/ -v /etc/localtime:/etc/localtime:ro --env-file ./env -p 127.0.0.1:9080:80 -p 127.0.0.1:3012:3012 bitwardenrs/server:latest`

But the only real difference between my command and yours are some optional parameters (like --env-file and forwarding the websocket port).

**Comment by Megalex42** [comment]
Mmm our command is basically the same. We're pulling the same docker image and forwarding port 80

When you say "work" what do you mean? I always get the error shown in https://imgur.com/a/SkiHNOI

**Comment by fbartels** [comment]
When I say work I mean create an account via the "create account" button and afterwards login with this account.

**Comment by mprasil** [comment]
@Megalex42, please read the replies first before telling us we don't understand how bitwarden_rs works. All of us replying here are contributors and we know the code and how it works quite well.

The issue with creating account is exactly the problem I've told you about. You're using Chrome and accessing your service via unencrypted HTTP protocol. Chrome does not support some crypto API in this configuration and that's why it doesn't work. It's in my comment above, it's also in the Readme. Either use different browser (just for signup, the rest should work) or set up HTTPS.

As for restricting who can create account, there are multiple ways how to achieve that.

**Comment by Megalex42** [comment]
So there's no way to pre-create an account?

**Comment by mprasil** [comment]
You can start `bitwarden_rs` with admin token and disabled signups. Then you can invite user from admin interface. Inviting user does not need to actually have working SMTP, if you have no SMTP set, it just means that user with that email will be able to create account even though the signups are otherwise disabled.
