### ISSUE TITLE
Allow user account creation during "docker run" to allow to login when SIGNUPS_ALLOWED is false and it's the first run.

### ISSUE THREAD

**Issue by Megalex42** [dani-garcia/bitwarden_rs#782]
Allow user account creation thru CLI tools to allow for better security, control and batch/automation

We know that we can disable signup:

https://github.com/dani-garcia/bitwarden_rs/wiki/Disable-registration-of-new-users

We can disable invitation:

https://github.com/dani-garcia/bitwarden_rs/wiki/Disable-invitations

But how do we create a user account to login with when SIGNUP is disabled?

There should be a way to create users thru command line

Currently, Signup is only allowed thru the GUI, which requires a few clicks and user interaction.
What if an admin wants to create 30 user accounts? It could become tedious to do manually

Thanks!

**Comment by mprasil** [comment]
> What if an admin wants to create 30 user accounts? It could become tedious to do manually

Well if you disable invitations, there's no good way to achieve that as this is what invitations are for. But if you don't disable invitations, you can create Organization and then any email invited into Organization (which can be done by any user that has the right to do so) will be able to register even with `SIGNUPS_ALLOWED=false`. That way you can disallow registration of random users, but can still let the users in a company or some other group to grow naturally as they invite each other.

I believe we have documentation problem, feel free to create issues for that and we can improve the wiki as some things are obvious to us, but might not be to new users.
