### ISSUE TITLE
"copy password" button not working on Chrome/Safari in web-vault 2.12.1

### ISSUE THREAD

**Issue by pdarcos** [dani-garcia/bitwarden_rs#786]
Hi guys,

Not sure if this is a bug in upstream bitwarden or in bitwarden_rs web vault, but the fact remains that something isn't working right when in the past it worked fine.

I opened a ticket on bitwarden [here](https://github.com/bitwarden/web/issues/436) but I suspect Kyle isn't going to spend much time on this it seems to work OK on the original bitwarden web vault.

I compiled latest web-vault as per your wiki and everything works fine except for the copy password button inside any web-vault item on Chrome/Brave and Safari (Firefox works fine).

I also tried recompiling the web vault without applying your patch but the issue remains - at least that rules out your patch as the cause of this bug.

Anyone else seeing this odd behavior? Unfortunately the logs don't show anything relevant, even when set to trace.

Any clues?

Cheers

**Comment by pdarcos** [comment]
Possibly related: I also just noticed I can no longer create any new organizations on the web-vault.
It's now showing me the bitwarden license file dialog (see screenshot).

![bitwarden_rs](https://user-images.githubusercontent.com/32959420/71560683-10320b00-2a65-11ea-95bf-2c2325ecf65a.png)

This is all very weird. I'm probably going to revert to an older web-vault version that was working fine.

Let me know if you need any logs, etc

**Comment by pdarcos** [comment]
FYI, I also just recompiled bitwarden_rs from latest git and the problems remain.

**Comment by pdarcos** [comment]
Update: I just recompiled the web vault using version 2.12.0 instead of latest master and now copy/paste on Chrome is working again. Kyle is also looking into this since it seems to be a bug recently introduced upstream.

Nonetheless, the inability to add organizations (as seen in the screenshot above) remains.

Should I close this ticket and open one for the organizations bug?

**Comment by dani-garcia** [comment]
If it asks for the license file it's because it was compiled wrong, I don't remember of the top of my head but there are two ways to compile the vault, one is called self hosted and the other is the default. You need to use the default one, even if the name seems to imply the opposite. Check the build script in my bw_web_builds repo.

**Comment by pdarcos** [comment]
Aha, that would explain it then!

I was using npm run dist:selfhost because I wanted to make sure GA and any other privacy compromising features were completely removed.

Does the default one strip those out too?
Thanks

**Comment by dani-garcia** [comment]
Analytics are already disabled in the patches we have, as far as I know that's the only 3rd party script in included.

**Comment by pdarcos** [comment]
Thanks @dani-garcia

**Comment by MeiRos** [comment]
Just noticed that I have the same issue lika pdarcos. Not the 'new organization' but the 'copy password' button isn't working. Chrome version 79.0.3945.123 and web vault version 2.12.1.
Is your copy password working @pdarcos ?
