### ISSUE TITLE
Server unaccessible via web

### ISSUE THREAD

**Issue by Ryonez** [dani-garcia/bitwarden_rs#79]
Sometime after 79fccccad778088093bad858258aafd7f2037e70 the server became inaccessible. There's been no changes other then a docker update, I now cannot access the server.

Edit, I should point out, I'm getting a `ERR_CONNECTION_REFUSED` response.

**Comment by Ryonez** [comment]
I'm unable to roll back the docker to test, @mprasil would you mind setting some tags up so I can try the older builds?

**Comment by mprasil** [comment]
Hi, what is your setup? 79fcccc actually fixed issue where service wasn't accessible outside of container. (issue introduced in #70) Right now I'm running the latest image and it seems to launch properly.

Can you share your logs when starting the container up? It should say something like:
```
Rocket has launched from http://0.0.0.0:80
```
Also please share how are you starting the container.

As for the tags, I'd like to. I need to make @dani-garcia bump up the version every now and then. I was thinking about making some daily tag once things settle down a bit.

**Comment by Ryonez** [comment]
`Configured for development.
=> address: localhost
=> port: 8000
=> log: normal
=> workers: 16
=> secret key: generated
=> limits: forms = 32KiB, json* = 10MiB
=> tls: disabled
Mounting '/':
=> GET /
=> GET /<p..>
=> GET /attachments/<uuid>/<file..>
=> GET /alive
Mounting '/api':
=> POST /api/accounts/register
=> GET /api/accounts/profile
=> POST /api/accounts/profile
=> GET /api/users/<uuid>/public-key
=> POST /api/accounts/keys
=> POST /api/accounts/password
=> POST /api/accounts/security-stamp
=> POST /api/accounts/email-token
=> POST /api/accounts/email
=> POST /api/accounts/delete
=> GET /api/accounts/revision-date
=> GET /api/sync
=> GET /api/ciphers
=> GET /api/ciphers/<uuid>
=> GET /api/ciphers/<uuid>/admin
=> GET /api/ciphers/<uuid>/details
=> POST /api/ciphers
=> POST /api/ciphers/admin
=> POST /api/ciphers/import
=> POST /api/ciphers/<uuid>/attachment multipart/form-data
=> POST /api/ciphers/<uuid>/attachment/<attachment_id>/delete
=> DELETE /api/ciphers/<uuid>/attachment/<attachment_id>
=> POST /api/ciphers/<uuid>/admin
=> POST /api/ciphers/<uuid>/share
=> POST /api/ciphers/<uuid>
=> PUT /api/ciphers/<uuid>
=> POST /api/ciphers/<uuid>/delete
=> POST /api/ciphers/<uuid>/delete-admin
=> DELETE /api/ciphers/<uuid>
=> POST /api/ciphers/delete
=> POST /api/ciphers/purge
=> POST /api/ciphers/move
=> GET /api/folders
=> GET /api/folders/<uuid>
=> POST /api/folders
=> POST /api/folders/<uuid>
=> PUT /api/folders/<uuid>
=> POST /api/folders/<uuid>/delete
=> DELETE /api/folders/<uuid>
=> GET /api/two-factor
=> POST /api/two-factor/get-recover
=> POST /api/two-factor/recover
=> POST /api/two-factor/get-authenticator
=> POST /api/two-factor/authenticator
=> POST /api/two-factor/disable
=> GET /api/organizations/<org_id>
=> POST /api/organizations
=> POST /api/organizations/<org_id>/delete
=> POST /api/organizations/<org_id>/leave
=> GET /api/collections
=> GET /api/organizations/<org_id>/collections
=> GET /api/organizations/<org_id>/collections/<coll_id>/details
=> GET /api/organizations/<org_id>/collections/<coll_id>/users
=> POST /api/organizations/<org_id>
=> POST /api/organizations/<org_id>/collections
=> POST /api/organizations/<org_id>/collections/<col_id>/delete-user/<org_user_id>
=> POST /api/organizations/<org_id>/collections/<col_id>
=> POST /api/organizations/<org_id>/collections/<col_id>/delete
=> POST /api/ciphers/<uuid>/collections
=> POST /api/ciphers/<uuid>/collections-admin
=> GET /api/ciphers/organization-details?<data>
=> GET /api/organizations/<org_id>/users
=> POST /api/organizations/<org_id>/users/invite
=> POST /api/organizations/<org_id>/users/<user_id>/confirm
=> GET /api/organizations/<org_id>/users/<user_id>
=> POST /api/organizations/<org_id>/users/<user_id>
=> POST /api/organizations/<org_id>/users/<user_id>/delete
=> PUT /api/devices/identifier/<uuid>/clear-token
=> PUT /api/devices/identifier/<uuid>/token
=> GET /api/settings/domains
=> POST /api/settings/domains
Mounting '/identity':
=> POST /identity/connect/token
Mounting '/icons':
=> GET /icons/<domain>/icon.png
Rocket has launched from http://localhost:8000`

Even though it says port 8000, it seems to be 80. Just to see if something changed, I map port 8000 as well, and that didn't work either. (I haven't changed anything in it.)

As to starting the docker, I use unRaid and start it from the web ui using the latest build with the following settings:
![image](https://user-images.githubusercontent.com/16157130/42678037-c8f95780-86d1-11e8-88df-f75b1baf1d8d.png)

Any chance dock can autotag builds in the meantime?

**Comment by mprasil** [comment]
This is the key:
```
Configured for development.
```

It sounds like you're running either the old broken image or you override the `ROCKET_ENV` variable. It needs to be set to staging, which is the default in the latest image. Can you force unRaid to pull the image?

**Comment by mprasil** [comment]
So far sounds like duplicate of #73.

**Comment by Ryonez** [comment]
Alright, it was because `ROCKET_ENV` was changed to be user settable. Not sure why I though it was 8000, or why it didn't respond when I tested the port.

The log is showing a warning:
`Warning: environment is 'production', but no `secret_key` is configured`

Do I need to worry about this?

**Comment by Ryonez** [comment]
Wait, it has a ENV set? Sorry, the page didn't update. One moment, and I can force it to check for an update, though I updated it this morning.

**Comment by dani-garcia** [comment]
The secret_key is only needed for the use of encrypted cookies, and we don't use cookies at all, so it should be fine.

**Comment by Ryonez** [comment]
Huh, seems that there was an update. Pulling it down now.

Yup, update works without the flag. Thank you for your help guys.
