### ISSUE TITLE
Unable to change email address

### ISSUE THREAD

**Issue by yegle** [dani-garcia/bitwarden_rs#792]
# Subject of the issue

It looks like I'm unable to change the email address from the settings page.

The request payload looks like this:
```
{"newEmail":"foo@example.com","masterPasswordHash":"some-hash"}
```

The response payload looks like this:
```
{"ErrorModel":{"Message":"Email cannot be changed to this address","Object":"error"},"Message":"","Object":"error","ValidationErrors":{"":["Email cannot be changed to this address"]},"error":"","error_description":""}
```

Server side log looks like this:

```
[2020-01-01 03:32:43][error][ERROR] Email cannot be changed to this address
[2020-01-01 03:32:43][response][INFO] POST /api/accounts/email-token (post_email_token) => 400 Bad Request
```

### Your environment
* Bitwarden_rs version: 1.13.0-95dd1cd7
* Install method: docker
* Clients used: web UI
* Reverse proxy and version: probably not applicable
* Version of mysql/postgresql:  probably not applicable
* Other relevant information: 

### Steps to reproduce
Change email address from the web under settings

### Expected behaviour
The email address changed.

### Actual behaviour
An error appear in the web:

An error has occurred.
Email cannot be changed to this address

**Comment by WinkelB** [comment]
Having the Same Problem.

**Comment by aneisch** [comment]
Seeing this as well. It looks like this is due to the following line:
**[https://github.com/dani-garcia/bitwarden_rs/blob/8d1b72b9512b90775e671b7ba08cd552a0aabd13/src/api/core/accounts.rs#L374](https://github.com/dani-garcia/bitwarden_rs/blob/8d1b72b9512b90775e671b7ba08cd552a0aabd13/src/api/core/accounts.rs#L374)**

If I allow signups I'm then able to change an email address.

**Comment by tomuta** [comment]
I think this might be a problem in `can_signup_user()`. I believe the function should return `true` if the whitelist is empty. Right now it only returns `true` if a match for the domain is found.

**Comment by dani-garcia** [comment]
This should be fixed now in the latest master, thanks to @tomuta
