### ISSUE TITLE
Building Binary Question

### ISSUE THREAD

**Issue by brentl99** [dani-garcia/bitwarden_rs#796]
I am using the instructions at:
  https://github.com/dani-garcia/bitwarden_rs/wiki/Building-binary
to build a binary.

There is an initial reference in the "Run/Compile" documentation to:
   "just compile with sqlite (binary located in target/release/bitwarden_rs)"
   "just compile with mysql (binary located in target/release/bitwarden_rs)"

Where is "target/release/bitwarden_rs"?

I have successfully compiled the web-vault manually given the instructions provided on this page, but I believe the SQLite and MySQL steps assume a prior step that is not documented.

Thank you.

**Comment by mqus** [comment]
Just below those two lines there is "cargo build --features sqlite --release" which you need to run to compile bitwarden_rs with sqlite support. This creates the binary in the `release` subfolder of the `target` directory. What may be missing from the documentation is that you have to download and extract the source code from a [release](https://github.com/dani-garcia/bitwarden_rs/releases) or from the current development state (https://github.com/dani-garcia/bitwarden_rs/archive/master.zip) before running the cargo command within the extracted directory. We probably assumed some kind of developer background and assumed the (to us obvious) state you usually start to compile from.

If this didn't help you, could you share some more details with us? Which operating system did you try to compile this on? What exactly did you do (steps we can use to repeat your approach, what have you entered in your shell, what did you click, etc) and what did you expect vs what you found.

PS: Thinking of the documentation, what background do you have and what level of detail would you expect personally? We will try to improve the docs according to your feedback.

**Comment by brentl99** [comment]
Thank you.  That is helpful and I will look at this again.
I am building it on CentOS 7 using devtools-7.  This required building node v11 from source as the node distribution that comes with CentOS 7 is too old.
I have also successfully completed all the "Install the web-vault" steps except the last step also involving cargo.
And yes, I know this is a "dumb" question, I am Stubbornly attempting to build bitwarden_rs "from scratch" and trying to see if I can get it working without docker, all while having no prior first hand experience with node, or docker.  I understand that may be unadvisable, but I know it is doable and I want to figure it out.
So I very much appreciate your patience.
Once I get it operational I will provide feedback for you to consider.
Thank you again for your reply.

**Comment by mqus** [comment]
> I am building it on CentOS 7 using devtools-7

Maybe the rpm package (https://github.com/dani-garcia/bitwarden_rs/wiki/Available-packages) could be useful to you.

> And yes, I know this is a "dumb" question, I am Stubbornly attempting to build bitwarden_rs "from scratch" and trying to see if I can get it working without docker, all while having no prior first hand experience with node, or docker. I understand that may be unadvisable, but I know it is doable and I want to figure it out.

That's how I did it, too ;-) I'm also not in the "docker all the things" faction and want to run my services on the os without any layers in between. I'm maintaining the package for Archlinux , so feel free to ask anything you want to know. If you want to start it automatically on system startup, I recommend using systemd (explained in the [wiki](https://github.com/dani-garcia/bitwarden_rs/wiki/Setup-as-a-systemd-service)).

**Comment by brentl99** [comment]
Thank you for your help.  I have bitwarden_rs built and almost running.  I am creating a new issue for my current (OpenSSL) issue.
