### ISSUE TITLE
Cannot pull rapsberry image using podman

### ISSUE THREAD

**Issue by fvzwieten** [dani-garcia/bitwarden_rs#797]
#713 # Subject of the issue
I have managed to get a working podman on raspbian 10 using the instructions in https://computingforgeeks.com/how-to-install-podman-on-debian/
However, when I do a pull for the raspberry image I get this:
root@rpi41:~# podman pull bitwardenrs/server:raspberry
Trying to pull docker.io/bitwardenrs/server:raspberry...
  Image architecture mismatch: image uses "amd64", expecting "arm"

I expect this is due to the fact the image in dockerhub is tagged as amd64 by mistake. Doing the same command with docker (running on a different rpi) seems to just pull the image..

Could you please change the architecture to "arm" on these images?

**Comment by mprasil** [comment]
Yeah, unfortunately docker hub does not support building ARM images, they only support amd64, so we use `balenalib/armv7hf-debian:buster` as base image, that can emulate arm parts on amd64 hardware. So technically it is amd64 image, but the binaries inside are actually arm. I'll have to figure out if there's some way to override the architecture label.

BTW maybe this could also be reported as bug in podman? I think they do the right thing by checking and refusing image with incorrect architecture label, but they also try to be compatible with docker.

**Comment by mprasil** [comment]
I think we could use [hooks](https://docs.docker.com/docker-hub/builds/advanced/) and some [trickery](https://github.com/rmoriz/multiarch-test/blob/master/hooks/build#L29-L51), but it's rather involved process..

**Comment by anishsuku** [comment]
I was able to find a workaround this issue using the "--override-arch=amd64" flag.

Eg:
podman pull --override-arch=amd64 bitwardenrs/server:raspberry
podman run --override-arch=amd64 bitwardenrs/server:raspberry ...

**Comment by fvzwieten** [comment]
Thanks @anishsuku That seemed to be a hidden switch up until recently. It worked like a charm.
