### ISSUE TITLE
Possible to use without a volume (connect to gcp or aws storage bucket instead or nosql document store)

### ISSUE THREAD

**Issue by dslovin** [dani-garcia/bitwarden_rs#798]
### Subject of the issue
Want to use without a local storage volume. Either use a Document DB or cloud storage bucket 

* Install method: docker
* Clients used: all 
* Reverse proxy and version: all
* Version of mysql/postgresql: all 
* Other relevant information:

**Comment by mprasil** [comment]
That is not supported. We use [diesel](https://diesel.rs/) as DB backend and that one does not support Document DB. You can use either hosted MySQL or PostgreSQL although I understand these wouldn't be as cheap to run.

There's pretty cool [serverless implementation of bitwarden API](https://github.com/vvondra/bitwarden-serverless) although from my understanding much more limited, but maybe that would be good enough for you?

**Comment by dslovin** [comment]
Thanks, I’ll check it out. I really liked your implementation. Hopefully you consider serverless in the future :)

**Comment by mprasil** [comment]
I think we can close this as the question was answered and AFAIK it's not going to happen anytime soon. (It would require support in Diesel or major code change to support any of the other DBs)
