### ISSUE TITLE
latest raspberry image exits immediately with error 1

### ISSUE THREAD

**Issue by fvzwieten** [dani-garcia/bitwarden_rs#799]
### Subject of the issue
I run the following on rpi4 with raspian buster and docker.io:
`docker run -d --name bitwarden -v /data/bitwarden/:/data/ -p 8081:80 bitwardenrs/server:latest`

I get:
```
root@rpi41:~# docker ps -a
CONTAINER ID        IMAGE                       COMMAND             CREATED             STATUS                      PORTS               NAMES
cc1c4bbabe84        bitwardenrs/server:latest   "/bitwarden_rs"     12 seconds ago      Exited (1) 10 seconds ago                       bitwarden
```
I tried this also on a rpi3 running dietpi (stretch).

I used to run the mprasil/bitwarden:raspberry image which worked (and still works) fine on both the rpi3 and rpi4, so I will for now keep using that.

**Comment by dani-garcia** [comment]
On a raspbery you'd have to use `bitwardenrs/server:raspberry`, the image you are currently using is for x86 hardware.

**Comment by Extarys** [comment]
New image? Update time!
Thanks for your hard work @dani-garcia

**Comment by fvzwieten** [comment]
Oops. Sorry!
