### ISSUE TITLE
Don't show Organization ciphers to unconfirmed users

### ISSUE THREAD

**Issue by mprasil** [dani-garcia/bitwarden_rs#80]
This leads to confusion and ciphers that can't be decrypted (#77)

**Comment by mprasil** [comment]
I've totally missed the 2f892cb commit. So chances are this might be resolved already. Going to rebuild the image and test.

**Comment by dani-garcia** [comment]
It's a partial fix, at least. This hides the ciphers, but we should probably also not show the organization or the collections unless the user is confirmed.

We should also make sure that an unconfirmed admin or owner can't make changes to the org.

**Comment by mprasil** [comment]
Good point do you want to keep the issue open for that?

**Comment by dani-garcia** [comment]
Yeah, I think we should leave it open for now.

**Comment by mprasil** [comment]
This should be completely resolved with #89 merged in.
