### ISSUE TITLE
How to migrate from Bitwarden Docker to BitwardenRs Docker

### ISSUE THREAD

**Issue by Avalarion** [dani-garcia/bitwarden_rs#801]
Hey there,

no actual issue, but I don't want to miss anything. We are using Bitwarden hosted at our Servers and dislike this heavy infrastructure for only 7 users. As I read this implementation should be far more lightweight and easier to maintain than the official one.

I have a few questions which I was not able to find answers for in the wiki or in other issues.

1.) How to Migrate from Bitwarden Server to Bitwarden RS Server

We have a running bitwarden instance. What do we need to migrate the MSSql Installation to this? Docker is no issue, but I don't know Rust.

2.) Organisations for Free?

With this server it looks like we are not required to pay money to Bitwarden anymore. I read that you request your users to still pay money to Bitwarden for Client and Co update. We are going to do this, but did I understand the texts right?

3.) How to Update the Server

When we have all data in Bitwarden RS what is necessary to update the server? How often do we get bitwarden client releases and have to wait before we are able to work with Bitwarden RS again? Are data migrations to new formats done within the server or do we have to start scripts manually? Is this even a thing?

Just to know how stable this will be as this will become a very important part of our infrastructure.

Have a nice weekend,

Bastian

**Comment by ToeiRei** [comment]
1 - The migration itself could be some work as you'd have to export every user manually
2 - If you're only using it and not selling it
3 - Just pull the new image (or build a new one)

**Comment by dani-garcia** [comment]
1- There is no way to automatically migrate from MsSql to bitwarden_rs as I imagine the database structure is somewhat different, you'd have to manually export each user and organization and then reimport them into bitwarden_rs, maybe it could be scripted somehow with the help of the bitwarden CLI?

2- Bitwarden_rs doesn't require any payment of any kind, but that said, we heavily depend on the continued existence of all the clients to work, which is something I couldn't possibly afford to maintain on my free time. So while not necessary at all, if you are interested in the maintenance of all the bitwarden clients, then yes I'd recommend supporting the official bitwarden project.

3- My plan has always been that any migrations or configuration changes would be applied in a backwards compatible way, and so far it has been the case, so any updates should only consist of pulling in a new image or downloading a new release and restarting the server. If you are interested in having the most stable server possible, I'd recomend using only the releases and having a look at the changelog before updating (https://github.com/dani-garcia/bitwarden_rs/releases).

Also about client updates, so far there were only a couple of client updates that broke anything, but I've usually solved those issues in less than a week or even before the clients got released. Thankfully the server API doesn't receive many mayor changes.

**Comment by mprasil** [comment]
I think this was answered and can be closed. Feel free to reopen if you need more help.
