### ISSUE TITLE
OpenSSL detected, creating keys... data/rsa_key.pem: No such file or directory

### ISSUE THREAD

**Issue by brentl99** [dani-garcia/bitwarden_rs#802]
I have built bitwarden_rs v2.10.1 with node v11.14.0 and mariadb 5.5 on CentOS 7 without docker.
When I startup bitwarden_rs I get the following error:
 OpenSSL detected, creating keys... data/rsa_key.pem: No such file or directory

Can someone tell me where the "data" directory is, or is it supposed to be?
"openssl version -a" provides me with a OPENSSLDIR of  "/etc/pki/tls" which does not have "data" in the path so I presume that bitwarden has the key path built in somewhere.

Thank you.

**Comment by mqus** [comment]
the `data` directory is created in the directory from which you start bitwarden_rs (PWD). for example, if you start it in the console via calling
```
$ /bin/bitwarden_rs
```

while you are in the directory `/home/myuser`, it will try to create it as `/home/myuser/data` (the location of the binary is not relevant). if bitwarden_rs doesn't have the neccessary rights to do so, it will fail in the manner you described. 
Afaik, this has nothing to do with openssl itself.

**Comment by brentl99** [comment]
Thank you, that addressed my issue.  I just had to create the "data" directory within the current working directory.
