### ISSUE TITLE
unRAID template support

### ISSUE THREAD

**Issue by cheesemarathon** [dani-garcia/bitwarden_rs#813]
Hi there
I originally created a template for the bitwarden_rs docker container for use with unRAID. Now that there is an official docker image and unRAID template I have depreciated my template. 

I have had, since then, a few support questions and I just want to know where to direct people. Typically a support thread is opened on the unRAID forums and support is provided there, but if you would prefer it to be over here on github then that's cool. I just want to know where to send people 😊

Thanks for making this awesome software! I use it every day!

**Comment by ksarnelli** [comment]
Thanks for all your work on the deprecated template!  Any idea what the SERVER_ADMIN_EMAIL parameter does in the new template?  I can't find any documentation on it, and can't find any reference to an admin email in the user or admin UI.

**Comment by fbartels** [comment]
@cheesemarathon are you talking about this template? https://github.com/selfhosters/unRAID-CA-templates/blob/master/templates/bitwardenrs.xml

**Comment by Roxedus** [comment]
IF there is any issues or questions about the template fbartels linked, me know

**Comment by cheesemarathon** [comment]
> @cheesemarathon are you talking about this template? https://github.com/selfhosters/unRAID-CA-templates/blob/master/templates/bitwardenrs.xml

That would be the one.

**Comment by cheesemarathon** [comment]
> IF there is any issues or questions about the template fbartels linked, me know

So you would like people to raise issues on github if they need support with bitwarden_rs on unraid?

**Comment by Roxedus** [comment]
> support with bitwarden_rs on unraid

When its most likely gonna be a container issue, yes.

I'm still working out that support-thread deal, since we don't maintain the images we create templates for.

**Comment by cheesemarathon** [comment]
> > support with bitwarden_rs on unraid
> 
> When its most likely gonna be a container issue, yes.
> 
> I'm still working out that support-thread deal, since we don't maintain the images we create templates for.

I appreciate that as I have created templates for images I don't maintain. Personally the way I have worked it is to create a support thread on the unraid forums and link to that in the template. I then provide first line of defense for support as it's not often an image issue, but if it is I'll ask the user to submit an issue at the relevant repo. This way you don't get issues raised where someone can't work out how to add a port in the unraid UI, which is not really a helpful issue it have here IMO

**Comment by Roxedus** [comment]
> Personally the way I have worked it is to create a support thread on the unraid forums and link to that in the template.

Could do that, but we (the selfhosters team) don't use all the containers we create templates. I have thought about opening issues in our repo for each template, and link it

**Comment by Roxedus** [comment]
@cheesemarathon https://forums.unraid.net/topic/88086-support-bitwardenrs-bitwarden_rs/

**Comment by dani-garcia** [comment]
Closed due to inactivity.
