### ISSUE TITLE
Update wiki Private CA/Self Signed certs

### ISSUE THREAD

**Issue by stshontikidis** [dani-garcia/bitwarden_rs#814]
### Subject of the issue
Wiki entry on working with private CA issuers and self signed certs has some example commands that are no longer valid for iOS 13 and macOS 10.15.  https://support.apple.com/en-us/HT210176
Wiki should reflect that valid server certificate can not have expiry > 825 and ExtendedKeyUsage = Server Authentication

I did a little writeup here
https://www.reddit.com/r/Bitwarden/comments/ep9qyz/self_signed_certs_iosmacos_issue_solved/ 

### Your environment

* Bitwarden_rs version: 2.12.1

* Install method: Docker Image 
* Clients used: iOS app, macOS app, chrome
* Reverse proxy and version: nginx/1.10.3
* Other relevant information: iOS 13.3 

### Steps to reproduce
Followed steps in wiki https://github.com/dani-garcia/bitwarden_rs/wiki/Private-CA-and-self-signed-certs-that-work-with-Chrome and then add certs to iOS >= 13.0. 

### Expected behaviour
SSL handshake should be successful

### Actual behaviour
iOS app has generic server connection error

### Relevant logs
nginx 
2020/01/15 16:12:31 [info] 13834#13834: *44031 peer closed connection in SSL handshake while SSL handshaking, client: 192.168.1.42, server: 0.0.0.0:443
2020/01/15 16:13:25 [info] 13834#13834: *44032 peer closed connection in SSL handshake while SSL handshaking, client: 192.168.1.42, server: 0.0.0.0:443

**Comment by stshontikidis** [comment]
I am willing to update the wiki but I am not involved in the project and did not just want to edit unannounced.

**Comment by dani-garcia** [comment]
Yeah of course, I'd appreciate if you could update the wiki to include the info you mention, thanks!

**Comment by stshontikidis** [comment]
Made the small update to ext file and server cert command, along with note to source of apple requirements.  Take a look and I think we can close this thread.

**Comment by dani-garcia** [comment]
Looks good to me, thanks!
