### ISSUE TITLE
postgresql env template

### ISSUE THREAD

**Issue by etibamecus** [dani-garcia/bitwarden_rs#815]
Hello, 

I just compiled bitwarden_rs using postgresql.

now i'm setting my bitwarden_rs.env file and I don't really if i'm supposed to point to a database and if yes, what should i set in front of DATABASE_URL=

thanks a lot for all your work !

**Comment by xoxys** [comment]
Connection string should be something like `DATABASE_URL=postgresql://localhost/test?user=fred&password=secret`.

But I am working on my own bitwarden_rs + postgres setup currently and can say more in a couple of minutes.

**Comment by etibamecus** [comment]
nice !

so if using UNIX socket can it be `DATABASE_URL=postgresql://unix:/var/run/postgresql/.s.PGSQL.5432/test?user=fred&password=secret` ?

would you consider it stable yet to use postgresql ?

thanks again !

**Comment by dani-garcia** [comment]
Closed due to inactivity.
