### ISSUE TITLE
Add basic CLI commands

### ISSUE THREAD

**Issue by xoxys** [dani-garcia/bitwarden_rs#816]
It could be handy to have some basic CLI options for the `bitwarden_rs` binary in place. Minimum set could be something like `bitwarden_rs --help` and `bitwarden_rs --version`.

These CLI options can also be used to verify if the compiled binary is executable.

**Comment by zethra** [comment]
I'd like to take this

**Comment by dani-garcia** [comment]
Sure thing, have at it! If you need help I'm usually either here or the Matrix chat.

**Comment by zethra** [comment]
@dani-garcia Do you have a preference as for as cli argument parsing is concerned?

**Comment by dani-garcia** [comment]
Do you mean choice of library? If nothing has changed, clap is the most popular so I'd go that way.

https://github.com/clap-rs/clap

**Comment by zethra** [comment]
In that case I'd like to use structopt, which is built on top of clap but provides a nicer api imo

**Comment by dani-garcia** [comment]
Ah, I thought the structopt api was merged into clap too, but apparently that's scheduled to be released on the next version of clap 3.0!

I agree the declarative api of structopt is nicer, I'd prefer to use that too.

**Comment by zethra** [comment]
I see that if the GIT_VERSION environment var is set at compile time the app with print that as it's version.  Should I use that for the version flag? If so what should it print if anything it that var is not set?  And if not what should I print?

**Comment by dani-garcia** [comment]
For the version flag I'd just print `bitwarden_rs` followed by a space and the GIT_VERSION value if present. Similar to how cargo --version or rustc --version do it.

If no version is provided, you could print something like.
```
bitwarden_rs (Version info from Git not present)
```

**Comment by zethra** [comment]
I opened a PR #888

**Comment by dani-garcia** [comment]
Closed because #888 got merged
