### ISSUE TITLE
iOS App Sync Failed

### ISSUE THREAD

**Issue by rotda** [dani-garcia/bitwarden_rs#817]
Hello , 

I have problem with the ios APP . Web Vault works fine.

"Sync Failed" 

in the log is :

[2020-01-17 14:21:21][bitwarden_rs::api::identity][WARN] Detected unexpected parameter during login: devicepushtoken
[2020-01-17 14:22:01][auth][ERROR] Unauthorized Error: Invalid device id

Can I somehow clean the device

**Comment by rotda** [comment]
also in docker logs looks ok
GET /api/sync application/json:
GET /api/sync
    => Matched: GET /api/sync?<data..> (sync)
    => Outcome: Success
GET /api/sync?<data..> (sync) => 200 OK
    => Response succeeded.

**Comment by Ogglord** [comment]
Same issue here - using latest docker image together with iOS app Bitwarden Password Manager v 2.2.5. I cannot login to an exising account. (2FA disabled for this attempt.)

**This is from the docker logs**
`
[..][request][INFO] POST /api/accounts/prelogin

[..][response][INFO] POST /api/accounts/prelogin (prelogin) => 200 OK

[..][request][INFO] POST /identity/connect/token

[..][bitwarden_rs::api::identity][WARN] Detected unexpected parameter during login: devicepushtoken

[..][error][ERROR] Username or password is incorrect. Try again. IP: xx.xx.xx.xx. Username: {removed}

[..][response][INFO] POST /identity/connect/token (login) => 400 Bad Request 
`

**Comment by interbiznw** [comment]
getting this same error on android

Detected unexpected parameter during login: devicepushtoken

account had 2fa Yubikey, also can no longer log into web vault....

**Comment by interbiznw** [comment]
on attempt to login in browser to webvault, get this error 

`[bitwarden_rs::error][ERROR] JsonError. {"TwoFactorProviders":[3],"TwoFactorProviders2":{"3":{"Nfc":true}},"error":"invalid_grant","error_description":"Two factor required."}`

**Comment by sic79** [comment]
> 
> 
> Same issue here - using latest docker image together with iOS app Bitwarden Password Manager v 2.2.5. I cannot login to an exising account. (2FA disabled for this attempt.)
> 
> **This is from the docker logs**
> 
> ```
> [..][request][INFO] POST /api/accounts/prelogin
> [..][response][INFO] POST /api/accounts/prelogin (prelogin) => 200 OK
> [..][request][INFO] POST /identity/connect/token
> [..][bitwarden_rs::api::identity][WARN] Detected unexpected parameter during login: devicepushtoken
> [..][error][ERROR] Username or password is incorrect. Try again. IP: xx.xx.xx.xx. Username: {removed}
> [..][response][INFO] POST /identity/connect/token (login) => 400 Bad Request 
> ```

I have exactly the same issue when trying to connect with iOS, my log is identical

**Comment by patrickli** [comment]
Android app also broken. Login is working fine but the app cannot sync with the server.

**Comment by Ubikfr** [comment]
Same here on Android app only

```
[2020-03-22 10:21:35][bitwarden_rs::api::identity][WARN] Detected unexpected parameter during login: devicepushtoken
[2020-03-22 10:26:01][error][ERROR] Invalid refresh token
```

Apps on Linux / MacOs / Windows and web vault are fine.

**Comment by rmatiash** [comment]
I had the same issue, both android and ios (ipad) apps. However after a docker pull everything is working again. Not sure if pulling again...

BR

**Comment by jjlin** [comment]
I don't think the `devicepushtoken` warning is relevant here, and that should be fixed soon.

For the actual issues, it's hard to debug without actual access to your database, which most people will understandably not want to share. But it generally sounds like something is mismatched in the database, or in the client state. Some general advice:

* Try uninstalling/reinstalling the Bitwarden app on the mobile device.
* It's generally safer to store your bitwarden_rs database on a local filesystem rather than something like NFS or SMB, which makes data corruption issues much more likely.

**Comment by dani-garcia** [comment]
Some sync issues with the mobile apps have been solved recently so this is probably not applicable anymore.

Other than that, try to delete the clients data and log in again, and make sure the credentials work on another device.
