### ISSUE TITLE
Parse bool values correctly

### ISSUE THREAD

**Issue by xoxys** [dani-garcia/bitwarden_rs#819]
Currently, uppercase bool values seems not to work e.g. `SIGNUPS_ALLOWED=False` which is really confusing and can lead to missconfigured public servers.

Normally, most common bool-ish string values like `1,0/yes,no/y,n/true,false/True,False` should be converted to a real bool while reading env variables.

**Comment by dani-garcia** [comment]
Should be fixed in https://github.com/dani-garcia/bitwarden_rs/commit/d212dfe735e59128667a4c579e52ce7e86b53a94 now.

**Comment by xoxys** [comment]
Cool, looks nice. Thanks for the fast fix.
