### ISSUE TITLE
It gets unresponsive sometime after starting the container

### ISSUE THREAD

**Issue by gerroon** [dani-garcia/bitwarden_rs#822]
### Subject of the issue
Hi

I started getting a strange issue. The BW_RS container becomes unresponsive sometime after starting, when I sya unresponsive I mean unresponsive to browsing via clients like Firefox. I can neither access the local ip nor the reverse proxied url. The Docker logs shows nothing, it looks  as if it is running normally.

Here last couple lines from `docker logs -f bitwarden` 
```
[2020-01-19 03:49:10][request][INFO] POST /notifications/hub/negotiate
[2020-01-19 03:49:10][response][INFO] POST /notifications/hub/negotiate (negotiate) => 200 OK
```

### Your environment

Debian Testing, Docker

`docker run -d --name bitwarden -v /media/bitwarden:/data/ -p 4080:80 -p 3012:3012 --restart=always bitwardenrs/server:latest`

* Bitwarden_rs version:  1.13.1

* Install method:  Docker 
* Clients used: Firefox, Android
* Reverse proxy and version: Apache

* Other relevant information: 

### Steps to reproduce
Start the Docker container  wand wait about half an hour, the web page is unaccessible.

### Expected behaviour
I should be able to access the site nomatter how long the container was up and running.

### Actual behaviour
The site is not reachable. The site is initally reachable for a while, but after sometime it is not reachable via all the IPs the server has or the reverse proxy (via Apache2)

### Relevant logs

`curl -v http://localhost:80/alive`

```
 Expire in 1 ms for 1 (transfer 0x55d21c2f0dc0)    
* Expire in 0 ms for 1 (transfer 0x55d21c2f0dc0)    
* Expire in 0 ms for 1 (transfer 0x55d21c2f0dc0)
* Expire in 1 ms for 1 (transfer 0x55d21c2f0dc0)
* Expire in 0 ms for 1 (transfer 0x55d21c2f0dc0)
* Expire in 0 ms for 1 (transfer 0x55d21c2f0dc0)
* Expire in 1 ms for 1 (transfer 0x55d21c2f0dc0)
* Expire in 0 ms for 1 (transfer 0x55d21c2f0dc0)
* Expire in 0 ms for 1 (transfer 0x55d21c2f0dc0)
* Expire in 1 ms for 1 (transfer 0x55d21c2f0dc0)
* Expire in 0 ms for 1 (transfer 0x55d21c2f0dc0)
* Expire in 0 ms for 1 (transfer 0x55d21c2f0dc0)
* Expire in 0 ms for 1 (transfer 0x55d21c2f0dc0)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 150000 ms for 3 (transfer 0x55d21c2f0dc0)
* Expire in 200 ms for 4 (transfer 0x55d21c2f0dc0)
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /alive HTTP/1.1
> Host: localhost
> User-Agent: curl/7.64.0
> Accept: */*
> 


```

`root@9af1c2f0025e:/# bash healthcheck.sh`
No results shown

**Comment by gerroon** [comment]
One thing I also see 


docker exec -ti bitwarden curl -v http://localhost:80/alive

```
* Expire in 0 ms for 1 (transfer 0x5573c1386dc0)
* Expire in 0 ms for 1 (transfer 0x5573c1386dc0)
* Expire in 0 ms for 1 (transfer 0x5573c1386dc0)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 150000 ms for 3 (transfer 0x5573c1386dc0)
* Expire in 200 ms for 4 (transfer 0x5573c1386dc0)
*   Trying ::1...
* TCP_NODELAY set
* Expire in 150000 ms for 3 (transfer 0x5573c1386dc0)
* Immediate connect fail for ::1: Cannot assign requested address
*   Trying ::1...
* TCP_NODELAY set
* Expire in 150000 ms for 3 (transfer 0x5573c1386dc0)
* Immediate connect fail for ::1: Cannot assign requested address
*   Trying ::1...
* TCP_NODELAY set
* Expire in 150000 ms for 3 (transfer 0x5573c1386dc0)
* Immediate connect fail for ::1: Cannot assign requested address

```

**Comment by gerroon** [comment]
In cant figure this out :( I am really thinking that either FF addon or the Android app is crashing this. Because crashes/unrespnsiveness is almost like random. Sometimes it takes horus sometimes 10 min after restrating the container. 

Noone else has this issue?

**Comment by mprasil** [comment]
This is strange. Just looking at the stats it seems to consume more memory than I'm used to seeing. (might not be relevant) Do you have many users?

It seems that the service just runs out of workers for whatever reason, can you share some apache configuration, that might be relevant. Perhaps websocket configuration isn't correct and it ends up using all the workers with persistent connections? (try to turn off websockets maybe?)

Also just total stab in the dark, but you can increase the number of worker threads ([the default is 10](https://github.com/dani-garcia/bitwarden_rs/blob/8867626de898bb8416ed8319806b1c220d57dcb1/docker/amd64/sqlite/Dockerfile#L72)):

```bash
docker run -d --name bitwarden \
  -v /media/bitwarden:/data/ \
  -p 4080:80 \
  -p 3012:3012 \
  --restart=always \
  -e ROCKET_WORKERS=50 \
  bitwardenrs/server:latest
```

**Comment by gerroon** [comment]
Hi

I have total 3 users.

Here is the apache conf. The rest is just couple extra lines about the site and ssl

```
        RewriteEngine On
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule /notifications/hub(.*) ws://<SERVER>:3012/$1 [P,L]
        ProxyPass / http://127.0.0.1:4030/

        ProxyPreserveHost On
        ProxyRequests Off
        RequestHeader set X-Real-IP %{REMOTE_ADDR}s


```

I will try increasing the workers to see if I get any remedy. Thanks for the pointers.

**Comment by jjlin** [comment]
You have a lot of hung calls to the healthcheck script for some reason. What OS version and Docker version are you running? Also, maybe try disabling the healthcheck (`docker run --no-healthcheck ...`) and see if that helps.

**Comment by gerroon** [comment]
Hi

I have no idea why health checks runs like that since I do not get involved with the container myself.

I am on Debian Testing, Docker version 19.03.5

I will also try your recommendation

**Comment by cmroanirgo** [comment]
Just browsing this fault and I notice either a) the issue or (more likely) b) a typo in this issue.

You state you start with: `docker run ... -p 4080:80`  (note port 4080)
Your apache conf is incorrect in using: `ProxyPass / http://127.0.0.1:4030/` (note port 4030)

Perhaps my comment is a red herring, or this is not the actual problem...? You *do* state that it works for a while...

**Comment by gerroon** [comment]
Hi

I tried to anonymize some info, might have mistyped. That is not the real issue, since I can always access it when it works.

Increasing number of workes seemed to help. I will test a bit more.

**Comment by jjlin** [comment]
Potentially related: #950

**Comment by BlackDex** [comment]
Closing this ticket because of inactivity.
Feel free to re-open if the issue isn't resolved using the `testing`/`master` version and updated docker software.
