### ISSUE TITLE
Allow configuration of invitation org name when inviting users

### ISSUE THREAD

**Issue by aroberts** [dani-garcia/bitwarden_rs#825]
### Subject of the issue

Inviting users via email results in a reference to a "bitwarden_rs" organization. This is turning out to be confusing to my users - it would be great if I could configure that string to be something else.

It looks like the string is hardcoded at `src/api/admin.rs:164`:
```rust
        let org_name = "bitwarden_rs";
        mail::send_invite(&user.email, &user.uuid, None, None, &org_name, None)
```

I think just being able to set this string via environment variables would solve my problem.

### Your environment

* Bitwarden_rs version: 1.13.1

* Install method: docker

**Comment by dani-garcia** [comment]
Sounds reasonable to me. Should we use the already existing SMTP_FROM_NAME as it serves a similar purpose? Or create a separate option?

**Comment by aroberts** [comment]
I'd vote for a separate var, but it would be great to default the new var's value to SMTP_FROM_NAME if left blank/unset

**Comment by dani-garcia** [comment]
Fixed, decided on creating a separate independent option to avoid making the configuration logic more complex than needed.
