### ISSUE TITLE
Every recompile takes 50 seconds. Even cargo's incremental build look like work.

### ISSUE THREAD

**Issue by insub** [dani-garcia/bitwarden_rs#827]
### Subject of the issue
Every recompile takes 50 seconds (cargo build --features sqlite) , so every time I change the code, even if it's only one file, I have to wait 50s to preview it, Is it normal to consume this time?
BTW, the cargo's incremental build look like work. 
Is there a better(fast) development way? (i'm a javascript coder, i don't have compiled language work experience)

### Your environment
MacOS, 10.15.3
* Bitwarden_rs version: 
v1.13.1

### Steps to reproduce
cargo build --features sqlite
......
Finished dev [unoptimized + debuginfo] target(s) in 53.89s

**Comment by dani-garcia** [comment]
Yes, building rust code is slow. If you only want to check if the code compiles and not actually run it, you can use `cargo check --features sqlite`, which should be considerably faster.

**Comment by insub** [comment]
Does this mean that if I modify a view, I have to wait 50 seconds before actually previewing it on the browser?

**Comment by dani-garcia** [comment]
If you modify the API, yes you'd have to wait and there's no faster way.

If you change the HTML templates, you can enable the following options:
```
TEMPLATES_FOLDER=src/static/templates
RELOAD_TEMPLATES=true
```

and with that any changes to the templates are applied immediately (for emails they apply to the next ones sent, for the admin page, after a page reload).

**Comment by insub** [comment]
@dani-garcia ok, thk!
