### ISSUE TITLE
Verification mail sending error IDN Domain

### ISSUE THREAD

**Issue by Latschenharry** [dani-garcia/bitwarden_rs#829]
Bitwardenrs is unable to send an verification mail to an IDN Domain.

### Your environment

* Bitwarden_rs version: 1.13.1-632d5526
* Install method: Docker Image
* Clients used: Webclient
* Other relevant information: Bitwardenrs is able to send a mail to an ACE converted Domain

### Steps to reproduce
Create an account with an IDN domain mail

### Expected behaviour
bitwardenrs is able to send the verification mail

### Actual behaviour
bitwardenrs is unable to send the verification mail

[bitwarden_rs::api::core::accounts][ERROR] Error sending delete account email: Error building email. invalid email address

**Comment by dani-garcia** [comment]
I'm not sure about your terminology, when you say IDN domain do you mean using non-ascii characters? And by ACE converted do mean punycode? (Starting with "xn--").

If so, I haven't tested it but we could consider converting the email internally, to make sure the library accepts it.

**Comment by Latschenharry** [comment]
Yes its exactly as described by you.

IDN=Internationalized Domain Name so for example:  überall-ist.de
ACE/punycode: xn--berall-ist-8db.de

An internal conversion would be very nice.

**Comment by dani-garcia** [comment]
Okay, I've changed it to convert the domain to ascii now in https://github.com/dani-garcia/bitwarden_rs/commit/def174a517716967b80d5ecb8407772668bfd631, can you give it a try? if you are using the docker images, those might take some hours to build still.

**Comment by Latschenharry** [comment]
Thank you very much for the fast help.
It works like it should.
