### ISSUE TITLE
Sharing credentials with attachments

### ISSUE THREAD

**Issue by shauder** [dani-garcia/bitwarden_rs#83]
I think I found a bug. I am unable to share attachments with an organization I create if it contains attachments. If I remove the attachments then I am able to share the credential. I can then go (from my personal vault) back to the credentials attachments and add them back. 

The second part of this is that I cannot add attachments to a credential from within an Organizations vault. I can add them to credentials from the personal vault but if I go to the org vault and try to add to either one shared with the org from my personal or one created within the org itself I cannot add attachments (all from the web vault).

This is the docker errors I see when trying to share credentials with attachments

`POST /api/ciphers/5c1ebdc8-cb84-4bbe-b028-a58e329f9df3/attachment/7bdf1a9f2b3e2a9ac7d3/share?organizationId=483d995a-f3bc-48bc-ac9a-6d2a86fbc137 multipart/form-data; boundary=---------------------------30775785013455629741874101108:
=> Error: No matching routes for POST /api/ciphers/5c1ebdc8-cb84-4bbe-b028-a58e329f9df3/attachment/7bdf1a9f2b3e2a9ac7d3/share?organizationId=483d995a-f3bc-48bc-ac9a-6d2a86fbc137 multipart/form-data; boundary=---------------------------30775785013455629741874101108.
=> Warning: Responding with 404 Not Found catcher.
=> Warning: Data left unread. Force closing network stream.
=> Error: Failed to write response: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }.`

This is the docker errors I see when trying to add attachments to a credential from the org vault
`POST /api/ciphers/91bab0fa-4a15-4687-8e96-b325f3af28d5/attachment-admin multipart/form-data; boundary=---------------------------1175028002436011802836152650:
    => Error: No matching routes for POST /api/ciphers/91bab0fa-4a15-4687-8e96-b325f3af28d5/attachment-admin multipart/form-data; boundary=---------------------------1175028002436011802836152650.
    => Warning: Responding with 404 Not Found catcher.
    => Warning: Data left unread. Force closing network stream.
    => Error: Failed to write response: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }.`

**Comment by mannp** [comment]
I get the same errors in the log when trying to share credentials with an attachment.

**Comment by mprasil** [comment]
Yeah there are some missing APIs.

@shauder has some WIP patch to fix this, so hopefully this will be resolved soon.

**Comment by mprasil** [comment]
I believe this was resolved in #107. The docker hub image is just being built, should be available in about two hours from now.
