### ISSUE TITLE
Disabling Signups not working for me

### ISSUE THREAD

**Issue by Zuwizara** [dani-garcia/bitwarden_rs#830]
### Subject of the issue
Signups are still possible after disabling it via Environment and/or admin interface. I tried both Environment-var and the admin interface, always restarted the container after disabling, however im still able to create sign up new user on the Login Page. Could someone verify if this is a problem in my deployment or a bug?

### Your environment
* Bitwarden_rs version: 1.13.1-632d5526
* Install method: Docker (using Compose in Portainer)
* Clients used: WebVault
* Reverse proxy and version: Traefik 1.7
* Version of mysql/postgresql: i use the includede database
* Other relevant information: 

### Steps to reproduce
Disable Signup in Admin Interface or via Environment Var, restart the server and sign up with a new email.

### Expected behaviour
Signups not possible after disabling them

### Actual behaviour
Signups are still possible

### Relevant logs
Please tell me which logs i should provide since i do not see anything relevant in the logs i see from the container in portainer.

**Comment by bergernetch** [comment]
Same problem here, same bitwarden_rs version, disabling via env var does not work. It does show up as disabled in the admin interface.

**Comment by Latschenharry** [comment]
Have you tried creating an account. Because the register button will always be there. If signups are disabled, you will only get an error when hitting the sent button.

**Comment by Zuwizara** [comment]
> Have you tried creating an account. Because the register button will always be there. If signups are disabled, you will only get an error when hitting the sent button.

Yes, i always created test users and it was successful

**Comment by mprasil** [comment]
Submitted a PR to hopefully fix this.

**Comment by bergernetch** [comment]
> > Have you tried creating an account. Because the register button will always be there. If signups are disabled, you will only get an error when hitting the sent button.
> 
> Yes, i always created test users and it was successful

Same here. I would like it when the create button would also be disabled or even better removed.

**Comment by dani-garcia** [comment]
This should be fixed now, sorry about that!

**Comment by molnarriso** [comment]
Hello, I have the same issue. Whitelisting domains for signup works, but disabling signups not, the same as the original poster. My version is 1.20.0, running on Ubuntu with caddy reverse proxy. Tried both env variable and setting it via web admin interface. Admin interface shows "Allow new signups" as false. I can still create new accounts via the "Create Account" button - the account created is actually working.
Is there some log info I can provide ?

**Comment by BlackDex** [comment]
@molnarriso Posting in a closed issue is not very useful.
Besides that, if you have `SIGNUPS_ALLOWED=false` configured you can't create an account via the web-vault.
There is one exception, and that is if you have configured `SIGNUPS_DOMAINS_WHITELIST`, every domain in that list is allowed to create an account no matter what `SIGNUPS_ALLOWED` is set to.

If you have checked those settings and still have an issue, i suggest to open a new topic at the Discussions and provide a support string which you can generate via the `/admin/diagnostics` page.
