### ISSUE TITLE
bitwardenrs/server:raspberry ignoring -e SIGNUPS_ALLOWED='false'

### ISSUE THREAD

**Issue by bigtarget** [dani-garcia/bitwarden_rs#832]
Hello, Not able to disable singups in RPi4 with rasbian buster and docker installed from official buster repositories. Is it possible to inject it somehow in a different way?

Thank you.

**Comment by dani-garcia** [comment]
There was a recent bug with it (https://github.com/dani-garcia/bitwarden_rs/issues/830), once the new images get built (should take a couple of hours more), the feature should work again.

**Comment by shayne** [comment]
Is `latest` (amd64) going to be updated as well? Looks like the ARM variants are up to date.

**Comment by bigtarget** [comment]
Working for raspberry now.
