### ISSUE TITLE
Enable client-side icon cache (HTTP Header)

### ISSUE THREAD

**Issue by Ornias1993** [dani-garcia/bitwarden_rs#835]
### Subject of the issue
Currently Icons are not cached client side, it would be nice if this gets made possible.

### Expected behaviour
Icons are not a big risk being cached client side, expected would be that icons are client-cached by default or at least client-side icon caching is enabled using the web headers.

### Actual behaviour
No icons are cached because the following header is set on the icons:
`cache-control: no-cache, no-store, max-age=0`

**Comment by dani-garcia** [comment]
Oh this makes perfect sense! Implemented in https://github.com/dani-garcia/bitwarden_rs/commit/ebb36235a70a2c539a7656454de3478ae776aa22 thanks!

**Comment by Ornias1993** [comment]
Thats... fast!
Thanks!
