### ISSUE TITLE
Cannot register on raspberry pi, "unexpected error"

### ISSUE THREAD

**Issue by rekesz4** [dani-garcia/bitwarden_rs#837]
### Subject of the issue
First of all, thanks for the assist with the ADMIN_TOKEN problem. If I input a password for the token I had to set a few of the SMTP variable regardless of the DISABLE_ADMIN_TOKEN. My current issue is that I cannot register, I get the following error message:

>bitwarden      | thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: >Io(Custom { kind: Other, error: "failed to lookup address information: Name or service not known" >})', src/libcore/result.rs:1188:5
>bitwarden      | note: run with `RUST_BACKTRACE=1` environment variable to display a >backtrace.

I think I originally started using bitwarden_rs in September 2019 and I didn't have these issues.

### Your environment
* Bitwarden_rs version: 1.13.1-5352321f
* Install method: Dockstarter
* Reverse proxy and version: Letsencrypt, nginx 1.1.0-ls91

### Steps to reproduce
Run bitwarden_rs via docker-compose and try to register.

### Expected behaviour
Ability to register

### Actual behaviour
Get "unexpected error" on webpage

### Relevant logs
>bitwarden      | [2020-01-30 15:49:48][start][INFO] Rocket has launched from http://0.0.0.0:80
>bitwarden      | [2020-01-30 15:50:39][request][INFO] POST /api/accounts/register
>bitwarden      | thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: >Io(Custom { kind: Other, error: "failed to lookup address information: Name or service not known" >})', src/libcore/result.rs:1188:5
>bitwarden      | note: run with `RUST_BACKTRACE=1` environment variable to display a >backtrace.

**Comment by dani-garcia** [comment]
Sounds like it's trying to send an email  while registering and failing, make sure the SMTP config is correct in the admin panel with the test smtp button.
