### ISSUE TITLE
Change collection permissions recursively

### ISSUE THREAD

**Issue by mbdotnet** [dani-garcia/bitwarden_rs#838]
Hello,

I use Bitwarden version 2.12.1 and wondered if it is possible to inherit / recursively set user rights for collections? 

Example:
User xx gets access rights for the collection Network and automatically also for Network/Firewall and Network/WiFiAP

**Comment by dani-garcia** [comment]
Collection names are encrypted in the clients so we can't set those permissions without help from the clients. This would need to be added to the official clients: https://community.bitwarden.com/c/feature-requests.
