### ISSUE TITLE
Offline Cache for changes via Client Apps (iOS, Windows)

### ISSUE THREAD

**Issue by Zuendapp** [dani-garcia/bitwarden_rs#841]
**Subject of the issue:**

Actually there is no offline cache for changes via client apps such as iOS or Windows

**Expected behaviour:**
Is it possible to implement an offline cache for the iOS and Microsoft APP to sync a change back when the server is reachable again?

**Actual behaviour:**
Error Code "There is a problem connecting to the server"

Thank you very much!

BR

**Comment by dani-garcia** [comment]
This can't be done as it would require client support, theres a thread in the official bitwarden forums https://community.bitwarden.com/t/offline-management-of-writeable-vault-items/107.
