### ISSUE TITLE
How to specify connection string to Sqlite as an environment variable?

### ISSUE THREAD

**Issue by tynor88** [dani-garcia/bitwarden_rs#842]
### Subject of the issue
Is it possible to specify the SQLite connectionstring, to mitgate WAL issues when hosting with Azure Files? It is possible with e.g. grafana, as specified here:
https://github.com/grafana/grafana/issues/20549#issuecomment-580743349

**Comment by dani-garcia** [comment]
If you mean adding the `?cache=private&mode=rwc` bits, you could try adding it to the DATABASE_URL parameter, you shouldn't need the journal_mode=WAL because that's already set by code.

**Comment by TynThordin** [comment]
@dani-garcia Thanks for the reply. However it does not work. It tries to create a file named db.sqlite3?cache=private&mode=rwc which obviously doesnt pass the settings to sqlite.
Any idea why it would do that?

**Comment by TynThordin** [comment]
@dani-garcia Sorry to disturb you. Do you have any idea how to circumvent this?

**Comment by BlackDex** [comment]
@TynThordin you can't.
If you want to change the settings of the sqlite database you need to do that afterwards using the sqlite3 tool it self.
Please see: https://www.sqlite.org/pragma.html

**Comment by voslucas** [comment]
@yggdrasil-tynor @tynor88  did you find a solution for sqlite3 hosting on Azure Files?

**Comment by yggdrasil-tynor** [comment]
> @yggdrasil-tynor @tynor88 did you find a solution for sqlite3 hosting on Azure Files?

Download the sqlitedb file and change the PRAGME. See what @BlackDex linked to.

We are running it stable for a year now with azure files.
