### ISSUE TITLE
Missing ARM/Raspberry images for bitwardenrs/server-mysql

### ISSUE THREAD

**Issue by maxirus** [dani-garcia/bitwarden_rs#844]
### Subject of the issue

[Docker Hub](https://hub.docker.com/r/bitwardenrs/server-mysql/tags) missing Tags for ARM & Raspberry Pi images for the MySQL version of bitwardenrs/server.

The standard version (SQLite) has these builds/tags ([See here](https://hub.docker.com/r/bitwardenrs/server/tags))

### Your environment

* Bitwarden_rs version: 1.13.1

* Install method: Helm
* Reverse proxy and version: nginx ingress
* Version of mysql/postgresql: 5.7.28
* Other relevant information: 

### Steps to reproduce

Navigate to the Docker Hub repo for bitwardenrs/server-mysql: https://hub.docker.com/r/bitwardenrs/server-mysql/tags

### Expected behaviour

Expected there to be tags for `armv6` and `raspberry` (ie. `1.13.1-raspberry`) much like the [bitwardenrs/server](https://hub.docker.com/r/bitwardenrs/server/tags) repo.

### Actual behaviour

Only `amd64` compatible images exist in the [bitwardenrs/server-mysql](https://hub.docker.com/r/bitwardenrs/server-mysql/tags) repo.

**Comment by mprasil** [comment]
Please see #530. Closing this as duplicate.
