### ISSUE TITLE
Missing wiki page about recover from backup

### ISSUE THREAD

**Issue by Lilja** [dani-garcia/bitwarden_rs#848]
I'm missing a page in the wiki section detailing how to recover from a backup. What should I do with the exported `sqlite` file?

**Comment by mprasil** [comment]
From the [wiki page](https://github.com/dani-garcia/bitwarden_rs/wiki/Backing-up-your-vault):

> To restore simply overwrite db.sqlite3 with backup.sqlite3

(essentially the backup is a copy of the entire DB, so you just replace the DB with your backup file)

Should we update the wiki to make it more obvious? I feel like it's easy to overlook.

**Comment by dani-garcia** [comment]
Closed due to inactivity.
