### ISSUE TITLE
Allow empty ADMIN_TOKEN when DISABLE_ADMIN_TOKEN is set to false

### ISSUE THREAD

**Issue by Roxedus** [dani-garcia/bitwarden_rs#849]
### Allow presenting the variable for the user(which in reality set it to NULL), but disabling the admin panel when DISABLE_ADMIN_TOKEN is explicit set to false 

As you may be aware of trough #813, I control this template, and would like to present the user with the ability to use `ADMIN_TOKEN`, in order to this I have to set it to NULL.

The reason that I want to present it this way is because it is a easier way to set settings in favor of environment variables. This is only also the only way to get started without enabling signup afaik. 

### Expected behaviour
Using the environment variables `-e ADMIN_TOKEN=""` AND `-e DISABLE_ADMIN_TOKEN=false` should not enable the admin panel, but still allow the container to run, due to explicit telling bitwarden to disallow insecure token, while the admin_token variable exists.

### Actual behaviour
Using the environment variables `-e ADMIN_TOKEN=""` AND `-e DISABLE_ADMIN_TOKEN=false` gives me the error about either removing/filling the admin_token

**Comment by jjlin** [comment]
It looks like this was fixed in 480ba93.

**Comment by Roxedus** [comment]
No, its not. That commit stops the container from running.

**Comment by jjlin** [comment]
Yeah, my mistake. I'll send a fix for this later today.
