### ISSUE TITLE
Password hints not available

### ISSUE THREAD

**Issue by Gigi1237** [dani-garcia/bitwarden_rs#85]
The api endpoint for getting password hints appears to be unimplemented. When either through a client or through the webapp, a user requests a password hint an `Errors have occurred` message pops up.

The server log reports:
```
POST /api/accounts/password-hint application/json; charset=UTF-8:
    => Error: No matching routes for POST /api/accounts/password-hint application/json; charset=UTF-8.
    => Warning: Responding with 404 Not Found catcher.
    => Response succeeded.
```

**Comment by mprasil** [comment]
We do save the hint on account creation and we also have `find_by_mail` implemented for `User`, so this one should be fairly easy to implement.

**Comment by dani-garcia** [comment]
That could be possible, it depends on if the web-vault actually shows the error message sent, because in some cases it just shows a generic error message.

**Comment by stammw** [comment]
Hello,

I'd like to try to solve this one, I'm really excited to try contributing to a rocket-rs based project!

Should I implement it returning the hint into the error response, or could I try to implement a minimal SMTP support ? Following these [implementation](https://github.com/bitwarden/core/blob/b2e6b49b14a98cc2b315a1017cf3473eddba0f33/src/Core/Services/Implementations/HandlebarsMailService.cs#L108) and [configuration](https://github.com/bitwarden/core/blob/master/util/Setup/EnvironmentFileBuilder.cs#L57) ?

**Comment by mprasil** [comment]
Hey, why not both? 😄

Returning the hint in error message is unverified concept. We're not sure the client will display it, but if it's same as the other endpoints, it should. It should be fairly easy to test and implement though, so I'd advise to start with this.

The smtp implementation is going to be quite a lot of code. For example we need to add email verification first otherwise the api could be abused for spam. Also we need to make sure all of this will stay optional.

**Comment by Gigi1237** [comment]
If it is possible to have the client display a custom error message, how about having the server optionally display the hint there? I know it's quite insecure but it could still be useful for small/single user installations where you are mindful of the hint being public, so it's something that meaningful only to you. This would allow forgetful people, like me, to still get hints without the trouble of setting up SMTP.

**Comment by mprasil** [comment]
Yeah, that's the idea behind the first approach. Server can return error json data with the message as one of the fields. Normally the handler on the client side shows the message as an error notification.

**Comment by stammw** [comment]
On what form should the option be handled? There can be a boolean option like "show password hint", or the controller could return the hint only in the case of absence of a valid SMTP configuration?

**Comment by mprasil** [comment]
I think separate option (can default to true) would be better. Some people might still want to use this hint hack even with smtp available.

**Comment by stammw** [comment]
What about the Issue then ?

**Comment by mprasil** [comment]
There's a lot of functionality that would benefit from SMTP, but it's probably a bit more involved implementation to do that. If you feel like working on this @stammw and as long as it's optional, I'm sure the PR would be appreciated.

**Comment by stammw** [comment]
Great,

I was planning to dive into a SMTP integration with [letter](https://github.com/lettre/lettre) and [handlebars](https://github.com/sunng87/handlebars-rust). 

I'll be on working on that this week!

**Comment by mprasil** [comment]
Note that we've [fixed an issue](https://github.com/dani-garcia/bitwarden_rs/commit/b3f3fd81aca91b0d14b71b5a3feea1cf298436cc) some time ago to show password hints via error message even in Vault 2.0, so I'm removing the "requires SMTP" tag as the feature currently works. The PR #137 is for extending the functionality to also support sending the hint via email.

**Comment by mprasil** [comment]
Now that #137 is merged, we just need to add appropriate documentation.

**Comment by mprasil** [comment]
Now that it's merged, I think we can finally close this! Great work @stammw and everyone else.
