### ISSUE TITLE
Bitwarden HA setup problems

### ISSUE THREAD

**Issue by fr-ashvini** [dani-garcia/bitwarden_rs#853]
### Subject of the issue

Hi I have two bitwarden server connected to external database. Basically objective is to achieve high availability. So the issue was to replicate the databases, so cameup with an idea to share the efs volume among the database and put the databases in docker swarm network. 
### Your environment

* Bitwarden_rs version: 

* Install method: 
* Clients used: 
* Reverse proxy and version: 
* Version of mysql/postgresql: 
* Other relevant information:

**Comment by fr-ashvini** [comment]
command used is 
docker service create  -v /home/ec2-user/efs  -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=password123" -p 1433:1433 --name sql1 -d mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04

and then updatedb on bitwarden servers. 

but its not as required.

**Comment by mprasil** [comment]
I'm kinda confused what documentation you follow. You're using mssql, which is not supported by bitwarden_rs and the is no updatedb command either.

Are you using the official bitwarden server? If yes, you need to ask for help there.

If you actually want to use bitwarden_rs, read the [documentation here](https://github.com/dani-garcia/bitwarden_rs/wiki).

**Comment by mprasil** [comment]
Also please fill in the information about your environment in the issue template, that might clear some confusion.

**Comment by fr-ashvini** [comment]
Hi Thanks for reply. 
Iam using Offical Bitwarden server. Thank you for your time.
