### ISSUE TITLE
User based Tokens/Api Keys

### ISSUE THREAD

**Issue by Roemer** [dani-garcia/bitwarden_rs#854]
Hello

For automations and such, it would be great to be able to have user create permanent / timely limited api keys or tokens (or certificates) that could be used to access certain passwords of that user in an automated way without the Master Password.
I am thinking of for example database logins for a CI that needs to create a database in order to perform some tests. The CI could get the password from bitwarden_rs with such an api key/token or certificate.

Is this somehow possible or maybe a planned feature? Or is this impossible because of security concerns?

**Comment by jjlin** [comment]
The upstream Bitwarden (and therefore bitwarden_rs as well) does not currently support "sharing" in the typical sense where the user retains ownership. When a user shares an item, they are actually transferring ownership of that item to an organization. Using collections, there are various ways to restrict access to certain items within an organization.

If your use case can fit into this sharing model, the closest solution is probably to create a CI user that has read-only access to certain collections, and then use the [Bitwarden CLI](https://help.bitwarden.com/article/cli/) to access those items.

**Comment by Roemer** [comment]
Just figured out how to do the read-only collection acccess. Guess I would go with that. I'll close this as this is probably something that should be discussed in the upstream first.
