### ISSUE TITLE
Copy Password button is not working on Chrome

### ISSUE THREAD

**Issue by palmyambition** [dani-garcia/bitwarden_rs#858]
### Subject of the issue

The copy password button, which is in Edit Item page, does NOT actually copy the password to clipboard, eventhoudg these is a popup message says that password is copied. It is misleading. 
### Your environment 

* Bitwarden_rs version: Version 2.12.1

* Install method: 
* Clients used: 
* Reverse proxy and version: 
* Version of mysql/postgresql: 
* Other relevant information: Chrome version: 73.0.3683.103 (Official Build)

**Comment by jjlin** [comment]
Reproducible for me. Actually, none of the fields (username, password, or URL) copies to clipboard from the edit page. It works on vault.bitwarden.com, though.

**Comment by thamma** [comment]
I can confirm the issue. Upon pressing either button, the username/password is neither copied to the system nor the primary clipboard.

**Comment by MeiRos** [comment]
This issue have been discussed here. https://github.com/dani-garcia/bitwarden_rs/issues/786
When the other issue was fixed that issue thread was closed. So, it's better to continue here.

**Comment by ghost64** [comment]
I have this issue but only within a login object.  If I use copy password from a login on the main vault screen using the gear icon.

**Comment by dani-garcia** [comment]
This should be fixed with the new web vault version in the latest commit https://github.com/dani-garcia/bitwarden_rs/commit/916e96b1434474fc16f8badac9f7ffdde573dd6b

**Comment by dani-garcia** [comment]
This is fixed so closing it.
