### ISSUE TITLE
Add support for yubikey?

### ISSUE THREAD

**Issue by dubwoc** [dani-garcia/bitwarden_rs#86]
Based on the error message I get below and the lack of reference to yubikey in the source I believe there isn't any support yet for yubikeys. Assuming that is correct this is a feature request for yubikey two factor support. If I am mistaken please help me figure out what I am doing wrong. 

> POST /api/two-factor/get-yubikey application/json; charset=UTF-8:
>     => Error: No matching routes for POST /api/two-factor/get-yubikey application/json; charset=UTF-8.
>     => Warning: Responding with 404 Not Found catcher.
>     => Response succeeded.
>

**Comment by dani-garcia** [comment]
At the moment, we only support U2F. If your YubiKey supports U2F (I think at least all the new ones do) you can use that option instead.

I'll leave this open, to consider implementing YubiKey support in the future.

**Comment by dani-garcia** [comment]
To keep the issue tracker more focused, I'm closing this issue in favor of the meta issue at #246.
