### ISSUE TITLE
Feature request: Disable attachments

### ISSUE THREAD

**Issue by Dubz** [dani-garcia/bitwarden_rs#865]
Title says it all.

I want to be able to disable the attachments feature on my system. Attachments take up storage space. Storage costs me money. I do not want to be paying excessive costs to host user attachments.

Logins aren't as much space so I'm alright with that, but when you can multiply someone's storage usage with a few attachments, that's not really something I'd like to have to pay for. They may add a few, or many, files, which would grow the used space exponentially.

**Comment by mprasil** [comment]
That sounds like good idea. I've created a PR to enable that.

**Comment by dani-garcia** [comment]
I've implemented the size limit functionality, with two limits, one for users and another for organizations, so depending where the cipher is located it can be one or the other, and setting it to zero disables uploading at all. The options are `USER_ATTACHMENT_LIMIT` and `ORG_ATTACHMENT_LIMIT` and they use KB.

https://github.com/dani-garcia/bitwarden_rs/commit/325039c31695ac981da3b88dbbe6c6f40c6a180d
