### ISSUE TITLE
Can't save data if server is down

### ISSUE THREAD

**Issue by uchagani** [dani-garcia/bitwarden_rs#869]
### Subject of the issue
This may not be an issue for bitwarden_rs but for the official browser extension but I figured I'd post it here first.

If the server is down, the browser extension can't add/save any new entries.  While this makes sense overall I believe it should at least save to the local DB and then sync whenever the next sync happens (and when the server is available).

### Your environment
* Bitwarden_rs version:  Server down, don't know.
* Install method: Docker
* Clients used: Browser extension

### Steps to reproduce
1.  Stop bitwarden_rs
2.  Create new credentials using a browser extension

### Expected behaviour
New credentials are stored in the local db

### Actual behaviour
New credentials fail to save

**Comment by mqus** [comment]
See https://community.bitwarden.com/t/offline-management-of-writeable-vault-items/107 for reference. 

> I don’t want to make simple what is really complex, but I think that to achieve offline modification is mandatory to add to bitwarden the ability to resolve conflicts between items. No?


> Yes, which can be very complex. This is why this feature doesn’t exist today.

**Comment by uchagani** [comment]
Ok good so I'm not the only one with this issue. Seems like an important
feature to have. Servers experience downtime. It's something applications
should take into consideration. Hopefully Bitwarden arrives at the same
conclusion.

Since this seems like core bitwarden functionality, should I go ahead and
close this? Or is this something bitwarden_rs can implement?

**Comment by mprasil** [comment]
> Or is this something bitwarden_rs can implement?

Because the issue is with server being down, I don't think there's anything we could do server side. This would all have to be client side implementation upstream.
