### ISSUE TITLE
Use postgresql database

### ISSUE THREAD

**Issue by rzig** [dani-garcia/bitwarden_rs#87]
Hi! Would it be possible to add support for PostgreSQL? I'd like to use a database independent of the docker container.

**Comment by mprasil** [comment]
It's definitely possible - diesel that's used ORM layer does support Postgres, howeven it's not an easy task to do that. Having DB backed swapable in place is not [goal of diesel](https://github.com/diesel-rs/diesel/issues/980#issuecomment-312849513) and hence you need some work around this.

Having said that I don't think we use SQL directly outside of the migrations code, so if someone is motivated enough to dive into the code to do that, patches would be welcome.

**Comment by mprasil** [comment]
Note that we're using [replace_into](https://docs.rs/diesel/1.2.2/diesel/fn.replace_into.html) a lot. It appears, that this might not be supported with Postgres.

**Comment by jgrip** [comment]
Upserts were added in 9.5, so this is supported on version 9.5 and up.
http://www.postgresqltutorial.com/postgresql-upsert/

Not looked at the bw_rs code to see how much work it would be yet.

**Comment by odarriba** [comment]
It would be very helpful tonbe able to deploy bw_rs in Kubernetes and ease the backup of the files! Also running multiple nodes without direct file sharing

**Comment by dani-garcia** [comment]
To keep the issue tracker more focused, I'm closing this issue in favor of the meta issue at #246.
