### ISSUE TITLE
Trouble downloading attachments

### ISSUE THREAD

**Issue by TobiasS1402** [dani-garcia/bitwarden_rs#871]
I have a bitwarden docker container with static volumes running for a while, i tried to upload attachments. That worked, i could also delete them. But opening them wouldnt work, it just kept loading. I am as of right now on the latest version of the docker image.

version: 1.13.1-63459c5f
bitwardenrs/server:latest
docker-compose
i tried it on mobile, web and desktop app.
I am running NGINX, but also a direct local connection didnt work.

I start bitwardenRS via docker. here is my environment:
```
  environment:
   ROCKET_TLS: '{certs="/ssl/live/domain/fullchain.pem",key="/ssl/live/domain/privkey.pem"}'
   PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
   ROCKET_ENV: 'staging'
   ROCKET_PORT: '80'
   ROCKET_WORKERS: '10'
   LOG_LEVEL: 'trace'
   EXTENDED_LOGGING: 'true'
   LOG_FILE: '/data/bitwarden.log'
   SIGNUPS_ALLOWED: 'false'

```
I should be able to open or download my attachment.

It just keeps loading, or the spinning wheel gives that indication

I am able to upload and delete the attachment, i dont see a log entry of me requesting it.
```
[2020-02-21 13:47:35][response][INFO] POST /notifications/hub/negotiate (negotiate) => 200 OK
[2020-02-21 13:47:51][request][INFO] DELETE /api/ciphers/b680b7c6-3ca8-4b36-b075-4849e4c5c739/attachment/0da42657ce7ece1713de
[2020-02-21 13:47:51][response][INFO] DELETE /api/ciphers/<uuid>/attachment/<attachment_id> (delete_attachment) => 200 OK
[2020-02-21 13:48:09][request][INFO] POST /api/ciphers/b680b7c6-3ca8-4b36-b075-4849e4c5c739/attachment
[2020-02-21 13:48:09][multipart::server][INFO] Multipart::with_boundary(_, "---------------------------263541272918957")
[2020-02-21 13:48:10][response][INFO] POST /api/ciphers/<uuid>/attachment multipart/form-data (post_attachment) => 200 OK

```

**Comment by ajgon** [comment]
Have the same problem, on top of that, my docker container dies after this. I have to restart it manually to make it work again. Here are my envs, hope that helps:

```
SMTP_PORT=465
SMTP_EXPLICIT_TLS=true
SMTP_FROM=mail-from@domain.tld
SMTP_PASSWORD=password
ADMIN_TOKEN=admin-token
SMTP_HOST=smtp.domain.tld
SMTP_USERNAME=mail-from@domain.tld
SMTP_SSL=true
DOMAIN=https://bitwarden.domain.tld
ROCKET_ENV=staging
ROCKET_PORT=80
ROCKET_WORKERS=10
```

Also I'm not sure, does it matter, but my container is in docker "internal" network, so it doesn't have access to the Internet.

**Comment by dani-garcia** [comment]
To download the attachments you need to set the DOMAIN env variable so the download links are generated correctly. Other than that, try downloading them in a browser with the dev tools open in the network page and check what request it's doing.

**Comment by TobiasS1402** [comment]
Thank you for your response.
Turned out my config in the admin panel was still pointing to my old, non-existant domain.
Changed it do: `bitwarden.currentdomain.com` and works like a charm now.

Cheers.
