### ISSUE TITLE
Using latest docker image and container fails to start with thread 'main' panicked at 'valid URL: RelativeUrlWithoutBase'

### ISSUE THREAD

**Issue by zoredache** [dani-garcia/bitwarden_rs#873]
### Subject of the issue

The latest update fails to start

    thread 'main' panicked at 'valid URL: RelativeUrlWithoutBase', src/config.rs:468:15

If I revert back to the previous image it starts fine.

bitwardenrs/server@sha256:9b5468a28d4cc1c9e575bbd45abdb317cf6ddc8ec3aaf9151ed344918f781e06

### Your environment

- Running as a docker service
- Debian Linux 10.3 on an x86_64 Intel System
- docker --version - `Docker version 19.03.6, build 369ce74a3c`
- image:
  - built on 2020-02-22 at 6:15 pm
  - Hash: bitwardenrs/server:latest@sha256:5255114e755d0a13a35e49855fd7f6c3747dc095ff9956ec077cec69172666e7

### Steps to reproduce

I just pulled down the latest update, and tried to start.  bitwardenrs was running great with previous build.

Full details of docker service here with domain and admin token obfuscated

- https://gist.github.com/zoredache/a6a48dbf86683993871a8df0910e645c#file-docker-service-inspect-bitwardenrs

### Expected behaviour
Expect the container to run.

### Actual behaviour

Container fails to start with this error.

    thread 'main' panicked at 'valid URL: RelativeUrlWithoutBase', src/config.rs:468:15

### Relevant logs
The output of `docker container logs` with `RUST_BACKTRACE=full` and `docker service inspect` are on this gist.

- https://gist.github.com/zoredache/a6a48dbf86683993871a8df0910e645c#file-docker-container-logs

**Comment by mprasil** [comment]
Can confirm, this only seems to happen when `DOMAIN` is set.

**Comment by dani-garcia** [comment]
I think this is related to the changes to use a subpath, but for now make sure the DOMAIN starts with http:// or https://

**Comment by dani-garcia** [comment]
Okay so I've just tested it and the cause is not including the protocol in the DOMAIN variable as I mentioned, which before we allowed but it was technically incorrect, and it would probably break certain features that rely on having the complete origin, like U2F.

In https://github.com/dani-garcia/bitwarden_rs/commit/cd8907542a5d128d36309a4c9218ea3f4bd07df3 I've made the error more clear, so I think this can be closed.

**Comment by salvationtower** [comment]
I am getting same error however I don't have the DOMAIN variable set.  does it need to be specified with the relative protocol? e.g. https://bitwarden.domain-name.com ??

**Comment by zoredache** [comment]
Thanks for the quick update @dani-garcia.  Adding the protocol seemed to fix things for me, and your update with better error messages was also useful.

I am not sure why I had a domain without a protocol. I suspect I had copy-pasted from some example, but I haven't been able to find it in the docs wiki.
