### ISSUE TITLE
IOS can't download attachments

### ISSUE THREAD

**Issue by snakefox666** [dani-garcia/bitwarden_rs#881]
Hello guys, my bitwarden_rs + nginx on docker is working perfectly fine, a big thanks for everything !!! The only issue I had is with the IOS apps and the attachements.
Working 
- upload and download from a web broser
- upload from IOS apps

not working
- donwloading attachements from ios apps

as I'm behind a nginx reverse proxy I already tried to play with the env DOMAIN without any sucess. When I hit the download button on IOS I had a message "can't download the attachments" and nothing in the logs of my NGIX, like if bitwarden can't build correctly the link ...

Any ideas g? ;-)

**Comment by shauder** [comment]
Seems like you likely still have a setting wrong or the domain setting not correct.  I am able to download from the iOS app no problem.

I am also behind a reverse proxy (nginx) running on docker with Let's Encrypt certificates.

**Comment by snakefox666** [comment]
Hey shauder, I think that I followed your nginx example in the wiki :-)
Do you know how I can check what's wrong ? Should I insist with the DOMAIN env ?

**Comment by shauder** [comment]
What kind of certificate are you using?

**Comment by BlackDex** [comment]
Also, do you see anything during the download failed in the log file of either nginx or bitwarden?

**Comment by snakefox666** [comment]
Hello guys, it's now working fine ! I played a little bit with  the env variable "DOMAIN" and now it's working perfectly fine. I think that I made a typo mistake in the URL, the domain URL should be added without the / final ( http://testexample.com and not http://testexample.com/ ).
Thanks all for your help on that one and have a nice day ;-)
