### ISSUE TITLE
Exposing multiple ports for SSL & non-SSL

### ISSUE THREAD

**Issue by j-mikhail** [dani-garcia/bitwarden_rs#889]
Hello, I have been able to enable HTTPS without issue, though I notice bitwarden_rs will no longer accept HTTP connections on the same port afterwards, which makes sense.

Is there way to expose a second port so that you can accept HTTP and HTTPS connections on the same server? Thanks!

**Comment by dani-garcia** [comment]
The Rocket web server we use doesn't allow exposing more than one port, if you need to have multiple ports listening, I'd recommend to use a reverse proxy, there are some basic examples on the wiki, but none specifically about listening on more than one port: https://github.com/dani-garcia/bitwarden_rs/wiki/Proxy-examples

Other than that, if you can use HTTPS, I'd heavily recommend to only use it, especially in such a security sensitive service as a password manager.
