### ISSUE TITLE
Invitation and other mails redirect to localhost 

### ISSUE THREAD

**Issue by christophedumont5** [dani-garcia/bitwarden_rs#890]
When we receive this email : 

This email is to notify you that xxx@xxx has accepted your invitation   to join XXXX.
--
Please log in to the   bitwarden_rs server and confirm them from the organization management page.
If you do not wish to confirm this user, you can also remove   them from the organization on the same page.

and we click the url generated is https://localhost. 
I would like to generate an url like : https://www.example.com
How do i do this ?

**Comment by mprasil** [comment]
I think you only need to set the `DOMAIN` [correctly](https://github.com/dani-garcia/bitwarden_rs/blob/master/.env.template#L136).

**Comment by christophedumont5** [comment]
Thks, adding DOMAIN=https://www.example.com to bitwarden_rs.env solved the problem.
