### ISSUE TITLE
Unable to send Mails - Error LetreErr

### ISSUE THREAD

**Issue by TobiasDax** [dani-garcia/bitwarden_rs#894]
### Unable to send Mails from Admin Page
I just setup Bitwarden RS behind a reverse Proxy using this tutorial: https://www.youtube.com/watch?v=HLcj-p-lcXY
When i try to setup the SMTP Data to send Emails everything looks fine but i get a strange error Message if i try to invite somebody or send a test mail:
"Error sending SMTP test mail
LetreErr"

### UNRAID Server with Docker
* Bitwarden_rs version: Version 1.13.1-161cccca
* Install method: Docker
* Clients used: Web
* Reverse proxy and version: Letsencrypt Docker container with nginx

### Steps to reproduce
I followed the linked youtube tutorial to the letter

### Expected behaviour
Should send mails

### Actual behaviour
Gives strange error popup, no mails sent

### Relevant logs
```[2020-03-05 14:26:03][request][INFO] POST /admin/test/smtp/
[2020-03-05 14:26:03][error][ERROR] LetreErr.

[CAUSE] Io(
Custom {
kind: Other,
error: Failure(

Ssl(
Error {

code: ErrorCode(
1,
),
cause: Some(
Ssl(
ErrorStack(
[
Error {

code: 336130315,
library: "SSL routines",
function: "ssl3_get_record",
reason: "wrong version number",

file: "../ssl/record/ssl3_record.c",
line: 332,
},
],
),
),
),
},
X509VerifyResult {
code: 0,
error: "ok",

},
),
),
},
)
[2020-03-05 14:26:03][response][INFO] POST /admin/test/smtp (test_smtp) => 400 Bad Request```

**Comment by TobiasDax** [comment]
II have no idea why or how... but today everything is working fine...

**Comment by baahver** [comment]
@Tobias, Did you you not change a thing? 
I have the same issue, but am not able to solve this.

**Comment by TobiasDax** [comment]
Sadly i have no idea. I let it sit over night and on the next day everything was working...
