### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by mobizent** [dani-garcia/bitwarden_rs#896]
This is not a product feature request but more of a request to enable discussions in github. 

like https://github.com/zeit/next.js/discussions

we could use that instead of the forums which has never been used..

**Comment by dani-garcia** [comment]
As far as I know, there's no way to enable that just yet, it's only enabled for next.js as a beta test.

The forum has only been active for less than a week so there hasn't been much adoption yet, we can consider enabling github discussions when they are out of private beta.
