### ISSUE TITLE
Support for Bitwarden CLI

### ISSUE THREAD

**Issue by yodaphone** [dani-garcia/bitwarden_rs#897]
Does bitwarden_rs support bitwarden cli?

saw these projects & thought it might be useful to try

https://github.com/joaojacome/bitwarden-ssh-agent 
https://github.com/ewjoachim/bitwarden-keyring 

when i did try the ssh agent, i get this error.

`request to https://bitwarden.domain.com/api/accounts/prelogin failed, reason: connect ECONNREFUSED 192.168.10.74:443
`

my bw_rs is running on port 8088. no ssl & i access it using a Caddy reverse proxy

**Comment by fbartels** [comment]
Hi @yodaphone,

i have no problems here working with the official cli. I think you only need to correct the url in the settings.

**Comment by yodaphone** [comment]
> Hi @yodaphone,
> 
> i have no problems here working with the official cli. I think you only need to correct the url in the settings.

thanks. it works if i use the internal URL of 192.168.10.74:74:8088 but doesnt when i go thro the proxy

thanks
