### ISSUE TITLE
Issues with attachment download

### ISSUE THREAD

**Issue by marviins87** [dani-garcia/bitwarden_rs#899]
Hi Team,

I've an issue with downloading some of my attachments since i've migrated my bitwarden_rs from google to digitalocean. I don't exactly know what happened but somehow I've a few encrypted attachment which are 0KB in size. Probably because some of those attachments were not uploaded successful to the digitalocean machine (i don't know what else could have happened).

I noticed this because during the downloading those attchments nothing happened.

Below some files which are empty:
> root@docker:~/docker-bitwarden/bw-data/attachments# find -type f -empty 
> ./75c7b60d-4f29-4a57-b0cc-13f8ffb08bcd/4dd18f61309da25d0064  
> **./6d7c20ab-065c-4dbc-89f4-2558680b8d0f/3f8f6075277cc85f056d**  
> ./15fb9eaa-53b3-4cfc-9352-4316517d3be9/05da110f174588b4c96b
> ./42a640d5-0cf4-4089-a652-682463940347/eee7913219adc7a55a53
> ./42a640d5-0cf4-4089-a652-682463940347/61bd23d0d8cc3de9c8b2

Fortunately I have made backups before migration and I'm able restore those attachments.
E.g. :

> root@docker:~/docker-bitwarden/bw-data/attachments/6d7c20ab-065c-4dbc-89f4-2558680b8d0f# ls -l
> total 316
> -rw-r--r-- 1 root root 131745 Mar  5 19:22 0d89a74c06adec5ec2b3
> **-rw-r--r-- 1 root root 181025 Mar 10 10:23 3f8f6075277cc85f056d**
> -rw-r--r-- 1 root root   1601 Mar  5 19:22 c6d768040383dded99fa

After restoring those encrypted attachments i'm still not able to download the attachment.

I cannot find the reason for this.

> Container log:
> [2020-03-10 11:28:27][request][INFO] GET /attachments/6d7c20ab-065c-4dbc-89f4-2558680b8d0f/3f8f6075277cc85f056d
> [2020-03-10 11:28:27][response][INFO] GET /attachments/<uuid>/<file..> (attachments) => 200 OK

Browser Network debug:

> Request URL:https://vault.********/attachments/6d7c20ab-065c-4dbc-89f4-2558680b8d0f/3f8f6075277cc85f056d
> Request Method:GET
> Remote Address:*.*.*.*:443
> Status Code:
> 200
> Version:HTTP/2

and

> Status 200
> Method GET
> Domain: ***
> File: 3f8f6075277cc85f056d
> Cause: fetch
> Type: octet-stream 
> Transferred: 177.58KB
> Size: 176.78KB

I don't know if it's a coincidence but as far as I know those attachments are PDF files. I'm able to download TXT file attachments without issues.

Does someone know how to proceed? Thanks in advance!

**Comment by marviins87** [comment]
Hmm.. from another PC it's working without issues..

**Comment by dani-garcia** [comment]
Closed due to inactivity.
