### ISSUE TITLE
Firefox client: Auto-Fill disables automatic TOTP copy

### ISSUE THREAD

**Issue by morten-b** [dani-garcia/bitwarden_rs#914]
### Subject of the issue
In the Firefox client the automatic TOTP copy does not work when Auto-Fill i enabled

### Your environment

* Bitwarden_rs version: Version 2.12.1 (from login page)

* Install method: Docker
* Clients used: Firefox extention

### Steps to reproduce

Enable Auto-Fill, let Auto-Fill type username and password, on the following page paste TOTP code, without manually copying it. 

### Expected behaviour
TOTP should be pasted

### Actual behaviour
Nothing/previous clipholder content is pasted

**Comment by BlackDex** [comment]
@morten-b This is not something we can fix because this something linked to the browser extensions.
I noticed that this happens on both Firefox and Chrome based browsers.

A workaround could be by disabling the auto-fill and just Ctrl+Shift+L to auto-fill the login, which does copy the TOTP value.

**Comment by morten-b** [comment]
Thanks you for the comment, I was expecting that it was related to the extentions, but thought that it was best to start reporting here. I'll pass it on to the officiel developers.

**Comment by morten-b** [comment]
New issue opened https://github.com/bitwarden/browser/issues/1184
