### ISSUE TITLE
After installing on Synology I can not create an account

### ISSUE THREAD

**Issue by empenoso** [dani-garcia/bitwarden_rs#915]
### Subject of the issue
After installing on Synology I can not create an account

### Your environment

* Bitwarden_rs version: bitwardenrs/server:latest

* Install method: Docker image
* Clients used:  not using
* Reverse proxy and version:  not using
* Version of mysql/postgresql:  not using
* Other relevant information: 

### Steps to reproduce
![снимок](https://user-images.githubusercontent.com/43311539/76949015-ba655480-6929-11ea-9ae6-a95b7f4d5769.png)
![снимок_1](https://user-images.githubusercontent.com/43311539/76949346-39f32380-692a-11ea-80c5-4a2a829dd640.png)

### Expected behaviour

I can’t create a new account when I go to the web interface.

### Actual behaviour

When I click the create account button nothing happens.
### Relevant logs

[bitwardenrs-server.txt](https://github.com/dani-garcia/bitwarden_rs/files/4348303/bitwardenrs-server.txt)

**Comment by BlackDex** [comment]
Do you use HTTPS? If not, that is probably the issue, since Chrome based browsers, and the latest Firefox versions do not allow some JavaScript functionality to work without HTTPS connections.

**Comment by empenoso** [comment]
I use HTTP.

**Comment by BlackDex** [comment]
Then you can not get it to work.
You will need a SSL certificate for bitwarden to work.
Also, mobile clients will not work at all wen there is no HTTPS.

Please see: https://github.com/dani-garcia/bitwarden_rs/wiki/Private-CA-and-self-signed-certs-that-work-with-Chrome on how to generate self-signed certificates, and try to use that.

**Comment by empenoso** [comment]
Thanks for answer!

**Comment by empenoso** [comment]
If I use Microsoft Edge on Windows, I can use HTTP. For initial setup within LAN.

**Comment by dani-garcia** [comment]
This isn't an issue, most browsers expect a secure domain (HTTPS) to use the crypto apis and there's nothing for us to do.
