### ISSUE TITLE
No syncing on Android 9

### ISSUE THREAD

**Issue by almanzarj** [dani-garcia/bitwarden_rs#923]
I am having an issue on Android 9 using Samsung Galaxy S8+ with Bitwarden version 2.3.1 Android App.

I have tried uninstall app, install app, clear cache, log out and login.

When I try to do sync vault now...I get error Syncing failed message. I also tried to sync using LTE and WIFI

**Comment by TerrierX** [comment]
Same issue on my site, but with Android 10

**Comment by b-sarrazin** [comment]
Same issue with Android 9 since the last update of the mobile application.

**Comment by aktivalux** [comment]
```
-----------------------------------------------------------
 Add-on: Bitwarden RS
 Open source password management solution
-----------------------------------------------------------
 Add-on version: 0.6.0
 You are running the latest version of this add-on.
 System: HassOS 3.12  (amd64 / qemux86-64)
 Home Assistant Core: 0.106.5
 Home Assistant Supervisor: 209
```

Sync fails for Android and iOS as well (basically all mobile apps). Sync still works for the browser extension and desktop apps.


Logs when trying to trigger a sync manually in the app:

```
[2020-03-24 07:13:16][request][INFO] GET /api/sync
[2020-03-24 07:13:16][response][INFO] GET /api/sync?<data..> (sync) => 200 OK
[24/Mar/2020:07:13:16 +0000] 200 80.187.119.59(172.30.32.1) GET /api/sync HTTP/1.0 (Bitwarden_Mobile/2.3.1 (Android 9; SDK 28; Model CLT-L29))
```

**Comment by aktivalux** [comment]
I had this issue with an installation on Home Assistant. I exported my vault and reinstalled the addon (which uses bitwarden_rs). Now it works again. Probably something got corrupted somehow.

**Comment by deeztek** [comment]
Try this.

 Exported my vault to .json. Then I did a search for the following:

"username": null,
"password": null

Then in the web browser, I located the particular entry and deleted it.

Not sure which entry it was, but after deleting 27 entries, the android app started syncing again.

**Comment by pltanton** [comment]
Got the same issue. I found in export that I have multiple (like 7 or so) equal entities with same name and empty fields (each field was empty). It appears after some weird exceptions in desktop client.

Delete of these entities solves the problem. Guess it kinda bag with fresh desktop client.

**Comment by UGuess** [comment]
> Try this.
> 
> Exported my vault to .json. Then I did a search for the following:
> 
> "username": null,
> "password": null
> 
> Then in the web browser, I located the particular entry and deleted it.
> 
> Not sure which entry it was, but after deleting 27 entries, the android app started syncing again.

@deeztek Thank you!!!!!broooooooooo, you save my day!

**Comment by dani-garcia** [comment]
I think this is probably related to https://github.com/dani-garcia/bitwarden_rs/issues/921, but if not there's the workaround explained above, so closing the issue.
