### ISSUE TITLE
Test with the new Vault v2.0 Public Preview

### ISSUE THREAD

**Issue by mprasil** [dani-garcia/bitwarden_rs#93]
This [was just announced](https://github.com/bitwarden/web/issues/217), I think we should create some test version to test it out and catch any bugs before the official release comes out.

**Comment by mprasil** [comment]
If anyone want's to help building the web application, it would be very welcome. Anyone familiar with node and npm can probably modify the Dockerfile easily.

**Comment by dani-garcia** [comment]
I've updated the Dockerfile to test the new vault in a beta branch here:
https://github.com/dani-garcia/bitwarden_rs/tree/beta

It's basically untested for now, but it compiles correctly and sets the corrects URLS.

**Comment by mannp** [comment]
Thanks for making the changes :)

I used your dockerfile and get the following error trying to build it'

> Step 7/32 : COPY docker/set-vault-baseurl.patch /web-build/ COPY failed: stat /var/lib/docker/tmp/docker-builder028410783/docker/set-vault-baseurl.patch: no such file or directory

**Comment by dani-garcia** [comment]
Strange, it works on Windows for me. I added a missing slash that was removed in this beta branch in the last commit. Hopefully that fixes it.

**Comment by mannp** [comment]
Not sure if I missed something, so will take another look tomorrow;

> Step 7/32 : COPY /docker/set-vault-baseurl.patch /web-build/ COPY failed: stat /var/lib/docker/tmp/docker-builder179203441/docker/set-vault-baseurl.patch: no such file or directory

**Comment by mannp** [comment]
This one doesn't work at all;

> https://github.com/dani-garcia/bitwarden_rs/blob/beta/Dockerfile

Seems there are a number of changes required to make it compatible, so will try testing later.

**Comment by mprasil** [comment]
@mannp there must be something wrong with your setup. I've successfully built `mprasil/bitwarden:beta` straight out of repository. Are you sure you have clean, updated workspace checked out?

**Comment by mannp** [comment]
Its the first time I have had an issue, just pasting the dockerfile as is into bitbucket as is and creating an automated build from it on dockerhub.

My other builds work fine that way, so perhaps the patch is not pulled from the dockerfile and needs to be pulled locally first.

Its not an issue as I was just trying before your 'official' build came out, but it seems there are a few broken items with the new web-vault, so will wait until you have the time to further update.

**Comment by mprasil** [comment]
Yeah this whole thing is to prepare for Vault 2 release. It hasn't even been released upstream, so there's no rush, but any help with testing it is welcome.

**Comment by mannp** [comment]
I'd presumed wrongly that the docker would pull in all necessary dependencies, including the patch itself rather than having to patch locally.

**Comment by mprasil** [comment]
If anyone is interested, I've triggered another [build](https://hub.docker.com/r/mprasil/bitwarden/builds/bxcn7teu7vnkt44vr33oqga/) with latest Vault code from master branch, should have couple new features and also translations. (btw, please do [help translating](https://github.com/bitwarden/web/issues/46#issuecomment-406274883) in the upstream project) The image should be built in about an hour.

**Comment by mprasil** [comment]
I've just pushed latest build of beta out and `mprasil/bitwarden:beta` is now ready to be tested. Maybe give it a spin, see if anything is broken since 2.0.0. If not I believe we've fixed all bugs we've found so far and this beta might be ready to be merged to master. What do you think @dani-garcia?

(also upstream Vault seems to be stabilized a bit and many minor issues are fixed on their side)

**Comment by mannp** [comment]
Did the 2FA issue get fixed before you merge to master by any chance?

V1 is working nicely here :)

**Comment by mprasil** [comment]
Can you test with the latest beta image? Just to see if it wasn't some upstream bug. I don't think the 2fa code is different between V1 and V2, so that's definitely strange. Are you running the versions with exact same setup?

**Comment by mannp** [comment]
I have used the exact same setup, the exact same ssl certs with one docker v1 and one v2.

V1 registers the Authenticator fine but v2 fails.

https://github.com/dani-garcia/bitwarden_rs/issues/105

**Comment by mprasil** [comment]
Okay, so the #124 is outstanding for the V2.

**Comment by mprasil** [comment]
Latest beta image is now built with the latest Vault v2 related fixes. We believe most of the bugs should be resolved. Please test `mprasil/bitwarden:beta` if anyone is interested and if no blockers pop up, we might get @dani-garcia to merge this into master. :tada:

**Comment by dani-garcia** [comment]
The new web vault is live in the 1.0.0 release now. If there are any bugs, please open a new issue!
