### ISSUE TITLE
"Bad Gateway" with Traefik v2

### ISSUE THREAD

**Issue by Daams13** [dani-garcia/bitwarden_rs#935]
Hi all !

I have following this wiki : https://github.com/dani-garcia/bitwarden_rs/wiki/Proxy-examples for enable HTTPS with Traefik V2 but i get "Bad Gateway" when I try to access on my URL bitwarden.mydomain.com.

The certificate is correctly create by lets enscript on my file "acme.json".

My Traefik configuration : 
![image](https://user-images.githubusercontent.com/62769755/77794385-1471c280-706c-11ea-9413-edbd02f58cb9.png)

My Bitwarden configuration : 
![image](https://user-images.githubusercontent.com/62769755/77794535-5e5aa880-706c-11ea-99e7-5e348ca2608b.png)

The Traefik's logs when I try to access to my "bitwarden.mydomain.com" : 
![image](https://user-images.githubusercontent.com/62769755/77795198-73840700-706d-11ea-8351-df953be66155.png)

And the page than I get : 
![image](https://user-images.githubusercontent.com/62769755/77795414-c78eeb80-706d-11ea-867d-db6e776f1e5d.png)

I don't see where the problem can come... We can see in the logs that Traefik redirects the url to the docker address of my container... 

Thanks a lot for your help !

**Comment by dennisgerding** [comment]
Hi, I guess its because you have to map Traefik to Bitwitwarden's internal ports (80 and 3012). I'm also unsure why you would open ports directly if you are using a reverse proxy.
Dennis

**Comment by Daams13** [comment]
Hi Dennis,

Thank you very much ! It's work !
I am a beginner with Traefik and also Docker... You just made me understand a new notion :)
I did not understand that the redirection must be done on the internal port of the docker and not on the redirected port.

Thanks again !

**Comment by mregni** [comment]
Hi @Daams13, sorry for replying to a closed issue here. But I have the exact same issue. 

Can you tell me how you fixed this Bad Gateway problem?
