### ISSUE TITLE
Backing up database

### ISSUE THREAD

**Issue by freakyshine** [dani-garcia/bitwarden_rs#938]
Hey there!

I'm really enjoying bitwarden_rs but I've come to my end of understanding. Which directory/file is necessary for saving the client's values? Is it possible to replace it and it is all going to work again?

Regards,
Daniel

**Comment by dani-garcia** [comment]
There's a pretty good description in the wiki: https://github.com/dani-garcia/bitwarden_rs/wiki/Backing-up-your-vault

It mentions backing up the database with the sqlite command, but you can also copy the files like normal as long as the server is stopped before.

**Comment by freakyshine** [comment]
"The files"? Which one would that be? I tried to replace the db.sqlite3 from another database but the client data wasn't there.

**Comment by dennisgerding** [comment]
I use a small script for backing up my vault. It could be easy for you.


```
#!/bin/bash

today=`date +%Y%m%d`
todayhuman=`date +"%d-%m-%Y %H:%M:%S"`
random=`head /dev/urandom | tr -dc a-f0-9 | head -c 12 ; echo ''`
workdir=/tmp/bwrs_$random
zipfile=/tmp/bwbackup-$today-$random.tar.gz

mkdir $workdir
mkdir $workdir/bw-data
mkdir $workdir/bw-data/attachments

cp -r /opt/docker/bitwarden_rs/bw-data/attachments/ $workdir/bw-data/
cp /opt/docker/bitwarden_rs/docker-compose.yml $workdir
cp /opt/docker/bitwarden_rs/bw-data/config.json $workdir/bw-data
sqlite3 /opt/docker/bitwarden_rs/bw-data/db.sqlite3 ".backup '$workdir/bw-data/db.sqlite3'"

find $workdir -type f | xargs sha256sum > /tmp/$random-shasum.txt
sha1sum=`cat /tmp/$random-shasum.txt`
cp /tmp/$random-shasum.txt $workdir/shasum.txt
rm /tmp/$random-shasum.txt

cd $workdir
tar -czf $zipfile *

rm -rf $workdir

size=`ls -sh $zipfile`
sha1sumfile=`sha256sum $zipfile`

echo -e "Vault backup of $todayhuman\n\n-- file information --\n$size\n$sha1sumfile\n\n-- archive information (shasum.txt) --\n$sha1sum" | mail -s "[bw_backup] $todayhuman ($random)" my@email.nl -A $zipfile

rm $zipfile
```

**Comment by freakyshine** [comment]
Oh, this looks very useful, thanks! 

May I ask why you remove the zip file in the end? Isn't that the final backup?
Also, why do you use a random variable? Is it common to use that for temporary directories?

**Comment by dennisgerding** [comment]
I remove the zipfile because I mail it to myself (my vault is really small in size). I also had some issues in my mail client making a thread of all the mails, adding a random string in it stopped my mail client from making a thread of it all. 
As side effect a random string also makes it possible to back up multiple times a day, however also the time could be used for that.

**Comment by freakyshine** [comment]
Hmm.. so that's still secure because the database's content is encrypted with the master password by the individual users, right?

**Comment by dennisgerding** [comment]
Yes I believe so.

**Comment by freakyshine** [comment]
Ok, thanks for your help :)

**Comment by dennisgerding** [comment]
In my case I just untar the archive and run ```docker-compose up -d```. That is (for me) possible since it holds the config file, database, attachments and the ```docker-compose.yml`` file. Docker will pull the images.
