### ISSUE TITLE
"Error sending SMTP test email LetreErr"

### ISSUE THREAD

**Issue by damnshaneisthatu** [dani-garcia/bitwarden_rs#943]
### Subject of the issue
I attempted to use Gmail to send bitwarden_rs emails. When I send the test mail I get a popup saying:
"Error sending SMTP test email
LetreErr"

### Your environment

* Bitwarden_rs version: 
Version: 1.14.1-843604c9

* Install method: Docker image
* Clients used: Unraid
* Reverse proxy and version: Nginx Proxy Manager with Let's Encrypt SSL cert

### Steps to reproduce

<img width="1048" alt="Screen Shot 2020-03-31 at 6 23 24 PM" src="https://user-images.githubusercontent.com/1761752/78089621-d848a580-737c-11ea-97d8-5e63e5efaa2d.png">
<img width="1075" alt="Screen Shot 2020-03-31 at 6 27 16 PM" src="https://user-images.githubusercontent.com/1761752/78089944-a2f08780-737d-11ea-952a-0e1ef050ba37.png">

### Expected behaviour
A successful test email sent to and received in my inbox.

### Actual behaviour
"Error sending SMTP test email
LetreErr"

### Relevant logs

<img width="699" alt="Screen Shot 2020-03-31 at 6 19 42 PM" src="https://user-images.githubusercontent.com/1761752/78089420-36c15400-737c-11ea-8580-22c2db040b4c.png">

**Comment by jjlin** [comment]
Try the settings in https://github.com/dani-garcia/bitwarden_rs/issues/924#issuecomment-602923625.

**Comment by damnshaneisthatu** [comment]
Worked with one caveat: had to use one of my other *@gmail.com addresses. My custom google domain wouldn't allow app passwords for the org.

**Comment by maikimaiko** [comment]
I had the same issue, only worked with my @gmail.com, not with my custom domain.
