### ISSUE TITLE
Organization settings

### ISSUE THREAD

**Issue by bokkabonga** [dani-garcia/bitwarden_rs#944]
### Subject of the issue
Organizations seem to have some settings about 2FA, the master password and the password generator that can be changed by the owner. In german they are called "Richtlinien" so i guess the English term would be "Policies".
Changing those "Policies" doesn´t change anything. I am not sure if this has been implented yet, but i couldn´t find any other Issue concerning this.

### Your environment

* Bitwarden_rs version: 1.14.1-843604c9

* Install method:  built from source
* Clients used: Web-Vault
* Reverse proxy and version: none
* Version of mysql/postgresql: mariadb 10.4

### Steps to reproduce

Changed the Policy for the password generator to at least 24 Signs and to include upper and lower, numbers and special characters. I made sure that the "Activate" checkbox was ticked and hit "Save".

### Expected behaviour

When generating a new password for an entry in the organization, the password should be generated according to the rules set.

### Actual behaviour

The password is generated with the default pattern (14 charakters, both upper and lower and numbers).

**Comment by BlackDex** [comment]
Hello @bokkabonga,

It seems you have to logout and back in again for this to work.
I tested this on the upstream bitwarden project, and it acts the same.
It probably needs a sync/refresh of these items.

Maybe you can report a bug to the upstream project and log past it's link here so we can track it if needed.

**Comment by bokkabonga** [comment]
Hey @BlackDex,

Logging out and back in did indeed do the trick for me. Thanks a lot! I will try to open a bug report in the upstream project next week at latest and leave the link here so it can be tracked.

Thanks a lot for your help :)

**Comment by giss69** [comment]
i have the same issue on Version: 1.14.2-8bbbff75. i can not change master password because of the password regulation. Logging out and back didn't help.

**Comment by dani-garcia** [comment]
What do you mean you can't change the password because of the policy? As long as you follow the policies it should allow you to change it just fine.

**Comment by giss69** [comment]
@dani-garcia 
i get always thins error:
`your new master password does not meet the policy requirements`
but it does.

**Comment by BlackDex** [comment]
@giss69 are you still having this issue? If so, could you give use a real life example of the settings for the policy what had been configured and what kind of password isn't allowed?

**Comment by BlackDex** [comment]
Closing this ticket because of inactivity.
Feel free to re-open if the issue isn't resolved using the `testing`/`master` version.
