### ISSUE TITLE
web vault

### ISSUE THREAD

**Issue by woolmonkey** [dani-garcia/bitwarden_rs#95]
I have followed the build instructionns and everything goes good till I try to run it.  It complains about the web vault not being installed and to follow the directions.  I downloaded the webvault did npm install npx and moved the directory to the right folder.

**Comment by mprasil** [comment]
Sounds like you moved wrong files to the folder, there should be index.html present there.

**Comment by woolmonkey** [comment]
No the index.html folder is there. Here is the contents of the folder
`todd@Password:~/bitwarden_rs/web-vault$ ls
app          css                 favicon.ico  index.html  lib            u2f-connector.html
app-id.json  duo-connector.html  images       js          manifest.json  version.json`

**Comment by mprasil** [comment]
Heh, the history of your post is some roller-coaster :) Glad you figured it all out.
