### ISSUE TITLE
.latest not loading latest built

### ISSUE THREAD

**Issue by yelch** [dani-garcia/bitwarden_rs#951]
I am happily using bitwardenrs on my synology and it's working great. Thank you!

The only 'issue' I have is, that pulling .latest still pulls 1.13.1 instead of 1.14.1

**Comment by jjlin** [comment]
I'm not familiar with how things work on Synology, but I assume ".latest" is a Synology thing? This is something you should take up with whoever is providing/packaging bitwarden_rs on Synology.

**Comment by yelch** [comment]
(sorry for the late reply). This is my source: https://registry.hub.docker.com
I'll try to reach somebody there... Tnx

**Comment by dani-garcia** [comment]
If you are using the docker hub images, bitwardenrs/server:latest will get you the latest commit, which is newer than 1.14.2, if it doesn't there's something weird in your docker config somewhere. 

If you are using some synology package, then no idea because we don't maintain those.
