### ISSUE TITLE
Signup Domain Whitelist doesn't work

### ISSUE THREAD

**Issue by AKDingfeld** [dani-garcia/bitwarden_rs#953]
### Subject of the issue
I can register accounts from domains that are not set on my whitelist in docker-compose file or admin-center.

### Your environment
* Bitwarden_rs version: Version: 1.14.1-ccf6ee79
* Install method: Docker-Compose
* Clients used: Win 10, Firefox, Edge
* Reverse proxy and version:
* Version of mysql/postgresql:
* Other relevant information: 

### Steps to reproduce

I added `    - SIGNUPS_DOMAINS_WHITELIST=mydomain.org` as environment variable to my docker-compose file. After restart i tried to register new accounts using the normal register form. I Tried some E-Mails like test@notmydomain.org
I added some domains in the whitelist in the admin-center with the same result.

### Expected behaviour
The registration should be blocked due to the whitelist.

### Actual behaviour
The registration worked.

**Comment by jjlin** [comment]
Most likely you also need to set `SIGNUPS_ALLOWED=false`, as mentioned in https://github.com/dani-garcia/bitwarden_rs/wiki/Disable-registration-of-new-users.

#957 should avoid this confusion, though.

**Comment by dani-garcia** [comment]
Closed due to inactivity.
