### ISSUE TITLE
restore from backup

### ISSUE THREAD

**Issue by gpopesc** [dani-garcia/bitwarden_rs#961]
Hello

I have been using bitwardenrs for almost one year and I am very happy with it.
Now I want to be on the safe side and I did database backups. I have also all the file from docker data folder.

How I can restore the database?
I tried to mount a different docker container with  other data folder (copied from original one), but it doesn't recognise any user from old one. I need to start from the beginning, with creating a new user. Is there any way to restore the data from old container?

Thank you

# Please submit all your third party help requests to the forum
Link: https://bitwardenrs.discourse.group/c/help

**Comment by empenoso** [comment]
Good question. I also want to know.

**Comment by jjlin** [comment]
There is a wiki page on this: https://github.com/dani-garcia/bitwarden_rs/wiki/Backing-up-your-vault

Please direct further usage/configuration questions to the forum.

**Comment by gpopesc** [comment]
Thank you very much, it is very clear for making backups.
What I really want to know is how to restore a backup? This part is not touched anywhere.
