### ISSUE TITLE
Building 1.14.2 on ARM fails to get rust nightly components

### ISSUE THREAD

**Issue by mqus** [dani-garcia/bitwarden_rs#962]
### Subject of the issue
I just tried to build the latest release on a raspberry pi (baremetal) and got the following error while cargo/rustup was updating the toolchain:
```
info: syncing channel updates for 'nightly-2020-04-08-armv7-unknown-linux-gnueabihf'
info: latest update on 2020-04-08, rust version 1.44.0-nightly (42abbd887 2020-04-07)
error: component 'clippy' for target 'armv7-unknown-linux-gnueabihf' is unavailable for download for channel nightly-2020-04-08
```
After looking at https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu.html, I decided to use `nightly-2020-04-10` and it build without any issues. This issue is basically the same as #622 .

I think this will be solved eventually by using another nightly build, the only open question is: Does it make sense to make a new release?

### Your environment
* Bitwarden_rs version: 1.14.2
* Install method: Archlinux package (my responsibility ;) ), sqlite release
* Clients used: Not applicable
* Reverse proxy and version: Not applicable
* Version of mysql/postgresql: Not applicable
* Other relevant information: 

### Steps to reproduce
On an ARM machine (e.g. Raspberry Pi with ArchlinuxARM):
```
$ git clone https://github.com/dani-garcia/bitwarden_rs
[...]
$ cd bitwarden_rs
$ git checkout 1.14.2
[...]
$ cargo build --release
info: syncing channel updates for 'nightly-2020-04-08-armv7-unknown-linux-gnueabihf'
info: latest update on 2020-04-08, rust version 1.44.0-nightly (42abbd887 2020-04-07)
error: component 'clippy' for target 'armv7-unknown-linux-gnueabihf' is unavailable for download for channel nightly-2020-04-08
```

**Comment by dani-garcia** [comment]
Well clippy is broken in a big percentage of the nightly builds, but it's not needed to compile the code so I'd recommend just using rustups minimal profile (`rustup set profile minimal` before installing).

I don't think it's enough to make a new release to fix it, but I'll have it in mind before making any new rust updates in the future.

**Comment by mqus** [comment]
I can set the rustup profile for me perfectly (and probably already did on my main machine,just forgot it :D) but I can't simply set the profile in the archlinux build script and change the setup of unsuspecting users... do you know a better solution than reading the old value, setting it and then reverting to the old one (which is what I would probably do)?

**Comment by mqus** [comment]
Btw, I also don't think a new release is necessary, one can trivially work around this.

**Comment by dani-garcia** [comment]
You can do something like `rustup override set --path <bitwardenrs_path> nightly-2020-04-10` or I think setting `RUSTUP_TOOLCHAIN` env variable also works.

**Comment by mqus** [comment]
Thank you!, i'll try this in the future. For now, I'm using the profile setting and resetting, which also limits the amount if space the new installed components take up.

**Comment by mqus** [comment]
As this is not a problem in the new version I'll close this issue now. Of course it could occur in the future again but I think there is nothing we can do to fix this here.
