### ISSUE TITLE
Bitwarden issue on startup with libcrypto.so and libssl.so

### ISSUE THREAD

**Issue by nady2804** [dani-garcia/bitwarden_rs#963]
Hello,
I'm a Bitwarden newby. I install the lastest version on my Qnap.
It work but i get this messages on startup.
[/opt/BitWarden] # vi BitWarden.sh
[/opt/BitWarden] # ./BitWarden.sh restart
[/opt/BitWarden] # ./bitwarden_rs: /usr/lib/libcrypto.so.1.0.0: no version information available (required by ./bitwarden_rs)
./bitwarden_rs: /usr/lib/libcrypto.so.1.0.0: no version information available (required by ./bitwarden_rs)
./bitwarden_rs: /lib/libssl.so.1.0.0: no version information available (required by ./bitwarden_rs)
/--------------------------------------------------------------------\
|                       Starting Bitwarden_RS                        |
|--------------------------------------------------------------------|
| This is an *unofficial* Bitwarden implementation, DO NOT use the   |
| official channels to report bugs/features, regardless of client.   |
| Report URL: https://github.com/dani-garcia/bitwarden_rs/issues/new |
\--------------------------------------------------------------------/

[2020-04-13 13:55:10][start][INFO] Rocket has launched from https://0.0.0.0:8000

thx Manfred

**Comment by dani-garcia** [comment]
Well no idea what the launch script is doing but I assume the QNAP package is missing a correct dependency, you should bring that issue with the package maintainer.
