### ISSUE TITLE
Secure note content undeletable

### ISSUE THREAD

**Issue by Ndrou** [dani-garcia/bitwarden_rs#965]
### Secure note text is undeletable
When you create a secure note, and you add a note, the note cannot be deleted when you try to edit that later. The previous note is displayed.

### Your environment

* Bitwarden_rs version: 1.14.2
* Install method: Docker image
* Clients used: Web / Desktop / CLI
* Reverse proxy and version: Traefik 2.2
* Version of mysql/postgresql: Postgresql 12.2
* Other relevant information: 

### Steps to reproduce
* Create a secure note
* Add text into the note field
* Save
* Edit the secure note
* Empty text in note field
* Save
* Refresh the page or resync client
* The previous note appears

### Expected behaviour
The secure note text should disappear.

### Actual behaviour
The previous secure note text appears.

**Comment by BlackDex** [comment]
I Can confirm this.
It doesn't happen on sqlite.

**Comment by dani-garcia** [comment]
Fixed in #966
