### ISSUE TITLE
Dockerfiles run services as the root user

### ISSUE THREAD

**Issue by xhalo32** [dani-garcia/bitwarden_rs#968]
### Subject of the issue
Shouldn't use the root user to run the services inside the containers.

https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b

**Comment by jjlin** [comment]
As noted in https://github.com/dani-garcia/bitwarden_rs/pull/1014#issuecomment-637965744, this probably isn't a good default for bitwarden_rs, but I've now added documentation on how to run as non-root:

https://github.com/dani-garcia/bitwarden_rs/wiki/Hardening-Guide#run-as-a-non-root-user

**Comment by jostyee** [comment]
@jjlin I've got a permission error after adding user settings to my docker-compose.yml:

```
[2020-06-11 15:37:54][bitwarden_rs][ERROR] Launch error Bind(
    Io(
        Os {
            code: 13,
            kind: PermissionDenied,
            message: "Permission denied",
        },
    ),
)
```

**Comment by Stampede10343** [comment]
> As noted in [#1014 (comment)](https://github.com/dani-garcia/bitwarden_rs/pull/1014#issuecomment-637965744), this probably isn't a good default for bitwarden_rs, but I've now added documentation on how to run as non-root:
> 
> https://github.com/dani-garcia/bitwarden_rs/wiki/Hardening-Guide#run-as-a-non-root-user

Should this remove the [listing here](https://github.com/dani-garcia/bitwarden_rs/wiki/Running-the-server-with-non-root-user), since its basically the same, and better suited in the Hardening Guide, IMO.

**Comment by jjlin** [comment]
@Stampede10343 I didn't notice that page, but I think it has a few additional things that would be good to mention. I'll merge it into the hardening guide page tonight. Thanks for calling attention to that.

**Comment by jjlin** [comment]
It's updated now.

**Comment by BlackDex** [comment]
Thx for the updated wiki, closing this issue.
