### ISSUE TITLE
SMTP_FROM_NAME not working

### ISSUE THREAD

**Issue by duffycop** [dani-garcia/bitwarden_rs#969]
### SMTP_FROM_NAME isn't working

In the last version of the Docker image the environment variable SMTP_FROM_NAME isn't working.
By taking a look at the source code I was able to identify the issue in the line 388 of src/config.rs
        smtp_from_name:         String, true,   def,     "Bitwarden_RS".to_string();
Maybe this should be as line 386 where the definition is
        smtp_from:              String, true,   def,     String::new();

So modified line 388 would be like this
        smtp_from_name:         String, true,   def,     String::new();

EDIT: I didn't tested the environment: tag in the docker-compose.yml file.

My docker-compose.yml look like this

> version: "3"
> services:
>   password:
>     container_name: password
>     image: bitwardenrs/server
>     restart: always
>     volumes:
>       - ./password/bw-data/:/data/
>     env_file: ./password/env
> 
>   nginx:
>     image: docker.io/nginx:latest
>     restart: always
>     container_name: nginx
>     ports:
>       - "80:80"
>       - "443:443"
>     volumes:
>       - ./nginx/etc:/etc/nginx
>       - ./nginx/certs:/etc/letsencrypt
>       - ./nginx/certs-data:/data/letsencrypt
>       - /var/run/docker.sock:/tmp/docker.sock:ro
>     depends_on:
>       - password

Thanks for your time! And you've done an amazing work here!
Best regards!

**Comment by jjlin** [comment]
`SMTP_FROM` and `SMTP_FROM_NAME` are different things. You probably have a config.json that's overriding your env var. Take a look at https://github.com/dani-garcia/bitwarden_rs/wiki/Configuration-overview.
