### ISSUE TITLE
Vault 2 is using PUT instead of POST when sharing

### ISSUE THREAD

**Issue by mprasil** [dani-garcia/bitwarden_rs#97]
As part of testing for #93, I've found, that the share functionality is broken in new Vault. The API endpoint used is `/api/ciphers/{{cipher_id}}/share`. We have the functionality already [implemented](https://github.com/dani-garcia/bitwarden_rs/blob/48e69cebab29585684be4bf22282ff1dd4697d24/src/api/core/ciphers.rs#L331) for `POST` so this should be easy backwards compatible fix.

**Comment by dani-garcia** [comment]
This was fixed by #111
