### ISSUE TITLE
Bitwarden_rs on Cloudron

### ISSUE THREAD

**Issue by nebulade** [dani-garcia/bitwarden_rs#974]
Hi there,

we have recently packaged bitwarden_rs together with the official web-vault as a [Cloudron](https://cloudron.io) app. It is now available for basically installation within a few clicks if you have a Cloudron installation. It was one of the most asked for apps to package from our community, so huge thanks to @dani-garcia for the great work. The main packaging work was actually done by @ViViDboarder !

Our package repo can be found at https://git.cloudron.io/cloudron/bitwardenrs-app and the app description page is at https://cloudron.io/store/com.github.bitwardenrs.html

I wanted to reach out here to ask what the best place is to let users know about that installation method. Should I just create a pull request for the wiki and create a similar page like the "Using Podman" one?

Best,
Johannes

**Comment by jjlin** [comment]
You can edit the wiki directly without PRs. https://github.com/dani-garcia/bitwarden_rs/wiki/Third-party-packages is probably the most relevant page.

**Comment by nebulade** [comment]
Awesome thanks for that, I've added a section now. Hope that is ok :-)
