### ISSUE TITLE
DELETE /api/ciphers not implemented

### ISSUE THREAD

**Issue by mprasil** [dani-garcia/bitwarden_rs#98]
New vault (#93) calls `DELETE` on `/api/ciphers` to "Delete selected" ciphers. We have `POST` handler [already implemented](https://github.com/dani-garcia/bitwarden_rs/blob/48e69cebab29585684be4bf22282ff1dd4697d24/src/api/core/ciphers.rs#L465) for this, so this should be easy to fix.

**Comment by mannp** [comment]
Is the stable release of v2 tagged for the docker image at all?

Currently using the beta build to get v2, but unclear if there is another build I should be using?

Thanks

**Comment by mannp** [comment]
Ok, so i updated my beta to the latest and it still doesn't delete any entries.

**Comment by mprasil** [comment]
This is why this issue was open. 😄 It hasn't been fixed yet, I think I've confused you somewhere into thinking it's been resolved.

**Comment by mprasil** [comment]
Resolved in #115
