### ISSUE TITLE
Error sending emails.

### ISSUE THREAD

**Issue by bassisd** [dani-garcia/bitwarden_rs#982]
I'm trying to use the bitwarden add-on on hassio, but i can't use/send any mail from the smtp service, i recive always an error to send during the setup.
anyone have any suggest (obviously the smtp parameters used are correct) only in the add-on i can't use it.
regards to all

**Comment by mqus** [comment]
Hi! I didn't know that bitwarden_rs is also available on hassio, sounds awesome!

Could you expand on your environment and configuration a bit more? 
What did you configure (please obfuscate the identifying details like the domain name or the email adress), where did you get the error message and what was the exact error message? 
Maybe screenshots could help. I (and probably most others here) haven't used hass.io yet. The steps you took also can be useful for reproducing (and fixing) your issue.

If we can't help you, you could also try to ask in the [addon issues](https://github.com/hassio-addons/addon-bitwarden/issues) or in the [forum post](https://community.home-assistant.io/t/home-assistant-community-add-on-bitwarden-rs/115573/72) for the addon. In any case, please report back if you solved your problem.

**Comment by Ornias1993** [comment]
> If we can't help you, you could also try to ask in the [addon issues](https://github.com/hassio-addons/addon-bitwarden/issues) or in the [forum post](https://community.home-assistant.io/t/home-assistant-community-add-on-bitwarden-rs/115573/72) for the addon. In any case, please report back if you solved your problem.

No it's the other way around:
If you used a forked or integrated version of something, you file an issue with those folks first. If they say it isn't related or limited to their "special version" you forward an issue to the upstream.

This can just as well be closed till then.

**Comment by BlackDex** [comment]
@bassisd, do you still have issues regarding the smtp?
The past few weeks a lot has been changed regarding that. Now i don't know if that is already has found is way too hassio, but if so, please try it again.

**Comment by BlackDex** [comment]
@bassisd Also, we have just released v1.17.0 which has all the latest fixes. Again i do not know how hassio works for this and if they have this new version available. But if they do, please check that.

**Comment by BlackDex** [comment]
Closing this ticket because of inactivity.
Feel free to re-open if the issue isn't resolved using the `testing`/`master` version.

Also, there is a new PR #1229 which when merged could help debugging smtp issues.
