### ISSUE TITLE
How does bitwarden_rs compare with bitwarden from 8bit?

### ISSUE THREAD

**Issue by FailProof** [dani-garcia/bitwarden_rs#983]
Hello everyone, I am a 20+ year IT veteran but a newbie to GitHub, Docker images and bitwarden_rs. I hope my question is not out of line or in bad form. I have installed this image and also the bitwarden docker images from 8bit. I noticed the 8bit install requires many images where this one (_rs) is a simple one image installation. So that leaves me wondering if there is something I would be missing in functionality from the bitwarden official installation. For example bitwarden has an image called ‘identity server’ but bitwarden_rs has no reference to this. I also read through documentation and the ‘missing features’ section but I didn’t see a reference to that there.
Is that a feature/functionality that I wouldn’t have or is that already packaged into this _rs image? So far it appears you have created a great image (superior?) with bitwarden_rs but since I am a newbie, I want to double check I am not missing something.

Thank you in advance for your patience and any guidance you can provide.

**Comment by mprasil** [comment]
Hi, I think the missing features wiki info is pretty accurate. The official service has multiple components, that work together as you've noticed. This makes sense especially for bigger deployments where you can deploy and scale each component individually. It is also using separate DB service.

With `bitwarden_rs` everything is integrated into one binary (and shipped as single image) and the only separate service that you can (optionally, if you prefer) run is external DB. (MySQL or PostgreSQL)

Which one is better depends on your situation. If you need official support from 8bit, you need to use official server. If you intend to run this for thousands of users, official server might be the way to go. If you want small deployment for yourself, perhaps `bitwarden_rs` will be less resource hungry. If you want to run it on something small like NAS or Raspberry Pi, `bitwarden_rs` might be your only option.

Hopefully that helps.

**Comment by FailProof** [comment]
Hi Miro, thank you for the quick reply. Everything you said makes sense. We will be using it for a smaller deployment so the bitwarden_rs image will be a great fit for us. Do you happen to know what the "identity server" and "icon server" do and if that's already built into _rs image?

**Comment by mprasil** [comment]
I'm not *that* familiar with official implementation, but I think identity server handles authorization and session handling, so the `bitwarden_rs` counterpart to that API is implemented [here](https://github.com/dani-garcia/bitwarden_rs/blob/master/src/api/identity.rs). Icon server fetches and caches favicons from webpages so that the client applications can display them. That part of the API is implemented [here](https://github.com/dani-garcia/bitwarden_rs/blob/master/src/api/icons.rs).

**Comment by FailProof** [comment]
wow, thanks for the information. I am very excited about bitwarden_rs. Thank you to the community and everyone involved in building and supporting this project. I will be closing this issue.
