### ISSUE TITLE
Bitwarden Create user not working

### ISSUE THREAD

**Issue by robertfgoodworth** [dani-garcia/bitwarden_rs#985]
Hi I just installed the Bitwarden App and tryed to create a user, filled in all the details and when i click on submit nothing happens.
I'm on the latest HA.

Cheers
Rob

**Comment by dani-garcia** [comment]
Any errors on the browsers console? Do you use HTTPS?

**Comment by robertfgoodworth** [comment]
Hi Daniel,

 

No HTTP, the web page loads fine, I click on create user which takes me to the create user page ok, I can fill in all the details, when I click on submit I get nothing, not even a page redirect or anything that looks like the submit worked.  I’m using the latest Chrome browser which I’ve had no problems with any other HA pages or apps.  I’ll see if I can get some browser data from dev mode as I click on the submit button and send it on. 

 

Regards

 

Robert Goodworth

21 Harcus Close 

Bonython, ACT, 2905

H: 02 62939660

M: 0428699792

robertfgoodworth@bigpond.com <mailto:robertfgoodworth@bigpond.com>   NOTE:  NEW EMAIL

**Comment by CloudAc** [comment]
No HTTP: That's is your problem.
If you're using firefox you won't get any response related to the missing SSL.
Create a an account with Chrome and it should be working.
Firefox is very strict for a long time about accessing pages without SSL.

**Comment by robertfgoodworth** [comment]
Thanks, Ill reconfigure as https.

 

Regards

 

Robert Goodworth

**Comment by dani-garcia** [comment]
I think this can be considered solved now that we know the issue is not using HTTPS.
