### ISSUE TITLE
Document postgres setup

### ISSUE THREAD

**Issue by cromefire** [dani-garcia/bitwarden_rs#996]
From the code and some issues it seems that postgres is supported, but in the wiki I couldn't find any info regarding it.
It would be good if there could be like 2 sentences be added about postgres somewhere, like:
```
Configure postgres like this:
VAR=pgsql://user:pw@host/DB
```
(Assuming it's as easy as that)

**Comment by djmattyg007** [comment]
My understanding is that support for the specific database you want to use has to be baked in at compile-time.

I think it would help a great deal to start getting this packaged by distros if support could just be controlled via configuration.

**Comment by cromefire** [comment]
So I found `bitwardenrs/server-postgres`, and from the diesel docs I gathered that prepending the full `postgresql` is correct, and that actually worked, so it just needs some documentation

**Comment by jpeeler** [comment]
Doesn't look like "pgsql" will work: https://github.com/dani-garcia/bitwarden_rs/pull/1044. I used this with all of the fields specified:

`DATABASE_URL='postgresql://[[user]:[password]@]host[:port][/database]'`

**Comment by cromefire** [comment]
Yeah see my last comment, but it would be good if it was documented somewhere or if there was at least a link to the diesel docs

**Comment by jjlin** [comment]
I leave it to an actual PostgreSQL user to write more comprehensive docs on the wiki, but #1095 should provide the basics.

**Comment by cromefire** [comment]
Yeah that's sufficient

**Comment by BlackDex** [comment]
Those changes together with this fresh wiki page, https://github.com/dani-garcia/bitwarden_rs/wiki/Using-the-PostgreSQL-Backend , should be enough. Closing this ticket.
