### ISSUE TITLE
Organization import with directory connector: HTTP 404

### ISSUE THREAD

**Issue by LiaraAlis** [dani-garcia/bitwarden_rs#999]
# Sync with directory connector fails with HTTP 404
When syncing an organization with the bitwarden directory connector, the called url (/api/organizations/<organization-id>/import) returns a http 404 error.
Ticket from directory connector repository: https://github.com/bitwarden/directory-connector/issues/43

Is it possible that this feature isn't supported in `bitwarden_rs`?

**Comment by dani-garcia** [comment]
Yes at the moment the official connector is not supported. There's a separate LDAP service in the wiki though, if that helps.

**Comment by LiaraAlis** [comment]
Thanks for your answer. That is too bad. :(
The separate LDAP service seems very complicated. Not very intuitive. I don't understand how it works.

**Comment by Leboubou111** [comment]
@dani-garcia The [separate LDAP service](https://github.com/ViViDboarder/bitwarden_rs_ldap) doesn't really sync LDAP users and groups... Just invite users to create an account into your BW_RS instance.
And user cannot login with their credential LDAP account.

I'm sad that I can't authenticate my LDAP users.
Anyway, congratulations for your work ;-)

**Comment by dani-garcia** [comment]
Creating new users and using their LDAP credentials to authenticate is impossible due to the way the encryption works, so both the separate service and a possible implementation of the official LDAP connector would work the same way, which means users need to create their own accounts and passwords won't be synced, not much we can do there, I'm afraid.

Support for the official LDAP connector is included in the feature request isssue, so I'll close this to keep the issue tracker focused.

**Comment by Gheben** [comment]
Any update about user/group sync ?
Test sync will display users and groups, but when I try to Sync, It fail.
![image](https://user-images.githubusercontent.com/23033675/114467842-ca15a200-9bea-11eb-8058-c3d123f83e1e.png)

**Comment by Leboubou111** [comment]
I hope every day that this function will be implemented.
But I understand, it's not easy.

**Comment by BlackDex** [comment]
There is support for the ldap connector already. Only no group support

**Comment by Leboubou111** [comment]
> There is support for the ldap connector already. Only no group support

For a LDAP user connexion ?
Are you sure ?

I think just for invit LDAP user by their email to create an account. 
I talk about that ; https://github.com/dani-garcia/bitwarden_rs/issues/999#issuecomment-641420465

**Comment by BlackDex** [comment]
There will never be a single password login option via either sso or ldap since you always need a master password to decrypt the vault data.

So, using the connector would give you almost the the same kind of feeling as sso. It should disable users and create accounts for them.

**Comment by Leboubou111** [comment]
I believe that the original project has this function with Directory Connector sync.

**Comment by BlackDex** [comment]
Well, then i would say try it out. Since there is basic support for it already. See https://github.com/dani-garcia/bitwarden_rs/commit/85e3c73525d327042c1ad142e48c044a5dbdd89c

**Comment by BlackDex** [comment]
Also read the release notes here: https://github.com/dani-garcia/bitwarden_rs/releases/tag/1.19.0

And the official docs regarding this https://bitwarden.com/help/article/directory-sync/

**Comment by Leboubou111** [comment]
I hadn't seen this update. Sorry, I'll try.
